### ISSUE TITLE
Not able to use SSL with self-signed certificate

### ISSUE THREAD

**Issue by nadgowdas** [minio/minio-go#1000]
I've setup minio with self-signed certificate, and I am able to access server on `https` from UI.

While connecting through minio client (go-sdk), I am getting 

`x509: certificate signed by unknown authority` error while listing or creating buckets.

We are able to use client from node-js app with two changes (a) `secure:true` (b) `minioClient.setRequestOptions({rejectUnauthorized: false})`. 

Can someone point me to enable the same for go-client ?

**Comment by harshavardhana** [comment]
> We are able to use client from node-js app with two changes (a) secure:true (b) minioClient.setRequestOptions({rejectUnauthorized: false}).

```go
clnt.SetCustomTransport(&http.Transport{
	MaxIdleConns:       10,
	IdleConnTimeout:    30 * time.Second,
	DisableCompression: true,
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
})
```

**Comment by kannappanr** [comment]
@nadgowdas Closing the issue as answered, based on comments from @harshavardhana . Please feel free to file a new issue if you have further questions.

**Comment by nadgowdas** [comment]
@harshavardhana @kannappanr Thank you for prompt reply. I am able to connect to minio now.

**Comment by NefixEstrada** [comment]
Even if the issue is already closed, the *correct* way to do this would be adding the self signed certificate to the client pool, not to simply disable the security checks:

```go
tr, err := minio.DefaultTransport(true)
if err != nil {
	log.Fatalf("error creating the minio connection: error creating the default transport layer: %v", err)
}
transport := tr.(*http.Transport)

b, err := ioutil.ReadFile("./minio.crt")
if err != nil {
	log.Fatalf("error creating the minio connection: error reading the certificate: %v", err)
}

if ok := transport.TLSClientConfig.RootCAs.AppendCertsFromPEM(b); !ok {
	log.Fatalf("error creating the minio connection: error parsing the certificate: %v", err)
}

clnt.SetCustomTransport(transport)
```
