### ISSUE TITLE
Redirect to correct region for Wasabi

### ISSUE THREAD

**Issue by mappu** [minio/minio-go#1009]
Hi,

For Amazon S3 in `minio-go`, one should leave the endpoint as `s3.amazonaws.com`, and then Minio makes a first request to `/?location`, which will find the bucket for all future requests.

Wasabi is an S3-compatible provider. Until now, they only had one region `s3.wasabisys.com` ("us-east-1"), but recently they added a new region `s3.us-west-1.wasabisys.com` ("us-west-1"). [Source](https://wasabi-support.zendesk.com/hc/en-us/articles/360005022391-How-do-I-access-different-Wasabi-storage-regions-from-my-storage-app-)

The bucket namespace is global across all Wasabi locations, just like Amazon S3.

I want minio-go to perform the same kind of automatic location detection when using s3.wasabisys.com instead of s3.amazonaws.com.

It nearly works already... but, not quite.

## My setup

- I have a bucket `east-bucket-test` configured in Wasabi's us-east-1 location
- I have a bucket `test-westbucket` configured in Wasabi's us-west-1 location
- Latest minio-go from git master (v6.0.6)
- Using `Client.TraceOn(os.Stderr)` to log HTTP requests

## Trying to access a us-west-1 bucket on us-east-1 endpoint

In this example I try to use the default / us-east-1 endpoint `s3.wasabisys.com`, but try to access a bucket on "us-west-1".

The `/?location` response is supported:

```
---------START-HTTP---------
GET /test-westbucket/?location= HTTP/1.1
Host: s3.wasabisys.com
User-Agent: Minio (windows; amd64) minio-go/v6.0.6
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180717T004909Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 17 Jul 2018 00:49:12 GMT
Server: WasabiS3/2.3.199-2018-07-10-1af1ca5 (head05)
X-Amz-Id-2: **REDACTED**
X-Amz-Request-Id: **REDACTED**
X-Wasabi-Location: https://s3.us-west-1.wasabisys.com/test-westbucket
---------END-HTTP---------
```

The location response is "us-west-1". This is successfully returned by `(minio).Client.GetBucketLocation` with no error.

But then, if i call e.g. `Client.BucketExists` on this bucket, future requests are still sent to the us-east server, despite that `us-west-1` was used for the v4 signature:

```
---------START-HTTP---------
HEAD /test-westbucket/ HTTP/1.1
Host: s3.wasabisys.com
User-Agent: Minio (windows; amd64) minio-go/v6.0.6
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180717/us-west-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: **REDACTED**
X-Amz-Date: 20180717T004910Z

HTTP/1.1 400 Bad Request
Connection: close
Content-Type: application/xml
Date: Tue, 17 Jul 2018 00:49:12 GMT
Server: WasabiS3/2.3.199-2018-07-10-1af1ca5 (head05)
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: **REDACTED**
X-Amz-Request-Id: **REDACTED**
---------END-HTTP---------
```

400 Bad Request means that the `BucketExists` call returns `err != nil`.

A closer look at the response:

```
minio.ErrorResponse{
  XMLName:xml.Name{Space:"", Local:""},
  Code:"400 Bad Request",
  Message:"400 Bad Request",
  BucketName:"test-westbucket",
  Key:"",
  RequestID:"**REDACTED**",
  HostID:"**REDACTED**", 
  Region:"us-east-1",
  StatusCode:400,
  Headers:http.Header{
    "X-Amz-Request-Id":[]string{"**REDACTED**"},
    "Content-Type":[]string{"application/xml"},
    "Date":[]string{"Tue, 17 Jul 2018 00:49:12 GMT"},
    "Server":[]string{"WasabiS3/2.3.199-2018-07-10-1af1ca5 (head05)"},
    "X-Amz-Bucket-Region":[]string{"us-east-1"},
    "X-Amz-Id-2":[]string{"**REDACTED**"},
  },
}
```

That should explain the problem.

## Trying to access a us-east-1 bucket on us-west-1 endpoint

The reverse situation is somehow different.

Starting with `GetBucketLocation` again:

```
---------START-HTTP---------
GET /east-bucket-test/?location= HTTP/1.1
Host: s3.us-west-1.wasabisys.com
User-Agent: Minio (windows; amd64) minio-go/v6.0.6
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20180717T013550Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 17 Jul 2018 01:35:53 GMT
Server: WasabiS3/2.3.199-2018-07-10-1af1ca5 (head01)
X-Amz-Id-2: **REDACTED**
X-Amz-Request-Id: **REDACTED**
X-Wasabi-Location: https://s3.wasabisys.com/east-bucket-test
---------END-HTTP---------
```

So far it's the same, We get a correct response of "us-east-1" from GetBucketLocation.

Then BucketExists:

```
---------START-HTTP---------
HEAD /east-bucket-test/ HTTP/1.1
Host: s3.us-west-1.wasabisys.com
User-Agent: Minio (windows; amd64) minio-go/v6.0.6
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20180717/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: **REDACTED**
X-Amz-Date: **REDACTED**

HTTP/1.1 200 OK
Connection: close
Content-Type: application/xml
Date: Tue, 17 Jul 2018 01:35:54 GMT
Server: WasabiS3/2.3.199-2018-07-10-1af1ca5 (head04)
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: **REDACTED**
X-Amz-Request-Id: **REDACTED**
---------END-HTTP---------
```

This unexpectedly succeeded. (In Minio v4.0.4 this was also a failure scenario).

It seems like the us-west-1 server can successfully handle some requests that were intended for the us-east-1 server, but, not in the reverse.

I can see that the `Host` header is still pointing to the us-west-1 server. So maybe it's proxying all the requests, instead of redirecting?

I tried my full application, and in fact minio-go with the us-west-1 server can handle all requests for an us-east-1 bucket (put/get/...)

## Next steps

Going forward from here -

In order to support automatic bucket redirection for Wasabi, the location parser needs to understand that `us-west-1` should have redirected to `s3.us-west-1.wasabisys.com`. That didn't happen.

We could either
1. Hardcode all the current known possibilities (bad idea); or
2. if a `*.wasabisys.com` host gives a Region response, then change the endpoint to `s3.REGION.wasabisys.com`, except for `us-east-1` which should remain as `s3.wasabisys.com`; or
3. parse the `X-Wasabi-Location` header; or
4. ask Wasabi to change their behaviour to more closely match Amazon S3

I think idea 4 is the best option, and then, idea 2/3 are of similar equivalence.

## Questions

What changes should be made for idea 4 to work?

Why does the autodetection "work" but only in one direction?

Would you allow a PR for an implementation of idea 2/3?

**Comment by kannappanr** [comment]
@mappu , Here is how I think you can go about handling this situation.

The simplest approach would be that, if you know which region the bucket exists, then you can directly connect to that particular endpoint. 

If that doesn't work for you, then you can use the `GetBucketLocation` API in `minio-go` against `s3.wasabisys.com` to get the `location` and have a lookup table in your application which will map the region that you receive to the appropriate endpoint. I believe that might be a simpler fix. Let us know what you think.

**Comment by harshavardhana** [comment]
> I can see the current method for minio-go to perform this autodetection for Amazon S3, is with a lookup table for endpoints in https://github.com/minio/minio-go/blob/master/s3-endpoints.go#L21 . So if you won't accept a patch for Wasabi-specific endpoints, there's no way to resolve this issue by the current method.

@mappu this is a never-ending process for us if we keep adding new endpoints for new providers. AWS S3 we did because It is more ubiquitous service and the choice was simply obvious.  Region-specific endpoints are complex for this reason alone. I am just not sure why Wasabi chooses to do it this way why to repeat what AWS S3 did. 

In any case, you can simply use minio.NewWithRegion() and force the region and have multiple such minioClients initialized, this will avoid GetBucketLocation(). 

Supporting `X-Wasabi-Location` like custom headers is not a good idea which is too specific to Wasabi, we do support redirection with `Location:` header which is HTTP RFC compliant if Wasabi can do that minio-go will work fine.

**Comment by deekoder** [comment]
@mappu we are closing this for now.
