### ISSUE TITLE
'At least one of the pre-conditions you specified did not hold' Error

### ISSUE THREAD

**Issue by legacy-vault** [minio/minio-go#1028]
The function '**ComposeObject**' returns the following error: 
"_At least one of the pre-conditions you specified did not hold_".

'StackOverflow.com' website Thread:
https://stackoverflow.com/questions/52371672/minio-at-least-one-of-the-pre-conditions-you-specified-did-not-hold-error

If something happens to the 'StackOverflow.com' website, then the minimal example representing the bug (source code with sample data) can be obtained here:
https://www.file-upload.com/hzthje923oh4

Thank you.

**Comment by kannappanr** [comment]
@legacy-vault Thanks for filing this issue. I was able to reproduce this issue and have sent a PR to fix this issue.
