### ISSUE TITLE
Missing S3 FIPS endpoints

### ISSUE THREAD

**Issue by lucasmrod** [minio/minio-go#1033]
There are S3 FIPS missing endpoints, see: https://aws.amazon.com/compliance/fips/.
- Expected behaviour: minio-go uses the provided S3 FIPS endpoint.
- Actual behaviour: minio-go replaces the provided S3 FIPS endpount with the non-FIPS URL in `makeTargetURL`...

**Comment by lucasmrod** [comment]
Here's the PR to include missing S3 FIPS endpoints: https://github.com/minio/minio-go/pull/1032

**Comment by kannappanr** [comment]
@lucasmrod Thanks for sending in a PR for this issue.

**Comment by kannappanr** [comment]
Closing this issue as #1032 is already merged
