### ISSUE TITLE
missing "." caused func (c Client) BucketExists(bucketName string) (bool, error) return error when bucket does not exist

### ISSUE THREAD

**Issue by panfengAtInspur** [minio/minio-go#1034]
"NoSuchBucket":                      "The specified bucket does not exist" ,  the sentence   "The specified bucket does not exist" is incorrect

**Comment by kannappanr** [comment]
@panfengAtInspur Not sure if I follow you correctly. The message and code is from [AWS specification] (https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList )

Missing `.` means your the bucket name does not match and the displayed error is correct.

Can you elaborate on your issue, if my understanding is not correct?

**Comment by panfengAtInspur** [comment]
> @panfengAtInspur Not sure if I follow you correctly. The message and code is from [AWS specification] (https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList )
> 
> Missing `.` means your the bucket name does not match and the displayed error is correct.
> 
> Can you elaborate on your issue, if my understanding is not correct?
Hi . In github.com/minio/minio-go/api-stat.go
func (c Client) BucketExists(bucketName string) (bool, error) {
	// Input validation.
	if err := s3utils.CheckValidBucketName(bucketName); err != nil {
		return false, err
	}

	// Execute HEAD on bucketName.
	resp, err := c.executeMethod(context.Background(), "HEAD", requestMetadata{
		bucketName:       bucketName,
		contentSHA256Hex: emptySHA256Hex,
	})
	defer closeResponse(resp)
	if err != nil {
		if ToErrorResponse(err).Code == "NoSuchBucket" {
			return false, nil
		}
		return false, err
	}
	if resp != nil {
		if resp.StatusCode != http.StatusOK {
			return false, httpRespToErrorResponse(resp, bucketName, "")
		}
	}
	return true, nil
}
in this function, when my bucket does not exist, code should follow 
		if ToErrorResponse(err).Code == "NoSuchBucket" {
			return false, nil
		}
but now missing "." cause ToErrorResponse(err).Code != "NoSuchBucket", it's not correct

(https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList ) is NoSuchBucket | The specified bucket does not exist. | 404 Not Found | Client
