### ISSUE TITLE
404 Not Found response from s3, function BucketExists return err!=nil,it's err should be nil, exists is false

### ISSUE THREAD

**Issue by panfengAtInspur** [minio/minio-go#1036]
when I call function BucketExists,  it get resp "404 Not Found" from s3. In function BucketExists, it follows 
		if resp.StatusCode != http.StatusOK {
			return false, httpRespToErrorResponse(resp, bucketName, "")
		}
error content is 		case http.StatusNotFound:
			if objectName == "" {
				errResp = ErrorResponse{
					StatusCode: resp.StatusCode,
					Code:       "NoSuchBucket",
					Message:    "The specified bucket does not exist.",
					BucketName: bucketName,
				}
			}
its logic should be the same to 		if ToErrorResponse(err).Code == "NoSuchBucket" {
			return false, nil
		}

rerurn code: exists is false,err is nil, but now error is not nil, error is ErrorResponse{
					StatusCode: resp.StatusCode,
					Code:       "NoSuchBucket",
					Message:    "The specified bucket does not exist.",
					BucketName: bucketName,
				}

**Comment by nitisht** [comment]
Thanks for the issue @panfengAtInspur do you mind sending a fix / PR directly. Looks like you already have it. We can then review
