### ISSUE TITLE
minio-go handles keep-alive connections weirdly

### ISSUE THREAD

**Issue by GiedriusS** [minio/minio-go#1037]
haproxy that we have in front of our s3 ceph-based storage sometimes receives invalid requests and responds with 400:

```
<142>Sep 19 15:31:22 eewwqq666prveee[32584]: 1.2.3.4:48998 [19/Sep/2018:15:31:22.030] http~ http/<NOSRV> -1/-1/-1/-1/349 400 187 - - CR-- 332/332/0/0/0 0/0 "<BADREQ>"
```

What's interesting is that the code which uses minio-go does not do any requests itself when this error appears. I tested this hypothesis by invoking `TraceOn()` on a client object. This means that minio-go somewhere leaks goroutines which do invalid requests.
The software which uses minio-go is this: https://github.com/improbable-eng/thanos. Let me know if I can help you out somehow to find and fix this issue.

**Comment by harshavardhana** [comment]
> What's interesting is that the code which uses minio-go does not do any requests itself when this error appears. I tested this hypothesis by invoking `TraceOn()` on a client object. This means that minio-go somewhere leaks goroutines which do invalid requests.
> The software which uses minio-go is this: https://github.com/improbable-eng/thanos. Let me know if I can help you out somehow to find and fix this issue.

why do you think this is a minio-go problem? @GiedriusS minio-go has no active go-routines, minio-go is simply a wrapper around Go HTTP client with AWS protocol implementation.

What would be better is to get a wireshark dump of from the haproxy server so that we can intercept the offending HTTP message.

**Comment by GiedriusS** [comment]
I skimmed the `minio-go` code a bit and it seemed like it does indeed spawn goroutines but looks like I am wrong. Plus, I suspected `minio-go` at the beginning because the Thanos code itself isn't making any requests using `minio-go` when that message gets printed so there could only be two culprits: `minio-go` or Go's standard library's HTTP client implementation.

However, I tested a bit more and it seems that underneath Go's stdlib HTTP client sends keep alive probes from time to time on TCP connections that were already established. They do not contain any HTTP headers or any content. Afterward, I found out that HAProxy has a option called `http-ignore-probes`. That is not enabled *by default* and every probe that Go's stdlib HTTP client does makes haproxy print that message as stated in the original post.

Thus, perhaps we could document this in https://github.com/minio/minio-go/blob/master/docs/API.md or, in your opinion, does this note belong in projects which actually use `minio-go` such as Thanos?

**Comment by harshavardhana** [comment]
> Thus, perhaps we could document this in https://github.com/minio/minio-go/blob/master/docs/API.md or, in your opinion, does this note belong in projects which actually use `minio-go` such as Thanos?

I don't think this should be documented in minio-go, this is a standard approach used in keep-alive probing.  HAProxy is making this an option where they can clearly ignore these probes in the first place automatically.

> I skimmed the `minio-go` code a bit and it seemed like it does indeed spawn goroutines but looks like I am wrong. Plus, I suspected `minio-go` at the beginning because the Thanos code itself isn't making any requests using `minio-go` when that message gets printed so there could only be two culprits: `minio-go` or Go's standard library's HTTP client implementation.

These are all short-lived and only present until the input content reaches EOF.

**Comment by GiedriusS** [comment]
This issue was originally opened because I suspected those short-lived goroutines and didn't know that haproxy by default prints those messages for HTTP probes. I guess I will close the ticket because you think that this doesn't belong in `minio-go`'s documentation. Thank you very much for your help! :)
