### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by wzkun** [minio/minio-go#1046]
I use minio in docker.And  the uri host returned by 'PresignedGetObject' or 'PresignedPutObject' api  is likely 'http://dockerhost:19001/......',i need to change the host to the real ip address or  domain name.
But after the change,it results 'The request signature we calculated does not match the signature you provided. Check your key and signing method.'.
But it works in minio-js,how can i deal with this bug?

**Comment by wzkun** [comment]
But if i want to use domain name like 's3.xxxx.xxxxx.com' to replace 172.17.0.2 ,how can i do?

**Comment by kannappanr** [comment]
@wzkun if you want to use domain name like 's3.xxxx.xxxxx.com', then you would have to use that name to make the connection like in the given sample code. Once the URL is generated, you cannot change it. The IPAddress/domain name is used to calculate a signature. Changing it will make signature verification fail on the server side.

As far as this working in `minio-js`, I am not sure I understand what you mean there, can you please provide us a sample code  and tell us what you would do with a sample generated URL. 

The behavior should consistent across SDKs, so we would like to know if there is any issue there.

**Comment by wzkun** [comment]
We now use the real ip address to create Client. Thanks all. @kannappanr @poornas
