### ISSUE TITLE
How to get minio filepath list.

### ISSUE THREAD

**Issue by wzkun** [minio/minio-go#1051]
I store many files in minio,and each file's name is like 'pathname/filename'.How can I get pathname list from minio-go? @

**Comment by nitisht** [comment]
@wzkun pls take a look at `ListBuckets` and `ListObjects` API

- https://docs.minio.io/docs/golang-client-api-reference#ListBuckets
- https://docs.minio.io/docs/golang-client-api-reference#ListObjectsV2

Do join us on Slack(https://slack.minio.io) for more such questions

**Comment by kannappanr** [comment]
@wksun Closing this issue now. Please feel free to reach out to us if you have more questions.
