### ISSUE TITLE
Failed dep ensure with minio-go import because of github.com/minio/go-homedir dep.

### ISSUE THREAD

**Issue by antonioazcoita** [minio/minio-go#1063]
Hi all,

I am having an error when from yesterday when I try to launch build a golang project using minio-go package. I get the following error:

Solving failure: 
	(1) failed to list versions for https://github.com/minio/go-homedir: fatal: could not read Username for 'https://github.com': terminal prompts disabled
: exit status 128
	(2) failed to list versions for ssh://git@github.com/minio/go-homedir: Host key verification failed.
fatal: Could not read from remote repository.

I have checked that the https://github.com/minio/go-homedir does not exist anymore and a new package for go-homedir dependencia is used: github.com/mitchellh/go-homedir

I do not know how to solve it because as it is an internal dependency of minio-go.  Is there any workaround to solve it?

Many thanks in advance.

Toni

**Comment by harshavardhana** [comment]
We have moved to `mitchellh/go-homedir` a long time ago @antonioazcoita - you must haven't checked the latest source - all you have to do this grep for it

```
~ git grep go-homedir
pkg/credentials/file_aws_credentials.go:        homedir "github.com/mitchellh/go-homedir"
pkg/credentials/file_minio_client.go:   homedir "github.com/mitchellh/go-homedir"
```

**Comment by antonioazcoita** [comment]
Many thanks for the response @harshavardhana.

Dep ensure this not get it and as it is dockerized , finally I installed it manually with go get and ignore it in dep ensure from Gopkg.toml and it works.
