### ISSUE TITLE
Endless cycle if io.ReadFull returns io.ErrUnexpectedEOF? or not?

### ISSUE THREAD

**Issue by dmitryrpm** [minio/minio-go#1071]
https://github.com/minio/minio-go/blob/c8a261de75c1a9a9ece4dcc0c81ff6db525bcf27/api-put-object.go#L215

In this loop if ReadFull returns io.ErrUnexpectedEOF - we down to endless circle... 
for example we are uploading bigfile, but io.Reader closed with io.Unexpected error

please check it)

**Comment by kannappanr** [comment]
@dmitryrpm Thanks for filing this issue. We will take a look.

**Comment by harshavardhana** [comment]
@dmitryrpm please provide a test program? - we don't have a way to reproduce. 

> but io.Reader closed with io.Unexpected error

https://golang.org/pkg/io/#Reader are you writing your own custom io.Reader?

**Comment by dmitryrpm** [comment]
Sorry, I understood what happened in my own code, it is reader without close!
Closed issue
