### ISSUE TITLE
 If AccessKey and SecretAccessKey could not be resolved - credentials will never be cached

### ISSUE THREAD

**Issue by d-ulyanov** [minio/minio-go#1072]
Hi, minio team!

If AccessKey and SecretAccessKey could not be resolved - credentials will never be cached.
Such situation is possible in EnvAWS provider if Env variables is empty or not exists.

But there is a case when we're accessing bucket in anonymous mode.

https://github.com/minio/minio-go/blob/master/pkg/credentials/chain.go#L68
https://github.com/minio/minio-go/blob/master/pkg/credentials/env_aws.go#L60

**Comment by harshavardhana** [comment]
yes, but in such situation is what is the point of setting ENVs? can you simply not use minio.New("", "") credentials handling is for situations when credentials are available if they are not its generally meaningless. 

Also one can write their own credential provider which basically is only implemented for anonymous access.

**Comment by d-ulyanov** [comment]
Hi, @harshavardhana!

We caught this behaviour in Thanos Store, which inits minio with following chain:
```
		chain = []credentials.Provider{
			&credentials.EnvAWS{},
			&credentials.FileAWSCredentials{},
			&credentials.IAM{
				Client: &http.Client{
					Transport: http.DefaultTransport,
				},
			},
		}
```
 
We have no AccessKey and  SecretAccessKey anywhere including ENV variables: only S3 endpoint and bucket name (bucket allows anonymous RW access).

It could be reasonable to cache empty credentials in chain if last provider returned empty values.
What do you think?

**Comment by harshavardhana** [comment]
> Hi, @harshavardhana!
> 
> We caught this behaviour in Thanos Store, which inits minio with following chain:
> 
> ```
> 		chain = []credentials.Provider{
> 			&credentials.EnvAWS{},
> 			&credentials.FileAWSCredentials{},
> 			&credentials.IAM{
> 				Client: &http.Client{
> 					Transport: http.DefaultTransport,
> 				},
> 			},
> 		}
> ```
> We have no AccessKey and SecretAccessKey anywhere including ENV variables: only S3 endpoint and bucket name (bucket allows anonymous RW access).
> 
> It could be reasonable to cache empty credentials in chain if last provider returned empty values.
> What do you think?

@d-ulyanov that will be unexpected from a chain point of view, chain means we honor the chain and credentials cannot be considered empty.  FWIW Thanos requires the credentials I am not sure if all anonymous can actually work. 

If there is a clear requirement for anonymous what could be done is simply to have an anonymous provider and this complies with the `credentials.Provider` interface.

```
chain = []credentials.Provider{
			&credentials.EnvAWS{},
			&credentials.FileAWSCredentials{},
			&credentials.IAM{
				Client: &http.Client{
					Transport: http.DefaultTransport,
				},
			},
                       &anonymous{}
		}
```

**Comment by d-ulyanov** [comment]
Ok, I've got your point, but it's still unclear what the reason to execute all chain's providers if all of them returned nothing? 
Is it for the case when I want to add ENV variables after starting my app? From my point of view in such cases its better to listen signals in app and reinitialise configuration explicitly.

**Comment by harshavardhana** [comment]
> Ok, I've got your point, but it's still unclear what the reason to execute all chain's providers if all of them returned nothing?
> Is it for the case when I want to add ENV variables after starting my app? From my point of view in such cases its better to listen signals in app and reinitialise configuration explicitly.

Chaining is meant for an order of things to pick from whatever is available, once the credentials are provided by one of the chains then its always going to be used until expires.  So if IsExpired() if returns false we never try to retrieve further. Anonymous credentials are considered to be always expired - that it is considered odd that you want the chain of credentials but you don't provide any mechanism to fetch credentials from. Thanos is designed correctly i.e it doesn't support anonymous credentials - it is doing that but with a penalty that it tries to fetch the credentials appropriately. 

Now with your specialized use case - write a new anonymous provider which simply returns empty creds and also says that these creds don't expire at all.  If you comply with this then we will never try to Retrieve from other providers. The downside is that anonymous will be always used until you restart the service.

**Comment by d-ulyanov** [comment]
Thanks for your answer @harshavardhana 

It seems that I can't use anonymous provider and mark it as unexpireable as you recommended, because chain will always skip provider which returns empty `creds.AccessKeyID == "" && creds.SecretAccessKey == ""`

```
func (c *Chain) Retrieve() (Value, error) {
	for _, p := range c.Providers {
		creds, _ := p.Retrieve()
		// Always prioritize non-anonymous providers, if any.
		if creds.AccessKeyID == "" && creds.SecretAccessKey == "" {
			continue
		}
		c.curr = p
		return creds, nil
	}
...
```

**Comment by d-ulyanov** [comment]
up

**Comment by harshavardhana** [comment]
The only way to fix this is @d-ulyanov to create two instances - one has an `--anonymous` mode and another non-anonymous.  Anonymous simply uses minio.New() with empty credentials.

I do not wish to change credentials package to support Anonymous because that's not its purpose, and this is a really a corner case usage of using unauthenticated access. So Thanos can provide a special flag if you wish to run in an anonymous mode without any signature.

**Comment by d-ulyanov** [comment]
Okay, got your point, and thanks for the reply
