### ISSUE TITLE
Allow changing the DefaultExpiryWindow for IAM credentials

### ISSUE THREAD

**Issue by dvelitchkov** [minio/minio-go#1075]
The `DefaultExpiryWindow` is hard-coded to 10 seconds - https://github.com/minio/minio-go/blob/master/pkg/credentials/iam_aws.go#L37 According to the official AWS IAM docs, the minimum amount of time that creds are valid for is 15 *minutes*. Seems a bit excessive to hit the EC2 metadata endpoint every 10 seconds? 

It normally isn't an issue, but we're running in EKS and using kube2iam to map IAM roles and hitting an issue with kube2iam (not this lib) that has to do with kube2iam being unable to handle too many requests at once. 

As a side question - and I'm sorry for sounding annoyed, but - *why* are you not using the *official* Go AWS SDK for S3? All of this (and god knows what else) could've been avoided if you hadn't rolled your own artisinal S3 client.

**Comment by harshavardhana** [comment]
@dvelitchkov the comment explains it properly - it's an expiring window - we don't hit the server unless its last 10 seconds. 

```
// DefaultExpiryWindow - Default expiry window.
// ExpiryWindow will allow the credentials to trigger refreshing
// prior to the credentials actually expiring. This is beneficial
// so race conditions with expiring credentials do not cause
// request to fail unexpectedly due to ExpiredTokenException exceptions.
```

So its 15minutes - 10secs when we trigger refresh.

**Comment by harshavardhana** [comment]
> As a side question - and I'm sorry for sounding annoyed, but - _why_ are you not using the _official_ Go AWS SDK for S3? All of this (and god knows what else) could've been avoided if you hadn't rolled your own artisinal S3 client.

minio-go is a simpler SDK with abstracted APIs and provides more richer go idiomatic functionalities. It also allows us to implement newer improved APIs beyond S3 so a client SDK is an important requirement for us.

**Comment by kannappanr** [comment]
@dvelitchkov Closing this issue based on the previous comments. Please feel free to reach out to us for further questions.
