### ISSUE TITLE
How to check if object exists

### ISSUE THREAD

**Issue by MichaHoffmann** [minio/minio-go#1082]
Is there a more idiomatic way to check if an object exists in a bucket then 
```
var (
	doesNotExist = "The specified key does not exist."
)
func objectExists(bucket, name string client *minio.Client) (bool, error) {
	_, err := client.StatObject(bucket, name, minio.StatObjectOptions{})
	if err != nil {
		switch err.Error() {
		case doesNotExist:
			return false, nil
		default:
			return false, errors.Wrap(err, "error stating object")
		}
	}
        return true, nil
}
```

This seems to work for now; but explicitly checking for a non-exported error string seems fragile to me.

Edit: it could be helpful to export error constants, so one could switch for something like `case s3errors.ObjectDoesNotExist`

**Comment by nitisht** [comment]
`client.StatObject` is the idiomatic way @MichaHoffmann rest is up to your applications requirements..

**Comment by MichaHoffmann** [comment]
But, to know if the object does not exist, one has to compare the error message string, to distinguish it from connectivity issues, right? It may be helpful to introduce error constants if thats the case.

**Comment by nitisht** [comment]
> It may be helpful to introduce error constants if thats the case.

That may be helpful, let me discuss with the team...

**Comment by vadmeste** [comment]
@MichaHoffmann mc does this way:

```
        objectStat, e := c.api.StatObject(bucket, object, opts)
        if e != nil {
                errResponse := minio.ToErrorResponse(e)
                if errResponse.Code == "AccessDenied" {
                        return nil, probe.NewError(PathInsufficientPermission{Path: c.targetURL.String()})
                }
                if errResponse.Code == "NoSuchBucket" {
                        return nil, probe.NewError(BucketDoesNotExist{
                                Bucket: bucket,
                        })
                }
                if errResponse.Code == "InvalidBucketName" {
                        return nil, probe.NewError(BucketInvalid{
                                Bucket: bucket,
                        })
                }
                if errResponse.Code == "NoSuchKey" {
                        return nil, probe.NewError(ObjectMissing{})
                }
                return nil, probe.NewError(e)
        }
```

That way it is possible to better analyze the reason of the failure (NoSuchKey) in your case

**Comment by MichaHoffmann** [comment]
Thank you, my only concern with that is that the `errResponse.Code` is a string. If i'm using minio-go as an SDK; for all i know that string could change. If `errResponse.Code` would be using (exported) constants, i could import them and would not need to worry about such changes.

**Comment by vadmeste** [comment]
@MichaHoffmann those strings are a part of S3 spec that didn't change for more than ten years and it won't.

**Comment by MichaHoffmann** [comment]
Fair enough, thank you for your replies.
