### ISSUE TITLE
Error to to retrieve new notifications at ListenBucketNotification channel

### ISSUE THREAD

**Issue by frieser** [minio/minio-go#1084]
Hello,

I'm facing the following error at listening new notification events in a Minio bucket:

1.- I set to listen the following events:

```go
go func() {
		// Create a done channel to control 'ListenBucketNotification' go routine.
		done := make(chan struct{})

		// Indicate a background go-routine to exit cleanly upon return.
		defer close(done)

		// Listen for bucket notifications on the bucket filtered by prefix, suffix and events.
		for notificationInfo := range c.client.ListenBucketNotification(bucketName, "", "", []string{
			"s3:ObjectCreated:Post",
			"s3:ObjectCreated:Put",
		}, done) {
			if notificationInfo.Err != nil {
				response <- &backend.Response{Error: notificationInfo.Err}
				continue
			}
			value, err := c.getPairValue(key)

			if err != nil {
				response <- &backend.Response{Error: err}
			}
			response <- &backend.Response{Value: value}
		}
	}()
```

2.- I receive the notification errors with the following notificationInfo.Err when I made a change in the bucket:

`Connection closed by foreign host http://scality:8000/titanbucket/?events=s3%3AObjectCreated%3APost&events=s3%3AObjectCreated%3APut&prefix=&suffix=. Retry again.`

3. The minio server logs the following error and restart the service:

`scality_1   | {"name":"S3","clientIP":"::ffff:172.18.0.1","clientPort":55968,"httpMethod":"GET","httpURL":"/titanbucket/?events=s3%3AObjectCreated%3APost&events=s3%3AObjectCreated%3APut&prefix=&suffix=","time":1551697069429,"req_id":"52f4b94d074f93bd0b40","level":"info","message":"received request","hostname":"73c478b4c8bd","pid":502}
scality_1   | {"name":"S3","time":1551697069468,"error":"input.charAt is not a function","stack":"TypeError: input.charAt is not a function\n    at awsURIencode (/usr/src/app/node_modules/arsenal/lib/auth/v4/awsURIencode.js:39:26)\n    at Object.keys.sort.map.key (/usr/src/app/node_modules/arsenal/lib/auth/v4/createCanonicalRequest.js:48:41)\n    at Array.map (native)\n    at createCanonicalRequest (/usr/src/app/node_modules/arsenal/lib/auth/v4/createCanonicalRequest.js:46:62)\n    at constructStringToSign (/usr/src/app/node_modules/arsenal/lib/auth/v4/constructStringToSign.js:17:32)\n    at Object.check [as headers] (/usr/src/app/node_modules/arsenal/lib/auth/v4/headerAuthCheck.js:130:26)\n    at extractParams (/usr/src/app/node_modules/arsenal/lib/auth/auth.js:93:47)\n    at Object.doAuth (/usr/src/app/node_modules/arsenal/lib/auth/auth.js:114:17)\n    at Object.callApiMethod (/usr/src/app/lib/api/api.js:85:28)\n    at routerGET (/usr/src/app/node_modules/arsenal/lib/s3routes/routes/routeGET.js:71:17)\n    at routes (/usr/src/app/node_modules/arsenal/lib/s3routes/routes.js:231:12)\n    at Server.routeRequest (/usr/src/app/lib/server.js:81:9)\n    at emitTwo (events.js:106:13)\n    at Server.emit (events.js:191:7)\n    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)","workerId":42,"workerPid":502,"level":"fatal","message":"caught error","hostname":"73c478b4c8bd","pid":502}
`

and restart the service

`scality_1   | {"name":"S3","time":1551697069469,"workerId":42,"workerPid":502,"level":"error","message":"shutdown of worker due to exception","hostname":"73c478b4c8bd","pid":502}
scality_1   | {"name":"S3","time":1551697069473,"workerId":42,"workerPid":502,"level":"error","message":"worker disconnected. making sure exits","hostname":"73c478b4c8bd","pid":57}
scality_1   | {"name":"S3","time":1551697069487,"workerId":42,"workerPid":502,"level":"error","message":"worker exited.","hostname":"73c478b4c8bd","pid":57}
scality_1   | {"name":"S3","time":1551697070376,"workerId":52,"workerPid":639,"level":"info","message":"new worker forked","hostname":"73c478b4c8bd","pid":57}
scality_1   | {"name":"MetadataFileClient","time":1551697071339,"level":"info","message":"connecting to metadata service at http://localhost:9990/MDFile/metadata","hostname":"73c478b4c8bd","pid":639}
scality_1   | {"name":"S3","time":1551697071363,"level":"warn","message":"scality kms unavailable. Using file kms backend unless mem specified.","hostname":"73c478b4c8bd","pid":639}
scality_1   | {"name":"S3","time":1551697071422,"https":false,"level":"info","message":"Http server configuration","hostname":"73c478b4c8bd","pid":639}
scality_1   | {"name":"S3","time":1551697071427,"address":"::","port":8000,"pid":639,"level":"info","message":"server started","hostname":"73c478b4c8bd"}`

So the error is in the minio SDK that logs is :
`error":"input.charAt is not a function","stack":"TypeError: input.charAt is not a function\n    at awsURIencode (/usr/src/app/node_modules/arsenal/lib/auth/v4/awsURIencode.js:39:26)\n  `

What I am missing? I read in the README something like:

`listenbucketnotification.go (Minio Extension)`

What is this minio extension? Maybe I need something to get the notifications to work? It sounds like a query string codification error?

Thank you in advance.

**Comment by nitisht** [comment]
Can you explain a bit on how you started the server @frieser also the args to create minio-go client

**Comment by frieser** [comment]
Thanks for the quick reply,

The server is in a docker container running from the official docker hub image https://hub.docker.com/r/scality/s3server/ from the latest tag https://github.com/scality/S3/blob/6018536acaf1969a9a8425e45be8b6c01b82c5e5/Dockerfile

This is my docker file that extends the official image that get data into it:

```Dockerfile
# SCALITY defaul env
ENV SCALITY_ACCESS_KEY_ID xxxxx
ENV SCALITY_SECRET_ACCESS_KEY xxxx
ENV ENDPOINT scality

# Setting data and metadata folders
ENV S3DATAPATH /usr/src/app/example-data/localData
ENV S3METADATAPATH /usr/src/app/example-data/localMetadata

# OS dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
		unzip \
		s3cmd \
	&& rm -rf /var/lib/apt/lists/*

# Copy initial configuration files for example metadata
ADD example_volume.zip /tmp/example_volume.zip

# Extract files
RUN mkdir /usr/src/app/example-data
RUN unzip -q /tmp/example_volume.zip -d /usr/src/app/example-data

# Clean unnecesary tools
RUN apt-get remove -y unzip

#Removing temporary files
RUN rm -f /tmp/scality_volume.zip
```

The minio client is initialized liked that:
```golang
mc, err := minio.New(endpoint, accessKeyID, secretAccessKey, false)
```

**Comment by nitisht** [comment]
well looks like Scality doesn't support Event notifications, additionally the Bucket Notification API is minio custom API so it is not expected to work

**Comment by frieser** [comment]
Ok, thanks for the help. It makes sense.
