### ISSUE TITLE
custom headers are not carried with further requests

### ISSUE THREAD

**Issue by nullne** [minio/minio-go#1085]
as mentioned in the heading,  custom header are not carried with further requests in some cases.

#####  new request
it seems that there will be a `getBucketLocationRequest` before every request in some cases. this request didn't carry the custom header

##### PUT
when upload an object whose size is larger than 64M, it will using multipart. Except first POST request carries the custom header, the following requests don't.

sample code
```
      options := minio.PutObjectOptions{
          UserMetadata: make(map[string]string),
      }
      options.UserMetadata["Cluster-Id"] = "02"
      reader := bytes.NewReader([]byte{})
      _, err = client.PutObjec("bucketName", "objectKey", reader.Size(), options)
      if err != nil {
          panic(err)
      }
```

in  `uploadPart` function  `github.com/minio/minio-go/api-put-object-multipart.go` , we can see the custom header are not passed to the header
```
    // Set encryption headers, if any.
    customHeader := make(http.Header)
    // https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html
    // Server-side encryption is supported by the S3 Multipart Upload actions.
    // Unless you are using a customer-provided encryption key, you don't need
    // to specify the encryption parameters in each UploadPart request.
    if sse != nil && sse.Type() == encrypt.SSEC {
        sse.Marshal(customHeader)
    }

    reqMetadata := requestMetadata{
        bucketName:       bucketName,
        objectName:       objectName,
        queryValues:      urlValues,
        customHeader:     customHeader,
        contentBody:      reader,
        contentLength:    size,
        contentMD5Base64: md5Base64,
        contentSHA256Hex: sha256Hex,
    }
```

maybe there are other cases i haven't found. In my scenario we use the custom header to identify different minio cluster since the storage of one cluster is limited.

i am happy to submit PR to fix this. Before that i should make sure whether  this is a problem, right ?

**Comment by harshavardhana** [comment]
Yes it is expected as part of S3 API, user metadata is a custom metadata for an object, so it is not meant for passing it around in all API operations.

What is the use case?

**Comment by kannappanr** [comment]
@nullne We cannot pass around custom header in between multi-part API calls. Can you please provide us with more info? Closing this until then.

**Comment by nullne** [comment]
thanks you guys.  we talked about this in slack channel, and worked it out by invoking `SetCustomTransport` of `minio.Client`
