### ISSUE TITLE
Issue with setting bucket lifecycle

### ISSUE THREAD

**Issue by aniztar** [minio/minio-go#1087]
When I try to set the bucket lifecycle, I get the following error - 

`A header you provided implies functionality that is not implemented`

I am trying the following - 

```
lifecycle := `<LifecycleConfiguration>
 <Rule>
   <ID>expire-bucket</ID>
   <Prefix></Prefix>
   <Status>Enabled</Status>
   <Expiration>
     <Days>365</Days>
   </Expiration>
 </Rule>
</LifecycleConfiguration>`

err = minioClient.SetBucketLifecycle("my-bucketname", lifecycle)
if err != nil {
    fmt.Println(err)
    return
}
```
What am I missing here?

**Comment by vadmeste** [comment]
@aniztar are you testing against Minio server ? because bucket lifecycle is not implemented yet

**Comment by kannappanr** [comment]
@anitzar Closing this issue assuming that you are connecting to `minio` server. Even if it is not `minio`, we cannot do anything about it as `minio-go` just displays the error returned by the server. please feel free to re-open the issue if you feel otherwise.

**Comment by aniztar** [comment]
Yes, I am connecting to minio server. I saw the api on this page - https://docs.minio.io/docs/golang-client-api-reference#SetBucketLifecycle
Since it was published on the page, I assumed it works. If it doesn't work against minio server, then which all supports this API?

**Comment by harshavardhana** [comment]
AWS S3 supports this API.

**Comment by kannappanr** [comment]
@aniztar minio-go is a client SDK and will work against any S3 server. We do not add just support for client side APIs that will work only against minio.

**Comment by aniztar** [comment]
> @aniztar are you testing against Minio server ? because bucket lifecycle is not implemented yet

Do you mean to say that bucket lifecycle is not implemented in minio server?

**Comment by vadmeste** [comment]
> @vadmeste Do you mean to say that bucket lifecycle is not implemented in minio server?

Yes exactly

**Comment by DHATRIBR** [comment]
Hi, is there any expected release date by which this set bucket lifecycle will be supported?

**Comment by vadmeste** [comment]
> Hi, is there any expected release date by which this set bucket lifecycle will be supported?

Expiry feature of bucket lifecycle is already implemented and released. Transition is planned but not fixed ETA

**Comment by DHATRIBR** [comment]
Okay, Thanks
