### ISSUE TITLE
Module incompatibility

### ISSUE THREAD

**Issue by ebati** [minio/minio-go#1088]
minio-go uses `go.mod` but it does not declare itself as v6. This makes using v6.0.15 and later harder as it is incompatible with semantic import versioning. 

I saw PR(#1021) from @marwan-at-work which changes the import paths and have version in go.mod, which is I think better way to move on to modules. It would be even better to include go.mod file and change imports to have major version in the next major version release [as suggested in module documentation](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher).

[Related documentation](https://github.com/golang/go/wiki/Modules#semantic-import-versioning)
> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.0) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg").

**Comment by nitisht** [comment]
thanks for reporting @ebati we’ll take a look

**Comment by harshavardhana** [comment]
@ebati feel free to send a fix

**Comment by ebati** [comment]
What is the agreed solution here? Do you want to create new major version(v7)?

**Comment by harshavardhana** [comment]
Why not v6 ?

**Comment by harshavardhana** [comment]
Also if you want to update you can update to `go get -u github.com/minio/minio-go@v6.0.18`

My concern is `go mod` is asking us to do some weird form of import styles.

**Comment by ebati** [comment]
After getting minio-go with `go get -u github.com/minio/minio-go@v6.0.18`, downloaded version is not listed as `v6.0.18` but listed as `v0.0.0-20190223084638-008c7aa71fc1` in `go.mod` file and also `v6.0.14` is shown as update in `go list -m -u all` as below
`github.com/minio/minio-go v0.0.0-20190223084638-008c7aa71fc1 [v6.0.14+incompatible]`

Editing `go.mod` file manually and writing `v6.0.14` solves `v0.0.0-*` problem but `v6.0.14` is still shown as update.

Moving forward with modules requires "weird" import style. AFAIK, it is necessary to be able to handle importing multiple version of the same module. Also, since having different major version shows different APIs, it is understandable to differentiate them with different import paths.

I believe that removing `go.mod` file is a better option than putting an incompatible `go.mod` file.

**Comment by harshavardhana** [comment]
> I believe that removing `go.mod` file is a better option than putting an incompatible `go.mod` file.

I guess removing `go.mod` is perhaps acceptable for now.  The import styles are really not the way it should have been implemented.  Migrating to newer versions such as v7 becomes even more problematic. Our releases are really automated and taking care of manually creating these directories in a git repo - when we move to the next major version is just going to be painful.

**Comment by harshavardhana** [comment]
Will fix this properly, as I figured there is a more easier way.

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio-go/pull/1111
