### ISSUE TITLE
How to check connection?

### ISSUE THREAD

**Issue by yazver** [minio/minio-go#1095]
How to check connection to Minio?

**Comment by nitisht** [comment]
can you elaborate @yazver ?

you can use these examples https://github.com/minio/minio-go/tree/master/examples/s3 to connect to your Minio instance.

**Comment by yazver** [comment]
I need to check connection to Minio instance without doing any operations (Ping).

**Comment by nitisht** [comment]
you can try this https://github.com/minio/minio/blob/master/docs/metrics/healthcheck/README.md

**Comment by harshavardhana** [comment]
Closing this issue as answered. Please join our community https://slack.minio.io for real-time discussions.
