### ISSUE TITLE
Option for disabling SHA256 signatures

### ISSUE THREAD

**Issue by Ape** [minio/minio-go#1098]
I would like to request an option for disabling the SHA256 signatures. I am using a local minio server and I don't believe the SHA256 signature are of any use in my use case.

This is important to me because profiling the client application shows that the SHA256 calculations in minio-go take around 25% of all cpu time used by the application.

```
0.044% 11.87s 26.05% github.com/minio/minio-go/pkg/s3signer.(*StreamingReader).Read
0.044% 11.45s 25.13% github.com/minio/minio-go/pkg/s3signer.(*StreamingReader).signChunk
0.044% 11.24s 24.67% github.com/minio/minio-go/pkg/s3signer.buildChunkSignature
24.21% 10.68s 23.44% github.com/minio/minio-go/pkg/s3signer.buildChunkStringToSign
24.21% 10.65s 23.38% github.com/minio/minio-go/pkg/s3signer.sum256
```

The application needs to make lots of file operations by design and the performace is a problem in some cases.

**Comment by harshavardhana** [comment]
Just use a TLS enabled server @Ape sha256 will be disabled.

**Comment by kannappanr** [comment]
@Ape Closing this issue based on the previous response. Please feel free to reach out to us if you have further questions.

**Comment by Ape** [comment]
@harshavardhana Thanks, I will try that. However, I don't really benefit from TLS itself since my application and the minio server are running inside docker containers and have very restricted access.

I think TLS would also have some performance implications and it requires certificate creation. Is there a way to disable both TLS and the SHA256 checksums?

**Comment by Ape** [comment]
I profiled the TLS version and it is indeed an improvement to the previous version. However, TLS itself still takes a significant amount of CPU time:

```
3.09s 7.86% crypto/tls.(*Conn).write
2.86s 7.28% crypto/tls.(*halfConn).encrypt
2.79s 7.10% crypto/tls.(*xorNonceAEAD).Seal
2.76s 7.02% golang_org/x/crypto/chacha20poly1305.(*chacha20poly1305).Seal
2.73s 6.94% golang_org/x/crypto/chacha20poly1305.(*chacha20poly1305).seal
2.68s 6.82% golang_org/x/crypto/chacha20poly1305.chacha20Poly1305Seal
```

**Comment by harshavardhana** [comment]
Well, there is nothing we can do about that @Ape - SHA256 is required by AWS S3 and without TLS is the only way to securely and correctly upload your content. 

It is part of the S3 protocol behavior - we don't want to make it optimal. Since content-integrity and security are not optional entities.
