### ISSUE TITLE
Missing return statement in optimalPartInfo?

### ISSUE THREAD

**Issue by MrCreosote** [minio/minio-go#1099]
https://github.com/minio/minio-go/blob/80c2fe34f1a5d3ade9fc79758f8faafaa149105b/api-put-object-common.go#L87-L89

Should there be a return here? I called PutObject with a size of -1 and a part size of 5MiB and was surprised to see that a 12GB file only had 23 parts, implying a ~500MiB part size.

I assume the code fell through the error (which would be triggered by a 5TiB size [which is assigned for -1 size values] and 5MiB parts) and calculated the part size based on the maximum object size and 10k parts.

**Comment by poornas** [comment]
Thanks @MrCreosote , that's a great catch. Sending a PR to fix this.
