### ISSUE TITLE
How to set the speed of GetObject or PutObject?

### ISSUE THREAD

**Issue by QiuMP** [minio/minio-go#1103]
Is it any way to set the limited speed for GetObject or PutObject?

**Comment by kannappanr** [comment]
@QiuMP I don't think you can do it. You can probably look to do this externally, instead of `minio-go`.

**Comment by harshavardhana** [comment]
Idea is you should write your own reader or writer to limit the bandwidth, we allow taking such readers.. AFAICS this is out of scope for minio-go

**Comment by QiuMP** [comment]
OK, I will try to write own reader or writer to limit the bandwidth.
Thanks.

**Comment by harshavardhana** [comment]
Thanks
