### ISSUE TITLE
Get the Content-Range header in (Core) GetObject

### ISSUE THREAD

**Issue by shubham1172** [minio/minio-go#1106]
While getting a range request's response, how to get the Content-Range? The ObjectInfo struct does not seem to contain it!

**Comment by harshavardhana** [comment]
Can you provide a sample code that you are trying for us to help you out?

**Comment by shubham1172** [comment]
Sure,

```golang
objectOptions := minio.GetObjectOptions{}
objectOptions.Header().Set("Range", _range) 
object, info, err := GetCore().GetObject(config.GetConfig().MinioBucket, key, objectOptions)
```

Now. info is the `ObjectInfo` struct, which is given in docs as:
```golang
type ObjectInfo struct {
    // An ETag is optionally set to md5sum of an object.  In case of multipart objects,
    // ETag is of the form MD5SUM-N where MD5SUM is md5sum of all individual md5sums of
    // each parts concatenated into one string.
    ETag string `json:"etag"`

    Key          string    `json:"name"`         // Name of the object
    LastModified time.Time `json:"lastModified"` // Date and time the object was last modified.
    Size         int64     `json:"size"`         // Size in bytes of the object.
    ContentType  string    `json:"contentType"`  // A standard MIME type describing the format of the object data.
    Expires      time.Time `json:"expires"`      // The date and time at which the object is no longer able to be cached.

    // Collection of additional metadata on the object.
    // eg: x-amz-meta-*, content-encoding etc.
    Metadata http.Header `json:"metadata" xml:"-"`

    // Owner name.
    Owner struct {
        DisplayName string `json:"name"`
        ID          string `json:"id"`
    }   `json:"owner"`

    // The class of storage used to store the object.
    StorageClass string `json:"storageClass"`

    // Error
    Err error `json:"-"`
}
```

I am trying to write a video streaming service which accepts partial requests. Earlier when using s3, I could get the header 'Content-Range` from s3ObjectOutput. However, this ObjectInfo struct does not seem to have it.

**Comment by kannappanr** [comment]
@shubham1172 You can generate `pre-signed get object` URL using `PresignedGetObject` API in `minio-go` 

Then you can use something like this ```
curl -v  -H "Range: bytes=1-5" "httplay.min.io:9000/test/issue?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20190522%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190522T214625Z&X-Amz-Expires=1000&X-Amz-SignedHeaders=host&X-Amz-Signature=713cf0fc81b3d94782b427bf226331a8c241f336503cdbeea7fe53a0b5ca032e"

```
This way the client can directly get the data from MinIO/S3. Let us know if this works for you.

**Comment by shubham1172** [comment]
Actually, I want to process the video stream before sending it to the client; So I will need to pass the data _through_ the server.

**Comment by kannappanr** [comment]
Will talk internally and see if we can expose all the response headers returned by MinIO as a map. In the meantime, you can also use pre-signed URL.

**Comment by kannappanr** [comment]
@shubham1172 We decided to return the response headers as part of GetObject, so you do not have to access it through Core.

**Comment by shubham1172** [comment]
Awesome! That'll be great.
