### ISSUE TITLE
Getting blank IAM security credential

### ISSUE THREAD

**Issue by shernshiou** [minio/minio-go#1114]
In some instance, querying `http://169.254.169.254/latest/meta-data/iam/security-credentials` (without slash) will return blank instead of the credential.

The workaround is to add additional slash behind the url. 

Reference: https://stackoverflow.com/questions/51925697/aws-ec2-metadata-for-security-credentials-gives-empty-response

**Comment by kannappanr** [comment]
@shernshiou  Thanks for the PR. Closing this issue as fixed by #1115
