### ISSUE TITLE
Add a new switch to explicitly control whether or not to use the virtual-hosted style

### ISSUE THREAD

**Issue by aofei** [minio/minio-go#1119]
The [`s3utils.IsVirtualHostSupported`](https://godoc.org/github.com/minio/minio-go/pkg/s3utils#IsVirtualHostSupported) is only compatible with Amazon S3 and Google Cloud Storage currently. That's not fair. In fact, there're other cloud service providers that are using the virtual-hosted style, such as [DigitalOcean Spaces](https://www.digitalocean.com/products/spaces/), [Alibaba Cloud OSS](https://www.alibabacloud.com/product/oss) and [Qiniu Cloud Kodo](https://www.qiniu.com/en/products/kodo). I really like to use minio-go to connect to all the Amazon S3 compatible object storage services. So, please consider adding a switch that can explicitly control whether or not to use the virtual-hosted style. :-)

**Comment by harshavardhana** [comment]
We already have it @aofei look at minio.NewWithOptions() and passing the options.BucketLookup

**Comment by aofei** [comment]
I tired just now, but both `minio.BucketLookupDNS` and `minio.BucketLookupPath` aren't work for [Alibaba Cloud OSS](https://www.alibabacloud.com/product/oss).

**Comment by harshavardhana** [comment]
Why would they not work?

**Comment by harshavardhana** [comment]
If Alibaba is not S3 compatible then support in minio-go is outside the scope of this project.

**Comment by aofei** [comment]
It's S3 compatible, I'm sure that. I'm digging the minio-go's code now. I'd love to know why it doesn't work for Alibaba Cloud OSS.

**Comment by harshavardhana** [comment]
Can you show me document where Alibaba says they are S3 compatible?

**Comment by harshavardhana** [comment]
And also what is the API that you are trying to use AFAIK Alibaba doesn't implement all S3 like APIs..

**Comment by aofei** [comment]
See https://www.alibabacloud.com/help/doc-detail/64919.htm. And I just use the get&put object API, no more.

**Comment by aofei** [comment]
I can provide you a pair of temporary access key and secret key. Do you want to test it on your side?

**Comment by harshavardhana** [comment]
It's not just get put do they implement getBucketLocation etc like APIs, if they don't then it won't work.

**Comment by aofei** [comment]
Alibaba Cloud OSS Compatible S3 APIs:

* Bucket operations:
  * Delete Bucket
  * Get Bucket (list objects)
  * Get Bucket ACL
  * Get Bucket lifecycle
  * _**Get Bucket location**_
  * Get bucket Logging
  * Head Bucket
  * Put Bucket
  * Put Bucket ACL
  * Put Bucket lifecycle
  * Put Bucket logging
* Object operations:
  * Delete Object
  * Delete Objects
  * Get Object
  * Get Object ACL
  * Head Object
  * Post Object
  * Put Object
  * Put Object Copy
  * Put Object ACL
* Multipart operations:
  * Abort Multipart Upload
  * Complete Multipart Upload
  * Initiate Multipart Upload
  * List Parts
  * Upload Part
  * Upload Part Copy

**Comment by harshavardhana** [comment]
It won't work @aofei because the XML namespace input is wrong. Alibaba choose to change xmlns value which is incompatible with what we expect. 

So it cannot be supported, you may fork minio-go and write your own support. But it can't be included in master branch.

**Comment by aofei** [comment]
Got it.

**Comment by aofei** [comment]
Sorry, I forgot to thank you. Sincerely thank you for your patience in helping me solve the problem. Have a good day! :-)

**Comment by harshavardhana** [comment]
> Sorry, I forgot to thank you. Sincerely thank you for your patience in helping me solve the problem. Have a good day! :-)

No problem always here to help! :clinking_glasses:  @aofei
