### ISSUE TITLE
why is core.GetObject doesn't have context as first parameter

### ISSUE THREAD

**Issue by jackielii** [minio/minio-go#1127]
`core` package's getObject function's signature is: 
```
func (c Client) getObject(ctx context.Context, bucketName, objectName string, opts GetObjectOptions) (io.ReadCloser, ObjectInfo, error) 
```
why is the core.GetObject's signature is:
```
func (c Core) GetObject(bucketName, objectName string, opts GetObjectOptions) (io.ReadCloser, ObjectInfo, error)
```

I reckon there should be a `core.GetObjectWithContext`

**Comment by harshavardhana** [comment]
Core is not for public usage @jackielii if you need you can fork minio-go and add it yourself.

**Comment by kannappanr** [comment]
@jackielii Closing this as won't fix. Please feel free to reach out to us if you have further questions.

**Comment by jackielii** [comment]
From the design of the `core` package, it looks like it's trying to expose the internal API publicly. I wonder what did you mean by "Core is not for public usage"? 

And I think it make sense to have the WithContext version: it's consistent with all other APIs

**Comment by harshavardhana** [comment]
Meaning it is not documented, it is not guaranteed to be API compatible in all versions. It's use is internal and it is not meant to be relied upon by third party applications.
