### ISSUE TITLE
Get ETag from put-object response

### ISSUE THREAD

**Issue by TennyZhuang** [minio/minio-go#1131]
s3 PutObject will return ETag, and the minio private API `putObjectDo` also return the `ObjectInfo`, but all public API will only return object size.

**Comment by kannappanr** [comment]
@TennyZhuang We generally like to keep our APIs simple. Will check internally and get back to you on this.

**Comment by harshavardhana** [comment]
@TennyZhuang can you explain further why do you need ETag in the response?

**Comment by TennyZhuang** [comment]
We split big object to small objects manually instead of using multipart in
our scene, then we need to calculate a big object etag with md5(part_etags)
manually.

Harshavardhana <notifications@github.com>于2019年7月4日 周四04:59写道：

**Comment by harshavardhana** [comment]
Why are you doing that and not using multipart API ?

**Comment by TennyZhuang** [comment]
We need to migrate some data to other storage and may break multipart upload.

**Comment by poornas** [comment]
@TennyZhuang, it might be better for you to compute ETag on the client side by using a wrapped stream and computing MD5 on the big object rather than relying on the SDK to return per part ETag and using that to compute final ETag. Trying to understand your use case and how your application is using this ETag.

 You might also want to consider doing a StatObject after each PUT operation to get ETag info.

**Comment by poornas** [comment]
ping @TennyZhuang, did you try this suggestion?

**Comment by TennyZhuang** [comment]
In the fact, our case is implement an S3-compatible object store, and use
minion as hot storage backend (with a bit capacity) . Any data in hot
storage may rotate to cold storage in a short time, and the lifecycle of a
valid multipart may be 7 days, and multiple multipart uploads may happen
with overlap, it’s uncontrollable in our case. And because of we implement
the s3 API by ourselves, we have to return every part’s md5 to user to
respect the S3 protocol, whether user need it.


poornas <notifications@github.com>于2019年8月8日 周四04:22写道：

**Comment by poornas** [comment]
@TennyZhuang, you can use the [Core API](https://github.com/minio/minio-go/blob/master/core.go) to get ETag from the PutObject call. Just fyi, start minio server with --compat flag if you want it to return S3 compatible MD5Sum.

**Comment by TennyZhuang** [comment]
Awesome! This is exactly I need. Thank you.

poornas <notifications@github.com>于2019年8月8日 周四08:24写道：
