### ISSUE TITLE
Provide explicit error when uploaded file size doesn't match actual size

### ISSUE THREAD

**Issue by lukepighetti** [minio/minio-go#1135]
I had an upload workflow that was functional until I started resizing the image. Unfortunately `minio-go` didn't give very helpful error messages, so it took a few hours before I realized that I was providing PutObject with the wrong file size. Just requesting a little more verbosity in errors in this area to help future devs out when they run into this mistake. Thanks.

**Comment by harshavardhana** [comment]
Can you provide an example for us to reproduce this problem?

**Comment by lukepighetti** [comment]
Yeah, call PutObject with the size integer that doesn't match the actual file size being uploaded

**Comment by harshavardhana** [comment]
Is the actual object bigger or smaller ? @lukepighetti

**Comment by lukepighetti** [comment]
The actual object was smaller

**Comment by harshavardhana** [comment]
> The actual object was smaller

So was your input a custom reader or *os.File stream? @lukepighetti ?

**Comment by lukepighetti** [comment]
The input was a buffer that implemented io.Reader
