### ISSUE TITLE
FileUploader.go example should return MakeBucket error

### ISSUE THREAD

**Issue by jamesnaftel** [minio/minio-go#1142]
The FileUploader.go example in the README.md returns the error for BucketExists when (I believe) it should return the MakeBucket error.  You see a difference in the error messages when using invalid bucket names.  MakeBucket defaults to strict naming so an "_" is flagged as invalid.  BucketExists does not default to strict naming so you get a "nil" for the error (even though you are inside the MakeBucket if error clause).

See [Gist for both errors](https://gist.githubusercontent.com/jamesnaftel/9a577e99e00d75768ace20a7ccf3a87b/raw/39af8495effd11b6ca13899ddad13dc8d276beac/bucket_example.go)

I'll submit a pull request to adjust the README.md to return the MakeBucket error.  I came across this in another project where it looked like the example was used.

**Question:**  Should MakeBucket and BucketExists have the same defaults when calling [checkBucketNameCommon](https://github.com/jamesnaftel/minio-go/blob/a45c90c613339104297e73f4114c5c39927dd56e/pkg/s3utils/utils.go#L272)?
MakeBucket uses CheckValidBucketNameStrict
BucketExist uses CheckValidBucketName

**Comment by harshavardhana** [comment]
No it doesn't @jamesnaftel  it is allow some older bucket names on AWS S3 which didn't follow the strict restrictions, so we fail with MakeBucket, but if it already exists we allow it.

**Comment by jamesnaftel** [comment]
Thx @harshavardhana.  Think it is worth changing the example?  The readme code gives me a nil for the error when using a character in the strict set.

**Comment by harshavardhana** [comment]
Yes that is acceptable

**Comment by kannappanr** [comment]
Closing this as #1143 is now merged. Thanks for the PR @jamesnaftel
