### ISSUE TITLE
return usermeta in StatObject

### ISSUE THREAD

**Issue by TennyZhuang** [minio/minio-go#1145]
It seems that PutObject support UserMeta option, but no any method to get the usermeta using minio-go.

**Comment by TennyZhuang** [comment]
It seems that the metadata is returned but undocumented.

https://github.com/minio/minio-go/blob/master/api-stat.go#L190

**Comment by TennyZhuang** [comment]
When I call put-object, I use map[string]string, and minio-go help me to add the prefix `X-Amz-Meta-`, but when I call stat-object, I can only get the the http Header with confusing `X-Amz-Meta-`. It's not user-friendly enough. A UserMetaData in ObjectInfo field with `map[string]string` type is better.

**Comment by harshavardhana** [comment]
> When I call put-object, I use map[string]string, and minio-go help me to add the prefix `X-Amz-Meta-`, but when I call stat-object, I can only get the the http Header with confusing `X-Amz-Meta-`(Not encode by me, but I have to decode it). It's not user-friendly enough. A UserMetaData in ObjectInfo field with `map[string]string` type is better.

We will fix it @TennyZhuang
