### ISSUE TITLE
Support Web Identity providers for IAM credentials for AWS EKS

### ISSUE THREAD

**Issue by barryib** [minio/minio-go#1156]
Add support for Web Identity providers for IAM credentials for AWS EKS (IAM Roles for Service Accounts) https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

This will be very useful in thanos https://github.com/thanos-io/thanos/issues/1494 running into an EKS cluster.

**Comment by harshavardhana** [comment]
We already support that @barryib

**Comment by harshavardhana** [comment]
https://godoc.org/github.com/minio/minio-go/pkg/credentials#NewIAM

**Comment by kannappanr** [comment]
@barryib Closing this issue now. Please feel free to reach out to us if you have other such questions at https://slack.min.io

**Comment by barryib** [comment]
I don't think it implemented. This is a new way (which come out few days ago) AWS provide IAM role to kubernetes pods and service account in EKS cluster.

This method add new env vars like

```
AWS_ROLE_ARN=arn:aws:iam::AWS_ACCOUNT_ID:role/IAM_ROLE_NAME
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

This was added recently in all AWS SDK. Here is the PR for the [aws-sdk-go](https://github.com/aws/aws-sdk-go/pull/2667)

More info here:
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
- https://github.com/aws/containers-roadmap/issues/23
- https://github.com/aws/containers-roadmap/issues/23#issuecomment-529840651
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by harshavardhana** [comment]
@barryib this is very specific to AWS - feel free to send a PR, we may not have cycles to address this as this moment.

**Comment by kannappanr** [comment]
@barryib Closing this issue now. Please feel free to send a PR when you get a chance
