### ISSUE TITLE
Support manual pagination by exposing continuation-token in ListObjectsV2()

### ISSUE THREAD

**Issue by RussellLuo** [minio/minio-go#1157]
Currently the [ListObjectsV2](https://github.com/minio/minio-go/blob/master/docs/API.md#ListObjectsV2) API does not support manual pagination (i.e. expose `continuation-token` as a parameter), which is required in our use case.

Is there any plan to support manual pagination? Thanks!

(This issue is similar to https://github.com/minio/minio-java/issues/752.)

**Comment by harshavardhana** [comment]
There is no plan, fork the project and change it in your fork @RussellLuo

**Comment by RussellLuo** [comment]
OK, thanks for your reply! @harshavardhana
