### ISSUE TITLE
Solving failure

### ISSUE THREAD

**Issue by g-balas** [minio/minio-go#1159]
Getting this error while compiling :

Solving failure: No versions of github.com/minio/minio-go met constraints:
        v6.0.35: Could not introduce github.com/minio/minio-go@v6.0.35, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.34: Could not introduce github.com/minio/minio-go@v6.0.34, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.33: Could not introduce github.com/minio/minio-go@v6.0.33, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.32: Could not introduce github.com/minio/minio-go@v6.0.32, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.31: Could not introduce github.com/minio/minio-go@v6.0.31, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.30: Could not introduce github.com/minio/minio-go@v6.0.30, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.29: Could not introduce github.com/minio/minio-go@v6.0.29, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.28: Could not introduce github.com/minio/minio-go@v6.0.28, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.27: Could not introduce github.com/minio/minio-go@v6.0.27, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.26: Could not introduce github.com/minio/minio-go@v6.0.26, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.25: Could not introduce github.com/minio/minio-go@v6.0.25, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.24: Could not introduce github.com/minio/minio-go@v6.0.24, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.23: Could not introduce github.com/minio/minio-go@v6.0.23, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.22: Could not introduce github.com/minio/minio-go@v6.0.22, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.21: Could not introduce github.com/minio/minio-go@v6.0.21, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.20: Could not introduce github.com/minio/minio-go@v6.0.20, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.19: Could not introduce github.com/minio/minio-go@v6.0.19, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.18: Could not introduce github.com/minio/minio-go@v6.0.18, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.17: Could not introduce github.com/minio/minio-go@v6.0.17, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.16: Could not introduce github.com/minio/minio-go@v6.0.16, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.15: Could not introduce github.com/minio/minio-go@v6.0.15, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.14: Could not introduce github.com/minio/minio-go@v6.0.14, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.13: Could not introduce github.com/minio/minio-go@v6.0.13, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.12: Could not introduce github.com/minio/minio-go@v6.0.12, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.11: Could not introduce github.com/minio/minio-go@v6.0.11, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.10: Could not introduce github.com/minio/minio-go@v6.0.10, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.9: Could not introduce github.com/minio/minio-go@v6.0.9, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.8: Could not introduce github.com/minio/minio-go@v6.0.8, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.7: Could not introduce github.com/minio/minio-go@v6.0.7, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.6: Could not introduce github.com/minio/minio-go@v6.0.6, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.5: Could not introduce github.com/minio/minio-go@v6.0.5, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.4: Could not introduce github.com/minio/minio-go@v6.0.4, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.3: Could not introduce github.com/minio/minio-go@v6.0.3, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v6.0.2: Could not introduce github.com/minio/minio-go@v6.0.2, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        6.0.1: Could not introduce github.com/minio/minio-go@6.0.1, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        6.0.0: Could not introduce github.com/minio/minio-go@6.0.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        5.0.0: Could not introduce github.com/minio/minio-go@5.0.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.9: Could not introduce github.com/minio/minio-go@4.0.9, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.8: Could not introduce github.com/minio/minio-go@4.0.8, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.7: Could not introduce github.com/minio/minio-go@4.0.7, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.6: Could not introduce github.com/minio/minio-go@4.0.6, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.5: Could not introduce github.com/minio/minio-go@4.0.5, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.4: Could not introduce github.com/minio/minio-go@4.0.4, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.3: Could not introduce github.com/minio/minio-go@4.0.3, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.2: Could not introduce github.com/minio/minio-go@4.0.2, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.1: Could not introduce github.com/minio/minio-go@4.0.1, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        4.0.0: Could not introduce github.com/minio/minio-go@4.0.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        3.0.3: Could not introduce github.com/minio/minio-go@3.0.3, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v3.0.2: Could not introduce github.com/minio/minio-go@v3.0.2, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v3.0.1: Could not introduce github.com/minio/minio-go@v3.0.1, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v3.0.0: Could not introduce github.com/minio/minio-go@v3.0.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v2.1.0: Could not introduce github.com/minio/minio-go@v2.1.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v2.0.4: Could not introduce github.com/minio/minio-go@v2.0.4, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v2.0.3: Could not introduce github.com/minio/minio-go@v2.0.3, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v2.0.2: Could not introduce github.com/minio/minio-go@v2.0.2, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v2.0.1: Could not introduce github.com/minio/minio-go@v2.0.1, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v2.0.0: Could not introduce github.com/minio/minio-go@v2.0.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v1.0.0: Could not introduce github.com/minio/minio-go@v1.0.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.2.5: Could not introduce github.com/minio/minio-go@v0.2.5, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.2.4: Could not introduce github.com/minio/minio-go@v0.2.4, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.2.3: Could not introduce github.com/minio/minio-go@v0.2.3, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.2.2: Could not introduce github.com/minio/minio-go@v0.2.2, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.2.1: Could not introduce github.com/minio/minio-go@v0.2.1, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.2.0: Could not introduce github.com/minio/minio-go@v0.2.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        v0.1.0: Could not introduce github.com/minio/minio-go@v0.1.0, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        master: Could not introduce github.com/minio/minio-go@master, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        log_format_modifications: Could not introduce github.com/minio/minio-go@log_format_modifications, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)
        release: Could not introduce github.com/minio/minio-go@release, as its subpackage github.com/minio/minio-go/v6 is missing. (Package is required by (root).)

Any idea ? I'm trying to use the minio-client-sdk, nothing special, I followed the doc.

**Comment by harshavardhana** [comment]
You have to use go mod versioning @g-balas

**Comment by kannappanr** [comment]
@g-balas Closing this issue. Please feel free to reach out to us at https://slack.min.io for further such questions
