### ISSUE TITLE
bucketname:"model/1234/1001/1/" but get `Bucket name contains invalid characters`

### ISSUE THREAD

**Issue by opriz** [minio/minio-go#1163]
Hi,
When I use mc, I can create these buckects successfully:
```
$ mc mb myminio/model/1234/1001/1/
Bucket created successfully `myminio/model/1234/1001/1/`.
```
But I use this bucket name`model/1234/1001/1/` when 
`m.client.BucketExists(bucketName)` ,got error `Bucket name contains invalid characters`.  
I found this regexp pattern should be matched in minio-go `checkBucketNameCommon` :
```
validBucketName = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9\.\-\_\:]{1,61}[A-Za-z0-9]$`)
```
and it doesn't contain "/" charactor.
I'll appreciate someone tell me how can I use bucketname  properly in multi-level structure style.

**Comment by harshavardhana** [comment]
mc mb uses two calls to create a bucket and also the prefix(directory) here - minio-go is an API 

you have to use two calls @opriz 

>     e := c.api.MakeBucket(bucket, region) --> bucket="model"
> _, e := c.api.PutObject(bucket, object, bytes.NewReader([]byte("")), 0, minio.PutObjectOptions{}); ---> bucket="model", object="1234/1001/1/"

**Comment by opriz** [comment]
@harshavardhana 
Thanks for telling.
But how can I check existence after I create this buckect `model/1234/1001/1/`  successfully? Cuz  it is not valid in `client.BucketExists(bucketName)`.
Did you mean `bucket` in minio is only the first level (model) ?
Then I should just check existence of bucket `model`, and the object `1234/1001/1/` ?

**Comment by harshavardhana** [comment]
It's not MinIO it's part of S3 API 
- a bucket is only top level
- a object is the heirarchy

**Comment by opriz** [comment]
@harshavardhana Thank you very much, I'll learn more

**Comment by harshavardhana** [comment]
Please close the issue

**Comment by kannappanr** [comment]
@opriz Closing this issue as answered
