### ISSUE TITLE
how to use PutObject with stream to append?

### ISSUE THREAD

**Issue by giskook** [minio/minio-go#1167]
Hi,
    I use [PutObject](https://docs.min.io/docs/golang-client-api-reference.html#PutObject)。The io.Reader is a bytes.Buffer witch I recved from my device.so the size is set to -1.But It seems It only can save the first blocks.Is there any best practise to append to minio-server?
Thanks,
zhangkai 
2019-09-26

**Comment by harshavardhana** [comment]
S3 API doesn't implement append APIs like posix support for -1 on a reader is a client only functionality you can't upload objects bigger than 5TiB it's a spec limit.

**Comment by giskook** [comment]
@harshavardhana the data is only 64k,my situation is to PutObject 64k,and after a while append another 64k to the object.

**Comment by harshavardhana** [comment]
You can't don't that.   You should append locally and upload

**Comment by giskook** [comment]
@harshavardhana In my another project .I pass the io.Reader as a net.TCPConn.It works great.But now I use bytes.Buffer to PutObject.It does not work.So I wonder if there is a `data struct` or `some thing like tcp connection` can help?

**Comment by harshavardhana** [comment]
You can't do that here.. S3 API expects content-length unfortunately. It's not meant for such type of workload. For that you need to write a custom server with custom protocol..

**Comment by giskook** [comment]
@harshavardhana means I should **not** pass net.TCPConn to PutObject?

**Comment by harshavardhana** [comment]
You can but it is better if you know the final object. Otherwise you can't append to the same object.

**Comment by giskook** [comment]
@harshavardhana One thing I have no idea about is the different with tcp connection and bytes.Buffer,both are implement io.Reader.and my bytes.Buffer is not close or reset when the transport.

**Comment by giskook** [comment]
append locally and upload
