### ISSUE TITLE
BucketACL.isAuthenticated should probably be isAuthenticatedRead

### ISSUE THREAD

**Issue by fkautz** [minio/minio-go#117]
There is no authenticated-read-write canned acl, but AuthenticatedRead is more descriptive.

**Comment by harshavardhana** [comment]
> There is no authenticated-read-write canned acl, but AuthenticatedRead is more descriptive.

The idea was that it was simple enough to call public-read-write as public, public-read as readonly, so authenticated-read as just 'authenticated' since authenticated-read is primarily for authenticated users. 

Either way both works.

**Comment by fkautz** [comment]
Ah, I see. I'm fine with this approach as well.

**Comment by harshavardhana** [comment]
> Ah, I see. I'm fine with this approach as well.

Closing
