### ISSUE TITLE
putobject-streaming fails with google cloud storage

### ISSUE THREAD

**Issue by dbregman** [minio/minio-go#1172]
The putobject-streaming example (https://github.com/minio/minio-go/blob/master/examples/s3/putobject-streaming.go)

Fails when run on **Google Cloud Storage**, with the following error message:
`http: ContentLength=-1 with Body length 623504` (623504 is the length of my test file)

EDIT: importantly, it only fails when SSL is disabled.

**Comment by dbregman** [comment]
in request-signature-streaming.go:

```
if s.bytesRead != s.contentLen {
    return 0, fmt.Errorf("http: ContentLength=%d with Body length %d",
        s.contentLen, s.bytesRead)
}
```

If this is simply disabled (check for length == -1), then it seems to work, although the bandwidth usage shows a curious pattern where it seems to completely pause uploading for a few seconds every 20 seconds or so.

**Comment by harshavardhana** [comment]
@dbregman is Google Cloud SDK not working for you ? Google cloud doesn't support S3 multipart APIs so it you use minio-go it can't work automatically.

**Comment by dbregman** [comment]
@harshavardhana my app currently uses the AWS SDK, now I need to support google as well so I thought using MinIO to support both with one code made sense.

**Comment by dbregman** [comment]
New information: The example works when SSL is enabled, does not work when it's not enabled.

This brings up another issue: I am doing most of my development on Windows, and SSL does not work on windows because x509.SystemCertPool() always returns nil. I had to hack the code to get it to work. To workaround this, MinIO should provide a way for users to specify a PEM file to be used when initializing the client object.

**Comment by dbregman** [comment]
I see, but maybe provide a function to construct the custom transport using the default transport together with custom certs?

Not being an expert on this, I wouldn't know how to construct a transport, there seem to be several obscure details involved, looking at the code for DefaultTransport() there are several comments linking to documentation about issues. I would end up copying this function into my code and adding a line to insert the certificates, which is what I will do for now I guess.

**Comment by kannappanr** [comment]
@dbregman Closing this issue for now. As we do not have cycles right now to spend on adding a function right now. Will get back to this in the near future when we have time to look at it

**Comment by dbregman** [comment]
@kannappanr My suggestion to add a particular function was just something that came up in this context. It is not related to the issue that you just closed, which I believe is still broken?

**Comment by kannappanr** [comment]
@dbregman `minio-go` is an SDK for S3 compatible object stores, just like AWS S3 Go SDK. As mentioned earlier, GCS is not yet fully supporting some of the common S3 API functionality. When using `minio-go` SDK, you should expect similar behavior compared to what you would get from AWS SDK.
