### ISSUE TITLE
Error occurred when stat an exist object which showed in the ListObjects result channel

### ISSUE THREAD

**Issue by songtianyi** [minio/minio-go#1174]
code
```
objectCh := minioc.MinioClient.ListObjects(common.AppConfigInstance.MinioCfg.DefaultBucketName,
		common.AppConfigInstance.MinioCfg.DefaultBucketDir, true, doneCh)
	for object := range objectCh {
		if object.Err != nil {
			fmt.Println("object error", object.Err)
			return
		}
		if !strings.HasSuffix(object.Key, ".config") {
			continue
		}
		// retrieve
		o, err := minioc.MinioClient.GetObject(common.AppConfigInstance.MinioCfg.DefaultBucketName, object.Key, minio.GetObjectOptions{})
		if err != nil {
			fmt.Println("get object", object.Key, "failed", err)
			continue
		}
		objInfo, err := o.Stat()
		if err != nil {
			fmt.Println("stat object error", err, "key is", object.Key, "objInfo", objInfo)
			continue
		}
```
error msg
```
stat object error The specified key does not exist. key is /volpfqewu9/atsgorrznf/e3ugf8fcuy/201910/2019-10-15.config objInfo {  0001-01-01 00:00:00 +0000 UTC 0  map[] { }  <nil>}
```
Error occured when stat an existed object which showed in the ListObjects result channel

**Comment by vadmeste** [comment]
@songtianyi I am not able to reproduce this, could you give more information about the version of minio-go and your Minio server and the type of the deployment of Minio server ?

**Comment by vadmeste** [comment]
@songis below is the code that you can try by yourself, it tests against play.min.io

```go
package main

import (
	"fmt"
	"os"

	"github.com/minio/minio-go/v6"
)

func main() {
	s3Client, err := minio.New("play.min.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	// List all objects from a bucket-name with a matching prefix.
	for object := range s3Client.ListObjects("vadmeste-bucket", "", true, doneCh) {
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		fmt.Println(object)
		o, err := s3Client.GetObject("vadmeste-bucket", object.Key, minio.GetObjectOptions{})
		if err != nil {
			fmt.Println("get object", object.Key, "failed", err)
			continue
		}
		objInfo, err := o.Stat()
		if err != nil {
			fmt.Println("stat object error", err, "key is", object.Key, "objInfo", objInfo)
			os.Exit(-1)
		}
	}
	return
}
```

**Comment by songtianyi** [comment]
My demo code works well in development env but fail prod env.
dev env
```
**minio-go**
commit 8afcf7be72ae6d4aa17ad3b5449b874df2d92003
Author: Harshavardhana <harsha@minio.io>
Date:   Mon Sep 2 22:17:38 2019 -0700

    Fix documentation on minio-go download (#1155)

**minio server**
VERSION
2019-09-05T23:24:38Z
MEMORY
Used: 6.1 MB | Allocated: 11 GB | Used-Heap: 6.1 MB | Allocated-Heap: 66 MB
PLATFORM
Host: de5e48cd57af | OS: linux | Arch: amd64
RUNTIME
Version: go1.12.8 | CPUs: 4
```
prod env
```
**minio-go**

go: finding github.com/minio/minio-go v6.0.14+incompatible

**minio server**

VERSION
2019-10-02T21:19:38Z
MEMORY
Used: 9.6 MB | Allocated: 33 GB | Used-Heap: 9.6 MB | Allocated-Heap: 65 MB
PLATFORM
Host: minio-3 | OS: linux | Arch: amd64
RUNTIME
Version: go1.13.1 | CPUs: 4
```

**Comment by vadmeste** [comment]
Could you check what's the exact minio-go version are you using ?

Check go.mod if you are using go module

**Comment by kannappanr** [comment]
@songtianyi Please try to use the latest version of `minio-go` which is `v6.0.39`, also can you describe more about the object itself. Can you do` mc stat` on the object in production and paste it here? If the object is being uploaded using `SSE-C` then you will not have privilege to download that object without specifying the `SSE-C` for that object.

**Comment by songtianyi** [comment]
> @songtianyi Please try to use the latest version of `minio-go` which is `v6.0.39`, also can you describe more about the object itself. Can you do` mc stat` on the object in production and paste it here? If the object is being uploaded using `SSE-C` then you will not have privilege to download that object without specifying the `SSE-C` for that object.

`mc stat` ok.
```
Name      : fdl-2018-03-29.csv
Date      : 2019-09-10 14:50:42 CST
Size      : 665 B
ETag      : 41eeeff0f53ec2a8aee961e58177890b-1
Type      : file
Metadata  :
  Content-Type: application/octet-stream

**Comment by songtianyi** [comment]
go mod tidy set the version of minio-go as `go: finding github.com/minio/minio-go v6.0.14+incompatible` automaticly

**Comment by harshavardhana** [comment]
as mentioned in the README.md you need to reference minio-go with proper versioned endpoint i.e 

```
go get github.com/minio/minio-go/v6
```

**Comment by songtianyi** [comment]
> as mentioned in the README.md you need to reference minio-go with proper versioned endpoint i.e
> 
> ```
> go get github.com/minio/minio-go/v6
> ```

i changed the import path to v6, the error no changes.

**Comment by harshavardhana** [comment]
> i changed the import path to v6, the error no changes.

First was to fix your import issues now we can look at the code - can you share your entire code? - a small snippet won't do. Preferably something we can download and execute locally would be immensely helpful.

**Comment by songtianyi** [comment]
> > i changed the import path to v6, the error no changes.
> 
> First was to fix your import issues now we can look at the code - can you share your entire code? - a small snippet won't do. Preferably something we can download and execute locally would be immensely helpful.

Here is the complete code to reproduce the error
```
package main

import (
	"fmt"
	"github.com/minio/minio-go/v6"
	"io"
	"strings"
)

func main() {
	retrieve()
}

func retrieve() {
	client, err := minio.New("39.105.192.98:39000",
		"ZTPWRZ19H2WBYUGI9B8S",
		"mVUmPizjQbn0Vv2Lxcw3GxJydCyp0QxPq3TOLbXe",
		false)
	if err != nil {
		panic(err)
	}
	// list csv object
	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	fmt.Println("retrieving cost profit data...")

	objectCh := client.ListObjects("enterprise-netdisc",
		"/", true, doneCh)
	for object := range objectCh {
		if object.Err != nil {
			fmt.Println("object error", object.Err)
			return
		}
		if !strings.HasSuffix(object.Key, ".csv") {
			continue
		}
		// retrieve
		o, err := client.GetObject("enterprise-netdisc", object.Key, minio.GetObjectOptions{})
		if err != nil {
			fmt.Println("get object", object.Key, "failed", err)
			continue
		}
		objInfo, err := o.Stat()
		if err != nil {
			fmt.Println("stat object error", err, "key is", object.Key, "objInfo", objInfo)
			continue
		}
		b := make([]byte, objInfo.Size)
		_, err = o.Read(b)
		if err != nil && err != io.EOF {
			fmt.Println("read object error", err)
			continue
		}
	}
}
```

**Comment by harshavardhana** [comment]
@songtianyi that is strange I am not sure why there is an extra `/` in front of the object - is your server MinIO here? 

```go
package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/minio/minio-go/v6"
)

func main() {
	retrieve()
}

func retrieve() {
	client, err := minio.New("39.105.192.98:39000",
		"ZTPWRZ19H2WBYUGI9B8S",
		"mVUmPizjQbn0Vv2Lxcw3GxJydCyp0QxPq3TOLbXe",
		false)
	if err != nil {
		panic(err)
	}

	// list csv object
	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	fmt.Println("retrieving cost profit data...")

	objectCh := client.ListObjects("enterprise-netdisc",
		"/", true, doneCh)
	for object := range objectCh {
		if object.Err != nil {
			fmt.Println("object error", object.Err)
			return
		}
		if !strings.HasSuffix(object.Key, ".csv") {
			continue
		}
		// retrieve
		o, err := client.GetObject("enterprise-netdisc", strings.TrimPrefix(object.Key, "/"), minio.GetObjectOptions{})
		if err != nil {
			fmt.Println("get object", object.Key, "failed", err)
			continue
		}
		objInfo, err := o.Stat()
		if err != nil {
			fmt.Println("stat object error", err, "key is", object.Key, "objInfo", objInfo)
			continue
		}
		b := make([]byte, objInfo.Size)
		_, err = o.Read(b)
		if err != nil && err != io.EOF {
			fmt.Println("read object error", err)
			continue
		}
	}
}
```

Just trimming off the `/` fixes the problem.

**Comment by songtianyi** [comment]
> @songtianyi that is strange I am not sure why there is an extra `/` in front of the object - is your server MinIO here?
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"io"
> 	"os"
> 	"strings"
> 
> 	"github.com/minio/minio-go/v6"
> )
> 
> func main() {
> 	retrieve()
> }
> 
> func retrieve() {
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	// list csv object
> 	// Create a done channel to control 'ListObjects' go routine.
> 	doneCh := make(chan struct{})
> 
> 	// Indicate to our routine to exit cleanly upon return.
> 	defer close(doneCh)
> 
> 	fmt.Println("retrieving cost profit data...")
> 
> 	objectCh := client.ListObjects("netdisc",
> 		"/", true, doneCh)
> 	for object := range objectCh {
> 		if object.Err != nil {
> 			fmt.Println("object error", object.Err)
> 			return
> 		}
> 		if !strings.HasSuffix(object.Key, ".csv") {
> 			continue
> 		}
> 		// retrieve
> 		o, err := client.GetObject("enterprise-netdisc", strings.TrimPrefix(object.Key, "/"), minio.GetObjectOptions{})
> 		if err != nil {
> 			fmt.Println("get object", object.Key, "failed", err)
> 			continue
> 		}
> 		objInfo, err := o.Stat()
> 		if err != nil {
> 			fmt.Println("stat object error", err, "key is", object.Key, "objInfo", objInfo)
> 			continue
> 		}
> 		b := make([]byte, objInfo.Size)
> 		_, err = o.Read(b)
> 		if err != nil && err != io.EOF {
> 			fmt.Println("read object error", err)
> 			continue
> 		}
> 	}
> }
> ```
> 
> Just trimming off the `/` fixes the problem.

ooooooooooops...

**Comment by harshavardhana** [comment]
> i need you to help me to delete the private minio access information @harshavardhana thanks again

you should change those credentials @songtianyi
