### ISSUE TITLE
Download failed, got 410 Gone

### ISSUE THREAD

**Issue by sequix** [minio/minio-go#1175]
`
squix@lenovo test-go$ GO111MODULE=on go get github.com/minio/minio-go/v6
go: downloading github.com/minio/minio-go v6.0.23+incompatible
verifying github.com/minio/minio-go@v6.0.23+incompatible: github.com/minio/minio-go@v6.0.23+incompatible: reading https://sum.golang.org/lookup/github.com/minio/minio-go@v6.0.23+incompatible: 410 Gone
`

system info

`
squix@lenovo test-go$ go version
go version go1.13 linux/amd64

squix@lenovo test-go$ uname -a 
Linux lenovo 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by sequix** [comment]
Got it work with the following command, sorry for interrupt.
go get -u github.com/minio/minio-go

**Comment by sequix** [comment]
it still not work for go mod, got same 410 response for 'go mod tidy'.

**Comment by harshavardhana** [comment]
You shouldn't be doing `go get -u` 

```
GO111MODULE=on go get github.com/minio/minio-go/v6
```

works fine locally @sequix are you sure your local setup has no proxy issues? @sequix

**Comment by kannappanr** [comment]
@sequix Closing this issue as answered. please feel free to get back to us if you still face issues
