### ISSUE TITLE
ListObjects api ignore plus character "+"

### ISSUE THREAD

**Issue by soolaugust** [minio/minio-go#1177]
Hello,

When I use ListObjects api, I found it will ignore "+" character  of object key:

![image](https://user-images.githubusercontent.com/10558124/67254476-c8649580-f4af-11e9-8c9f-e795d3291dbd.png)

In minio, it shows as following:

![image](https://user-images.githubusercontent.com/10558124/67254497-ed590880-f4af-11e9-86c3-5aeda386e52d.png)

As you can see, the plus character "+" is replaced with space.

**Comment by soolaugust** [comment]
After deep research. I think things happend in following codes:

https://github.com/minio/minio-go/blob/e11840609c348b5d1e46185b7f6e98ce6e6bc313/api-list.go#L259

```golang
![image](https://user-images.githubusercontent.com/10558124/67255984-627c0c00-f4b7-11e9-9073-038797226fc5.png)
```

since golang url package will handle '+' to 'escape':

```golang
		case '+':
			if mode == encodeQueryComponent {
				t[j] = ' '
			} else {
				t[j] = '+'
			}
			j++
			i++
```

However if we use `PathUnescape`, this wouldn't happen. 

So I wanna know your opinion, thanks :)

**Comment by nitisht** [comment]
feel free to send a PR @soolaugust we can discuss / review

**Comment by soolaugust** [comment]
@nitisht , I opened a PR for this, please help to review, thanks :)

**Comment by vadmeste** [comment]
Hey @soolaugust.

I am not able to understand exactly the issue, can you describe more how to reproduce it ?

**Comment by soolaugust** [comment]
@vadmeste Hi, yes, let me explain the issue.

Currently we are pushing some files name format like `xxxiW_Sag+Mass1xxx`, when I want to get using minio-go, the `ListObjects` api will return without ''+  character, like `xxxiW_Sag Mass1xxx`. and if I want use this to get the object, it will return a 404 error.

**Comment by vadmeste** [comment]
The thing is that I am not able to reproduce it:

```
package main

import (
	"fmt"

	"github.com/minio/minio-go/v6"
)

func main() {
	s3Client, err := minio.New("play.min.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	// List all objects from a bucket-name with a matching prefix.
	for object := range s3Client.ListObjects("vadmeste-testbucket", "", true, doneCh) {
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		fmt.Println(object)
	}
	return
}
```

**Comment by soolaugust** [comment]
@vadmeste ，yes, I see. that's weird, because I upload same file in `play.minio.io:9000` and my local minio, `ListObjects` returns normal in `play.minio.io:9000` while issue happend in my local minio. the version is 2018-12-19T23:46:24Z.

**Comment by vadmeste** [comment]
> the version is 2018-12-19T23:46:24Z.

I guess if you upgrade MinIO server, the issue will be fixed

**Comment by soolaugust** [comment]
I think so. the issue will open until I find the root issue. What do you think of?

**Comment by vadmeste** [comment]
> I think so. the issue will open until I find the root issue. What do you think of?

No need, most likely your Minio version does not support url encoding yet, that's why it is confusing minio-go.

**Comment by soolaugust** [comment]
yeah. you're right. after deep check, the older minio will response with space string when meeting '+'. and new minio will response with `%2B`. that's why minio-go get confusing. 

Thanks for your kindly help. so I could found the real reason. @vadmeste
