### ISSUE TITLE
Multipart file upload without knowing it's size with Pause/Resume

### ISSUE THREAD

**Issue by ikhosravi** [minio/minio-go#1186]
Hi,
Is there any example of putting a file without knowing it's size with pause and resume ability?
I'm partially receiving a file and trying to upload it before I get the whole file so i need partially upload here.
as i might have some delays in receiving it pausing put operation and resume it again might be required.
Thanks  in advance

**Comment by harshavardhana** [comment]
There is no pause and resume in AWS S3 API, it's not possible for us to implement a strictly consistent API to cater for pause and resume functionality.

**Comment by ikhosravi** [comment]
It might be a misunderstanding but I saw the topic here: 
https://aws.amazon.com/about-aws/whats-new/2010/11/10/Amazon-S3-Introducing-Multipart-Upload/
"With this feature you can create parallel uploads, pause and resume an object upload, and begin uploads before you know the total object size."
As this is supported by S3, Is there any example of this feature?
Thanks

**Comment by harshavardhana** [comment]
Pause and resume doesn't work in a strictly consistent manner @ikhosravi it was clarified properly with https://github.com/aws/aws-sdk-go/issues/1518 that blog is outdated.

**Comment by ikhosravi** [comment]
Thanks @harshavardhana 
Just for clarification: if the application maintain the list of parts locally is this safe to do pause and resume?

**Comment by harshavardhana** [comment]
> Thanks @harshavardhana
> Just for clarification: if the application maintain the list of parts locally is this safe to do pause and resume?

Yes but minio-go cannot keep any state @ikhosravi you need to write your own SDK to do it.

**Comment by kannappanr** [comment]
@ikhosravi Closing the issue based on the above discussion. Please feel free to reach out to us at https://slack.min.io, if you have more questions.
