### ISSUE TITLE
Not able to connect to server with SSL on Windows

### ISSUE THREAD

**Issue by GoryMoon** [minio/minio-go#1191]
When I try to connect to the test server with SSL as in the example in the README I get the following error (without SSL it works)
`Get https://play.min.io/: x509: certificate signed by unknown authority`

I found that it was the `crypto/x509.Verify` function that threw it. 
On line [749](https://github.com/golang/go/blob/acf3ff2e8a0ee777a35b42879c90a1d5a130988f/src/crypto/x509/verify.go#L749) of the `crypto/x509.Verify` function there is a check to use Windows own verification if `rootCAs` is nil.

The problem is that in [DefaultTransport](https://github.com/minio/minio-go/blob/7bb4ac4dfa8be91227211bca4c0386e591d828b5/transport.go#L62) the `rootCAs` is set to an empty pool and causing it not to use the Windows verify function.

I tested this by adding this code and I can successfully connect to the server and other servers:
```go
if runtime.GOOS == "windows" {
	transport, _ := minio.DefaultTransport(true)
	transport.(*http.Transport).TLSClientConfig.RootCAs = nil
	api.SetCustomTransport(transport)
}
```

**Comment by harshavardhana** [comment]
This is the correct behavior for windows.. there is an upstream Go bug, we can't fix anything on our end here.

**Comment by GoryMoon** [comment]
Was thinking that by not setting the `RootCAs` to a new empty pool would be a resolution to this issue without the workaround. 
The `crypto/x509.Verify` sets the `RootCAs` if it's `nil` for non windows systems.

**Comment by harshavardhana** [comment]
But we are not doing anything special here, this looks like a bug in upstream Go.

**Comment by GoryMoon** [comment]
You are setting a default `RootCAs` in [transport.go](https://github.com/minio/minio-go/blob/7bb4ac4dfa8be91227211bca4c0386e591d828b5/transport.go#L62) for `minio.DefaultTransport` that's used by default when creating a new [Client](https://github.com/minio/minio-go/blob/7bb4ac4dfa8be91227211bca4c0386e591d828b5/api.go#L306).

From the TLS [documentation ](https://godoc.org/crypto/tls#Config.RootCAs)
```go
    // RootCAs defines the set of root certificate authorities
    // that clients use when verifying server certificates.
    // If RootCAs is nil, TLS uses the host's root CA set.
    RootCAs *x509.CertPool
```
What I take from that is that it should only be set when using custom root CAs. When left `nil` it gets populated by the TLS. For Windows it uses another method to check the host's root CAs.

I'm only using this on Windows in dev, it's going on a linux server later on so it's not that important, just felt the workaround wouldn't be needed and to help others when it happens to them.

**Comment by harshavardhana** [comment]
This is a bug still, rootCAs if empty should still use hostCAs or append to it .. I am not why they don't do it.

This is why it's exposing a bug, nil is not a way to communicate.
