### ISSUE TITLE
ERROR! we are not support trunk upload signature

### ISSUE THREAD

**Issue by jinriyang** [minio/minio-go#1194]
I use minio-go to upload file to my  s3 server ,but I get error repsonse!
Is there anything minio can do? 
 ![image](https://user-images.githubusercontent.com/28684043/70217460-29a0a980-177c-11ea-8d4f-a7788cfa9b52.png)

![image](https://user-images.githubusercontent.com/28684043/70217197-a5e6bd00-177b-11ea-85c7-a841f369e05e.png)
![image](https://user-images.githubusercontent.com/28684043/70217596-6cfb1800-177c-11ea-8ec2-07209b4549f2.png)

**Comment by jinriyang** [comment]
If i use
// Initialize minio client object.
	minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)

it also work well

**Comment by jinriyang** [comment]
If i use
// Initialize minio client object.
minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)

it also doesn't work well

**Comment by harshavardhana** [comment]
This looks like a server bug @jinriyang

**Comment by jinriyang** [comment]
> This looks like a server bug @jinriyang

But when  I use AWS S3 SDK ,I can upload file to my server.Only use minio-go ,it will not work well . 
My server doesn't support  trunk upload. Is there any way to use minio-go to support?

**Comment by harshavardhana** [comment]
We only support chunked uploads, you should implement all S3 related functionalities. It won't work otherwise.
