### ISSUE TITLE
How to multiple PutObject ?

### ISSUE THREAD

**Issue by arck123** [minio/minio-go#1195]
files, err := ioutil.ReadDir(tempImage)
    if err != nil {
        log.Fatal(err)
    }
    for _, f := range files {
            log.Println(f.Name())
    }

	// Initialize minio client object.
	minioClient, err := minio.New(config.Endpoint, config.AccessKeyID, config.SecretAccessKey, config.UseSSL)
	if err != nil {
		log.Println(err)
	}
	contentType, err := lib.GetFileContentType(f)
	if err != nil {
		log.Println(err)
	}
	// Upload the file with FPutObject
	n, err := minioClient.FPutObject(config.BucketName, objectName, tempImage, minio.PutObjectOptions{ContentType:contentType})
	log.Println("FPutObject : ", n)
	if err != nil {
		log.Println(err)
	}

**Comment by kannappanr** [comment]
@arck123 S3 API doesn't allow multiple objects to be uploaded at the same time. You can make multiple `PutObject` API calls in parallel. Closing this issue. Please reach out to us at https://slack.min.io for such questions
