### ISSUE TITLE
GOAWAY retry

### ISSUE THREAD

**Issue by lestatcheb** [minio/minio-go#1196]
https://github.com/minio/minio-go/blob/master/retry.go#L90

Should we add GOAWAY error to func isHTTPReqErrorRetryable too ?

example of error:
`http2: server sent GOAWAY and closed the connection; LastStreamID=49, ErrCode=NO_ERROR, debug="",`

**Comment by harshavardhana** [comment]
This is an upstream bug in http2 in Go - just use http1.1 for now. @lestatcheb

**Comment by lestatcheb** [comment]
> This is an upstream bug in http2 in Go - just use http1.1 for now. @lestatcheb

@harshavardhana can you give url to that upstream bug issue in go?

**Comment by harshavardhana** [comment]
https://github.com/golang/go/issues/32112
