### ISSUE TITLE
Policy exceeds the maximum allowed document size

### ISSUE THREAD

**Issue by arck123** [minio/minio-go#1202]
do you have a solution ?

![minio](https://user-images.githubusercontent.com/18304433/70690937-d3ed6500-1c85-11ea-807d-e7ceb7845bfd.jpeg)

**Comment by kannappanr** [comment]
MinIO has  a policy document size limit of `20KB` and this means that this bucket has policies bigger than that. 

You can do
```
mc policy get-json myminio/bucket
```
Modify the policy json to how you want it to be and make sure that it is less than 20KB and then do
```
mc policy set-json /path/to/the/json myminio/bucket
```

Closing this issue as answered, please feel free to reach out to us at https://slack.min.io for further such questions
