### ISSUE TITLE
ListObjectsV2WithMetadata does not return metadata

### ISSUE THREAD

**Issue by florentsolt** [minio/minio-go#1203]
`ObjectInfo` structs that goes via the channel have empty `Metadata` and `UserMetadata`.
But when doing a `StatObject` on the same `.Key` the `ObjectInfo` returned is full.

What am I doing wrong or missing here?

**Comment by harshavardhana** [comment]
Are you talking to MinIO server here? Then you need to wait for a new release this feature is only available in current master.

If you not using MinIO it won't work since it's a MinIO only feature.

**Comment by florentsolt** [comment]
Yes I'm using a MinIO server.
Oh! I didn't know it was a new feature, any when it will be released?

**Comment by harshavardhana** [comment]
Soon @florentsolt NO eta yet.

**Comment by florentsolt** [comment]
@harshavardhana 👍 and btw congrats for your amazing work here
