### ISSUE TITLE
IAM credentials broken

### ISSUE THREAD

**Issue by radix-aw** [minio/minio-go#1223]
On 6.0.45 I am unable to get IAM-based credentials working. The problem seems to be in [getIAMRoleURL](https://github.com/minio/minio-go/blob/a8fa81f2c36397fc9dcc622f4a121776b1f15312/pkg/credentials/iam_aws.go#L170), where if the endpoint is empty, the URL consists of only the path and not the host (e.g. `/latest/meta-data/iam/security-credentials/`). I am unable to locate any usage of `defaultIAMRoleEndpoint`, and it would make sense to use it if the endpoint is an empty string.

**Comment by harshavardhana** [comment]
Feel free to send a PR @radix-aw
