### ISSUE TITLE
Minio client overwrites the endpoint configuration regardless of temporary or permanent redirect

### ISSUE THREAD

**Issue by kfelter** [minio/minio-go#1232]
When the minio client gets a redirect, it overwrites the endpoint configuration regardless of temporary or permanent redirect.
## Expected Behavior

On temporary redirect, the endpoint of the client should not change. On permanent redirect the endpoint should change.
## Current Behavior

Endpoint is overwritten regardless of statuscode

## Possible Solution

add logic in api.go to conditionally set the endpoint based on a permanent or temporary redirect

## Steps to Reproduce (for bugs)

1. create a minio.Client with endpoint acme.redirector.com
2. have your redirector point to an s3/minio instance
3. use get object ( this gets a temporary redirect and returns the object )
4. use get object again, ( this goes directly to the s3 instance now even if it was a temporary redirect )

## Context

We are using a redirector to point to different minio gateway caches

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by vadmeste** [comment]
@kfelter unfortunately, Go doesn't help us to do what you asked, we cannot know if this is a temporary or permanent redirect in CheckRedirect

```
        // CheckRedirect specifies the policy for handling redirects.
        // If CheckRedirect is not nil, the client calls it before
        // following an HTTP redirect. The arguments req and via are
        // the upcoming request and the requests made already, oldest
        // first. If CheckRedirect returns an error, the Client's Get
        // method returns both the previous Response (with its Body
        // closed) and CheckRedirect's error (wrapped in a url.Error)
        // instead of issuing the Request req.
        // As a special case, if CheckRedirect returns ErrUseLastResponse,
        // then the most recent response is returned with its body
        // unclosed, along with a nil error.
        //
        // If CheckRedirect is nil, the Client uses its default policy,
        // which is to stop after 10 consecutive requests.
        CheckRedirect func(req *Request, via []*Request) error
```

The only solution is to avoid overwriting endpointURL in all cases (temporary or permanent redirects), but it might be not a good option as well because that means the request will always go to the original URL and get redirected each time.

I think we are not going to fix this. Closing this issue. Please free to reopen if you want to discuss this more.
