### ISSUE TITLE
EnableVersioning:A header you provided implies functionality that is not implemented

### ISSUE THREAD

**Issue by yuyuanshifu** [minio/minio-go#1241]
When I wanted to use EnableVersioning field, an error occured:A header you provided implies functionality that is not implemented

The minio version is:

        "Id": "28982fb206995a8d1ebd0a9e9eeb15d689ef516f1b9d62ae31bf97bf924a363c",
        "Created": "2020-03-05T07:30:17.839784657Z"

**Comment by nitisht** [comment]
MinIO doesn't support versioning yet, it is being added with this PR https://github.com/minio/minio/pull/9045

Closing this as duplicate of https://github.com/minio/minio/issues/2111
