### ISSUE TITLE
Context cancelation not handled.

### ISSUE THREAD

**Issue by fortyanov** [minio/minio-go#1246]
newRetryTimer does not handle context cancellation.
Steps for bug reproduction:
1. Create minio client
`minioClient, err = minio.New(config.URL, config.AccessKey, config.SecretKey, config.SSL)`
2. Put some file with context
`_, err = minioClient.FPutObjectWithContext(timeoutCtx, config.Bucket, key, fileName, minio.PutObjectOptions{ContentType: contentType})`
3. Disable minio server
4. Resend file with context
`_, err = minioClient.FPutObjectWithContext(timeoutCtx, config.Bucket, key, fileName, minio.PutObjectOptions{ContentType: contentType})`

Context timeout will work correctly on  `req = req.WithContext(ctx) ` but will be ignored in `c.newRetryTimer(ctx, reqRetry, DefaultRetryUnit, DefaultRetryCap, MaxJitter, doneCh)` so retries with timeout will be send requests with context again and again, ignoring the fact that all answers return an error related to the context timeout.

**Comment by vadmeste** [comment]
@fortyanov thanks for reporting this.

Yes, I was able to reproduce this by adding a fake sleep in PutObject handler in MinIO server.

Are you willing to send a fix PR for that ?

**Comment by ckoehn** [comment]
This issue was already closed by #1250 and #1260.
