### ISSUE TITLE
No way to set HTTP client timeout

### ISSUE THREAD

**Issue by klauspost** [minio/minio-go#1251]
It is not possible to set the timeout of the internal [HTTP client](https://github.com/minio/minio-go/blob/master/api.go#L312) so there is no way to set a maximum request time and dead TCP connections can hang, potentially forever.

This would enable us to fix https://github.com/minio/warp/issues/92 without having to use contexts for all calls.

**Comment by harshavardhana** [comment]
@klauspost we can set transport timeout using SetCustomTransport() - httpClient itself just uses the timeout.

**Comment by klauspost** [comment]
@harshavardhana I am not sure this actually covers all the cases. We have infinitely hanging connections now. 

We have not set `ResponseHeaderTimeout` on the transport, which *might* fix the hanging, but I do not see that this guarantees the requests will always return within a given timeframe.
