### ISSUE TITLE
Different results with GetObject and FGetObject

### ISSUE THREAD

**Issue by halfshoe** [minio/minio-go#1252]
I am trying to make thumbnails from files saved with minio. No i get different results with GetObject and FGetObject. Below is sample code without error handling:

```
package main

import (
        "bytes"
        "fmt"
         "image/jpeg"
         "io"
         "os"
	"github.com/bakape/thumbnailer/v2"
	"github.com/minio/minio-go"
)

func main() {
	endpoint := "play.min.io"
	accessKeyID := "Q3AM3UQ867SPQQA43P2F"
	secretAccessKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
	useSSL := true

	minioClient, _ := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
        minioClient.FPutObject("files", "test", "./2.mp4", minio.PutObjectOptions{})

        // Exchange this line with commented ones and all is ok
        f, _ := minioClient.GetObject("files", "test", minio.GetObjectOptions{})
	
	// err = minioClient.FGetObject("files", "test", "./3.mp4", minio.GetObjectOptions{})
	// f, err := os.Open("./3.mp4")
        // defer f.Close()

        _, thumb, err2 := thumbnailer.Process(f,
		thumbnailer.Options{ThumbDims: thumbnailer.Dims{Width: uint(150), Height: uint(150)}})

	if err2 != nil {
		panic("Something wrong")
	}

	var jpgBuffer bytes.Buffer
	jpeg.Encode(&jpgBuffer, thumb, &jpeg.Options{Quality: 70})

        of, _ := os.OpenFile("./thumb.jpg", os.O_RDWR|os.O_CREATE, os.ModePerm)

	defer of.Close()
	io.Copy(of, &jpgBuffer)
}
```
So, it looks like the stream returned by the function GetObject is not binary corresponding to the contents of the file. If i using FGetObject and working with produced file, all is ok
[2.zip](https://github.com/minio/minio-go/files/4356159/2.zip)

I attach zip file with mp4 movie. Please help me sort out this problem.

**Comment by harshavardhana** [comment]
You are not closing the file @halfshoe when returned from GetObject()

**Comment by halfshoe** [comment]
@harshavardhana, I missed this in the example, but I do not think that this is related to the problem

**Comment by harshavardhana** [comment]
> @harshavardhana, I missed this in the example, but I do not think that this is related to the problem

@halfshoe that is not possible because FGetObject is using the same code underneath - so it is an implementation issue here on your end.

**Comment by halfshoe** [comment]
@harshavardhana, you can try ). I attached mp4 file on which the problem is reproduced

**Comment by kannappanr** [comment]
@halfshoe I have to install lot more packages to try this example out. One thing I noticed was that you should change `"github.com/minio/minio-go"` to `"github.com/minio/minio-go/v6"`

**Comment by kannappanr** [comment]
```
package main

import (
         "io"
	"log"
         "os"
	"github.com/minio/minio-go"
)

func main() {
	endpoint := "play.min.io"
	accessKeyID := "Q3AM3UQ867SPQQA43P2F"
	secretAccessKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
	useSSL := true

	minioClient, _ := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
        minioClient.FPutObject("files", "test", "./2.mp4", minio.PutObjectOptions{})

        // Exchange this line with commented ones and all is ok
        reader, _ := minioClient.GetObject("files", "test", minio.GetObjectOptions{})
	
	 err := minioClient.FGetObject("files", "test", "./3.mp4", minio.GetObjectOptions{})
	 f, _ := os.Open("./3.mp4")
        defer f.Close()

	localFile, err := os.Create("4.mp4")
	if err != nil {
		log.Fatalln(err)
	}
	defer localFile.Close()

	stat, err := reader.Stat()
	log.Println(stat.Size)
	if err != nil {
		log.Fatalln(err)
	}

	if _, err := io.CopyN(localFile, reader, stat.Size); err != nil {
		log.Fatalln(err)
	}
}
```
If you see if the above example, I saved the file in both cases and did a linux diff command on the saved files and did not find any difference.

Closing this issue here, please feel free to reach out to us at https://slack.min.io for further questions.
