### ISSUE TITLE
downloading apk file from Go client seems to get corrupted

### ISSUE THREAD

**Issue by wozuo** [minio/minio-go#1257]
Hi everyone, first of all I want to thank everybody involved with this project, great work!
Now to my problem: 
I tried uploading a few different file types using the python minio client and then downloading the files with the go minio client. Every file type works fine, except .apk Android apps. At some point along the way they are corrupted.After uploading such an APK file, and then downloading it again, the downloaded APK file is smaller and misses a very small part of the file. 

Now my question: Does anybody else observe this or is there a way to fix this behaviour?

Best regards
Marc

**Comment by harshavardhana** [comment]
Most probably your code is not correct, please share the code.

**Comment by wozuo** [comment]
Hey thanks for answering, I'm not sure there is much room for mistakes and ZIP files for example work fine. But I'm uploading using the Python client like so:
```
with open(file.name, "rb") as file_data:
    file_stat = os.stat(file.name)
    minioClient.put_object("bucket", "test", file_data, file_stat.st_size)
```
And downloading via the go client like so:
```
object, err := minioClient.GetObject("bucket", filename, minio.GetObjectOptions{})
apk, err := os.Create(path)
if _, err = io.Copy(apk, object); err != nil {...}
```

**Comment by harshavardhana** [comment]
> object, err := minioClient.GetObject("bucket", filename, minio.GetObjectOptions{})
> apk, err := os.Create(path)
> if _, err = io.Copy(apk, object); err != nil {...}

you are not closing the stream here @wozuo for both object and apk

**Comment by wozuo** [comment]
Ah sorry I forgot to include that in my sample code, but I have that in there as well. The APKs are still corrupted

**Comment by kannappanr** [comment]
@wozuo Do you have a sample APK file that you can upload here?

**Comment by wozuo** [comment]
Hey @kannappanr thanks for your response, the problem was the upload. After I discovered the APK files are also corrupted after downloading using the browser, I reexamined the Python upload code and found the problem. Thanks a lot to you both for helping!
