### ISSUE TITLE
retry.go   goroutine channel leak in v6.0.51 ?

### ISSUE THREAD

**Issue by hanqingwu** [minio/minio-go#1259]
when I do putObject, getObject , RemoveObject   about 440 times,    i  found gorountine always 
 increase  in  retry.go  ,  and when i stop all action, then  I get the some goroutine profile about retry.go ,   goroutine not decrease  in retry.go .  And I check  the V6.0.50,   not  reproduce.

goroutine profile: total 293
288 @ 0x438630 0x406a1d 0x4067e5 0x7ff4db 0x4677f1
0x7ff4da	github.com/minio/minio-go/v6.Client.newRetryTimer.func2+0xaa	/home/wuhanqing/go/pkg/mod/github.com/minio/minio-go/v6@v6.0.51/retry.go:73

**Comment by harshavardhana** [comment]
You need to pass context and cancel it @hanqingwu 

But it shouldn't leak, because the retry should return. Please provide a goroutine profile let's look at it.

**Comment by hanqingwu** [comment]
[goroutine_profile.txt](https://github.com/minio/minio-go/files/4425218/goroutine_profile.txt)

**Comment by hanqingwu** [comment]
I do not call retry.go direct,  I  only use func PutObject , GetObjet and so on .

**Comment by hanqingwu** [comment]
and I add some debug info , so  I found some gorouine block in   Client.newRetryTimer.   go func  , maybe block by channel .

**Comment by hanqingwu** [comment]
when  PutObject, GetObject  Test more than 1000 times ,  goroutine increase to  more than 600 

goroutine profile: total 632
619 @ 0x438630 0x406a1d 0x4067e5 0x7ff61e 0x4677f1
	0x7ff61d	github.com/minio/minio-go/v6.Client.newRetryTimer.func2+0x1ed	/home/wuhanqing/go/pkg/mod/github.com/minio/minio-go/v6@v6.0.51/retry.go:73

**Comment by hanqingwu** [comment]
[test_retry.txt](https://github.com/minio/minio-go/files/4425982/test_retry.txt)
This is my test.go ,  it can reproduce the issuse  only in v6.0.51

**Comment by vadmeste** [comment]
> [test_retry.txt](https://github.com/minio/minio-go/files/4425982/test_retry.txt)
> This is my test.go , it can reproduce the issuse only in v6.0.51

@hanqingwu is it possible for you to test this PR ? https://github.com/minio/minio-go/pull/1260

**Comment by hanqingwu** [comment]
ok,  i will test it . @vadmeste

**Comment by hanqingwu** [comment]
@vadmeste ,  I  have test it ,  It has been fixed by #1260.

**Comment by vadmeste** [comment]
> @vadmeste , I have test it , It has been fixed by #1260.

Thanks, closing the issue then.
