### ISSUE TITLE
Unable to BucketExistsWithContext() on AWS bucket if conditional IAM rules applied.

### ISSUE THREAD

**Issue by cooperaj** [minio/minio-go#1271]
I'm setting up a backup bucket thats locked down for multiple user access. Each user should have a folder that they alone should have read/write access to.

I've defined this with a policy like this (terraform)

```terraform
  // not the whole policy. just the relevant bit
  statement {
    sid = "AllowBackupUsersAccessToS3Bucket"
    actions = [
      "s3:ListBucket"
    ]
    resources = [
      aws_s3_bucket.backup.arn
    ]
    condition {
      test     = "StringLike"
      variable = "s3:prefix"

      values = [
        "",
        "&{aws:username}/"
      ]
    }
  }
```

The BucketExistsWithContext function will fail with Access Denied with a policy like this. It looks like (after step through debugging) that the code makes a 'HTTP HEAD /' call to the bucket url 'https://s3.eu-west-1.amazonaws.com/BUCKET_NAME' which should succeed due to the "" prefix value but still fails. I can only guess that since there is no prefix value in the url AWS tries to pull one from the metadata attached to the request and this library does not attach one.

I've played with various combinations of all these permissions in the IAM policy simulator and the only one I can get to work with this library (via kopia.io backup tool) is to grant access to the entire bucket.

**Comment by harshavardhana** [comment]
You need GetBucketLocation as well @cooperaj otherwise specify the correct region.

**Comment by cooperaj** [comment]
Nope, sorry. As the comment says this is a small part of the overall policy. In addition I have

```terraform
  statement {
    sid = "AllowBackupUsersToQueryForBucketLocation"
    actions = [
      "s3:GetBucketLocation"
    ]
    resources = [
      aws_s3_bucket.backup.arn
    ]
  }

  statement {
    sid = "AllowBackupUsersFullControlOfOwnFolderInBucket"
    actions = [
      "s3:*"
    ]
    resources = [
      "${aws_s3_bucket.backup.arn}/&{aws:username}",
      "${aws_s3_bucket.backup.arn}/&{aws:username}/*"
    ]
  }
```

Step debugging tells me that the getLocation call works just fine. It's the HEAD call afterwards that fails.

**Comment by harshavardhana** [comment]
> Step debugging tells me that the getLocation call works just fine. It's the HEAD call afterwards that fails.

Then you need to add HeadBucket @cooperaj

**Comment by kannappanr** [comment]
@cooperaj Your policy needs to have atleast `HeadBucket` allowed for that API to work. If you are not passing region, you also need `GetBucketLocation`. Please feel free to reach out to us at https://slack.min.io for further such questions

**Comment by cooperaj** [comment]
A previous iteration of this policy had s3:HeadBucket assigned to *. This also didn't work and was later removed as according to the AWS documentation HeadBucket is a part of ListBucket anyway (https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html)

This policy is based mostly on this documentation https://aws.amazon.com/premiumsupport/knowledge-center/s3-folder-user-access/

**Comment by harshavardhana** [comment]
> A previous iteration of this policy had s3:HeadBucket assigned to *. This also didn't work and was later removed as according to the AWS documentation HeadBucket is a part of ListBucket anyway (https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadBucket.html)
> 
> This policy is based mostly on this documentation https://aws.amazon.com/premiumsupport/knowledge-center/s3-folder-user-access/

If it fails its not minio-go problem here @cooperaj you need to fix your policies appropriately.

Use client.TraceOn(os.Stderr) to see which calls fail, we need all those calls to be approved in your policy.
