### ISSUE TITLE
file priority changed after downloaded from server

### ISSUE THREAD

**Issue by hebe9585** [minio/minio-go#1274]
file priority changed after downloaded from server
## Expected Behavior

we used the interface  FPutObject to upload file to server and used FGetObject to download file to local. There was a found that the file's priority on local which was going to be uploaded was -rw-r--r--. After uploaded to server, checked it on server, it's still -rw-r--r--.
when downloaded from server to local, we think the file's priority should be the same.

## Current Behavior

But when it was downloaded to local， the file priority changed to -rw------- 
## Steps to Reproduce (for bugs)

1.use the interface  FPutObject to upload file to server 
 the file's priority on local which is going to be uploaded is -rw-r--r--
2.after uploaded to server, check it on server, it's still -rw-r--r--.
3.use FGetObject to download file to local.But when it was downloaded to local， the file priority changed to -rw------- .
4.

## Regression
y

## Your Environment

* Version used (`minio version`):RELEASE.2020-02-27T00-23-05Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by klauspost** [comment]
FWIW this is where the file permissions are set: https://github.com/minio/minio-go/blob/925dba936c72d0fd69b04255bb98fa1d0ee4fef7/api-get-object-file.go#L85

**Comment by klauspost** [comment]
Though I don't see we permissions being stored anywhere, so I don't think preserving them is an option.

**Comment by kannappanr** [comment]
@hebe9585 Please use `GetObject` and use the appropriate file permissions to store the object on your local file system. Closing this issue as answered, please feel free to reach out to us if you have further questions.
