### ISSUE TITLE
Help building

### ISSUE THREAD

**Issue by i0x71** [minio/minio-go#1278]
Having a little bit of trouble here with the minio-go modules, not sure if i am missing some steps here. Any suggestions ?

Thanks

~ **GO111MODULE=on go get github.com/minio/minio-go/v6**
go: cannot find main module; see 'go help modules'

~/ **git clone https://github.com/minio/minio-go/v6.git**
**cd minio-go**

~/minio-go$ **GO111MODULE=on go get github.com/minio/minio-go/v6**
 github.com/minio/minio-go/v6
./api.go:569:16: c.httpClient.CloseIdleConnections undefined (type *http.Client has no field or method CloseIdleConnections)

Go hello world works as per the https://golang.org/doc/install

**Comment by harshavardhana** [comment]
you are using an `old` Go version @i0x71 please move to latest.

**Comment by i0x71** [comment]
Thanks, will try that

**Comment by i0x71** [comment]
Installed latest 1.14 and GO111MODULE=on go get github.com/minio/minio-go/v6
works.
Thanks, please close the ticket

**Comment by i0x71** [comment]
I am not facing another issue, any suggestions would be welcome, thank you

i0x71@debian:~/mcpipe/src$ GO111MODULE=on go get github.com/minio/minio-go/v6
go: downloading github.com/minio/minio-go v1.0.0
go: downloading github.com/minio/minio-go/v6 v6.0.54
go: downloading github.com/minio/minio-go v6.0.14+incompatible
go: github.com/minio/minio-go/v6 upgrade => v6.0.54
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: downloading gopkg.in/ini.v1 v1.42.0
go: downloading golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: downloading golang.org/x/text v0.3.0
i0x71@debian:~/mcpipe/src$ go run mcpipe.go 
mcpipe.go:4:2: cannot find module providing package github.com/minio/minio-go/v6: working directory is not part of a module
i0x71@debian:~/mcpipe/src$ cd ..
i0x71@debian:~/mcpipe$ go run src/mcpipe.go 
src/mcpipe.go:4:2: cannot find module providing package github.com/minio/minio-go/v6: working directory is not part of a module

**Comment by harshavardhana** [comment]
```
GO111MODULE=on go run src/mcpipe.go
```

You need to start reading Go docs on how to do these things @i0x71 - our issues are not meant for Q/A on go building exercise.

**Comment by i0x71** [comment]
Issue was fixed by running the following steps
GO111MODULE=on go get github.com/minio/minio-go/v6
go mod init github.com/minio
