### ISSUE TITLE
Disconnect/Close connection

### ISSUE THREAD

**Issue by i0x71** [minio/minio-go#1284]
Hello,
I could not find any mentions here: https://docs.min.io/docs/golang-client-api-reference.html

As to how i can disconnect the client, any suggestions ?

Thanks

**Comment by harshavardhana** [comment]
There is no such thing, its an HTTP client what are you trying to achieve?

**Comment by i0x71** [comment]
I have a function which open a minio connection on demand, at the moment that function creates a client and gets an object.
Should the minio.New part be moved to a global space and just be reused ?
If so is there any connection error/close handing that needs to be done ?

**Comment by harshavardhana** [comment]
> I have a function which open a minio connection on demand, at the moment that function creates a client and gets an object.
> Should the minio.New part be moved to a global space and just be reused ?
> If so is there any connection error/close handing that needs to be done ?

First I think you need to get a hang of writing code using net/http https://golang.org/pkg/net/http/

minio.New is a single persistent object for the life time of a program
connection error/close handling is automatically done in the code.
you only need to Close() the Reader() that is sent to you for consumption such as GetObject()

**Comment by harshavardhana** [comment]
Also please ask these questions in our https://slack.min.io - we would like to limit GitHub issues for issue management alone.
