### ISSUE TITLE
Remove metadata using CopyObject fails

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio-go#1295]
I am trying to copy an object within a S3 bucket to remove its metadata:

```go
metadata := map[string]string{}
src := minio.NewSourceInfo(bucketName, name, nil)
dst, err := minio.NewDestinationInfo(bucketName, name, nil, metadata)
if err != nil {
	return err
}
err = client.CopyObject(dst, src)
if err != nil {
	return err
}
```

This fails with an error with S3 saying that the copy is illegal because I'm not altering anything (including metadata).

The reason seems to be that when the length of metadata is 0, the `getUserMetaHeadersMap` returns early:

https://github.com/minio/minio-go/blob/master/api-compose-object.go#L155

Instead, it should still set `r["x-amz-metadata-directive"] = "REPLACE"` in the following block.

Trying to manually set the `x-amz-metadata-directive` header in the metadata object doesn't work that isn't one of the `isAmzHeader` headers. The only "workaround" that seemed to work was to set an empty header (`"": ""`).

**Comment by kannappanr** [comment]
@ItalyPaleAle We are making a change in minio-go such that if you want the metadata to be replaced, you can set the `x-amz-metadata-directive` option to `REPLACE` as a metadata

```
package main

import (
	"log"
	"os"
	"github.com/minio/minio-go/v6"
)

func main() {
	s3Client, err := minio.New("play.min.io", "minio", "minio123", true)
	if err != nil {
		log.Fatalln(err)
	}

	// Enable trace.
	 s3Client.TraceOn(os.Stderr)

	// Source object
	src := minio.NewSourceInfo("test", "issue", nil)

        m := make(map[string]string)
        m["x-amz-metadata-directive"]="REPLACE"
	// Destination object
	dst, err := minio.NewDestinationInfo("test", "issue", nil, m)
	if err != nil {
		log.Fatalln(err)
	}

	// Initiate copy object.
	err = s3Client.CopyObject(dst, src)
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Successful.")
}
```

**Comment by ItalyPaleAle** [comment]
This will work. Thanks for the quick fix!
