### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by davidjije** [minio/minio-go#1297]
Hi, recently i was struggling with minio and discovered very weird bug.
I have one variable for image, which is `multipart.File (implements io.Reader)`
Before calling `PutObject()` method if i use this method `image.DecodeConfig(image)` - minio `PutObject()` returns me this error after some waiting - `"Put "some-url": net/http: HTTP/1.x transport connection broken: http: ContentLength='x' with Body length 'x' "`
Otherwise is uploads object successfully within milliseconds.

**Comment by kannappanr** [comment]
@davidjije Can you please provide a sample code to reproduce the issue?

**Comment by davidjije** [comment]
https://gist.github.com/davidjije/e60788892f951c3f401469ed0237c978 - file.go
https://gist.github.com/davidjije/f2533a7df552610a86a8fcb9fb75a121 - store.go

**Comment by davidjije** [comment]
> @davidjije Can you please provide a sample code to reproduce the issue?

https://gist.github.com/davidjije/e60788892f951c3f401469ed0237c978 - file.go
https://gist.github.com/davidjije/f2533a7df552610a86a8fcb9fb75a121 - store.go

**Comment by klauspost** [comment]
You read from `src` inside `getImageDimension`, so the `io.Reader` you send to `s.store.Save` no longer returns the entire image, but only the remaining data.

**Comment by davidjije** [comment]
> You read from `src` inside `getImageDimension`, so the `io.Reader` you send to `s.store.Save` no longer returns the entire image, but only the remaining data.

Whoops... Thank you very much
