### ISSUE TITLE
Record Metrics on Deleted Objects in Bulk Delete

### ISSUE THREAD

**Issue by MichaHoffmann** [minio/minio-go#1303]
I would like to record metrics like "how many objects were deleted", "how much space was freed" when performing concurrent `RemoveObjects` calls with the minio-sdk. I'm inclined to think that its not possible because, when the S3-api call fails due to connectivity, i cannot be sure which objects were batched. Am i wrong, is there a way to achieve this?

**Comment by harshavardhana** [comment]
You need to do this in your application, Go SDK only provides abstracted primitives for S3 API only

**Comment by MichaHoffmann** [comment]
Of course i understand that, but im not sure how to do this, thats why i asked.

**Comment by harshavardhana** [comment]
> Of course i understand that, but im not sure how to do this, thats why i asked.

There is no one size fits all solution here, it is entirely dependent on how you implement it and how involved is your application.

Simplest is Listing namespace, which returns size and pass it to delete objects. Upon success you know how much you deleted.

This is the simplest of course but more involved might require maintain an index somewhere which is updated once deletes happen, this index is queriable to look for how much data was deleted etc.

Beyond this it's out of scope for us. - SDKs are present,  how to write an application is your choice.
