### ISSUE TITLE
Breaking changes to v7

### ISSUE THREAD

**Issue by vadmeste** [minio/minio-go#1308]
The list of possible breaking changes before v7:
[x] Removing WithContext functions
[x] New Copy/Compose API (Harsha)
[x] New Versioninig API
[x] GetObjectTagging() returns a map of key/value instead of a string
[x] MakeBucket using options for location/locking instead of separate functions
[x] Removal of public Err() functions
[x] StatObjectOptions is a type alias of GetObjectOptions
[x] Implement SetBucketVersioning(bucket, Enable/Suspend) (pending review)
[x] ILM change, receives a structure instead of the XML
[x] Check if minio-go SQL is capable to not send an empty xml configuration tag to indicate the default value instead of empty.
[x] Check the documentation and examples before the release!!!!

**Comment by harshavardhana** [comment]
All done!
