### ISSUE TITLE
Export initiateMultipartUpload, completeMultipartUpload functions

### ISSUE THREAD

**Issue by cschloer** [minio/minio-go#1309]
Hi.

I'm trying to implement multipart upload in the browser. Something similar to this: https://github.com/prestonlimlianjie/aws-s3-multipart-presigned-upload

That requires the ability to start a multipart upload on the server, get urls for each part, and complete the multipart upload. As of now that is not possible with the minio client, despite the fact that those functions exist. Can you export the necessary functions?

https://github.com/minio/minio-go/blob/master/api-put-object-multipart.go#L185

**Comment by vadmeste** [comment]
@cschloer you should be able to use minio.NewCore() (https://godoc.org/github.com/minio/minio-go#Core) and execute low levels S3 APIs

**Comment by cschloer** [comment]
I appreciate the quick reply!
