### ISSUE TITLE
STS Web Identity Credentials not cached

### ISSUE THREAD

**Issue by gregoryfranklin** [minio/minio-go#1321]
When using `credentials.IAM{}` with AWS_WEB_IDENTITY_TOKEN_FILE, the credentials are not cached resulting in an AssumeRoleWithWebIdentity STS call on every request.

#1183 added the ability to use the AWS_WEB_IDENTITY_TOKEN_FILE environment variable with `credentials.IAM{}`
https://github.com/minio/minio-go/blob/v6.0.56/pkg/credentials/iam_aws.go#L83
It does this by creating the STSWebIdentity credentials provider in `func (m *IAM) Retrieve()` and calling `Retrieve()` on that
https://github.com/minio/minio-go/blob/v6.0.56/pkg/credentials/iam_aws.go#L107

However, when you call IsExpired() in the IAM credentials provider it always returns true because the expiry has been set on the STSWebIdentity credentials provider not on the IAM credentials provider.

For reference, in the case of ECS and EC2 roles, the expiry is set correctly
https://github.com/minio/minio-go/blob/v6.0.56/pkg/credentials/iam_aws.go#L140

In my case, the impact of this is that Thanos runs extremely when using IAM Roles for Service Accounts because it is making an STS call on every request to S3.
https://github.com/thanos-io/thanos/issues/2097

**Comment by harshavardhana** [comment]
@gregoryfranklin feel free to send a fix
