### ISSUE TITLE
Big File breakpoint-upload

### ISSUE THREAD

**Issue by yuyuanshifu** [minio/minio-go#1324]
The PutObject function has uploaded big file by multiparts, why don't minio support break-point upload?
I suppose that :
1、minio record the uploading result of every part and provide a interface to query
2、public the part upload interface and complate multi part interface
So we can make big file breakpoint-upload come true.

**Comment by harshavardhana** [comment]
@yuyuanshifu This library is meant to be simple, minio-go automatically handles multipart upload as the stream is read. Providing low level access is not the intention of this library.

For low level access you should stick to aws-sdk-go
