### ISSUE TITLE
STSWebIdentity doesn't allow overriding http.Client Transport to provide CA

### ISSUE THREAD

**Issue by OliverKnights** [minio/minio-go#1326]
When calling NewSTSWebIdentity a Credentials object with provider set to STSWebIdentity is returned. (sts_web_identity.go:97)
```
	return New(&STSWebIdentity{
		Client: &http.Client{
			Transport: http.DefaultTransport,
		},
		stsEndpoint:         stsEndpoint,
		getWebIDTokenExpiry: getWebIDTokenExpiry,
	}), nil
```
 This provider field is unexported with no way to override the default transport mechanism set on the http.Client. This means when making the assume role request to a MinIO instance with self signed certificates the request fails with `x509: certificate signed by unknown authority` as we haven't provided the CA.

This is in contrast with the actual minio client, which provides a `SetCustomTransport` method.
Would it be possible to provide something similar for the STSWebIdentity object?

Many thanks
Oliver

**Comment by harshavardhana** [comment]
We already expose http.Client which can take custom transport, there is no reason to have SetCustomTransport API, use as shown below. 

> return New(&STSWebIdentity{
> 		Client: &http.Client{
> 			Transport: myShinyTransport,
> 		},
> 		stsEndpoint:         stsEndpoint,
> 		getWebIDTokenExpiry: getWebIDTokenExpiry,
> 	}), nil

**Comment by OliverKnights** [comment]
Thanks for the reply and sorry to leave it so long before responding,
The http.Client is exposed in the STSWebIdentity, but when using the NewSTSWebIdentity constructor that gets returned in a Credentials struct, in which the Provider (STSWebIdentity) is an unexported field, hence cannot be modified.

I originally thought I could get around this by not using the NewSTSWebIdentity constructor and instead calling credentials.New and constructing the object myself as the constructor does. But of course stsEndpoint and getWebIDTokenExpiry are unexported fields so I can no longer set those.

Does that make sense?

**Comment by harshavardhana** [comment]
> Thanks for the reply and sorry to leave it so long before responding,
> The http.Client is exposed in the STSWebIdentity, but when using the NewSTSWebIdentity constructor that gets returned in a Credentials struct, in which the Provider (STSWebIdentity) is an unexported field, hence cannot be modified.
> 
> I originally thought I could get around this by not using the NewSTSWebIdentity constructor and instead calling credentials.New and constructing the object myself as the constructor does. But of course stsEndpoint and getWebIDTokenExpiry are unexported fields so I can no longer set those.
> 
> Does that make sense?

Actually It can be an exported field, let me see if there is a cleaner way to add this.
