### ISSUE TITLE
Provide errors to public API

### ISSUE THREAD

**Issue by Russiancold** [minio/minio-go#1339]
Hi! Is making errors from `v6/s3-errors.go` public in your backlog?

**Comment by harshavardhana** [comment]
No we are not doing that what is the purpose?

**Comment by Russiancold** [comment]
@harshavardhana Now I see only one way to check an error - comparing it to hardcoded string. I don't really like it. Is there any other way? In my particular case I want to check if the requested bucket exists looking into `*Object` from `GetObject`

**Comment by harshavardhana** [comment]
> @harshavardhana Now I see only one way to check an error - comparing it to hardcoded string. I don't really like it. Is there any other way? In my particular case I want to check if the requested bucket exists looking into `*Object` from `GetObject`

You are okay with hardcoded error type but not with strings ?

The string error code doesn't change it's part of S3 spec.

**Comment by Russiancold** [comment]
Hardcoded `if err == minio.BucketNotExistsError` will not compile if the public API changes. So yes, it's much better)
Okay, hope, that messages will not change further)

**Comment by harshavardhana** [comment]
> Hardcoded `if err == minio.BucketNotExistsError` will not compile if the public API changes. So yes, it's much better)
> Okay, hope, that messages will not change further)

S3 has zillion errors we cannot make zillon error types in that manner. We have one type ErrorResponse and look for correct code in that response.

**Comment by ddevault** [comment]
AWS's S3 Go library sees fit to add at least a few strongly typed errors:

https://docs.aws.amazon.com/sdk-for-go/api/service/s3/

See i.e. ErrCodeBucketAlreadyExists, ErrCodeBucketAlreadyOwnedByYou, etc. minio-py also sees fit to offer similar errors like [`minio.errors.BucketAlreadyOwnedByYou`](https://github.com/minio/minio-py/blob/d266a153118499a57ef0ad5d0aa0e04693d98422/README.md#quick-start-example---file-uploader).

Strongly typed errors are an absolute necessity for proper handling of expected errors. String munging heuristics are no substitute.
