### ISSUE TITLE
Minio always uses MD5 also for SHA256 hashes?

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio-go#1346]
I noticed this reading the code so must admit I haven't actually tried it, but...

Shouldn't this line:

https://github.com/minio/minio-go/blob/master/api.go#L92

Be using https://github.com/minio/sha256-simd instead?

**Comment by harshavardhana** [comment]
> I noticed this reading the code so must admit I haven't actually tried it, but...
> 
> Shouldn't this line:
> 
> https://github.com/minio/minio-go/blob/master/api.go#L92
> 
> Be using https://github.com/minio/sha256-simd instead?

No, it is not @ItalyPaleAle it is just interface compatibility it is not used by default - that has nothing to do with the actual usage internally. 

You don't need to set CustomMD5, CustomSHA256 unless you writing your own implementation.

**Comment by ItalyPaleAle** [comment]
Ok thanks for clarifying :) 

I'm trying to update my code to use the v7 APIs but can't find docs besides the API themselves, so I've been digging in the source code.

**Comment by harshavardhana** [comment]
> I'm trying to update my code to use the v7 APIs but can't find docs besides the API themselves, so I've been digging in the source code.

Docs are available at https://pkg.go.dev/github.com/minio/minio-go/v7?tab=doc and also

**Comment by ItalyPaleAle** [comment]
I don't know if I'm doing something wrong on my side, then, but the docs here: https://docs.min.io/docs/golang-client-api-reference and the examples like: https://github.com/minio/minio-go/blob/master/examples/s3/getobject.go#L40

Don't seem to work to create a new Minio Client object.

The API reference shows a different interface than the docs and code samples: https://pkg.go.dev/github.com/minio/minio-go/v7?tab=doc#New

**Comment by harshavardhana** [comment]
> I don't know if I'm doing something wrong on my side, then, but the docs here: https://docs.min.io/docs/golang-client-api-reference and the examples like: https://github.com/minio/minio-go/blob/master/examples/s3/getobject.go#L40

Those were missed in our updates I am fixing them now @ItalyPaleAle
