### ISSUE TITLE
Range ignored with client.GetObject requests

### ISSUE THREAD

**Issue by ItalyPaleAle** [minio/minio-go#1347]
Sorry for the second issue. I've been trying to understand why this isn't working for over 2 hours now, and upgrading the client library from v6 to v7 doesn't seem to solve it.

When testing against a Minio server, this seems to reproduce the issue all the times:

```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	client, err := minio.New(os.Getenv("S3_ENDPOINT"), &minio.Options{
		Creds:  credentials.NewStaticV4(os.Getenv("AWS_ACCESS_KEY_ID"), os.Getenv("AWS_SECRET_ACCESS_KEY"), ""),
		Secure: false,
	})
	if err != nil {
		panic(err)
	}

	opts := minio.GetObjectOptions{}
	opts.SetRange(0, 100)
	obj, err := client.GetObject(context.Background(), "e2e", "data/1612589f-c4b4-4e52-b85b-6594e2a4f602", opts)
	if err != nil {
		panic(err)
	}
	defer obj.Close()

	stat, err := obj.Stat()
	if err != nil || stat.Size == 0 {
		panic(err)
	}
	fmt.Println(stat.Size)

	read, err := ioutil.ReadAll(obj)
	if err != nil {
		panic(err)
	}
	fmt.Println(len(read))
}
```

In the example above, I'm only trying to request the first 100 bytes from the file. However, the code still returns the entire file, and the output is:

```
$ go run .
600549
600549
```

(600549 is the full size of the file)

Setting a range that doesn't start from 0 doesn't seem to work either.

**Comment by harshavardhana** [comment]
> ```go
> 	opts.SetRange(0, 100)
> ```

You don't set the Range in that manner @ItalyPaleAle you use the returned reader to be a Seeker or ReadAt

**Comment by harshavardhana** [comment]
> ```go
> 	stat, err := obj.Stat()
> ```

Think of it like filesystem APIs

**Comment by ItalyPaleAle** [comment]
Do you have any documentation or example for this?

Without those, I went through the APIs and I found that `GetObject` supports a `minio.GetObjectOptions` argument, which has a `SetRange` method... It's weird that the option is available even though it's not supported.

**Comment by harshavardhana** [comment]
> Without those, I went through the APIs and I found that `GetObject` supports a `minio.GetObjectOptions` argument, which has a `SetRange` method... It's weird that the option is available even though it's not supported.

Its simply a type alias to StatObjectOptions @ItalyPaleAle it is not meant for that we didn't document that on purpose.

the returned value from GetObject() is like *os.File you can do Seek, ReadAt with it I guess you know how to use *os.File

**Comment by harshavardhana** [comment]
> Its simply a type alias to StatObjectOptions @ItalyPaleAle it is not meant for that we didn't document that on purpose.

Will just mention that its not supposed to be used in this manner :-)

**Comment by jamisonhyatt** [comment]
I'l be honest - this issue confuses me. 

The original report says setting the range header doesn't work...but it seems to work perfectly fine when speaking with S3. Is this an incompatibility with minio?

Then there's communication that you're not supposed to use it, yet it's both [exported and properly documented](https://github.com/minio/minio-go/blob/39dead307a0db5aedfe21b55567e6cf2b665f94e/api-get-options.go#L107).

What am I missing here?

``` go
	req = minio.GetObjectOptions{}
	err = req.SetRange(727, 1754)
	if err != nil {
		log.Fatal(err)
	}

	obj, err = client.GetObject(ctx, bucket, "some/key", req)
	if err != nil {
		log.Fatal(err)
	}
	b, err = ioutil.ReadAll(obj)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("length of content with range header is %v\n",len(b))
```
> length of content with range header is 1028

I also verified with an MD5 hash that the above is the correct, expected, 1028 bytes.

``` go
	obj, err = client.GetObject(ctx, bucket, "same/key", minio.GetObjectOptions{})
	if err != nil {
		log.Fatal(err)
	}
	b, err = ioutil.ReadAll(obj)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("length of content without range header is %v\n",len(b))
```
> length of content without range header is 1225216

**Comment by jamisonhyatt** [comment]
ah, @ItalyPaleAle - it appears that `opts.SetRange(0, 100)` works as expected to set a `range` header, but does a `delete(headers["range"])`, if you happen to `Stat` the object *before* reading it.

**Comment by ItalyPaleAle** [comment]
@jamisonhyatt I fixed this by using the core API rather than the higher-level one: https://godoc.org/github.com/minio/minio-go#NewCore

In my case, I needed lower-level control on the requests made to Minio as I needed precise access to the chunks and streams.
