### ISSUE TITLE
putObjectMultipartStreamNoLength not returning (spinning) on ErrUnexpectedEOF

### ISSUE THREAD

**Issue by streamer45** [minio/minio-go#1353]
Hi,

I'm having an issue when trying to feed `PutObject` with a reader coming from a HTTP request where the request's body is converted into a `http.MaxBytesReader`. If the underlying connection is suddenly interrupted the reader will return `ErrUnexpectedEOF` but the loop in `putObjectMultipartStreamNoLength` will keep iterating on `totalPartsCount` which in my case gets set to 8192. This in turn will make the CPU spike and a high number of requests being made by the minio client of zero length in body.

Is there a reason for ignoring `ErrUnexpectedEOF`?

Here's an example which should reproduce the issue:

```go
package main

import (
	"bytes"
	"log"
	"net/http"

	"github.com/minio/minio-go/v6"
)

func main() {
	endpoint := "localhost:9000"
	accessKeyID := ""
	secretAccessKey := ""
	maxFileSize := int64(1024 * 1024 * 1024) // 1GB

	uploadHandler := func(w http.ResponseWriter, req *http.Request) {
		minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, false)
		if err != nil {
			log.Fatalln(err)
		}
		r := http.MaxBytesReader(w, req.Body, maxFileSize+bytes.MinRead)
		written, err := minioClient.PutObject("test", "testfile", r, -1, minio.PutObjectOptions{})
		if err != nil {
			log.Fatalln(err)
		}
		log.Println(written)
	}

	http.HandleFunc("/upload", uploadHandler)
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

```sh
curl -X POST http://localhost:8080/upload --upload-file some_file --limit-rate 1k
```

Interrupting the upload before its completion triggers the problem.

Any help with this would be greatly appreciated, thanks :)

**Comment by harshavardhana** [comment]
This is actually a bug in the io.ReadFull implementaion or the io.Reader passed to io.ReadFull because 

```
ReadFull reads exactly len(buf) bytes from r into buf. It returns the number of bytes copied and an error if fewer bytes were read. The error is EOF only if no bytes were read. If an EOF happens after reading some but not all the bytes, ReadFull returns ErrUnexpectedEOF. On return, n == len(buf) if and only if err == nil. If r returns an error having read at least len(buf) bytes, the error is dropped.
```

Let's highlight 

> The error is EOF only if no bytes were read.

So here the issue is that io.ReadFull has `length` == 0 and err set to io.ErrUnexpectedEOF this means that

> 		r := http.MaxBytesReader(w, req.Body, maxFileSize+bytes.MinRead)

has an incorrect reader implementation which returns io.ErrUnexpectedEOF which an io.Reader shouldn't do, 
so points to a deeper bug in the Go ecosystem.


```go
// ReadAtLeast reads from r into buf until it has read at least min bytes.
// It returns the number of bytes copied and an error if fewer bytes were read.
// The error is EOF only if no bytes were read.
// If an EOF happens after reading fewer than min bytes,
// ReadAtLeast returns ErrUnexpectedEOF.
// If min is greater than the length of buf, ReadAtLeast returns ErrShortBuffer.
// On return, n >= min if and only if err == nil.
// If r returns an error having read at least min bytes, the error is dropped.
func ReadAtLeast(r Reader, buf []byte, min int) (n int, err error) {
	if len(buf) < min {
		return 0, ErrShortBuffer
	}
	for n < min && err == nil {
		var nn int
		nn, err = r.Read(buf[n:])
		n += nn
	}
	if n >= min {
		err = nil
	} else if n > 0 && err == EOF {
		err = ErrUnexpectedEOF
	}
	return
}
```

So here the implementation simply ignores the situation when `nn == 0` and `err == io.ErrUnexpectedEOF` which should be either silently converted to `err == io.EOF`  or it can lead to bugs like this since the reader is consistently returning io.ErrUnexpectedEOF instead of `io.EOF` at EOF. 

So I went ahead and added logs to io.ReadAtLeast() which is where I saw that r.Read() indeed returns io.ErrUnexpectedEOF with `nn == 0` - this can lead to quite a lot of bugs from the caller who expects to believe this language 

```
ReadFull reads exactly len(buf) bytes from r into buf. It returns the number of bytes copied and an error if fewer bytes were read. The error is EOF only if no bytes were read. If an EOF happens after reading some but not all the bytes, ReadFull returns ErrUnexpectedEOF. On return, n == len(buf) if and only if err == nil. If r returns an error having read at least len(buf) bytes, the error is dropped.
```

Now keeping all this in mind that io.Reader implementations can return io.ErrUnexpectedEOF this means that io.ReadFull is going to lead to bugs in subtle ways if not well understood. 

https://golang.org/pkg/io/#Reader documentation either lacks this clarity or looks like MaxBytesReader is not following this because If I keep reading after the client has closed connection, then it keeps returning io.ErrUnexpectedEOF which is an implementation issue here. 

Modified the code
```
go run ./t.go
2020/07/24 20:21:55 Read-1 65536 unexpected EOF
2020/07/24 20:21:55 Read-2 0 unexpected EOF
2020/07/24 20:21:55 Should be io.EOF false
```

```go
package main

import (
        "bytes"
        "io"
        "log"
        "net/http"
)

func main() {
        maxFileSize := int64(1024 * 1024 * 1024) // 1GB

        uploadHandler := func(w http.ResponseWriter, req *http.Request) {
                r := http.MaxBytesReader(w, req.Body, maxFileSize+bytes.MinRead)
                buf := make([]byte, 100*1024*1024)

                // First read
                n, err := io.ReadFull(r, buf)
                log.Println("Read-1", n, err)

                // Second read
                n, err = io.ReadFull(r, buf)
                log.Println("Read-2", n, err)
                log.Println("Should be io.EOF", err == io.EOF)
        }

        http.HandleFunc("/upload", uploadHandler)
        log.Fatal(http.ListenAndServe(":8080", nil))
}
```

To dig further avoid using wrapper io.ReadFull() lets directly call r.Read

```go
package main

import (
        "bytes"
        "io"
        "log"
        "net/http"
)

func main() {
        maxFileSize := int64(1024 * 1024 * 1024) // 1GB

        uploadHandler := func(w http.ResponseWriter, req *http.Request) {
                r := http.MaxBytesReader(w, req.Body, maxFileSize+bytes.MinRead)
                buf := make([]byte, 100*1024*1024)

                // First read
                n, err := r.Read(buf)
                log.Println("Read-1", n, err)

                // Second read
                n, err = r.Read(buf)
                log.Println("Read-2", n, err)
                log.Println("Should be io.EOF", err == io.EOF)
        }

        http.HandleFunc("/upload", uploadHandler)
        log.Fatal(http.ListenAndServe(":8080", nil))
}
```

```
go run ./t.go
2020/07/24 20:23:27 Read-1 65536 <nil>
2020/07/24 20:23:33 Read-2 0 unexpected EOF
2020/07/24 20:23:33 Should be io.EOF false
```

This should be io.EOF since the client has canceled the connection. 

> When Read encounters an error or end-of-file condition after successfully reading n > 0 bytes, it returns the number of bytes read. It may return the (non-nil) error from the same call or return the error (and n == 0) from a subsequent call. An instance of this general case is that a Reader returning a non-zero number of bytes at the end of the input stream may return either err == EOF or err == nil. The next Read should return 0, EOF.

**Comment by harshavardhana** [comment]
NOTE: I used curl with 3 bytes a second

>curl -X POST http://localhost:8080/upload --upload-file ~/Downloads/ubuntu-18.04-desktop-amd64.iso --limit-rate 3

**Comment by streamer45** [comment]
@harshavardhana 

thank you for the excellent analysis :+1: 

So, if I understood this correctly, the main issue is that we expect `EOF` to be returned since `Read()` returned 0 but instead we get an `ErrUnexpectedEOF` which _in theory_ should be returned only when at least some data was read.

Also, directly passing the HTTP request's body works fine which indicates it's indeed the `http.MaxBytesReader` causing the problems. 

Looking at that, the problem appears to be the _sticky_ error they use here:
https://golang.org/src/net/http/request.go?s=36920:36960#L1117
After the first failure the `Read()` implementation will just return 0 and whatever the original error was.

Maybe it makes sense to also raise this with the Golang's team, at least to get some clarification.

**Comment by harshavardhana** [comment]
> @harshavardhana 
> 
> thank you for the excellent analysis :+1: 
> 
> So, if I understood this correctly, the main issue is that we expect `EOF` to be returned since `Read()` returned 0 but instead we get an `ErrUnexpectedEOF` which _in theory_ should be returned only when at least some data was read.
> 
> Also, directly passing the HTTP request's body works fine which indicates it's indeed the `http.MaxBytesReader` causing the problems. 
> 
> Looking at that, the problem appears to be the _sticky_ error they use here:
> https://golang.org/src/net/http/request.go?s=36920:36960#L1117
> After the first failure the `Read()` implementation will just return 0 and whatever the original error was.
> 
> Maybe it makes sense to also raise this with the Golang's team, at least to get some clarification.

Yes definitely that's the bug here, http.MaxBytesReader is actually making a strong assumption which is defeating io.Reader behavior.

But we do have a workaround.
