### ISSUE TITLE
Working with S3 accelerated

### ISSUE THREAD

**Issue by bjg2** [minio/minio-go#1361]
I'm trying to work with accelerated S3, but can't manage to do so, can you explain how it is expected to work?

I tried this:
```
	minio.New("s3-accelerate.amazonaws.com", &minio.Options{
		Creds:  credentials.NewStaticV4(s3Auth.AccessKey, s3Auth.SecretKey, ""),
		Secure: true,
		Region: "accelerate",
	})
```

Also, tried to put the region of my bucket, it worked, but slow as if not accelerated.

**Comment by kannappanr** [comment]
```
minio.New("s3-accelerate.amazonaws.com", &minio.Options{
		Creds:  credentials.NewStaticV4(s3Auth.AccessKey, s3Auth.SecretKey, ""),
		Secure: true,
                Region: "us-east-1", // appropriate region
	})
```

```
// Enable S3 transfer accelerate endpoint.
	s3Client.SetS3TransferAccelerate("s3-accelerate.amazonaws.com")
```
Once you add `s3Client.SetS3TransferAccelerate("s3-accelerate.amazonaws.com")` it should use the accelerate endpoint. If the bucket is configured to use it, the speed will be faster.

closing this as answered. please feel free to reach out to us if you have further questions

**Comment by bjg2** [comment]
It works, thanks!

Just a quick question: as I understand regardless of the endpoint parameter in New, the line bellow is the one that makes request accelerated:

```
	s3Client.SetS3TransferAccelerate("s3-accelerate.amazonaws.com")
```

So, I can give "s3-accelerate.amazonaws.com" as endpoint parameter to New always (even if the bucket is not accelerated)? I'm aksking because I see it works that way. :)
