### ISSUE TITLE
ISSUE in first sample code in the given URL https://github.com/minio/minio-go/tree/v7.0.4?

### ISSUE THREAD

**Issue by prashant7july** [minio/minio-go#1365]
Hi,

I'm trying to work with minio-go v7, but facing the issue as below after execute the docker run command and then use _docker logs CONATNER_ID_ . Please advise for missing area?

&minio.Client{endpointURL:(*url.URL)(0xc000022500), credsProvider:(*credentials.Credentials)(0xc000066900), overrideSignerType:0, appInfo:struct { appName string; appVersion string }{appName:"", appVersion:""}, secure:false, httpClient:(*http.Client)(0xc0001b0870), bucketLocCache:(*minio.bucketLocationCache)(0xc00000ee80), isTraceEnabled:false, traceErrorsOnly:false, traceOutput:io.Writer(nil), s3AccelerateEndpoint:"", region:"", random:(*rand.Rand)(0xc0001b08d0), lookup:0, md5Hasher:(func() md5simd.Hasher)(0x7cc1e0), sha256Hasher:(func() md5simd.Hasher)(0x7cc2a0)}

**Dockerfile**
```
FROM golang:latest
WORKDIR /app
RUN go mod init uploadsvc
COPY . .
RUN go build -o main .
CMD ["./main"]
```

**main.go**
```
package main

import (
	"log"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"

	"os"
)

func main() {
	endpoint := os.Getenv("MINIO_URL")	
	accessKeyID := os.Getenv("MINIO_ACCESS_KEY")
	secretAccessKey := os.Getenv("MINIO_SECRET_KEY")
	useSSL := false

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln(err)
	}

	log.Printf("%#v\n", minioClient) // minioClient is now setup
}
```

**Execute docker command -**
```
docker build -t upload:latest .
docker run -d --net="host" \
    --name=uploadsample \
    -e MINIO_URL="play.min.io" \
    -e MINIO_ACCESS_KEY="Q3AM3UQ867SPQQA43P2F" \
    -e MINIO_SECRET_KEY="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG" \
    upload:latest

```

**Comment by nitisht** [comment]
What is the problem here?

**Comment by prashant7july** [comment]
Whats is this -

&minio.Client{endpointURL:(*url.URL)(0xc000022500), credsProvider:(*credentials.Credentials)(0xc000066900), overrideSignerType:0, appInfo:struct { appName string; appVersion string }{appName:"", appVersion:""}, secure:false, httpClient:(*http.Client)(0xc0001b0870), bucketLocCache:(*minio.bucketLocationCache)(0xc00000ee80), isTraceEnabled:false, traceErrorsOnly:false, traceOutput:io.Writer(nil), s3AccelerateEndpoint:"", region:"", random:(*rand.Rand)(0xc0001b08d0), lookup:0, md5Hasher:(func() md5simd.Hasher)(0x7cc1e0), sha256Hasher:(func() md5simd.Hasher)(0x7cc2a0)}

**Comment by nitisht** [comment]
> Whats is this -
> 
> &minio.Client{endpointURL:(*url.URL)(0xc000022500), credsProvider:(*credentials.Credentials)(0xc000066900), overrideSignerType:0, appInfo:struct { appName string; appVersion string }{appName:"", appVersion:""}, secure:false, httpClient:(*http.Client)(0xc0001b0870), bucketLocCache:(*minio.bucketLocationCache)(0xc00000ee80), isTraceEnabled:false, traceErrorsOnly:false, traceOutput:io.Writer(nil), s3AccelerateEndpoint:"", region:"", random:(*rand.Rand)(0xc0001b08d0), lookup:0, md5Hasher:(func() md5simd.Hasher)(0x7cc1e0), sha256Hasher:(func() md5simd.Hasher)(0x7cc2a0)}

I think this is because you're printing the `minioClient`

**Comment by prashant7july** [comment]
Really thanks

**Comment by prashant7july** [comment]
Really thanks
