### ISSUE TITLE
How to set the policy of the directory in the bucket

### ISSUE THREAD

**Issue by iamwlb** [minio/minio-go#1375]
The earlier api was
```go
SetBucketPolicy(bucketname, objectPrefix string, policy policy.BucketPolicy) error
```
But now the api is
```go
SetBucketPolicy(ctx context.Context, bucketname, policy string) error
```
In the new api, the policy is a json, which is not as convenient as the old version of the api.

**Comment by harshavardhana** [comment]
You don't set bucket policy on a directory that's why it's called bucket policy.

Directory is part of the resource string you need to construct read about it  https://docs.aws.amazon.com/AmazonS3/latest/dev/access-policy-language-overview.html it here.

**Comment by harshavardhana** [comment]
> The earlier api was
> 
> ```go
> SetBucketPolicy(bucketname, objectPrefix string, policy policy.BucketPolicy) error
> ```
> 
> But now the api is
> 
> ```go
> SetBucketPolicy(ctx context.Context, bucketname, policy string) error
> ```
> 
> In the new api, the policy is a json, which is not as convenient as the old version of the api.

You construct the JSON as you want use the `pkg/policy` if needed in this repo to generate a canned JSON

**Comment by iamwlb** [comment]
> > The earlier api was
> > ```go
> > SetBucketPolicy(bucketname, objectPrefix string, policy policy.BucketPolicy) error
> > ```
> > 
> > 
> > But now the api is
> > ```go
> > SetBucketPolicy(ctx context.Context, bucketname, policy string) error
> > ```
> > 
> > 
> > In the new api, the policy is a json, which is not as convenient as the old version of the api.
> 
> You construct the JSON as you want use the `pkg/policy` if needed in this repo to generate a canned JSON

can you give me a demo?
