### ISSUE TITLE
retry will cause unnecessary wait on the last times

### ISSUE THREAD

**Issue by magictour** [minio/minio-go#1383]
```
      go func() {
		defer close(attemptCh)
		for i := 0; i < maxRetry; i++ {
			select {
			case attemptCh <- i + 1:
			case <-ctx.Done():
				return
			}
			select {
			case <-time.After(exponentialBackoffWait(i)):
			case <-ctx.Done():
				return
			}
		}
	}()
```

This code  in retry.go will wait until the time.After(exponentialBackoffWait(i)) timeout when outside context does not cancel at the last retry.

Maybe it should be waiting before the next retry, rather than waiting after the retry

**Comment by vadmeste** [comment]
@magictour not correct. Try the following code:
```
package main

import (
        "context"
        "fmt"
        "time"
)

func main() {
        ctx, cancel := context.WithCancel(context.Background())

        cancel()

        select {
        case <-time.After(100 * time.Hour):
        case <-ctx.Done():
        }

        select {
        case <-time.After(100 * time.Hour):
        case <-ctx.Done():
        }

        fmt.Println("Finished")

}
```

It will quit immediately after printing "Finished"

**Comment by harshavardhana** [comment]
> @magictour not correct. Try the following code:
> 
> ```
> package main
> 
> import (
>         "context"
>         "fmt"
>         "time"
> )
> 
> func main() {
>         ctx, cancel := context.WithCancel(context.Background())
> 
>         cancel()
> 
>         select {
>         case <-time.After(100 * time.Hour):
>         case <-ctx.Done():
>         }
> 
>         select {
>         case <-time.After(100 * time.Hour):
>         case <-ctx.Done():
>         }
> 
>         fmt.Println("Finished")
> 
> }
> ```
> 
> It will quit immediately after printing "Finished"

I think @magictour your understanding is not correct, can you explain what issue you are talking about?

**Comment by magictour** [comment]
This happened when outside context does not call the cancel() function immediately.

The code can be found in the file api.go -> executeMethod

```

	// Create cancel context to control 'newRetryTimer' go routine.
	retryCtx, cancel := context.WithCancel(ctx)

	// Indicate to our routine to exit cleanly upon return.
	defer cancel()

	// Blank indentifier is kept here on purpose since 'range' without
	// blank identifiers is only supported since go1.4
	// https://golang.org/doc/go1.4#forrange.
	for range c.newRetryTimer(retryCtx, reqRetry, DefaultRetryUnit, DefaultRetryCap, MaxJitter) {
                // ignore some code

		// Verify if error response code is retryable.
		if isS3CodeRetryable(errResponse.Code) {
			continue // Retry.
		}

		// Verify if http status code is retryable.
		if isHTTPStatusRetryable(res.StatusCode) {
			continue // Retry.
		}

		// For all other cases break out of the retry loop.
		break
	}
```
when should be retry, the function cancel() can not be called, the for loop will block.

@vadmeste @harshavardhana

**Comment by harshavardhana** [comment]
> This happened when outside context does not call the cancel() function immediately.
> 
> The code can be found in the file api.go -> executeMethod
> 
> ```
> 
> 	// Create cancel context to control 'newRetryTimer' go routine.
> 	retryCtx, cancel := context.WithCancel(ctx)
> 
> 	// Indicate to our routine to exit cleanly upon return.
> 	defer cancel()
> 
> 	// Blank indentifier is kept here on purpose since 'range' without
> 	// blank identifiers is only supported since go1.4
> 	// https://golang.org/doc/go1.4#forrange.
> 	for range c.newRetryTimer(retryCtx, reqRetry, DefaultRetryUnit, DefaultRetryCap, MaxJitter) {
>                 // ignore some code
> 
> 		// Verify if error response code is retryable.
> 		if isS3CodeRetryable(errResponse.Code) {
> 			continue // Retry.
> 		}
> 
> 		// Verify if http status code is retryable.
> 		if isHTTPStatusRetryable(res.StatusCode) {
> 			continue // Retry.
> 		}
> 
> 		// For all other cases break out of the retry loop.
> 		break
> 	}
> ```
> when should be retry, the function cancel() can not be called, the for loop will block.
> 
> @vadmeste @harshavardhana 

The context is passed by caller too, once that is canceled the request is canceled.

Let's avoid anecdotal observations use it in a code and show us a reproducer.

**Comment by harshavardhana** [comment]
I just tested by printing and using with `mc` by making simple changes

```
mc mirror --json -a /usr/sbin play/testbucket >/dev/null
minio-go: Context done: timer
minio-go: Context done: timer
^Cminio-go: Context done: first
minio-go: Context done: timer
minio-go: Context done: first
minio-go: Context done: first
minio-go: Context done: first
minio-go: Context done: first
minio-go: Context done: first
minio-go: Context done: timer
```

```diff
 git diff
diff --git a/retry.go b/retry.go
index 6e2826f..b7f7e2a 100644
--- a/retry.go
+++ b/retry.go
@@ -19,7 +19,9 @@ package minio
 
 import (
        "context"
+       "fmt"
        "net/http"
+       "os"
        "time"
 )
 
@@ -71,15 +73,17 @@ func (c Client) newRetryTimer(ctx context.Context, maxRetry int, unit time.Durat
                defer close(attemptCh)
                for i := 0; i < maxRetry; i++ {
                        select {
-                       case attemptCh <- i + 1:
                        case <-ctx.Done():
+                               fmt.Fprint(os.Stderr, "minio-go: Context done: first\n")
                                return
+                       case attemptCh <- i + 1:
                        }
 
                        select {
-                       case <-time.After(exponentialBackoffWait(i)):
                        case <-ctx.Done():
+                               fmt.Fprint(os.Stderr, "minio-go: Context done: timer\n")
                                return
+                       case <-time.After(exponentialBackoffWait(i)):
                        }
                }
        }()
```

**Comment by magictour** [comment]
```
package main

import (
        "context"
        "fmt"
        "time"
)

func main() {
        ctx, cancel := context.WithCancel(context.Background())

        defer cancel()

        attemptCh := make(chan int)
        go func() {
            defer close(attemptCh)
            select {
            case attemptCh <- 1:
            case <-ctx.Done():
            }

            select {
            case <-time.After(100 * time.Hour):
            case <-ctx.Done():
            }
        }()

        for range attemptCh {

        }

        fmt.Printf("Finished with err: %v\n", ctx.Err())
}
```

> > This happened when outside context does not call the cancel() function immediately.
> > The code can be found in the file api.go -> executeMethod
> > ```
> > 
> > 	// Create cancel context to control 'newRetryTimer' go routine.
> > 	retryCtx, cancel := context.WithCancel(ctx)
> > 
> > 	// Indicate to our routine to exit cleanly upon return.
> > 	defer cancel()
> > 
> > 	// Blank indentifier is kept here on purpose since 'range' without
> > 	// blank identifiers is only supported since go1.4
> > 	// https://golang.org/doc/go1.4#forrange.
> > 	for range c.newRetryTimer(retryCtx, reqRetry, DefaultRetryUnit, DefaultRetryCap, MaxJitter) {
> >                 // ignore some code
> > 
> > 		// Verify if error response code is retryable.
> > 		if isS3CodeRetryable(errResponse.Code) {
> > 			continue // Retry.
> > 		}
> > 
> > 		// Verify if http status code is retryable.
> > 		if isHTTPStatusRetryable(res.StatusCode) {
> > 			continue // Retry.
> > 		}
> > 
> > 		// For all other cases break out of the retry loop.
> > 		break
> > 	}
> > ```
> > 
> > 
> > when should be retry, the function cancel() can not be called, the for loop will block.
> > @vadmeste @harshavardhana
> 
> The context is passed by caller too, once that is canceled the request is canceled.
> 
> Let's avoid anecdotal observations use it in a code and show us a reproducer.

The function executeMethod work like this, it will be blocked until 100 hours:


```
package main

import (
        "context"
        "fmt"
        "time"
)

func main() {
        ctx, cancel := context.WithCancel(context.Background())

        defer cancel()

        attemptCh := make(chan int)
        go func() {
            defer close(attemptCh)
            select {
            case attemptCh <- 1:
            case <-ctx.Done():
            }

            select {
            case <-time.After(100 * time.Hour):
            case <-ctx.Done():
            }
        }()

        for range attemptCh {

        }

        fmt.Printf("Finished with err: %v\n", ctx.Err())
}

```

**Comment by harshavardhana** [comment]
I already showed you it won't @magictour
