### ISSUE TITLE
Re-add `start-after` parameter to the SDK

### ISSUE THREAD

**Issue by jtlisi** [minio/minio-go#1396]
I noticed the `start-after` parameter was exposed in both the Javascript and Python SDKs. I also noticed it was added to this SDK in PR #990. However, it was removed a few months ago in PR #1332.

The `start-after` feature is very useful and can make LIST operations much less expensive on both the client and server side from a CPU and network perspective. Would a PR to re-add `start-after` to this SDK be accepted?

**Comment by harshavardhana** [comment]
start-after is similar to marker are you expecting something else?

**Comment by harshavardhana** [comment]
Added in #1509
