### ISSUE TITLE
type *minio.Client has no field or method SetCustomTransport

### ISSUE THREAD

**Issue by geordee** [minio/minio-go#1399]
When I try to use minio-go SDK, with custom transport I get the following error.

`minioClient.SetCustomTransport undefined (type *minio.Client has no field or method SetCustomTransport)`

I am trying to follow the instructions from issue #1000 

```go
if Config.AllowInsecure {
  minioClient.SetCustomTransport(&http.Transport{
    MaxIdleConns:    10,
    IdleConnTimeout: 30 * time.Second,
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
  })
}
```

**Comment by harshavardhana** [comment]
Just set it as part of `opts.Transport` @geordee - doc is out of date.

**Comment by Zalberth** [comment]
> Just set it as part of `opts.Transport` @geordee - doc is out of date.

Indeed
