### ISSUE TITLE
Instructions in the README.md do not mention about using GO111MODULE=on for build/run

### ISSUE THREAD

**Issue by ticpu** [minio/minio-go#1402]
Following the instructions from the main page of the project do not work and result in errors during build.

The instructions state: 
1. This document assumes that you have a working Go development environment.
2. Download using `GO111MODULE=on go get github.com/minio/minio-go/v7`
3. Run using `go run file-uploader.go`

I can confirm that my build environment is working for other projects.

This is using the version shipped with the latest version of Ubuntu Focal.
`go version go1.13.8 linux/amd64`

Using either go build or go run result in the same output.
```
$ go build file-uploader.go
file-uploader.go:7:2: cannot find package "github.com/minio/minio-go/v7" in any of:
        /usr/lib/go-1.13/src/github.com/minio/minio-go/v7 (from $GOROOT)
        /home/jerome/go/src/github.com/minio/minio-go/v7 (from $GOPATH)
file-uploader.go:8:2: cannot find package "github.com/minio/minio-go/v7/pkg/credentials" in any of:
        /usr/lib/go-1.13/src/github.com/minio/minio-go/v7/pkg/credentials (from $GOROOT)
        /home/jerome/go/src/github.com/minio/minio-go/v7/pkg/credentials (from $GOPATH)
```

However, if I `export GO111MODULE=on` before building or running, everything is fine.  The documentation only mentions that it should be used during the `go get`.

**Comment by harshavardhana** [comment]
Fixed in fe1f3855b146c1b6ce4199740d317e44cf9e85c2
