### ISSUE TITLE
No error raised on un-successful connection

### ISSUE THREAD

**Issue by Sonipn** [minio/minio-go#1403]
Hello,
I'm reaching you today as I have a question about connection establishment using minio-go. My thought would be that `New()` return an error when the endpoint is invalid and/or the credentials are? 
Instead, you'll get an error on later calls.

I would like to check if the connection is successful when launching my service, without having to call heavy methods that won't be used at this point. Like the `Ping()` method with the `sql`go module. I know about the existence of the the `/minio/health/live` endpoint, I believe a method in the SDK would be a great addition if not checking for it when initializing the minio client.

**Comment by klauspost** [comment]
The `minio-go` package is for S3 and cannot use any minio specific endpoints.

In most cases it would also just add an additional roundtrip with little additional info than doing the actual call.

I guess you can just do a `HeadBucket` or `ListBuckets` call if you need the information on startup.

**Comment by Sonipn** [comment]
Indeed, didn't thought about the fact that minio sdk wasn't used only for minio S3 servers, closing, thank you.
