### ISSUE TITLE
AWS list API returns invalid XML character which fail parsing XML response

### ISSUE THREAD

**Issue by mohsha-msft** [minio/minio-go#1408]
Please checkout  https://forums.aws.amazon.com/thread.jspa?threadID=46125 and
https://github.com/Azure/azure-storage-azcopy/issues/1197#issuecomment-716862690 for more context

**Comment by harshavardhana** [comment]
This is because AWS S3 doesn't return XML 1.1 instead only XML 1.0 and unfortunately doesn't support crazy characters.
