### ISSUE TITLE
Invalid s3 URL Encoding type decoding for GCS

### ISSUE THREAD

**Issue by mweibel** [minio/minio-go#1410]
I'm using minio to access a GCS bucket via S3 API (HMAC Key) using `mc`.
Directories/Files with whitespace in it return using `+` instead. 

List objects response:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
   <Name>test</Name>
   <Prefix>Lib/</Prefix>
   <Marker />
   <Delimiter>/</Delimiter>
   <IsTruncated>false</IsTruncated>
   <Encoding-Type>url</Encoding-Type>
   <Contents>
      <Key>Foo/</Key>
      <Generation>1605513310623194</Generation>
      <MetaGeneration>1</MetaGeneration>
      <LastModified>2020-11-16T07:55:10.623Z</LastModified>
      <ETag>"d41d8cd98f00b204e9800998ecf8427e"</ETag>
      <Size>0</Size>
   </Contents>
   <CommonPrefixes>
      <Prefix>Foo/Foo+Bar+Baz/</Prefix>
   </CommonPrefixes>
   <CommonPrefixes>
      <Prefix>Foo/bla/</Prefix>
   </CommonPrefixes>
</ListBucketResult>
```

[`ListBucketResult` struct](https://github.com/minio/minio-go/blob/master/api-s3-datatypes.go#L199) encodes `EncodingType` without a dash, therefore not being able to decode it. This results in `mc` returning invalid filenames for those with special characters (like whitespace).

Comparing this to [the ListObjects API docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html) seems like this is an error in the GCS implementation of the S3 API. However I guess it's easier to change within minio than somehow reporting a bug report with Google.
GCS API docs however don't even mention `Encoding-Type`: https://cloud.google.com/storage/docs/xml-api/get-bucket-list

How to solve? I'm not sure. 
Requests to the API are being done using encoding-type `url` always. Given that APIs should usually work the same, I believe calls to `decodeS3Name` could be done using `url` always, without depending on the response. 
https://github.com/minio/minio-go/blob/master/api-list.go#L567-L609

**Comment by harshavardhana** [comment]
> [`ListBucketResult` struct](https://github.com/minio/minio-go/blob/master/api-s3-datatypes.go#L199) encodes `EncodingType` without a dash, therefore not being able to decode it. This results in `mc` returning invalid filenames for those with special characters (like whitespace).

This is really GCS incompatibility issue with AWS S3 we cannot use multiple different names in this manner to cater for broken compatibility.

**Comment by harshavardhana** [comment]
> Requests to the API are being done using encoding-type `url` always. Given that APIs should usually work the same, I believe calls to `decodeS3Name` could be done using `url` always, without depending on the response.

The reason we do that because some implementations do not honor `encoding-type` query param, so we cannot assume either. We have to behave according to S3 implementation where encoding-type=url  is set returns it in XML as expected.

**Comment by mweibel** [comment]
Thanks for the response. I created an issue on Google's issue tracker for this: https://issuetracker.google.com/issues/180199987

> The reason we do that because some implementations do not honor encoding-type query param, so we cannot assume either.

In my opinion my proposed implementation change would still allow for this behavior and therefore would allow for both types of incompatibilities to work. As you've got one kind of fix for an incompatibility in there already, why isn't another for GCS not possible?

https://github.com/helio/minio-go/commit/08645c095419103190f7f8e0e312880364428253

**Comment by harshavardhana** [comment]
> In my opinion my proposed implementation change would still allow for this behavior and therefore would allow for both types of incompatibilities to work. As you've got one kind of fix for an incompatibility in there already, why isn't another for GCS not possible?

Unfortunately no @mweibel this is a hack

```go
	encodingType := listMultipartUploadsResult.EncodingType
	if encodingType == "" {
		encodingType = "url"
	}
```

It will fail in unknown ways, that we assume URL encoding and decode valid content that is 
uploaded with `%` in their names. We cannot unfortunately take such risk as this library is heavily
used and dependent in many projects.

Correct fix is server side.
