### ISSUE TITLE
Add support for "starts-with" post policy content type

### ISSUE THREAD

**Issue by MichaelHudgins** [minio/minio-go#1420]
The post policy generation currently allows for only exact match of content types.  It would be helpful if, like key, a "starts-with" could be specified instead of an exact match. 

A typical use case for this would be a policy that allows all images, or all videos to be uploaded.  As seen in the aws post policy api page:

https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html#sigv4-ConditionMatching 

To achieve this, i purpose one of the following: 

- Add a SetContentTypeStartsWith method on PostPolicy
- Add a flag to indicate to use starts with to the existing method SetCondition
- Add the ability to add a policyCondition directly 

I wouldn't mind doing the work to make this happen, would just want to know if this functionality is valuable enough to add.  It seems as if the first option is most in line with the current code base.

**Comment by harshavardhana** [comment]
Good idea feel free to send a PR @MichaelHudgins

**Comment by harshavardhana** [comment]
Fixed by #1421
