### ISSUE TITLE
go get is failing 

### ISSUE THREAD

**Issue by rihazmihar** [minio/minio-go#1424]
I am able to see the series of error message while building it in my application. I tried 'go get' command at the command prompt. seeing same error. any suggestion. even the Makefile is giving same error while compilation.

$ go get github.com/minio/md5-simd
go: downloading github.com/minio/md5-simd v1.1.1
go: github.com/minio/md5-simd upgrade => v1.1.1
go: downloading github.com/klauspost/cpuid v1.2.3
# github.com/minio/md5-simd
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s: Assembler messages:
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:61: Error: no such instruction: `text ·block16(SB),4,$0-40'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:63: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:63: Error: too many memory references for `movq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:64: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:64: Error: too many memory references for `movq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:65: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:65: Error: too many memory references for `movq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:66: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:66: Error: too many memory references for `kmovq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:67: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:67: Error: too many memory references for `movq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:68: Error: junk `(SB)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:68: Error: too many memory references for `movq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:100: Error: too many memory references for `vmovupd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:101: Error: junk `(BX)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:101: Error: too many memory references for `vmovupd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:102: Error: junk `(BX)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:102: Error: too many memory references for `vmovupd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:103: Error: junk `(BX)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:103: Error: too many memory references for `vmovupd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:106: Error: junk `(AX)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:106: Error: too many memory references for `vmovupd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:109: Error: too many memory references for `vpbroadcastq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:112: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:113: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:114: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:115: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:117: Error: too many memory references for `kmovq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:118: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:119: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:121: Error: too many memory references for `vxorps'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:122: Error: too many memory references for `vmovapd'
go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:123: Error: too many memory references for `vxorps'

**Comment by harshavardhana** [comment]
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s: Assembler messages:
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:61: Error: no such instruction: `text ·block16(SB),4,$0-40' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:63: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:63: Error: too many memory references for `movq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:64: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:64: Error: too many memory references for `movq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:65: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:65: Error: too many memory references for `movq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:66: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:66: Error: too many memory references for `kmovq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:67: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:67: Error: too many memory references for `movq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:68: Error: junk `(SB)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:68: Error: too many memory references for `movq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:100: Error: too many memory references for `vmovupd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:101: Error: junk `(BX)' after expression go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:101: Error: too many memory references for `vmovupd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:102: Error: junk `(BX)' after expression go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:102: Error: too many memory references for `vmovupd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:103: Error: junk `(BX)' after expression go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:103: Error: too many memory references for `vmovupd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:106: Error: junk `(AX)' after expression go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:106: Error: too many memory references for `vmovupd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:109: Error: too many memory references for `vpbroadcastq' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:112: Error: too many memory references for `vmovapd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:113: Error: too many memory references for `vmovapd' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:114: Error: too many memory references for `vmovapd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:115: Error: too many memory references for `vmovapd' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:117: Error: too many memory references for `kmovq'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:118: Error: too many memory references for `vmovapd' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:119: Error: too many memory references for `vmovapd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:121: Error: too many memory references for `vxorps' go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:122: Error: too many memory references for `vmovapd'
> go/pkg/mod/github.com/minio/md5-simd@v1.1.1/block16_amd64.s:123: Error: too many memory references for `vxorps'

You need to use go1.14 or newer

**Comment by rihazmihar** [comment]
go version
go version go1.14.6 gccgo (Ubuntu 10.2.0-13ubuntu1) 10.2.0 linux/amd64

**Comment by rihazmihar** [comment]
I using above version. Please suggested what could be the reason for this behavior. 

go get github.com/minio/minio-go/v7
go: github.com/minio/minio-go/v7 upgrade => v7.0.6
# github.com/minio/md5-simd
go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s: Assembler messages:
go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:61: Error: no such instruction: `text ·block16(SB),4,$0-40'
go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:63: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:63: Error: too many memory references for `movq'
go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:64: Error: junk `(FP)' after expression
go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:64: Error: too many memory references for `movq'

**Comment by harshavardhana** [comment]
> I am using above version of go lang. Please suggest what could be the reason for this behavior.
> 
> go get github.com/minio/minio-go/v7
> go: github.com/minio/minio-go/v7 upgrade => v7.0.6
> 
> # github.com/minio/md5-simd
> go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s: Assembler messages:
> go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:61: Error: no such instruction: `text ·block16(SB),4,$0-40' go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:63: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:63: Error: too many memory references for `movq' go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:64: Error: junk `(FP)' after expression
> go/pkg/mod/github.com/minio/md5-simd@v1.1.0/block16_amd64.s:64: Error: too many memory references for `movq'

> go version go1.14.6 gccgo (Ubuntu 10.2.0-13ubuntu1) 10.2.0 linux/amd64

This is not the correct Go version use the ones from `golang.org/dl` not gccgo.

**Comment by rihazmihar** [comment]
Thank you. I had installed the golang, but later Installed gcc compiler, hence it had overwritten the path details in PATH variable it seems. I updated the PATH env variable, it ispicking the right go version which solved the issue.

**Comment by klauspost** [comment]
@rihazmihar 

Dont use gccgo it will effectively disable use of all assembly optimized functions.
