### ISSUE TITLE
put object encrypt got error need provided keys must be made over a secure connection

### ISSUE THREAD

**Issue by daddycarbone** [minio/minio-go#1425]
my minio client was set secure connection "true" and i follow the example on this repo for put object encrypt, but got error 
```
Requests specifying Server Side Encryption with Customer provided keys must be made over a secure connection.
```

here is the code i implement:

```

	password := "test this"

	encryption := encrypt.DefaultPBKDF([]byte(password), []byte(bucketName+input.Filename))
	_, errUpload := minioClient.PutObject(
		context.Background(),
		bucketName, pwd,
		input.File, input.Size,
		minio.PutObjectOptions{
			ServerSideEncryption: 	 encryption,
			ContentType:             input.ContentType,
		},
	)
	if errUpload != nil {
		return errUpload
	}
```

to set policy:

```
		policy := fmt.Sprintf(
			`
			{
				"Version":"2012-10-17",
				"Statement":[
					{
						"Effect":"Allow",
						"Principal":{
							"AWS":["*"]
						},
						"Action":["s3:GetBucketLocation","s3:ListBucket"],
						"Resource":["arn:aws:s3:::%s"]
					},
					{
						"Effect":"Allow","Principal":{"AWS":["*"]},
						"Action":["s3:GetObject"],
						"Resource":["arn:aws:s3:::%s/*"]
					}
				]
			}
			`,
			bucketsName, bucketsName)
```
do i miss something for this?? 

and is put object encryption only for s3 ? because my minio was self host

**Comment by harshavardhana** [comment]
SSE-C requires TLS - this is AWS S3 spec.

**Comment by daddycarbone** [comment]
is that mean if self-host, I cant do encrypt put object? I have followed the examples on here though @harshavardhana

**Comment by harshavardhana** [comment]
> is that mean if self-host, I cant do encrypt put object? I have followed the examples on here though @harshavardhana

self host still requires TLS configured

**Comment by kannappanr** [comment]
@daddycarbone You need to generate the certs. Please take a look at https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html

**Comment by daddycarbone** [comment]
hey @harshavardhana @kannappanr thx for your info :)
