### ISSUE TITLE
minio-go v7: cpuid.CPU.AVX512F undefined (type cpuid.CPUInfo has no field or method AVX512F) when using virtual machine.

### ISSUE THREAD

**Issue by Racle** [minio/minio-go#1426]
I posted issue on md5-simd GitHub also.
You can find issue and more detailed information here https://github.com/minio/md5-simd/issues/19

This happens with minio-go v7.

**Comment by harshavardhana** [comment]
Use go1.14 and above

**Comment by Racle** [comment]
> Use go1.14 and above

I'm using go 1.15.6 on my virtual machine.

Docker image which was on example used 1.15.6 also.

This is broken on V7 and it doesn't even run on latest go. 
This will break many docker containers in the future..

**Comment by harshavardhana** [comment]
@Racle just set GO111MODULE=on

**Comment by Racle** [comment]
> 
> 
> @Racle just set GO111MODULE=on

That doesn't fix the issue. Any other ideas?

I still get this with my local VM and with docker (example in [minio-example.zip](https://github.com/minio/md5-simd/files/5660044/minio-example.zip), I just added `ENV GO11MODULE=on` to that)

![image](https://user-images.githubusercontent.com/759091/101515433-03ad7680-3987-11eb-82e4-f848f805daf0.png)

**Comment by harshavardhana** [comment]
You `GO111MODULE=on` - incorrect env passed - we even say this here 

https://github.com/minio/minio-go#download-from-github

> GO111MODULE=on go get github.com/minio/minio-go/v7

**Comment by Racle** [comment]
> 
> 
> You `GO111MODULE=on` - incorrect env passed - we even say this here
> 
> https://github.com/minio/minio-go#download-from-github
> 
> > GO111MODULE=on go get github.com/minio/minio-go/v7

I thought that was just a typo, because with that I get this:

```go
GO111MODULE=on go get                                                                                                                                                                                                                                                               
go: cannot find main module; see 'go help modules'
```

**Comment by harshavardhana** [comment]
> ```go
> GO111MODULE=on go get                                                                                                                                                                                                                                                               
> go: cannot find main module; see 'go help modules'
> ```

Yes because your code is not using `go.mod` yet first do `go mod init` - Start reading about how to use `go modules` here https://github.com/golang/go/wiki/Modules

**Comment by Racle** [comment]
> 
> 
> > ```go
> > GO111MODULE=on go get                                                                                                                                                                                                                                                               
> > go: cannot find main module; see 'go help modules'
> > ```
> 
> Yes because your code is not using `go.mod` yet first do `go mod init` - Start reading about how to use `go modules` here https://github.com/golang/go/wiki/Modules

That explains it and fixes it.

That should also be on README.md as not everyone still uses go mod and this will break their stuff (as it happened with our code).

That said, it's good time to move to go mod.
