### ISSUE TITLE
memory leak -putObject with -1

### ISSUE THREAD

**Issue by pankajverma** [minio/minio-go#1440]
hi,

i have seen if we use putObject with -1(for streaming) it takes memory to perform the job which can be controlled by partsize, but after the object gets upload then the memory should be released which is not happening.

i can see my go-service which uses this API,  retain the memory, and only gets released after i restarted it. 
i have seen the other issue(https://github.com/minio/minio-go/issues/1176) and post related to the mem issue and understand the streaming will const the more mem. but it seems to me that it is not getting released.

go-minio-v7.0.6
minio:RELEASE.2020-11-19T23-48-16Z
snap of pprof output. 

![pprof](https://user-images.githubusercontent.com/389074/104028001-3056e700-51ee-11eb-94bd-652410f7d07d.png)

**Comment by klauspost** [comment]
Are you setting `PutObjectOptions.Progress`? Mainly asking so I know where to look.

**Comment by pankajverma** [comment]
no i have not set this. 
after seeing this mem issue i have only set the partSize to a lower value

**Comment by klauspost** [comment]
I don't see how a reference can be held after the function has returned.

How have you determined that it is leaked an not simply the runtime keeping the memory from the OS?

**Comment by pankajverma** [comment]
actually,i keep the service running for 30 mins and more to see if the mem utilization get dropped after the put object return but it doesn't

here is the pprof inuse_space snippet.

     File: objectStore
Type: inuse_space
Time: Jan 7, 2021 at 1:56pm (IST)
Duration: 25.35s, Total samples = 641.52MB 
Showing nodes accounting for -639.52MB, 99.69% of 641.52MB total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                            -640MB   100% |   github.com/minio/minio-go/v7.Client.putObjectCommon /home/user/go/pkg/mod/github.com/minio/minio-go/v7@v7.0.6/api-put-object.go:245
    -640MB 99.76% 99.76%     -640MB 99.76%                | github.com/minio/minio-go/v7.Client.putObjectMultipartStreamNoLength /home/user/go/pkg/mod/github.com/minio/minio-go/v7@v7.0.6/api-put-object.go:295
----------------------------------------------------------+-------------
                                           -0.52MB   100% |   regexp.(*Regexp).backtrack /usr/local/go/src/regexp/backtrack.go:319
   -0.52MB  0.08% 99.84%    -0.52MB  0.08%                | regexp.(*bitState).reset /usr/local/go/src/regexp/backtrack.go:91
----------------------------------------------------------+-------------
                                            0.50MB   100% |   google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams /home/user/go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/http2_server.go:493
    0.50MB 0.078% 99.77%     0.50MB 0.078%                | google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders /home/user/go/pkg/mod/google.golang.org/grpc@v1.32.0/internal/transport/http2_server.go:433
----------------------------------------------------------+-------------
                                            0.50MB   100% |   net/http.Header.Set /usr/local/go/src/net/http/header.go:37 (inline)
    0.50MB 0.078% 99.69%     0.50MB 0.078%                | net/textproto.MIMEHeader.Set /usr/local/go/src/net/textproto/header.go:22
----------------------------------------------------------+-------------

**Comment by pankajverma** [comment]
is there any other way you suggest to confirm if this is a mem leak?

**Comment by klauspost** [comment]
This profile shows that 640 megs was released?

**Comment by pankajverma** [comment]
thanks for your quick reply.
so the -640 means it released the mem?, {if so then I was reading it wrong :( }

**Comment by klauspost** [comment]
You can try doing 50 uploads sequentially. If memory keeps going up it is a leak.

**Comment by pankajverma** [comment]
yeah I tried that it goes up, also I tried concurrent 20 uploads then also it goes up and after that leaving it ideal for like an hr, just to see if the mem get released but it didn't.

**Comment by klauspost** [comment]
Concurrent will make it hard to see, since everything will be allocated at the same time. That is why you should try serially to see if memory keeps building up.

**Comment by pankajverma** [comment]
ok, I did 3 uploads(filesize=10MB,  partSize 4MB) one by one and yes mem% goes up.

**Comment by klauspost** [comment]
Make the part sizes big and make a lot of requests. This can be pretty much anything.

**Comment by pankajverma** [comment]
initially, i had tried with the default partsize(128mb) and serial upload.

I have attached a program that can simulate the problem.
[testputObj.go.zip](https://github.com/minio/minio-go/files/5796117/testputObj.go.zip)

**Comment by klauspost** [comment]
I simplified the code a bit and added come synchronization:

https://play.golang.org/p/jGxIrOFE97U

It works fine and there is no leaks. One observation is that moving `buf := make([]byte, 4*1024*1024)` outside the loop improves it. Waiting for the put to *actually* complete, not just for the write to finish helps.

You are providing a reader with no seek option, so it will have to buffer significant portions, but as you can see that can also be managed.

There is a problem with your code. Manage your resources carefully.
