### ISSUE TITLE
Unable to use gateway on GovCloud

### ISSUE THREAD

**Issue by tachang** [minio/minio-go#1446]
```
# ./minio gateway s3
ERROR Unable to initialize gateway backend: The provided token is malformed or otherwise invalid.
```

This message is probably due to the way `sts` URLs are on govcloud. I got the same message when doing `aws sts get-caller-identity` if I don't set the region to `us-gov-west-1`. So my guess is somewhere in the code the region needs to be set properly.

## Expected Behavior

The gateway mode starts and gets credentials from the IAM metadata on the EC2 instance.

## Current Behavior

```
# ./minio gateway s3
ERROR Unable to initialize gateway backend: The provided token is malformed or otherwise invalid.
```

## Possible Solution

Figure out where the STS endpoint is.

## Steps to Reproduce (for bugs)

1. Spin up a govcloud EC2 instance
2. Install minio
3. Run it with ./minio gateway s3

## Context
Unable to use on GovCloud

## Regression
No

**Comment by tachang** [comment]
Thanks. I'm having trouble finding the area of code where this happens.

**Comment by harshavardhana** [comment]
> Thanks. I'm having trouble finding the area of code where this happens.

its in `pkg/credentials/iam_aws.go`

**Comment by tachang** [comment]
Thanks. Found it over here: https://github.com/minio/minio-go/blob/master/pkg/credentials/iam_aws.go#L59

Looks like it is hardcoded unless AWS_WEB_IDENTITY_TOKEN_FILE is set. And then you can use AWS_REGION to override. Not sure what AWS_WEB_IDENTITY_TOKEN_FILE is (will have to research). I just set it to AWS_WEB_IDENTITY_TOKEN_FILE=1 and I was able to start it.

**Comment by tachang** [comment]
Still having an error though so not sure if that is actually the problem.

**Comment by vadmeste** [comment]
@tachang do you know what's the STS endpoint of GovCloud ?

**Comment by tachang** [comment]
Actually this is a setup error:
`./minio gateway s3 https://s3.us-gov-west-1.amazonaws.com`
works! Closing this issue.
