### ISSUE TITLE
UNSIGNED PUT

### ISSUE THREAD

**Issue by thatMacAdmin** [minio/minio-go#1454]
Hi All,

I am attempting to put a file object to my backend custom S3 instance. This instance does not allow unsigned PUTs. How do I make the client send over a X-Amz-Content-Sha256 header with the put?

**Comment by harshavardhana** [comment]
unsigned PUTs are allowed in AWS S3 when the connection is TLS - your backend should implement this appropriately.

**Comment by thatMacAdmin** [comment]
I will speak with my companies S3 Object team and mention this. However, any way to force it in the meantime?

**Comment by harshavardhana** [comment]
> I will speak with my companies S3 Object team and mention this. However, any way to force it in the meantime?

No sir @thatMacAdmin to be properly S3 compatible the backend server should simply comply with AWS S3 behavior.
