### ISSUE TITLE
Issues found by Svace static analyzer

### ISSUE THREAD

**Issue by vvdvortsova** [minio/minio-go#1457]
Hello
These are warnings found with the Svace.
In each case, using a variable res after comparison with nil, res may be nil. It may lead to panic.
https://github.com/minio/minio-go/blob/a57fec8037ec86c0f84116a7ccec82666b71dcd5/api-get-lifecycle.go#L69

```bash
// Request server for current bucket lifecycle.
func (c Client) getBucketLifecycle(bucketName string) (string, error) {
	// Get resources properly escaped and lined up before
	// using them in http request.
	urlValues := make(url.Values)
	urlValues.Set("lifecycle", "")
	// Execute GET on bucket to get lifecycle.
	resp, err := c.executeMethod(context.Background(), "GET", requestMetadata{
		bucketName:  bucketName,
		queryValues: urlValues,
	})
	defer closeResponse(resp)
	if err != nil {
		return "", err
	}
//null check
	if resp != nil {
		if resp.StatusCode != http.StatusOK {
			return "", httpRespToErrorResponse(resp, bucketName, "")
		}
	}
//After having been compared to NULL value at api-get-lifecycle.go:64, pointer '(github.com/minio/minio-go.Client).executeMethod(c, context.Background(), "GET", complit)' is dereferenced at api-get-lifecycle.go:70.
//[dereference] Dereference
	bucketLifecycleBuf, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	lifecycle := string(bucketLifecycleBuf)
	return lifecycle, err
}
```

https://github.com/minio/minio-go/blob/a57fec8037ec86c0f84116a7ccec82666b71dcd5/api-get-policy.go#L70
```bash
func (c Client) getBucketPolicy(bucketName string) (string, error) {
	// Get resources properly escaped and lined up before
	// using them in http request.
	urlValues := make(url.Values)
	urlValues.Set("policy", "")
	// Execute GET on bucket to list objects.
	resp, err := c.executeMethod(context.Background(), "GET", requestMetadata{
		bucketName:       bucketName,
		queryValues:      urlValues,
		contentSHA256Hex: emptySHA256Hex,
	})
	defer closeResponse(resp)
	if err != nil {
		return "", err
	}
//null check
	if resp != nil {
		if resp.StatusCode != http.StatusOK {
			return "", httpRespToErrorResponse(resp, bucketName, "")
		}
	}
//After having been compared to NULL value at api-get-policy.go:65, pointer '(github.com/minio/minio-go.Client).executeMethod(c, context.Background(), "GET", complit)' is dereferenced at api-get-policy.go:71.
//[dereference] Dereference
	bucketPolicyBuf, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}
	policy := string(bucketPolicyBuf)
	return policy, err
}
```
https://github.com/minio/minio-go/blob/a57fec8037ec86c0f84116a7ccec82666b71dcd5/api-list.go#L717
```bash
func (c Client) listMultipartUploadsQuery(bucketName, keyMarker, uploadIDMarker, prefix, delimiter string, maxUploads int) (ListMultipartUploadsResult, error) {
	// Get resources properly escaped and lined up before using them in http request.
	urlValues := make(url.Values)
	// Set uploads.
	urlValues.Set("uploads", "")
	// Set object key marker.
	if keyMarker != "" {
		urlValues.Set("key-marker", keyMarker)
	}
	// Set upload id marker.
	if uploadIDMarker != "" {
		urlValues.Set("upload-id-marker", uploadIDMarker)
	}
	// Set object prefix, prefix value to be set to empty is okay.
	urlValues.Set("prefix", prefix)
	// Set delimiter, delimiter value to be set to empty is okay.
	urlValues.Set("delimiter", delimiter)
	// maxUploads should be 1000 or less.
	if maxUploads == 0 || maxUploads > 1000 {
		maxUploads = 1000
	}
	// Set max-uploads.
	urlValues.Set("max-uploads", fmt.Sprintf("%d", maxUploads))
	// Execute GET on bucketName to list multipart uploads.
	resp, err := c.executeMethod(context.Background(), "GET", requestMetadata{
		bucketName:       bucketName,
		queryValues:      urlValues,
		contentSHA256Hex: emptySHA256Hex,
	})
	defer closeResponse(resp)
	if err != nil {
		return ListMultipartUploadsResult{}, err
	}
//null check
	if resp != nil {
		if resp.StatusCode != http.StatusOK {
			return ListMultipartUploadsResult{}, httpRespToErrorResponse(resp, bucketName, "")
		}
	}
	// Decode response body.
	listMultipartUploadsResult := ListMultipartUploadsResult{}
//After having been compared to NULL value at api-list.go:587, pointer '(github.com/minio/minio-go.Client).executeMethod(c, context.Background(), "GET", complit)' is dereferenced at api-list.go:594.
//[dereference] Dereference
	err = xmlDecoder(resp.Body, &listMultipartUploadsResult)
	if err != nil {
		return listMultipartUploadsResult, err
	}
	return listMultipartUploadsResult, nil
}
```

**Comment by harshavardhana** [comment]
> Hello
> These are warnings found with the Svace.
> In each case, using a variable res after comparison with nil, res may be nil. It may lead to panic.
> https://github.com/minio/minio-go/blob/a57fec8037ec86c0f84116a7ccec82666b71dcd5/api-get-lifecycle.go#L69
> 
> ```shell
> // Request server for current bucket lifecycle.
> func (c Client) getBucketLifecycle(bucketName string) (string, error) {
> 	// Get resources properly escaped and lined up before
> 	// using them in http request.
> 	urlValues := make(url.Values)
> 	urlValues.Set("lifecycle", "")
> 	// Execute GET on bucket to get lifecycle.
> 	resp, err := c.executeMethod(context.Background(), "GET", requestMetadata{
> 		bucketName:  bucketName,
> 		queryValues: urlValues,
> 	})
> 	defer closeResponse(resp)
> 	if err != nil {
> 		return "", err
> 	}
> //null check
> 	if resp != nil {
> 		if resp.StatusCode != http.StatusOK {
> 			return "", httpRespToErrorResponse(resp, bucketName, "")
> 		}
> 	}
> //After having been compared to NULL value at api-get-lifecycle.go:64, pointer '(github.com/minio/minio-go.Client).executeMethod(c, context.Background(), "GET", complit)' is dereferenced at api-get-lifecycle.go:70.
> //[dereference] Dereference
> 	bucketLifecycleBuf, err := ioutil.ReadAll(resp.Body)
> 	if err != nil {
> 		return "", err
> 	}
> 	lifecycle := string(bucketLifecycleBuf)
> 	return lifecycle, err
> }
> ```
> 
> https://github.com/minio/minio-go/blob/a57fec8037ec86c0f84116a7ccec82666b71dcd5/api-get-policy.go#L70
> 
> ```shell
> func (c Client) getBucketPolicy(bucketName string) (string, error) {
> 	// Get resources properly escaped and lined up before
> 	// using them in http request.
> 	urlValues := make(url.Values)
> 	urlValues.Set("policy", "")
> 	// Execute GET on bucket to list objects.
> 	resp, err := c.executeMethod(context.Background(), "GET", requestMetadata{
> 		bucketName:       bucketName,
> 		queryValues:      urlValues,
> 		contentSHA256Hex: emptySHA256Hex,
> 	})
> 	defer closeResponse(resp)
> 	if err != nil {
> 		return "", err
> 	}
> //null check
> 	if resp != nil {
> 		if resp.StatusCode != http.StatusOK {
> 			return "", httpRespToErrorResponse(resp, bucketName, "")
> 		}
> 	}
> //After having been compared to NULL value at api-get-policy.go:65, pointer '(github.com/minio/minio-go.Client).executeMethod(c, context.Background(), "GET", complit)' is dereferenced at api-get-policy.go:71.
> //[dereference] Dereference
> 	bucketPolicyBuf, err := ioutil.ReadAll(resp.Body)
> 	if err != nil {
> 		return "", err
> 	}
> 	policy := string(bucketPolicyBuf)
> 	return policy, err
> }
> ```
> 
> https://github.com/minio/minio-go/blob/a57fec8037ec86c0f84116a7ccec82666b71dcd5/api-list.go#L717
> 
> ```shell
> func (c Client) listMultipartUploadsQuery(bucketName, keyMarker, uploadIDMarker, prefix, delimiter string, maxUploads int) (ListMultipartUploadsResult, error) {
> 	// Get resources properly escaped and lined up before using them in http request.
> 	urlValues := make(url.Values)
> 	// Set uploads.
> 	urlValues.Set("uploads", "")
> 	// Set object key marker.
> 	if keyMarker != "" {
> 		urlValues.Set("key-marker", keyMarker)
> 	}
> 	// Set upload id marker.
> 	if uploadIDMarker != "" {
> 		urlValues.Set("upload-id-marker", uploadIDMarker)
> 	}
> 	// Set object prefix, prefix value to be set to empty is okay.
> 	urlValues.Set("prefix", prefix)
> 	// Set delimiter, delimiter value to be set to empty is okay.
> 	urlValues.Set("delimiter", delimiter)
> 	// maxUploads should be 1000 or less.
> 	if maxUploads == 0 || maxUploads > 1000 {
> 		maxUploads = 1000
> 	}
> 	// Set max-uploads.
> 	urlValues.Set("max-uploads", fmt.Sprintf("%d", maxUploads))
> 	// Execute GET on bucketName to list multipart uploads.
> 	resp, err := c.executeMethod(context.Background(), "GET", requestMetadata{
> 		bucketName:       bucketName,
> 		queryValues:      urlValues,
> 		contentSHA256Hex: emptySHA256Hex,
> 	})
> 	defer closeResponse(resp)
> 	if err != nil {
> 		return ListMultipartUploadsResult{}, err
> 	}
> //null check
> 	if resp != nil {
> 		if resp.StatusCode != http.StatusOK {
> 			return ListMultipartUploadsResult{}, httpRespToErrorResponse(resp, bucketName, "")
> 		}
> 	}
> 	// Decode response body.
> 	listMultipartUploadsResult := ListMultipartUploadsResult{}
> //After having been compared to NULL value at api-list.go:587, pointer '(github.com/minio/minio-go.Client).executeMethod(c, context.Background(), "GET", complit)' is dereferenced at api-list.go:594.
> //[dereference] Dereference
> 	err = xmlDecoder(resp.Body, &listMultipartUploadsResult)
> 	if err != nil {
> 		return listMultipartUploadsResult, err
> 	}
> 	return listMultipartUploadsResult, nil
> }
> ```

resp is never nil when err is not nil looks like a bogus check to me.
