### ISSUE TITLE
Access to the AWS request ID headers

### ISSUE THREAD

**Issue by bjg2** [minio/minio-go#1458]
We have a problem that AWS requests occasionally stall for us since last Thursday, and their support asked to provide request id headers of requests that stall (here are the headers in question https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-id-values/). Problem is, using FGetObject (and even GetObject for that matter) does not expose these headers, and we cannot find any interface that provides those info.

How can we provide AWS with these headers they need to be able to debug the issue?

**Comment by kannappanr** [comment]
@bjg2 You can use the tracing APIs to get that information

You can add this line

`s3Client.TraceOn(os.Stderr)` 

here https://github.com/minio/minio-go/blob/master/examples/s3/getobject.go#L48

this will print headers returned by AWS S3.
