### ISSUE TITLE
Have a problem using UserTags for an object

### ISSUE THREAD

**Issue by GinkT** [minio/minio-go#1462]
Hello, everyone! I'm building my test project with go minio sdk. In code below i'm trying to put an object with UserTags and then list all objects from my bucket. 

```
        n, err := minioClient.FPutObject(ctx, bucketName, objectName, filePath, minio.PutObjectOptions{
		UserTags: map[string]string{
			"tag": "sometag",
		},
	})
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("Successfully uploaded etag %s of size %d\n", n.ETag, n.Size)

	objectCh := minioClient.ListObjects(ctx, bucketName, minio.ListObjectsOptions{
		WithMetadata: true,
		Recursive:    true,
	})
	log.Println("Printing a list of objects:\n")
	for object := range objectCh {
		log.Printf("found object of size: %d, key: %s, \nuser tags: %d\nobject: %+v",
			object.Size, object.Key, object.UserTagCount, object)

		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
	}
```

And the output i'm getting: 
![image](https://user-images.githubusercontent.com/29507617/110596756-be206580-8190-11eb-8271-866711aed866.png)

So the question is, am i doing something wrong?

**Comment by harshavardhana** [comment]
> 	objectCh := minioClient.ListObjects(ctx, bucketName, minio.ListObjectsOptions{
> 		WithMetadata: true,
> 		Recursive:    true,
> 	})

ListObjects do not return UserTags @GinkT only UserMetadata and using this is a MinIO extension only. AWS S3 does not implement this API.

**Comment by GinkT** [comment]
> > objectCh := minioClient.ListObjects(ctx, bucketName, minio.ListObjectsOptions{
> > WithMetadata: true,
> > Recursive:    true,
> > })
> 
> ListObjects do not return UserTags @GinkT only UserMetadata and using this is a MinIO extension only. AWS S3 does not implement this API.

Thx!
