### ISSUE TITLE
Trying to get a correct url by PresignedGetObject

### ISSUE THREAD

**Issue by GinkT** [minio/minio-go#1464]
### Problem

I'm using PresignedGetObject in code below:
```
url, err := client.PresignedGetObject(ctx, bucketName, objectName, time.Hour * 24 * 7, nil)
	if err != nil {
		return "", errors.Wrap(err, "GenerateUrl")
	}

	return url.String(), nil
```

Generated url have a domain name of my docker container:
![image](https://user-images.githubusercontent.com/29507617/111452814-f04b3d80-8723-11eb-8e5d-e4deb7131de2.png)

The thing is i can't give a client this url. Where do i need to specify a public IP of my host machine to properly generate URL's for client get requests? I specified env variables MINIO_DOMAIN and MINIO_PUBLIC_IPS for my docker container with minio.

**Comment by harshavardhana** [comment]
> Generated url have a domain name of my docker container:

Have a new constructor with the right domain name @GinkT `minio.New(...mydomain, ...)`
