### ISSUE TITLE
SetBucketPolicy: Error not nil in case of http.StatusOK

### ISSUE THREAD

**Issue by muhlemmer** [minio/minio-go#1467]
I am using Minio V7 with an S3 _compatible_ storage from pcextreme.com. 

If I run this snippet:

````
policy := {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicReadGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::myBucket/*"
            ]
        }
    ]
}

if err := s3.SetBucketPolicy(ctx, myBucket, policy); err != nil {
    panic(err)
}
````
I get:

````
panic: 200 OK
````
The culprit seems to be:

https://github.com/minio/minio-go/blob/3e37d03ccc2b61ad87b4ab044b3111b21ccadad7/api-bucket-policy.go#L66-L68

As a work-around I do something like:

````
if err := s3.SetBucketPolicy(ctx, myBucket, policy); err != nil 
        var er minio.ErrorResponse
	if errors.As(err, &er) && er.StatusCode == http.StatusOK {
		return
	}
       panic(err)
}

````

I am aware this is probably a provider specific problem, returning another code as the "standard S3". However, StatusOK still means ok ;). Let me know your opinion and I can sent a pull request if desired.

**Comment by joewhite86** [comment]
This is already fixed on master: https://github.com/minio/minio-go/pull/1466
