### ISSUE TITLE
FGetObj hardcoded umask 

### ISSUE THREAD

**Issue by fdefilippo** [minio/minio-go#1468]
Hi, could you add an option to use the umask of the environment in which the application runs instead of using the hardcoded one ?

https://github.com/minio/minio-go/blob/92fe50d14294782d96402deb861d442992038109/api-get-object-file.go#L31
```
	// If exists, open in append mode. If not create it as a part file.
	filePart, err := os.OpenFile(filePartPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
```

thank you.

**Comment by klauspost** [comment]
Just use the regular [GetObject](https://docs.min.io/docs/golang-client-api-reference#GetObject) and write the file or chmod it afterwards.
