### ISSUE TITLE
Why is there an inconsistent length?

### ISSUE THREAD

**Issue by liuaiyuan** [minio/minio-go#1474]
```shell
Put "xxx": readfrom tcp xxx->xxxx: http: ContentLength=84481 with Body length 81409
```
fileSize: 84481

```go
resp, err := http.Get(addr)
if err != nil {
  log.Error(err.Error())
  return
}

defer resp.Body.Close()

fileByte, err := ioutil.ReadAll(resp.Body)
if err != nil {
  log.Error(err.Error())
  return
}

r := bytes.NewReader(fileByte)

client.PutObject(ctx, "app1", "1.jpg", r, r.Size(), minio.PutObjectOptions{})

```

**Comment by harshavardhana** [comment]
Not sure why but your reader is wrong here..  print your `len(fileByte)`

**Comment by liuaiyuan** [comment]
> 不知道为什么，但是您的读者在这里是错误的..打印您的 `len(fileByte)`

fileSize: 84481
len(fileByte): 84481
r.Size(): 84481

**Comment by liuaiyuan** [comment]
> Not sure why but your reader is wrong here.. print your `len(fileByte)`


fileSize: 84481
len(fileByte): 84481
r.Size(): 84481

**Comment by liuaiyuan** [comment]
> Not sure why but your reader is wrong here.. print your `len(fileByte)`

sorry!!!!

I know the problem, because I used `mimetype`, there will be no problem if I don't use it;

**Comment by klauspost** [comment]
@liuaiyuan Post all the code needed to reproduce. You are probably reading from it in some code that you omitted.

`client.PutObject(ctx, "app1", "1.jpg", bytes.NewReader(fileByte), len(filByte), minio.PutObjectOptions{})`

**Comment by liuaiyuan** [comment]
> @liuaiyuan发布所有需要复制的代码。您可能正在通过省略的一些代码从中读取信息。
> 
> `client.PutObject(ctx, "app1", "1.jpg", bytes.NewReader(fileByte), len(filByte), minio.PutObjectOptions{})`

yes !! Because i used `mimetype` thanks for reply

**Comment by liuaiyuan** [comment]
> @liuaiyuan Post all the code needed to reproduce. You are probably reading from it in some code that you omitted.
> 
> `client.PutObject(ctx, "app1", "1.jpg", bytes.NewReader(fileByte), len(filByte), minio.PutObjectOptions{})`

yes !! Because i used mimetype thanks for reply
