### ISSUE TITLE
Timeout everytime enable secure connection (https)

### ISSUE THREAD

**Issue by mikaeru** [minio/minio-go#1476]
Hey there!

I always get time out error every time try to upload something from an html form to my bucket. It says `Full Error Messages : Get "https://_an address_/_my bucket name_/?location=": dial tcp _an ip address_: i/o timeout{}`.

But, if i disable the secure option, it runs well. In case you want to know, I use IBM Cloud Storage

**Comment by harshavardhana** [comment]
> I always get time out error every time try to upload something from an html form to my bucket. It says `Full Error Messages : Get "https://_an address_/_my bucket name_/?location=": dial tcp _an ip address_: i/o timeout{}`.

You need to check it your backend supports TLS @mikaeru

**Comment by mikaeru** [comment]
Ahh, it's fixed now. I have no idea what's happening so there's no more error like that
