### ISSUE TITLE
WARN: 500 MB memory allocation not addressed in documentation for Client.PutObject

### ISSUE THREAD

**Issue by sdhoward** [minio/minio-go#1478]
https://pkg.go.dev/github.com/minio/minio-go/v7#Client.PutObject

```
- For size input as -1 PutObject does a multipart Put operation
  until input stream reaches EOF. Maximum object size that can
  be uploaded through this operation will be 5TiB.
```

Related to https://github.com/minio/minio-go/issues/1473, please clarify that if the size is not specified, it will be assumed to be 5TB, each chunk will be assumed to be 500 MB, and that >500 MB will be allocated per upload.

**Comment by creker** [comment]
The bigger problem I think is that buffers are not pooled.

**Comment by harshavardhana** [comment]
> The bigger problem I think is that buffers are not pooled.

You can't pool random buffers @creker you can control the buffer size using PartSize

**Comment by creker** [comment]
@harshavardhana you can, you did that in the previous version of the library. Then it was removed which was a mistake I think. PartSize helps but it's not enough. Not pooling buffers still causes unnecessary load on the GC.

**Comment by harshavardhana** [comment]
> @harshavardhana you can, you did that in the previous version of the library. Then it was removed which was a mistake I think. PartSize helps but it's not enough. Not pooling buffers still causes unnecessary load on the GC.

We cannot we did the pooling it was worse.  S3 API unfortunately makes it very hard for us to achieve an efficient streaming-based approach.

**Comment by sdhoward** [comment]
The comment in the code should be updated so that the doc warns the user about this default behavior. I'm really not asking for anything more complicated than that.

**Comment by harshavardhana** [comment]
> The comment in the code should be updated so that the doc warns the user about this default behavior. I'm really not asking for anything more complicated than that.

Feel free to send a PR to update the doc @sdhoward
