### ISSUE TITLE
Feature Idea: detect when files need to be reloaded

### ISSUE THREAD

**Issue by the-maldridge** [minio/minio-go#1487]
When using mechanisms such as the AWS Shared Credentials File it would be nice to detect that the file has changed and reload the credentials if necessary.  This would allow for the case where an external process such as Hashicorp Vault populates this file, or where a human using saml2iam cycles the credentials out from under a running application.

I could see this being done either by a watcher on the file, a timer to diff the file periodically, or a hook that an application could call from a signal handler to re-read credentials.

**Comment by harshavardhana** [comment]
This is an application requirement not for an SDK to be doing this @the-maldridge - we cannot hold resources on the system. We have helpers provided which you can write custom credential handlers - write your own logic there. 

But this is out of scope for us.

**Comment by the-maldridge** [comment]
Thanks, I'll notify the downstream application that this is considered a defect on their part due to lack of support in the SDK.
