### ISSUE TITLE
ListObject v1 api don't properly follow S3 api

### ISSUE THREAD

**Issue by alexises** [minio/minio-go#1492]
I'm stuck with an issue with 3rd party S3 implementation that follow the spec in a lazy mannier.

When I'm list a directory with more than 1000 file, multiples query should be made. XML return NextMarker as empty and IsTruncated as True.

According to S3 API ref, it's a valid biavior : https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html 

{code}
    When response is truncated (the IsTruncated element value in the response is true), you can use the key name in this field as marker in the subsequent request to get next set of objects. Amazon S3 lists objects in alphabetical order Note: This element is returned only if you have delimiter request parameter specified. If response does not include the NextMarker and it is truncated, you can use the value of the last Key in the response as the marker in the subsequent request to get the next set of object keys. 
{code}

But comportment on api-list.go is not following this behavior.

```
			// If next marker present, save it for next request.
			if result.NextMarker != "" {
				marker = result.NextMarker
			}

			// Listing ends result is not truncated, return right here.
			if !result.IsTruncated {
				return
			}
```

This cause infinite loop with only the first 1000 entry listed.

good co

**Comment by harshavardhana** [comment]
> I'm stuck with an issue with 3rd party S3 implementation that follow the spec in a lazy mannier.

The issue here is your 3rd party S3 implementation @alexises - we only use reset the marker - marker always has correct values you should the full code.

```
                        // If contents are available loop through and send over channel.
                        for _, object := range result.Contents {
                                // Save the marker.
                                marker = object.Key
                                select {
                                // Send object content.
                                case objectStatCh <- object:
                                // If receives done from the caller, return here.
                                case <-ctx.Done():
                                        return
                                }
                        }

                        // Send all common prefixes if any.
                        // NOTE: prefixes are only present if the request is delimited.
                        for _, obj := range result.CommonPrefixes {
                                select {
                                // Send object prefixes.
                                case objectStatCh <- ObjectInfo{Key: obj.Prefix}:
                                // If receives done from the caller, return here.
                                case <-ctx.Done():
                                        return
                                }
                        }

                        // If next marker present, save it for next request.
                        if result.NextMarker != "" {
                                marker = result.NextMarker
                        }

                        // Listing ends result is not truncated, return right here.
                        if !result.IsTruncated {
                                return
                        }
```

They must have incorrectly implemented the S3 API @alexises
