### ISSUE TITLE
Multipart Upload for REST APIs

### ISSUE THREAD

**Issue by joewhite86** [minio/minio-go#1500]
I want to provide a REST endpoint in my application, which is capable of handling multipart uploads, like S3 does already.

Since most of the functionality for this is private in the client itself I would currently need to copy over lots of code from the lib into my own.

I think it might be useful, to have public functions for this, like 
- newUploadID
- uploadPart
- completeMultipartUpload

Is there anything I miss or are there other ways to accomplish this?

**Comment by harshavardhana** [comment]
For that we have something called as core.go - although we don't change a lot of functions there we do not provide API compatibility for these functions between new releases.

Only API compatibility provided is for published functions.

**Comment by joewhite86** [comment]
Perfect, exactly what I need. Thanks
