### ISSUE TITLE
Use options to make request's headers for executeMethod? is support？ 

### ISSUE THREAD

**Issue by hbaiyu** [minio/minio-go#1511]

**Comment by harshavardhana** [comment]
Please explain clearly what are you asking for, closing this issue until then.

**Comment by hbaiyu** [comment]
does it support gzip contentencoding for multpart upload&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio-go] Use options to make request's headers for executeMethod? is support？  (#1511)





 
Please explain clearly what are you asking for, closing this issue until then.

**Comment by hbaiyu** [comment]
uploadPart function haven't options argument&nbsp;
how set request headers




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "minio/minio-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio-go] Use options to make request's headers for executeMethod? is support？  (#1511)





 
Please explain clearly what are you asking for, closing this issue until then.
