### ISSUE TITLE
 Get MD5 value of file ！！

### ISSUE THREAD

**Issue by QQGoblin** [minio/minio-go#1512]
I need to implement such a function: when uploading a file to Minio, if the MD5 value of the file is the same as that of a file in Minio, the upload process will be terminated immediately!

Whether Minio has related interface, let me realize this function quickly. For example, the interface to quickly find the file MD5.

**Comment by harshavardhana** [comment]
md5 is broken using that for file checksum is a bad idea use something like 

- highwayhash
- blake2b
