### ISSUE TITLE
How long will the incomplete object be deleted?

### ISSUE THREAD

**Issue by hbaiyu** [minio/minio-go#1517]

**Comment by vadmeste** [comment]
@hbaiyu incomplete multipart uploads will be automatically removed by MinIO server each 24 hours.

**Comment by hbaiyu** [comment]
Can I set a timeout?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio-go] How long will the incomplete object be deleted? (#1517)





 
@hbaiyu incomplete multipart uploads will be automatically removed by MinIO server each 24 hours.

**Comment by harshavardhana** [comment]
> Can I set a timeout?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minio/minio-go" ***@***.***&gt;; 发送时间:&nbsp;2021年7月19日(星期一) 下午5:35 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [minio/minio-go] How long will the incomplete object be deleted? (#1517) @hbaiyu incomplete multipart uploads will be automatically removed by MinIO server each 24 hours. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

No you cannot

**Comment by hbaiyu** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 晚上11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio-go] How long will the incomplete object be deleted? (#1517)





  
Can I set a timeout?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "minio/minio-go" @.&gt;; 发送时间:&nbsp;2021年7月19日(星期一) 下午5:35 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [minio/minio-go] How long will the incomplete object be deleted? (#1517) @hbaiyu incomplete multipart uploads will be automatically removed by MinIO server each 24 hours. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
No you cannot
