### ISSUE TITLE
Is there any way save ip camera's rtsp stream to minio?

### ISSUE THREAD

**Issue by neo502721** [minio/minio-go#1519]
Hi, I want save my ip camera's rtsp stream to minio. Is there any way? Thanks!

**Comment by harshavardhana** [comment]
@neo502721 this is outside the scope of this project. If you have a readable stream it work with PutObject()

**Comment by neo502721** [comment]
> @neo502721 this is outside the scope of this project. If you have a readable stream it work with PutObject()

Thank you very much. I will check it.
