### ISSUE TITLE
Minio memory consumption keeps increasing.

### ISSUE THREAD

**Issue by smanglapanw** [minio/minio-go#1523]
I am performing a write load test on minio.  Minio version:- minio/minio:RELEASE.2021-07-15T22-27-34Z

1) trying with file size of 400 KB file to be written in memory 
2) using the locust tool for load testing. 
3) Minio memory consumption keeps increasing even on very small rps e.g. 7 or 8
4) Ran the load test for 1 hour. 
memory usage of minio reached from 125 MB to 3.5 GB 
5) start with a fresh minio servers. minio servers configuration is 
number of servers:- 4
cpu:- 3 cores
memory :- 6 GB 
6) request is not getting failed .. but only issue is memory doesn't release even load test is stopped. 

I want to understand how the minio use the memory. Does it need a very huge memory size. 

from previous issues I found that 
```Note: MinIO allocates 10MiB per read and writes on a bufPool . This memory is reused so for example if you have 1000 concurrent connections you will see 10G memory usage.
MinIO erasure coding uses 10MiB buffer per stream so if you are uploaded 1000 concurrent streams it will use 1000 * 10 = 10GiB memory. Now, this memory is not given back to GC because MinIO reuses same 10GiB for the next 1000 concurrent operations. So if your concurrent operations increase the memory is always allocated and reused again and again.
you will always know that there is a top-level limit based on the client's concurrent requirement. If you can show that just uploading a single stream leaks memory then it makes sense, but without that I don't think what you are seeing is unusual.


```

But I am not seeing any of these behaviors .. 
Can someone help in understanding what should I expect in case of memory usage? Minio is critical component of my system, so much memory swallowing is something not acceptable.

**Comment by harshavardhana** [comment]
@smanglapanw 

> 5\. start with a fresh minio servers. minio servers configuration is
>     number of servers:- 4
>     cpu:- 3 cores
>     memory :- 6 GB

This is a toy setup - you can't expect to have a distributed system with such low memory. If you really want to keep memory under limits you should set something like MINIO_API_REQUESTS_MAX=3 (match this with your system cores).  Please provide an `mc admin profile` output etc for us to see where the memory usage is from.

> 4\. Ran the load test for 1 hour.
>     memory usage of minio reached from 125 MB to 3.5 GB

This is perfectly normal - MinIO is written in Go and Go is a garbage collected language and relinquishes resources to the system as and when needed. This is not proof of anything that is unusual. 

You will have to provide more analysis and further details - closing this issue until then.
