### ISSUE TITLE
Support user provided Content-MD5

### ISSUE THREAD

**Issue by AtomicNibble** [minio/minio-go#1524]
Hello,

I already have a MD5 of object I want to upload using minio.
But it looks like minio only supports creating the MD5 itself which is a waste of CPU cycles in my case.

I thought maybe I could set it via `PutObjectOptions.UserMetadata` but `Content-MD5` is not supported in `isStandardHeader` so it will end up as `x-amz-meta-Content-MD5` which is of no use.

Would it be possible to add `Content-MD5` to `isStandardHeader` to support such a use case?

Or maybe it's possible another way?

Thanks,
Tom.

**Comment by klauspost** [comment]
@AtomicNibble It will not work for multipart uploads, so it would not work without further modifications.

You can provide a [custom md5 function](https://github.com/minio/minio-go/blob/b39adc06d635f44bca6245e6a43e340c97e8cc37/api.go#L104) that can check for known payloads, though it isn't trivial.

**Comment by lifa1225** [comment]
> Hello,
> 
> I already have a MD5 of object I want to upload using minio.
> But it looks like minio only supports creating the MD5 itself which is a waste of CPU cycles in my case.
> 
> I thought maybe I could set it via `PutObjectOptions.UserMetadata` but `Content-MD5` is not supported in `isStandardHeader` so it will end up as `x-amz-meta-Content-MD5` which is of no use.
> 
> Would it be possible to add `Content-MD5` to `isStandardHeader` to support such a use case?
> 
> Or maybe it's possible another way?
> 
> Thanks,
> Tom.

Hi,Tom.
I also need to get MD5.So when I upload the file,I will use "x-amz-meta-Content-MD5" filed.
I can see the "x-amz-meta-Content-MD5" filed in S3browser.
![image](https://user-images.githubusercontent.com/59470742/128119743-c82b1968-1301-4349-9200-9c0bfae76a73.png)

But in my program, the "ObjectInfo" returned does not contain the x-amz-meta-Content-MD5 field:
```
objectCh = minioClient.ListObjects(ctx, specifyBucket, minio.ListObjectsOptions{
			Prefix:       "", 
			Recursive:    true,
			WithMetadata: true,
		})
```
Is there any way to get x-AMz-meta-content-MD5?

**Comment by harshavardhana** [comment]
> I can see the "x-amz-meta-Content-MD5" filed in S3browser.

what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`

**Comment by lifa1225** [comment]
> > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> 
> what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`

Sorry,it's `x-amz-meta-s3cmd-attrs`.
Is there any way to get it?

**Comment by harshavardhana** [comment]
> > > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> > 
> > 
> > what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`
> 
> Sorry,it's `x-amz-meta-s3cmd-attrs`.
> Is there any way to get it?

Yes it's in objectInfo.Metadata https://github.com/minio/minio-go/blob/master/examples/s3/listobjectsV2WithMetadata.go

**Comment by lifa1225** [comment]
> > > > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> > > 
> > > 
> > > what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`
> > 
> > 
> > Sorry,it's `x-amz-meta-s3cmd-attrs`.
> > Is there any way to get it?
> 
> Yes it's in objectInfo.Metadata https://github.com/minio/minio-go/blob/master/examples/s3/listobjectsV2WithMetadata.go

I have used `WithMetadata: true`,but the returned ObjectInfo does not contain Metadata information

![image](https://user-images.githubusercontent.com/59470742/128122558-78335eac-ea32-444d-af93-19d98c13871e.png)

**Comment by harshavardhana** [comment]
> > > > > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> > > > 
> > > > 
> > > > what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`
> > > 
> > > 
> > > Sorry,it's `x-amz-meta-s3cmd-attrs`.
> > > Is there any way to get it?
> > 
> > 
> > Yes it's in objectInfo.Metadata https://github.com/minio/minio-go/blob/master/examples/s3/listobjectsV2WithMetadata.go
> 
> I have used `WithMetadata: true`,but the returned ObjectInfo does not contain Metadata information
> 
> ![image](https://user-images.githubusercontent.com/59470742/128122558-78335eac-ea32-444d-af93-19d98c13871e.png)

Is your backend server MinIO ?

**Comment by lifa1225** [comment]
> > > > > > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> > > > > 
> > > > > 
> > > > > what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`
> > > > 
> > > > 
> > > > Sorry,it's `x-amz-meta-s3cmd-attrs`.
> > > > Is there any way to get it?
> > > 
> > > 
> > > Yes it's in objectInfo.Metadata https://github.com/minio/minio-go/blob/master/examples/s3/listobjectsV2WithMetadata.go
> > 
> > 
> > I have used `WithMetadata: true`,but the returned ObjectInfo does not contain Metadata information
> > ![image](https://user-images.githubusercontent.com/59470742/128122558-78335eac-ea32-444d-af93-19d98c13871e.png)
> 
> Is your backend server MinIO ?

No,my backend server is ceph-radosgw.

**Comment by harshavardhana** [comment]
> > > > > > > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> > > > > > 
> > > > > > 
> > > > > > what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`
> > > > > 
> > > > > 
> > > > > Sorry,it's `x-amz-meta-s3cmd-attrs`.
> > > > > Is there any way to get it?
> > > > 
> > > > 
> > > > Yes it's in objectInfo.Metadata https://github.com/minio/minio-go/blob/master/examples/s3/listobjectsV2WithMetadata.go
> > > 
> > > 
> > > I have used `WithMetadata: true`,but the returned ObjectInfo does not contain Metadata information
> > > ![image](https://user-images.githubusercontent.com/59470742/128122558-78335eac-ea32-444d-af93-19d98c13871e.png)
> > 
> > 
> > Is your backend server MinIO ?
> 
> No,my backend server is ceph-radosgw.

UserMetadata in listing is MinIO specific API you can't use it with Ceph. You need to additionally perform HeadObject() to get the metadata.

**Comment by lifa1225** [comment]
> > > > > > > > I can see the "x-amz-meta-Content-MD5" filed in S3browser.
> > > > > > > 
> > > > > > > 
> > > > > > > what you are highlighting its `x-amz-meta-s3cmd-attrs` not `x-amz-meta-content-md5`
> > > > > > 
> > > > > > 
> > > > > > Sorry,it's `x-amz-meta-s3cmd-attrs`.
> > > > > > Is there any way to get it?
> > > > > 
> > > > > 
> > > > > Yes it's in objectInfo.Metadata https://github.com/minio/minio-go/blob/master/examples/s3/listobjectsV2WithMetadata.go
> > > > 
> > > > 
> > > > I have used `WithMetadata: true`,but the returned ObjectInfo does not contain Metadata information
> > > > ![image](https://user-images.githubusercontent.com/59470742/128122558-78335eac-ea32-444d-af93-19d98c13871e.png)
> > > 
> > > 
> > > Is your backend server MinIO ?
> > 
> > 
> > No,my backend server is ceph-radosgw.
> 
> UserMetadata in listing is MinIO specific API you can't use it with Ceph. You need to additionally perform HeadObject() to get the metadata.

10/5000 
thanks!
Is there a description of this function?

**Comment by harshavardhana** [comment]
You can look at https://pkg.go.dev/github.com/minio/minio-go/v7

**Comment by AtomicNibble** [comment]
> 
> 
> @AtomicNibble It will not work for multipart uploads, so it would not work without further modifications.
> 
> You can provide a [custom md5 function](https://github.com/minio/minio-go/blob/b39adc06d635f44bca6245e6a43e340c97e8cc37/api.go#L104) that can check for known payloads, though it isn't trivial.

All my uploads are below the multipart threshold so is not a issue for my use case.

I did see the custom md5Haser function but since there is no context a solution using this would be a bit of a hack imo. It would also not be very memory efficent as the object push code allocates a full buffer for hashing.

```go
		// Create a buffer.
		buf := make([]byte, size)

		length, rErr := readFull(reader, buf)
		if rErr != nil && rErr != io.ErrUnexpectedEOF && rErr != io.EOF {
			return UploadInfo{}, rErr
		}

               // Calculate md5sum.
		hash := c.md5Hasher()
		hash.Write(buf[:length])
		md5Base64 = base64.StdEncoding.EncodeToString(hash.Sum(nil))
		reader = bytes.NewReader(buf[:length])
		hash.Close()
```

I do think whitelisting `Content-MD5` in `isStandardHeader` only when `DisableMultipart` is set is a acceptable change since it's not a breaking change, I can make a PR with some tests if this is acceptable?

Tom.
