### ISSUE TITLE
Add support for saving markers from listing objects

### ISSUE THREAD

**Issue by AtomicNibble** [minio/minio-go#1525]
I want to be able list objects in a bucket with a limit of say 1000 and be able to save the marker and continue later.

A typically use case would be listing objects with pagination.
I see this logic is inside `listObjectsQuery` but this function is not public.

Can we add support for markers to the public interface, so a application can save and pass them?

Thanks,
Tom.

**Comment by klauspost** [comment]
@AtomicNibble Just use the regular marker function to resume and pass the object to resume listing.
