### ISSUE TITLE
Question about PresignedPutObject API

### ISSUE THREAD

**Issue by ABNER-1** [minio/minio-go#1535]
Thanks for the prefect open source tools.

When I use minio SDK, I try to get a PresignedPutObject for others (not controlled by me) to put object into it.

I think I need some limits about the presigned url.
I found the header like 'x-amz-content-sha256' can do that. I can limit the user of the presigned put object url that they can only upload specific file. Of course, the object will not been shown before it has been already uploaded.

However, there are no chance in minio go sdk PresignedPutObject API for me to make it.
I think the feature may be very fantastic.

Thanks for any suggestions or answers.

**Comment by harshavardhana** [comment]
https://pkg.go.dev/github.com/minio/minio-go/v7?utm_source=godoc#Client.Presign use this to construct whatever you like.

**Comment by ABNER-1** [comment]
Thanks for your answer.
I tried this API.
However it can not add a header like 'x-amz-content-sha256'  and signature including this header.

**Comment by ABNER-1** [comment]
I found that there is a PR #1449  like my question. 
However it's open and can not make it because it doesn't add this feature to Presign API.

**Comment by harshavardhana** [comment]
> I found that there is a PR #1449 like my question.
> However it's open and can not make it because it doesn't add this feature to Presign API.

you can add the x-amz-content-sha256 as part of the url.Values{} query param.

**Comment by ABNER-1** [comment]
I tested and found that it just add a query kv into url. (Will this be inclued into signature?)

And I even can not use that url to put object. I am trying to solve this problem. 
But I think query param isn't the best choice.

**Comment by minio-trusted** [comment]
https://pkg.go.dev/github.com/minio/minio-go/v7#Client.PresignHeader - This the API that addresses x-amz-content-sha256 requirement.
