### ISSUE TITLE
ListObjects does not stop after hitting MaxKeys

### ISSUE THREAD

**Issue by WeirdMachine** [minio/minio-go#1536]
Hey there!
If i use the ListObject function like this: 
```
	listOptions := minio.ListObjectsOptions{
		MaxKeys:    5,
	}

	for report := range mc.ListObjects(context.Background(), "some-bucket", listOptions) {
		if report.Err != nil {
			log.Fatal(report.Err.Error())
		}
		println(report.Key)
	}
```

I would expect to only get 5 objects returned, but it will return all objects inside the bucket. 

Is this intended behavior?

**Comment by klauspost** [comment]
@WeirdMachine As the documentation states it is per request:

```
	// The maximum number of objects requested per
	// batch, advanced use-case not useful for most
	// applications
	MaxKeys int
```

You can cancel the provided context if you aren't interested in more results. If you want you can set `MaxKeys` slightly higher than the number your expect to read.

**Comment by WeirdMachine** [comment]
Thanks for the quick answer! I already use a context to do so.

**Comment by victory-wu** [comment]
If I use canelContext, then MaxKeys is meaningless, right？

**Comment by victory-wu** [comment]
> @WeirdMachine As the documentation states it is per request:
> 
> ```
> 	// The maximum number of objects requested per
> 	// batch, advanced use-case not useful for most
> 	// applications
> 	MaxKeys int
> ```
> 
> You can cancel the provided context if you aren't interested in more results. If you want you can set `MaxKeys` slightly higher than the number your expect to read.

If I use canelContext, then MaxKeys is meaningless, right？

**Comment by harshavardhana** [comment]
The listing in this SDK mimic's listing of all content matching the relevant input. It does not limit itself to X amount of entries. If you are looking for something this means you are using listing for incorrect reasons - points to a design problem in your application.

But if you are a bit adamant about this use case then this is not the right SDK for you.
