### ISSUE TITLE
prop:Question example change/set ACL

### ISSUE THREAD

**Issue by remotejob** [minio/minio-go#1537]
I use digitalocean Space https://docs.digitalocean.com/reference/api/spaces-api/

After upload object ---> default ACL:

Object owner:
Display name: "264981"
ID: "264981"
Object grant:
 - Display name: "264981"
 - ID: "264981"
 - URI: ""
 - Permission: "FULL_CONTROL"
key: Content-Type
 - value: [text/javascript]
key: X-Amz-Acl
 - value: [private]

-------------------------------------
But I need:

Object owner:
Display name: "264981"
ID: "264981"
Object grant:
 - Display name: ""
 - ID: ""
 - URI: "http://acs.amazonaws.com/groups/global/AllUsers"
 - Permission: "READ"
Object grant:
 - Display name: "264981"
 - ID: "264981"
 - URI: ""
 - Permission: "FULL_CONTROL"
key: Content-Type
 - value: [image/jpeg]
key: X-Amz-Acl
 - value: [public-read]

--------------------------------------
So I need to add extra Grantee and change X-Amz-Acl:
How set ACL at Upload (minioClient.FPutObject)
My guess: use some how minio.PutObjectOptions ??

**Comment by harshavardhana** [comment]
We do not support ACLs @remotejob - ACLs are deprecated ways to manage object access. Please move to bucket policies. 

minio-go does not implement support for ACLs

**Comment by julienrbrt** [comment]
I was wondering the same and this does the job:

```go
userMetaData := map[string]string{"x-amz-acl": "public-read"}
options := minio.PutObjectOptions{UserMetadata: userMetaData, ContentType: contentType}
```

Credits to https://www.digitalocean.com/community/questions/how-to-set-permission-of-all-files-in-a-bucket-as-public-on-every-upload

**Comment by harshavardhana** [comment]
> I was wondering the same and this does the job:
> 
> ```go
> userMetaData := map[string]string{"x-amz-acl": "public-read"}
> options := minio.PutObjectOptions{UserMetadata: userMetaData}
> ```
> 
> Credits to https://www.digitalocean.com/community/questions/how-to-set-permission-of-all-files-in-a-bucket-as-public-on-every-upload

No it does not.
