### ISSUE TITLE
tests: Add functional tests for bucket tagging

### ISSUE THREAD

**Issue by vadmeste** [minio/minio-go#1552]
Add functional tests for bucket tagging, PUT/GET/DELETE.

**Comment by romanchechyotkin** [comment]
Hello, this task is 3 years old, but i can do it, wanna start my opensource adventure. 
Is this still valid issue?

**Comment by klauspost** [comment]
@romanchechyotkin Good first topic indeed! I don't see it added to the repo.

It should be added to [functional_tests.go](https://github.com/minio/minio-go/blob/14b3aa6d56708fdf2071346aadcdb085069d8937/functional_tests.go#L13663). Add an entry. When I do it, I just add it at the top and add a temporary "return". To start out maybe copy an existing like `testMakeBucketError` and modify that.

I then run it against a local minio install with a simple script. You can adapt that to your needs:
```
SET ACCESS_KEY=minio
SET SECRET_KEY=minio123
SET SERVER_ENDPOINT=127.0.0.1:9001
SET MINT_DATA_DIR=
SET MINT_MODE=full
SET ENABLE_HTTPS=false
SET ENABLE_KMS=true

go build functional_tests.go && functional_tests
```

**Comment by romanchechyotkin** [comment]
#1986 here is my PR

**Comment by harshavardhana** [comment]
Task completed vi #1986
