### ISSUE TITLE
list_objects transforms whitespaces into "+"

### ISSUE THREAD

**Issue by mikegit21** [minio/minio-go#1562]
When using the list_objects method to get the names of all files in the bucket: 

```
self.client.list_objects(bucket_name=bucket, recursive=True)
```

The file names will be returned without whitespaces but "+" characters instead. This would be okay if the fget_object method, which i use afterwards to download all the files, would be able to deal with those file paths, but it's not. Calling this method using a name resulting from the list_objects method results in a s3Error: No such key / Object does not exist.

I am using version 7.1.0, which according to my knowledge is the latest version.

**Comment by klauspost** [comment]
@mikegit21 This doesn't look like the Go SDK. Which language are you using?

**Comment by mikegit21** [comment]
Wrong SDK page, sry ...
