### ISSUE TITLE
Allow Last-Modified time format to support single digit parsing

### ISSUE THREAD

**Issue by TestMsr** [minio/minio-go#1566]
server return
Sun, 1 Jan 2006 12:00:00 GMT

the default http.TimeFormat parse failed .change to 
Sun, 01 Jan 2006 12:00:00 GMT

it can be parsed 

the first time format can be find here by s3 doc
https://docs.amazonaws.cn/AmazonS3/latest/API/API_HeadObject.html#API_HeadObject_ResponseSyntax

`date, err := time.Parse(http.TimeFormat, h.Get("Last-Modified"))`

**Comment by harshavardhana** [comment]
Please provide a reproducer, this is an incomplete issue.

**Comment by TestMsr** [comment]
@harshavardhana 
some s3 compatible object storage return Last-Modified header with single digit day,minio-go can not handle this.
but aws-sdk-go can parse this format.as you can see here [https://github.com/aws/aws-sdk-go/blob/main/private/protocol/rest/unmarshal.go#L233](url)

so i think we should use RFC822TimeFormat too,it can parse both time style
