### ISSUE TITLE
Add slash to x-amz-copy-source header

### ISSUE THREAD

**Issue by TestMsr** [minio/minio-go#1577]
aws s3 doc shows the x-amz-copy-source pattern: \/.+\/.+

minio-go ignore the first slash，both style accepted with aws s3，i think we should follow the document

(i met a s3 compatiable storage only support this pattern)

**Comment by harshavardhana** [comment]
> aws s3 doc shows the x-amz-copy-source pattern: /.+/.+
> 
> minio-go ignore the first slash，both style accepted with aws s3，i think we should follow the document
> 
> (i met a s3 compatiable storage only support this pattern)

Ask your S3 compatible storage to support both formats. We shall keep the way it works with AWS S3 for now as there is no reason to change this.
