### ISSUE TITLE
Please consider adding option to opt-out chunked uploads

### ISSUE THREAD

**Issue by suraciii** [minio/minio-go#1581]
Hi, I was diving into using minio-go to upload objects to a S3-compatible (but not fully compatible🙁) object store, it didn't support chuncked uploads, which are using by minio-go by default.

Similar issue like #774 and #1194.

Also I found if I force minio-go using multipart stream uploads, this issue can be avoid, so for now I'm doing so in a fork as a workaround.

Is it reasonable to: 1. add a option, to force using multipart stream uploads despites object size, 2. or to allow non-chuncked uploads on `putObject`

**Comment by harshavardhana** [comment]
You can set `opts.DisableMultipart = true`

**Comment by suraciii** [comment]
@harshavardhana Sorry I didn't explain myself well -

I'm not trying to disable multipart.
`c.putObjectMultipartStream` - this works well
`c.putObject` - this not, s3 server reply with chunked not support error.

So what I request is to support using `c.putObjectMultipartStream` always, even for small objects, or make `c.putObject` using non-chunked uploads.

**Comment by harshavardhana** [comment]
> So what I request is to support using `c.putObjectMultipartStream` always, even for small objects, or make `c.putObject` using non-chunked uploads.
> 
> so options like "ForceMultipart" or "DisableChunck" are helpful

You can talk to your S3 compatible storage over TLS - it automatically disables chunked uploads.

**Comment by suraciii** [comment]
@harshavardhana Thank you
