### ISSUE TITLE
Parse expires response header broken after #1566

### ISSUE THREAD

**Issue by TestMsr** [minio/minio-go#1588]
I got a response header in ceph like this

- Expires: 1632280617

cause parse err.

https://github.com/minio/minio-go/commit/56f3625bd90b6a3bf44559258307b8d2f5a5047c#diff-8b7f25bac2ae04c2ce2abb628c6aa28103fd113103a62f3e9d232fa995684915L292

is there any reason that expires parse err was ignored before?

**Comment by harshavardhana** [comment]
> I got a response header in ceph like this
> 
> * Expires: 1632280617

Ask Ceph to fix their implementation 

```
Expires:
```

Header is `HTTP-Date` https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires

Also, reference the HTTP1.1 spec https://httpwg.org/specs/rfc7234.html#header.expires


> is there any reason that expires parse err was ignored before?

Its not ignored to expose broken implementations.

**Comment by TestMsr** [comment]
@harshavardhana it can be reproduced in aws s3

step:
1.presigned a put url with minio-go
2.put object bypass minio gateway s3
3.stat the object directly


minio-go trace:
HEAD /exp HTTP/1.1
Host: *.s3.dualstack.us-east-1.amazonaws.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.15
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211119T090557Z

HTTP/1.1 200 OK
Connection: close
Content-Length: 2
Accept-Ranges: bytes
Content-Type: application/octet-stream
Date: Fri, 19 Nov 2021 09:05:58 GMT
Etag: "f970e2767d0cfe75876ea857f92e319b"
Expires: 1637313635
Last-Modified: Fri, 19 Nov 2021 09:04:07 GMT
Server: AmazonS3
X-Amz-Id-2: eZjnuABHgOZfMMjVE/EUweFeUb3G/uwQpeGc2U2r4NTkJpQUHBQhv98uw/X8yL3X/2f+p8hzfcs=
X-Amz-Request-Id: 6R3JANTHYZ089WPG
---------END-HTTP---------

**Comment by harshavardhana** [comment]
> @harshavardhana it can be reproduced in aws s3
> 
> step: 1.presigned a put url with minio-go 2.put object bypass minio gateway s3 3.stat the object directly

Their documentation says 

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html

```
The Expires header field lets you specify an expiration date and time using the format specified in RFC 2616, Hypertext Transfer Protocol -- HTTP/1.1 Section 3.3.1, Full Date, for example:

Sat, 27 Jun 2015 23:59:59 GMT
```

We shall stick to HTTP standard here..

**Comment by harshavardhana** [comment]
And also recommends 

```
We recommend that you use the Cache-Control max-age directive instead of the Expires header field to control object caching. If you specify values both for Cache-Control max-age and for Expires, CloudFront uses only the value of Cache-Control max-age.
```
So you are better off moving away from "Expires:" header @TestMsr

**Comment by TestMsr** [comment]
There is no way for me to avoid this. I use presinged v2 signature to put object with minio and the url contains expires param.
And minio set the expires url query as header.
So it maybe the minio's bug.Is' the way  minio should fix this.

my reuqest to minio:
curl --location --request PUT 'http://-:9000/bucket/exp?AWSAccessKeyId=-&Expires=1637315151&Signature=-' \
--data-raw 'as'

and the minio gateway mode transform the new request to aws:

PUT /exp HTTP/1.1
Host: *.s3.dualstack.us-east-1.amazonaws.com
User-Agent: MinIO (linux; amd64) minio-go/v7.0.11
Content-Length: 174
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211119/us-east-1/s3/aws4_request,SignedHeaders=expires;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=**REDACTED**
Content-Type: binary/octet-stream
Expires: 1637315151
X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
X-Amz-Date: 20211119T092921Z
X-Amz-Decoded-Content-Length: 2
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 0
Date: Fri, 19 Nov 2021 09:29:22 GMT
Etag: "f970e2767d0cfe75876ea857f92e319b"
Server: AmazonS3
X-Amz-Id-2: KnsicRzZvM94N4YYmJA7kQuv8KtEtY8WJSCjHatoF1GqkyxiGTdOGcLY95ZekiQPoHV52X0oUos=
X-Amz-Request-Id: H3FE3HDGQJ98H0EZ

**Comment by harshavardhana** [comment]
Yes this is a MinIO bug, but it is also an error from AWS S3 they are not parsing things properly.

The Expires param in presigned v2 - is not the same value as Expires metadata for an object.

**Comment by TestMsr** [comment]
> Yes this is a MinIO bug, but it is also an error from AWS S3 they are not parsing things properly.
> 
> The Expires param in presigned v2 - is not the same value as Expires metadata for an object.

Got it!
