### ISSUE TITLE
Cannot assign a value to the unexported field 'retrieved'

### ISSUE THREAD

**Issue by DevOpserzhao** [minio/minio-go#1589]
```
	var minioClient, err = minio.New("s3.amazonaws.com", &minio.Options{
		Creds: credentials.NewChainCredentials([]credentials.Provider{&credentials.FileAWSCredentials{
			"",
			"",
			true,
		}}),
		Secure: true,
		Region: "ap-northeast-1",
	})
	if err != nil {
		log.Fatalln(err)
	}
```
ture is error

Cannot assign a value to the unexported field 'retrieved'

**Comment by harshavardhana** [comment]
> var minioClient, err = minio.New("s3.amazonaws.com", &minio.Options{
> 		Creds: credentials.NewChainCredentials([]credentials.Provider{&credentials.FileAWSCredentials{
> 			"",
> 			"",
> 			true,
> 		}}),
> 		Secure: true,
> 		Region: "ap-northeast-1",
> 	})
> 	if err != nil {
> 		log.Fatalln(err)
> 	}

You need to use `credentials.NewFileAWSCredentials()`
