### ISSUE TITLE
Cannot GetObject after Stat call

### ISSUE THREAD

**Issue by lubishata** [minio/minio-go#1590]
Hello, 

I'm trying to make streaming zip write and zip read from minio test server and I'm experience very strange issue when reading content of the file after I've got Stat(). 

        `endpoint := "s3.xxxxxxx.xxx"
	accessKeyID := "xxxxxxxxx"
	secretAccessKey := "xxxxxxxxxxx"
	useSSL := true

	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln(err)
	}

	bucketName := "bucket1"
	objectName := "text-data.zip"
	contentType := "application/zip" 

	object, err := minioClient.GetObject(context.Background(), bucketName, objectName, minio.GetObjectOptions{})
	if err != nil {
		fmt.Println(err)
		return
	}
	stat, err := object.Stat() //If Stat is not invoked everything works like a charm

	localFile, err := os.Create("local-file.zip")
	if err != nil {
		fmt.Println(err)
		return
	}
	if _, err = io.Copy(localFile, object); err != nil {
		fmt.Println(err) //If Stat is called before writing I get "There were headers present in the request which were not signed"
		return
	}`
	
Whenever I get stat of un object this object can't be read because Read or ReadAt fails with following error "There were headers present in the request which were not signed".
Environment is Golang 1.17 and minio server version 2021-11-09T03:21:45Z.
In trace logs at the server response is "400 Bad Request".

Am I missing something and how is suppose to get object size if I want to use it as parameter at io.ReadAt?

**Comment by vadmeste** [comment]
@lubishata I wasn't able to reproduce this. Can you paste the log ? just add this `minioClient.TraceOn(os.Stderr)` after initialization of minioClient

**Comment by lubishata** [comment]
Sure, 

Here it is:
`---------START-HTTP---------
GET /bucket1/?location= HTTP/1.1
Host: s3.xerberos.com
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211123/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20211123T141446Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 133
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 23 Nov 2021 14:12:24 GMT
Server: nginx/1.18.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: sofia
X-Amz-Request-Id: 16BA3252987E2753
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
---------START-HTTP---------
HEAD /bucket1/text-data.txt HTTP/1.1
Host: s3.xerberos.com
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211123/sofia/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211123T141446Z

HTTP/1.1 200 OK
Content-Length: 901739
Accept-Ranges: bytes
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/zip
Date: Tue, 23 Nov 2021 14:12:24 GMT
Etag: "3a8db358da279d419652a49e6bd03a88-1"
Last-Modified: Tue, 02 Nov 2021 14:55:01 GMT
Server: nginx/1.18.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Bucket-Region: sofia
X-Amz-Request-Id: 16BA32529E7D0CB1
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
{3a8db358da279d419652a49e6bd03a88-1 text-data.txt 2021-11-02 14:55:01 +0000 UTC 901739 application/zip 0001-01-01 00:00:00 +0000 UTC map[Content-Type:[application/zip]] map[] map[] 0 {{ }  } []  false false   0001-01-01 00:00:00 +0000 UTC  <nil> <nil>}
---------START-HTTP---------
GET /bucket1/text-data.txt HTTP/1.1
Host: s3.xerberos.com
User-Agent: MinIO (windows; amd64) minio-go/v7.0.15
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20211123/sofia/s3/aws4_request, SignedHeaders=host;if-match;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
If-Match: "3a8db358da279d419652a49e6bd03a88-1"
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20211123T141446Z
Accept-Encoding: gzip

HTTP/1.1 400 Bad Request
Content-Length: 374
Connection: keep-alive
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 23 Nov 2021 14:12:25 GMT
Server: nginx/1.18.0 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Bucket-Region: sofia
X-Amz-Request-Id: 16BA3252A44FF6E4
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>There were headers present in the request which were not signed</Message><Key>text-data.txt</Key><BucketName>bucket1</BucketName><Resource>/bucket1/text-data.txt</Resource><Region>sofia</Region><RequestId>16BA3252A44FF6E4</RequestId><HostId>72b2aa98-481a-4c0b-8bc8-b7fe9baa6729</HostId></Error>---------END-HTTP---------
There were headers present in the request which were not signed`

**Comment by vadmeste** [comment]
@lubishata most likley your load balancer is changing something in your request. Can you bypass it for now and test it ?

**Comment by lubishata** [comment]
Yep,  you're absolutely right. It seems that nginx changing headers. I'll find out what in the config is the problem and let you know. 
Thanks a lot.

**Comment by lubishata** [comment]
proxycache  was turned on and this was the reason.
