### ISSUE TITLE
Specify ContentType on PutObject, not returned in ObjectInfo.ContentType from ListObjects?

### ISSUE THREAD

**Issue by tomqwpl** [minio/minio-go#1593]
I have an odd issue I'm trying to understand. 
I create an object in MinIO using PutObject, and specify a ContentType:
```
	_, err = n.c.s3Client.PutObject(ctx, s3BucketName, s3ObjectName, f, fileInfo.Size, minio.PutObjectOptions{
		ContentType: info.ContentType,
	})
```
I can see in minio console that the content type has been stored, under "Object Metadata" there is an entry for "content-type".
When I then use ListObjects to retrieve information about the object however, I don't get the ContentType back:
```
	objectch := s.client.ListObjects(ctx, s.bucketName, minio.ListObjectsOptions{
		Prefix:       prefix,
		Recursive:    true,
		WithMetadata: true,
	})
	for o := range objectch {
		if o.Err != nil {
			return nil, o.Err
		}
		fmt.Printf("%s %s\n", o.Key, o.ContentType)
                fmt.Printf("%v\n", o.UserMetadata)
```

The `o.ContentType` field is blank.
However, the content type DOES get returned in the UserMetadata field as "content-type", in the same way that it is displayed in the minio console.

Is this expected? If so, what's the ContentType field for in the ObjectInfo?

Thanks

**Comment by harshavardhana** [comment]
> The `o.ContentType` field is blank.
> However, the content type DOES get returned in the UserMetadata field as "content-type", in the same way that it is displayed in the minio console.

ContentType is not populated @tomqwpl this is only populated during StatObject()/GetObject() - HTTP header availability.  

ListObjects do not return such HTTP headers so they are populated as part of UserMetadata. So use UserMetadata.

NOTE: this is just a MinIO extension AWS S3 doesn't return any content-type in ListObjects.

**Comment by tomqwpl** [comment]
OK, that explains it.
Thanks.
