### ISSUE TITLE
Retrying error "read: operation timed out" in ListObjectsV2 API

### ISSUE THREAD

**Issue by mohsha-msft** [minio/minio-go#1594]
We're getting "read: operation timed out" from ListObjectsV2 API. Now, this error is retriable and most likely will be resolved by making another retry. 

Question: Do you have any documentation on how we can retry when APIs return these errors? In general, is there a way client app can control retrying of an given API? If you can provide us some examples, it'd be super amazing.

Thanks

**Comment by harshavardhana** [comment]
> Question: Do you have any documentation on how we can retry when APIs return these errors? In general, is there a way client app can control retrying of an given API? If you can provide us some examples, it'd be super amazing.

First of all, this should never happen - if this is happening means that either your server is saturated and not responding anymore.

Or your client doesn't have enough bandwidth. 

Please provide trace output by setting setTraceOn()

**Comment by mohsha-msft** [comment]
Thanks for your quick response. I'll try to set TraceOn() on the S3 Client and get back to you. I'll also check if the server is getting saturated or not. 

But can we (client) control the retrying parameters of a given API? For instance, if we want to provide a different retry value (say 20 times) or retry on certain errors only?

**Comment by harshavardhana** [comment]
> But can we (client) control the retrying parameters of a given API? For instance, if we want to provide a different retry value (say 20 times) or retry on certain errors only?

This SDK retries automatically up to 10 times - so we need to see what is the error here and if we can handle it and automatically retry.

**Comment by harshavardhana** [comment]
Please reply to my comment, closing this as non-actionable until then.
