### ISSUE TITLE
remove jsoniter dependency

### ISSUE THREAD

**Issue by elagergren-spideroak** [minio/minio-go#1597]
The dependency `github.com/json-iterator/go` uses `github.com/modern-go/reflect2`, which calls `(reflect.Value).MethodByName`. Calling that method puts the linker into a conservative mode where it does not dead-code eliminate _any_ exported methods.

This causes executable sizes to balloon. As a test, replacing `github.com/json-iterator/go` with the stdlib's `json` package reduced the size of an executable from 24 MB to 14 MB (!!).

**Comment by harshavardhana** [comment]
> This causes executable sizes to balloon. As a test, replacing `github.com/json-iterator/go` with the stdlib's `json` package reduced the size of an executable from 24 MB to 14 MB (!!).

Very cool @elagergren-spideroak feel free to send a fix.

**Comment by elagergren-spideroak** [comment]
Oops, I actually got my wires crossed. I meant to post the bit about DCE and binary sizes elsewhere (another dependency of ours).

What I _meant_ to post here is that `github.com/json-iterator/go`, which uses `github.com/modern-go/reflect2`, is an expensive dependency. In total, it's about 1 MB of the total executable size. Replacing it with the stdlib removes that cost.

**Comment by harshavardhana** [comment]
Sure the reason for us to use jsoniter is performance so if it's 1MiB cost then it's not a big deal.

We want to make sure we don't bloat the binary unnecessary but 1MiB be tolerable.

**Comment by harshavardhana** [comment]
jsoniter is tolerable..
