### ISSUE TITLE
UploadInfo.LastModified is not populated by PutObject()

### ISSUE THREAD

**Issue by jkowalski** [minio/minio-go#1600]
I was hoping to use `UploadInfo.LastModified` returned by `PutObject()` to get the server-assigned modification time of the blob in one shot, without having to go through separate `StatObject()` but it always returns `time.Time{}`

I scanned through the source code and it seems to be only set in `CopyObject` but not inside `putObjectDo()`.

Is that intentional? server limitation? or a client bug?

**Comment by harshavardhana** [comment]
Server never sends ModTime response in S3 protocol. We do not want to waste call doing another Stat() operation.

Do this yourself outside.

**Comment by jkowalski** [comment]
Should the field be removed or made nullable to indicate it's not always set?

**Comment by harshavardhana** [comment]
> Should the field be removed or made nullable to indicate it's not always set?

the returned value is LastModified.IsZero() that is null in Go.
