### ISSUE TITLE
GOLANG SDK support is not working as expected

### ISSUE THREAD

**Issue by k963** [minio/minio-go#1611]
I was following the quick start guide for Golang SDK  (https://docs.min.io/docs/golang-client-quickstart-guide.html). I'm facing the issue while running the program and I cant import the minio package  "github.com/minio/minio-go/v7". The "v7" folder isn't available inside the package folder when I checked in my system and go get command is not successful.

Even I used go playground to test the code, the build is failing there also.
https://go.dev/play/p/VClJKXWGBJn

Either the documents are not updated or is there any issue in the minio package I'm not sure.

I couldn't' find anything which resolves this issue, so correct me if I'm missing anything.

**Comment by klauspost** [comment]
@k963 Your Go version is probably too old. Upgrade to 1.17.x

Playground isn't failing, it is simply timing out.
