### ISSUE TITLE
Access Denied problem for public image

### ISSUE THREAD

**Issue by delgec** [minio/minio-go#1613]
Hello everyone

I uploaded an image and I checked the file after upload. It was exists but when I open the browser, I am getting an error (access denied) 

How can I fix this?

Error:
AccessDeniedAccess Denied.no-image.pngzu-bucket3/zu-bucket3/no-image.pngus-east-116CC0D0E60C1333Fc1758167-4426-454f-9aae-5c3dfdf6df64

Absolute path:
https://play.min.io/zu-bucket3/no-image.png
http://s3.amazonaws.com/doc/2006-03-01/zu-bucket3/no-image.png

**Comment by harshavardhana** [comment]
> https://play.min.io/zu-bucket3/no-image.png

Bucket needs a public anonymous policy - all objects need authentication by default. `mc policy set download play/zu-bucket3` to make sure the object is publicly accessible.
