### ISSUE TITLE
Change host during pre-signed url creation.

### ISSUE THREAD

**Issue by lromor** [minio/minio-go#1616]
The minio client instantiation doesn't seem to allow offline pre-signed url generation (https://github.com/minio/minio/issues/14241, https://github.com/minio/minio/issues/10222).

If I try to instantiate a client with an unreachable host to generate a presigned url I get:

```
Get "http://foobar/data/?location=": dial tcp: lookup foobar on 10.0.0.1:53: no such host
```

What I'm trying to show here is that I couldn't find a way to generate a presigned url when offline using your client. 

For now I'll proceed writing my own signing function but it's far from ideal.

**Comment by harshavardhana** [comment]
you need to generate pre-signed URL by providing the necessary `Host` header in the https://pkg.go.dev/github.com/minio/minio-go/v7#Client.PresignHeader
