### ISSUE TITLE
CustomSHA256 doesn't seem to be used when uploading object

### ISSUE THREAD

**Issue by montag451** [minio/minio-go#1618]
Hi,

I'm trying to use a custom implementation for computing SHA256 checksums (I want to use the AVX512 version of [sha256-simd](https://github.com/minio/sha256-simd#support-for-avx512)) but my custom function is never called. In which circumstances the `CustomSHA256` function provided when creating `minio.Client` is used?

**Comment by klauspost** [comment]
Described here: https://github.com/minio/minio-go/blob/cb21d7dd9e4faec51eb6125f008ae0e7d8414960/api.go#L312
