### ISSUE TITLE
IMDSv2 slow response

### ISSUE THREAD

**Issue by saracen** [minio/minio-go#1625]
https://github.com/minio/minio-go/pull/1489 introduced `IMDSv2` support. Similar to the issues described in the official AWS SDK (https://github.com/aws/aws-sdk-go/issues/2972), the IAM credential provider potentially introduces a several minute delay.

A workaround appears to be to [adjust the EC2 instances hop limit](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html#configuring-IMDS-existing-instances) (details regarding this are also discussed in the `aws-sdk-go` issue).

The official SDK solved this by setting a `1s` timeout for the metadata service request. This bug affects many users of GitLab-Runner (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28656), and whilst I can fix this in Runner by adjusting the client transport, this will affect all requests and might have ramifications beyond fixing just this problem.

Are we okay to add a similar solution to the official SDK? Maybe by coping the transport and setting a timeout of 1s just for the `fetchIMDSToken` call? If so, and unless anybody else beats me to this, I should be able to work on this tomorrow.

**Comment by harshavardhana** [comment]
> Are we okay to add a similar solution to the official SDK? Maybe by coping the transport and setting a timeout of 1s just for the `fetchIMDSToken` call? If so, and unless anybody else beats me to this, I should be able to work on this tomorrow.

Sure feel free to send a PR @saracen
