### ISSUE TITLE
Inconsistent LastModified field

### ISSUE THREAD

**Issue by jhwz** [minio/minio-go#1632]
I had a brief search and could not find a similar issue.

When fetching object info via `client.StatObject` and `client.ListObjects` the last modified field is not equal. For `StatObject` the LastModified field only seems to be accurate to the second, but `ListObjects` seems to be accurate to the millisecond.

For example the below test:
```go
func TestLastModified(t *testing.T) {
	ctx := context.Background()
	const bucket = "testing"
	const path = "mc_tests/foo"

	uploadInfo, err := c.PutObject(ctx, bucket, path, strings.NewReader("foo"), 3, minio.PutObjectOptions{})
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(uploadInfo.LastModified)

	info, err := c.StatObject(ctx, bucket, path, minio.GetObjectOptions{})
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(info.LastModified)

	ch := c.ListObjects(ctx, bucket, minio.ListObjectsOptions{
		Prefix: path,
	})
	for obj := range ch {
		if obj.Err != nil {
			t.Fatal(obj.Err)
		}
		fmt.Println(obj.LastModified)
	}
	
	t.Fail()
}
```

outputs:

```sh
0001-01-01 00:00:00 +0000 UTC
2022-04-10 20:51:06 +0000 UTC
2022-04-10 20:51:06.821 +0000 UTC
```

I'm unsure as to why the upload info has the `LastModified` field but it's not populated, but that's not as important!

This leads to inconsistent behaviour when comparing the last modified times. Is this behaviour intended?

The Minio server this test is using is running `Version: 2022-04-01T03:41:39Z`

**Comment by harshavardhana** [comment]
Generally Stat() should have same level of time resolution, looks like it's getting truncated due to the fact of time.rfc339 parsing.

**Comment by jhwz** [comment]
Hopefully an easy fix then - thanks.

**Comment by vadmeste** [comment]
@jhwz what is your S3 server here ?

**Comment by jhwz** [comment]
> @jhwz what is your S3 server here ?

`MinIO, version: 2022-04-01T03:41:39Z` as stated above
