### ISSUE TITLE
Hi, I request to get uploaded documents, It find docs and return the URL but the status code is not 200, its 404

### ISSUE THREAD

**Issue by abbasymot** [minio/minio-go#1647]
```
// Get the documents url
		presignedURL, err := minIo.ResignedGetObject(bucketName, address, time.Minute*15)
		if err != nil {
			panic(tools.NewError(err.Error(), http.StatusInternalServerError, nil))
		}

// Check if error code is not NotSuchKey append presignedURL to links
_, e := minIoClient.StatObject(c.Context(), bucketName, f, minio.GetObjectOptions{})
if e != nil {
	errResponse := minio.ToErrorResponse(e)
	if errResponse.StatusCode == 200 {
		links = append(links, presignedURL)
	}
}
```

![image](https://user-images.githubusercontent.com/96351106/165725371-216b89b0-6dd8-4bc3-92f5-638d5d4d5be0.png)

If I delete the if statement I get urls
![image](https://user-images.githubusercontent.com/96351106/165726519-507b66e1-e1ba-46fa-84a4-b9ec16f95da1.png)

**Comment by klauspost** [comment]
Creating a presigned URL does not check if the object exists. It is a client-side operation.

**Comment by abbasymot** [comment]
> 

Thanks, but  what should I do instead?

**Comment by klauspost** [comment]
You can use `StatObject` to see if the object exists.

**Comment by abbasymot** [comment]
> 
Thank you
