### ISSUE TITLE
FPutObject method error with use ssl 

### ISSUE THREAD

**Issue by wangchuxiao-dev** [minio/minio-go#1650]
FPutObject return error is: XML syntax error on line 1: element <link> closed by </head>]]

nginx config:  
```
location ~^/storage {
                 proxy_buffering off;
                 proxy_set_header Host $host;
                 rewrite ^/storage/(.*)$ /$1 break;
                 proxy_pass http://127.0.0.1:10005;
           }

```
10005 was minio 9000 port

minio version: RELEASE.2022-02-26T02-54-46Z

sdk version: github.com/minio/minio-go/v7

my upload code:

```
client, err := minio.New(endPoint.Host, &minio.Options{
		Creds:  credentials.NewStaticV4(minioResp.AccessKeyID, minioResp.SecretAccessKey, minioResp.SessionToken),
		Secure: true,
	})
	if err != nil {
		return "", "", utils.Wrap(err, "")
	}
	_, err = client.FPutObject(context.Background(), minioResp.BucketName, newName, filePath, minio.PutObjectOptions{ContentType: newType})
	if err != nil {
		return "", "", utils.Wrap(err, "")
	}

```

**Comment by vadmeste** [comment]
@wangchuxiao-dev minio-go error means it did not get the expected answer. Most likley there is an issue in your configuration (it looks like it is receving HTML and not XML from MinIO)

By the way, you cannot modify the request path in your load balancer, https://docs.min.io/docs/setup-nginx-proxy-with-minio.html
