### ISSUE TITLE
Absolute paths regression with swift3 on openstack kilo

### ISSUE THREAD

**Issue by dudymas** [minio/minio-go#167]
## Summary
I'm currently working with swift3 and auth version2 on openstack kilo, and I noticed that the mc client was reporting 500's when making any request to the s3 endpoint. The issue appears to be related to the absolute paths used by the minio client.

## Analysis

Normally a GET to swift's S3 would go like this:
```
GET /bucket/object/path HTTP/1.1
Host: 10.0.0.0
```

Instead, I'm seeing this from mc:
```
GET https://10.0.0.0/bucket/object/path HTTP/1.1
Host: 10.0.0.0
```

While this works with many s3 implementations, the swift3 implementation is rather conservative and the juno/kilo release of swift doesn't appear to know how to map those routes.

To show this, I rigged up a simple HAProxy config that strips the path out, leaving the rest of the request the same:
```
global
  log 127.0.0.1 local1 notice
  maxconn 256

defaults
  log global
  mode http
  timeout connect 15000ms
  timeout client 15000ms
  timeout server 25000ms
  option http-server-close
  option httplog

listen https-swift-in
  bind *:443 ssl crt /certs/server-bundle.pem
  reqrep ^(^[^\ :]*)\ https://[^\ /]+(/.*) \1\ \2
  server server1 10.0.0.1:8080 maxconn 32
```

Note the 'reqrep' . That did the trick and mc was happily grabbing details and downloading files from the bucket/container.
I don't know how to test delete with the current mc client yet (I just started using it yesterday ;-) ) But that should work too.

**Comment by harshavardhana** [comment]
> I don't know how to test delete with the current mc client yet (I just started using it yesterday ;-) ) But that should work too.

We do not have delete implemented, since we just generally think it is a bad idea to provide delete through a CLI tool that could lead to data loss and it becomes even more evident with ``mc`` like tool. 

If one has to Delete explicitly do it through a management console. Where it is a scheduled and controlled delete which can be easily audited.

**Comment by harshavardhana** [comment]
This issue should be fixed by now, closing this - re-open if seen again.
