### ISSUE TITLE
Post policy SetContentLengthRange with min=max=0 will omit  content-length-range condition ?

### ISSUE THREAD

**Issue by hotrungnhan** [minio/minio-go#1674]
I think this policy.SetContentLengthRange should throw an error if min=max=0, currently it will omit `content-length-range` make harder to predict. 
![image](https://user-images.githubusercontent.com/40029631/178096363-140d3ac0-84cc-4841-bdb7-5d7f0ab21d90.png)

**Comment by harshavardhana** [comment]
Feel free to send a PR @hotrungnhan

**Comment by harshavardhana** [comment]
This is fixed in #1675
