### ISSUE TITLE
ComposeObject does not work for copying from another region

### ISSUE THREAD

**Issue by bjg2** [minio/minio-go#1683]
Stating object in another region gives bad request, and ComposeObject stats sources.

This is my wild temp fix that helped me get through the issue in my local run (I added otherCli to use for stating).

![image](https://user-images.githubusercontent.com/6639273/182124236-ccbe4476-b0b8-4c9d-afe0-5ac1fd4a5a45.png)

**Comment by harshavardhana** [comment]
> Stating object in another region gives bad request, and ComposeObject stats sources.
> 
> This is my wild temp fix that helped me get through the issue in my local run (I added otherCli to use for stating).
> 
> ![image](https://user-images.githubusercontent.com/6639273/182124236-ccbe4476-b0b8-4c9d-afe0-5ac1fd4a5a45.png)

Please provide reproducers we cannot imagine your setup.

**Comment by bjg2** [comment]
Sorry if I wasn't clear enough.
 - I was copying objects from eu-west-1 to eu-central-1.
 - I couldn't copy objects bigger than 5GB through CopyObject(), so I had to use ComposeObject() with ranges of the source object as sources.
 - I called ComposeObject() on eu-central-1 client, as I want to compose object there.
 - ComposeObject() calls StatObject() for each source, and calls it on client on which ComposeObject() was called (eu-central-1 one).
 - Stating object from another region finishes with 400 Bad Request, so everything fails (as it tries to stat objects from eu-west-1).

I managed to mitigate and do the execute the copy of the objects I needed at the moment with the code change mentioned above, as this was a one-time migration. I will not hit this in the future, but wanted to notify you as minio is a great tool and I wanted to give you a feedback of this broken behavior.

If some part of this was unclear, I can describe further.

**Comment by vadmeste** [comment]
> I was copying objects from eu-west-1 to eu-central-1.

Are you using ComposeObject() between two separate S3 servers ?

**Comment by harshavardhana** [comment]
> Sorry if I wasn't clear enough.
> 
> * I was copying objects from eu-west-1 to eu-central-1.
> * I couldn't copy objects bigger than 5GB through CopyObject(), so I had to use ComposeObject() with ranges of the source object as sources.
> * I called ComposeObject() on eu-central-1 client, as I want to compose object there.
> * ComposeObject() calls StatObject() for each source, and calls it on client on which ComposeObject() was called (eu-central-1 one).
> * Stating object from another region finishes with 400 Bad Request, so everything fails (as it tries to stat object from eu-west-1).
> 
> I managed to mitigate and do the execute the copy of the objects I needed at the moment with the code change mentioned above, as this was a one-time migration. I will not hit this in the future, but wanted to notify you as minio is a great tool and I wanted to give you a feedback of this broken behavior.
> 
> If some part of this was unclear, I can describe further.

We still need to see the code @bjg2
