### ISSUE TITLE
HealthCheck don't work

### ISSUE THREAD

**Issue by Fukutu** [minio/minio-go#1693]
I was trying to detect on application startup if the minio server is up but the `IsOffline`  function always returns false

example:
```golang
client, err := minio.New("127.0.0.1:9000",  &minio.Options{
	Creds:  credentials.NewStaticV4("invalid-key", "invalid-secret", ""),
	Secure: false,
})
if err != nil {
	log.Fatalln(err)
}

cancel, err := client.HealthCheck(1 * time.Second)
if err != nil {
	log.Fatalln(err)
}
defer cancel()

// always false
if client.IsOffline()   {
	log.Fatalln("storage is offline!")
}
```

**Comment by harshavardhana** [comment]
@Fukutu provide invalid secret key doesn't make the healthcheck invalid. - 403 is considered as server is active and receiving requests.

Heathcheck determines server is offline if server returns 5xx or upon network errors.

**Comment by Fukutu** [comment]
> @Fukutu provide invalid secret key doesn't make the healthcheck invalid. - 403 is considered as server is active and receiving requests.
> 
> Heathcheck determines server is offline if server returns 5xx or upon network errors.

But with correct credentials the HealthCheck until don't detect if the server is offline

**Comment by harshavardhana** [comment]
> But with correct credentials the HealthCheck until doesn't detect if the server is offline

huh?
