### ISSUE TITLE
key is ignored when using auto-extract

### ISSUE THREAD

**Issue by sarnikowski** [minio/minio-go#1694]
I am trying to upload a `tar.gz` file to minio and extract this to a folder within a bucket. For this purpose I am doing something along the lines of:
```go
var key string
userMetaData := make(map[string]string)

userMetadata["X-Amz-Meta-Snowball-Auto-Extract"] = "true"
key = fmt.Sprintf("%s/%s", strings.TrimSuffix(file.Name, ".tar.gz"), "some-file.tar.gz")

_, err := s.client.PutObject(ctx, bucket, key, file.Content, file.Size, minio.PutObjectOptions{
	ContentType:  file.ContentType,
	UserMetadata: userMetadata,
})
```
However, no matter what I specify in the key, the tarball is always extracted to the root of the bucket. What I would like, is to extract the content to a folder by the same name as the tarball file, without the extension. Is this possible ?

**Comment by klauspost** [comment]
@sarnikowski Yes, you must specify full paths for files in the archive. This is how it is implemented in AWS S3.

**Comment by sarnikowski** [comment]
Alright. Thank you for the quick response ! :)
