### ISSUE TITLE
PutObject for s3 csv extract fails.

### ISSUE THREAD

**Issue by binnie268** [minio/minio-go#1711]
Minio Version used minio-go: github.com/minio/minio-go/v7 v7.0.24
Minio bitnami chart version used: bitnami/minio:2022.8.13-debian-11-r0

So we call GetObject to retrieve a CSV file from a zip:
`func (ms minioService) GetObject(
	ctx context.Context,
	bucketName string,
	path string,
) (*minio.Object, error) {
	var opts minio.GetObjectOptions

	// Add extract zip header to request:
	opts.Set("x-minio-extract", true)

	// Download file from the archive
	reader, err := ms.minioClient.GetObject(ctx, bucketName, path, opts)
	if err != nil {
		return nil, err
	}

	return reader, nil
}`

Then we call PutObject to put the object into another bucket:

`func (ms minioService) PutObject(
	ctx context.Context,
	bucketName string,
	object *minio.Object,
	newFileName string,
	fileSize int64,
) error {
	log.Info("minio#PutObject Start Progress of uploading file.")
	// progressBarLog := pb.New64(fileSize)
	// defer progressBarLog.FinishPrint("minio#PutObject File Uploaded.")
	// progressBarLog.Start()
	info, err := ms.minioClient.PutObject(ctx, bucketName, newFileName, object, fileSize, minio.PutObjectOptions{})
	if err != nil {
		return err
	}
	log.Info("minio#PutObject info on the upload", info)

	return nil
}`

Some files passes PutObject, but this particular file keeps on erroring out.

This results in an error:
` 0.00%ERROR[2022-10-18T18:56:08Z] Failed to put file into bucket                bucketName=data-sources error="Put \"http://minio:9000/data-sources/data-source-1.csv?partNumber=1&uploadId=41381d95-27cb-4bad-b4ed-e64a43539dc6\": net/http: HTTP/1.x transport connection broken: http: ContentLength=16777216 with Body length 0" method=PutObject newFileName=data-source-1.csv
`
[test2.zip](https://github.com/minio/minio-go/files/9814535/test2.zip)

**Comment by binnie268** [comment]
I upgraded minio-go to 7.0.42 and get the same issue. I am doing this:
`
**reader**, err := ms.minioClient.GetObject(ctx, bucketName, path, opts)
**fileStats**, _ := **reader.Stat()**
info, err := ms.minioClient.PutObject(ctx, bucketName, newFileName, object, **fileStats.Size**, minio.PutObjectOptions{Progress: progressBarLog})
`
Unless the reader.Stat from minio is giving back the wrong size, I am not sure how the size could be incorrect.

BTW this only happens for couple files in the zip extract. I also attached test2.zip above which fails too.

**Comment by klauspost** [comment]
Sure I'll check it out.

**Comment by klauspost** [comment]
I think the root cause could be that you are doing multipart upload which triggers a range request which isn't supported by s3zip (and probably will not be).

You could either:

A) Disable multipart on your putobject.
B) Wrap the returned `io.Reader` in a `io.NopCloser()` to remove the Seek and ReadAt functionality from the returned reader.

Try these out and let me know your results. I will look into updating the documentation and see if we are returning correct headers and errors from the server.

**Comment by binnie268** [comment]
I will try those. Also these are my object info, let me know if there is any other information you need: 
`github.com/minio/minio-go/v7.ObjectInfo {ETag: "", Key: "test2.zip/v_3_0_Issuer_Data_Filtered_[1].csv", LastModified: time.Time(2022-10-18T19:39:28Z){wall: 0, ext: 63801718768, loc: *time.Location nil}, Size: 54063851, ContentType: "text/plain; charset=utf-8", Expires: time.Time(0001-01-01T00:00:00Z){wall: 0, ext: 0, loc: *time.Location nil}, Metadata: net/http.Header ["Content-Type": ["text/plain; charset=utf-8"], ], UserMetadata: github.com/minio/minio-go/v7.StringMap [], UserTags: map[string]string [], UserTagCount: 0, Owner: github.com/minio/minio-go/v7.Owner {XMLName: (*"encoding/xml.Name")(0x140004c5530), DisplayName: "", ID: ""}, Grant: []github.com/minio/minio-go/v7.Grant len: 0, cap: 0, nil, StorageClass: "", IsLatest: false, IsDeleteMarker: false, VersionID: "", ReplicationStatus: "", Expiration: time.Time(0001-01-01T00:00:00Z){wall: 0, ext: 0, loc: *time.Location nil}, ExpirationRuleID: "", Restore: *github.com/minio/minio-go/v7.RestoreInfo nil, Err: error nil}`

**Comment by binnie268** [comment]
Hi @klauspost,

I tried DisableMultipart: `info, err := ms.minioClient.PutObject(ctx, bucketName, newFileName, object, fileSize, minio.PutObjectOptions{Progress: progressBarLog, DisableMultipart: true}) 
` 
and it works fine.

- Is there any disadvantage to disable multipart for s3 extracted files on PutObject? Our files can go up to **1 GB**

I tried` io.NopCloser()` and I got this error: `ERROR[2022-10-21T15:52:53-04:00] minio copy from data-uploads to data-sources bucket failed  error="Put \"http://localhost:9000/data-sources/data-source-37013.csv?partNumber=1&uploadId=b52ced23-3e01-430d-ba4d-0c57aeae6f79\": readfrom tcp [::1]:49948->[::1]:9000: http: ContentLength=16777216 with Body length 0" method=copyDataSourceFromDataUploadsToDataSourcesBucketForZip`

This is part of my code:
```
reader, err := ms.minioClient.GetObject(ctx, bucketName, path, opts); 
minioObjectNOPCloser := io.NopCloser(reader);
fileStats, _ := reader.Stat(); info, err := ms.minioClient.PutObject(ctx, bucketName, newFileName, minioObjectNOPCloser, fileStats.Size, minio.PutObjectOptions{Progress: progressBarLog})
```

**Comment by klauspost** [comment]
@binnie268 Could you provide a clean reproducer I can run? Or enable trace `c.TraceOn(os.StdOut)`.

Are you sure you shouldn't just use [transparent compression](https://blog.min.io/transparent-data-compression/)?

**Comment by binnie268** [comment]
Hi @klauspost , this is the trace:
```
INFO[2022-10-25T12:20:56-04:00] starting putting object                      

 0 / 54063851    0.00%---------START-HTTP---------
POST /data-uploads/v_3_0_Issuer_Data_Filtered_%5B1%5D.csv.csv?uploads= HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; arm64) minio-go/v7.0.42
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20221025/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-checksum-algorithm;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Checksum-Algorithm: CRC32C
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20221025T162104Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 285
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Tue, 25 Oct 2022 16:21:04 GMT
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 17215C569CA8D502
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
---------START-HTTP---------
GET /data-uploads/test2.zip/v_3_0_Issuer_Data_Filtered_%5B1%5D.csv HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (darwin; arm64) minio-go/v7.0.42
Authorization: AWS4-HMAC-SHA256 Credential=minioadmin/20221025/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-minio-extract, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20221025T162104Z
X-Minio-Extract: true
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 54063851
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: text/plain; charset=utf-8
Date: Tue, 25 Oct 2022 16:21:04 GMT
Last-Modified: Tue, 18 Oct 2022 19:39:28 GMT
No-Gzip-Compression: true
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
Vary: Accept-Encoding
X-Amz-Request-Id: 17215C569D63BFC2
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
---------END-HTTP---------
```

This is the code that should work:
```
func main() {
	s3Client, err := minio.New("minio-server-address:9000", &minio.Options{
		Creds: credentials.NewStaticV4("access-key", "secret-key", ""),
	})
	if err != nil {
		log.Fatalln(err)
	}

var opts minio.GetObjectOptions

	// Add extract header to request:
	opts.Set("x-minio-extract", "true")

	// Download API.md from the archive
	rd, err := r.minioClient.GetObject(r.ctx, "data-uploads", "test2.zip/v_3_0_Issuer_Data_Filtered_[1].csv", opts)
	fileStat, err := rd.Stat()
	minioObjectNOPCloser := io.NopCloser(rd)
	progress := pb.New64(fileStat.Size)
	defer progress.FinishPrint("fileuploaded")
	progress.Start()
	info, err := r.minioClient.PutObject(r.ctx, bucketName, "v_3_0_Issuer_Data_Filtered_[1].csv", minioObjectNOPCloser, fileStat.Size, minio.PutObjectOptions{Progress: progress})
	if err != nil {
		log.Fatalln(err)
		return nil, err
	}
	log.Info("info on the upload", info)
	if err != nil {
		log.Fatalln(err)
	}

	return rd, nil
}
}
```

**Comment by harshavardhana** [comment]
> Minio bitnami chart version used: bitnami/minio:2022.8.13-debian-11-r0

We do not support bitnami version @binnie268 please use MinIO official containers.

**Comment by klauspost** [comment]
I tried a standalone test using our playground. It seems a bit slow, but I will check if that is just because the playground is limiting speeds:

https://gist.github.com/klauspost/9e14d31d5917435b49bf18ee24c46525

**Comment by klauspost** [comment]
Tried the code above locally. Completes in 377.0467ms (succesfully)

So I still cannot reproduce.
