### ISSUE TITLE
[Question] Strange behavior when PutObject

### ISSUE THREAD

**Issue by haunt98** [minio/minio-go#1722]
After upgrade from v6 to v7, PutObject is not work reliablely.

When use client v6, I use PutObjectWithContext with timeout 30s, I see client make 3 requests, 2 
failed, 1 success.

When use client v7, I use PutObject with timeout 30s, I see client make 3 requests, all failed.

Is there any idea I can debug?

**Comment by klauspost** [comment]
Please post the debug output from add `client.TraceOn(os.Stderr)`.

**Comment by haunt98** [comment]
Looks like the bug is not related with minio-go, there is data race elsewhere in my code.
