### ISSUE TITLE
listObjectsV2Query not url decoding object keys

### ISSUE THREAD

**Issue by PatrikMuniak** [minio/minio-go#1723]
I'm using a s3 compatible storage, not AWS S3 and when I try to list the objects of the bucket I get url encoded keys but those are not getting decoded by the method.
for example, this is what I am getting:
`bWltaXItdGVzdA%3D%3D/R2F0ZWtlZXBlckFsZXJ0cw%3D%3D`

### Expected behavior 
minio should return keys url decoded
the previous string should look like this:
`bWltaXItdGVzdA==/R2F0ZWtlZXBlckFsZXJ0cw==`

### Code:
By my understanding in api-list.go the function listObjectsV2Query https://github.com/minio/minio-go/blob/d6fbd4980ec84fb532ad7b46ee097e007392780b/api-list.go#L171
makes a request by specifying encoding-type to be "url" so it's requesting the response's content to be url encoded, but when
`listBucketResult` gets defined the EncodingType does not get changed and is an empty string. 
This causes decodeS3Name (https://github.com/minio/minio-go/blob/d6fbd4980ec84fb532ad7b46ee097e007392780b/api-list.go#L996 ) to not inescape the keys. 

Waiting for some feedback on the issue, happy to give a go to fix it.

**Comment by harshavardhana** [comment]
> I'm using a s3 compatible storage, not AWS S3 and when I try to list the objects of the bucket I get url encoded keys but those are not getting decoded by the method. for example, this is what I am getting: .

Who is the S3 compatible vendor? Looks like their implementation is buggy.

**Comment by PatrikMuniak** [comment]
@harshavardhana HCP S3. Had a better look and agree with your conclusion
