### ISSUE TITLE
Doc issue with GetObject

### ISSUE THREAD

**Issue by aubonbeurre** [minio/minio-go#1724]
Hi !

I run into a leak when running mino with GetObject: I was using the doc and it does not call defer obj.Close()

I thought it'd be a nice addition in case people run into it as well!

**Comment by harshavardhana** [comment]
If a function returns an io.ReadCloser - by contract it is expected that you close the reader after reading, not closing is your application bug and not understanding the contract presented.

However, we will update the doc to mention closing the reader 39267760ed9bb78c88d17be63fcafcefb767a366
