### ISSUE TITLE
does minio-go sdk support add expect header with 100-continue?

### ISSUE THREAD

**Issue by leowkong** [minio/minio-go#1727]
does minio suppor add expect header with 100-continue? 
 I saw this was merged but can not find in the newest code 
https://github.com/minio/minio-go/pull/335

**Comment by harshavardhana** [comment]
it is not very useful we removed it a long time ago

```
commit fdf3754b90581a92998422eea1493d0774baf2e0
Author: Harshavardhana <harsha@minio.io>
Date:   Wed Apr 5 12:23:35 2017 -0700

    api: Do not need Expect header. (#640)
    
    Expect header is not support and implemented by GCS
    and some S3 endpoints. Remove it as it doesn't add
    much purpose.
```

**Comment by WGH-** [comment]
It might be useful for PUT with condition (e.g. [`If-None-Match: *` :)](https://github.com/minio/minio-go/commit/0b004e328e1e6d2b9d7d1689ea9dd71b3cf0fa74))

**Comment by WGH-** [comment]
> Not needed, Go doesn't allow custom handling of 100-continue.

Custom, yeah, but at least it won't send the request body until the server says "continue".

**Comment by WGH-** [comment]
Though it all probably doesn't matter much in the end, as the server will interrupt the transfer as soon as it determines that there's conflict, so there's, roughly speaking, just one TCP window of wasted data.

Sorry for the noise :)

**Comment by harshavardhana** [comment]
> > Not needed, Go doesn't allow custom handling of 100-continue.
> 
> Custom, yeah, but at least it won't send the request body until the server says "continue".

yeah but its bogus, Go net/http writes "continue" regardless of what the incoming request is.
