### ISSUE TITLE
AWS me-central-1 region is not supported in endpoints

### ISSUE THREAD

**Issue by gaurav34065** [minio/minio-go#1729]
Looks like thanos uses the [minio client](https://github.com/minio/minio-go) library to upload Prometheus data into AWS S3.
Thanos is erroring out saying `me-central-1` region is not supported as it's using minio-go internally. Can we please add support for `me-central-1` region in minio-go.
Issue for thanos : https://github.com/thanos-io/thanos/issues/5904

**Comment by harshavardhana** [comment]
Updated here https://github.com/minio/minio-go/pull/1726 should be available in next release.
