### ISSUE TITLE
Ability to update

### ISSUE THREAD

**Issue by Shokoufehsafa** [minio/minio-go#1733]
No way to update the bucket/object. To rename for example an object we need to copy and delete the object.

**Comment by harshavardhana** [comment]
That is S3 API - no renames allowed @Shokoufehsafa

**Comment by klauspost** [comment]
That is my design. The S3 API does not provide move operations, so even if we "emulate" these it would be with the same operations.

Keeping them separate makes it clearer what should happen in terms of error handling and doesn't trick devs into thinking these are atomic operations.

**Comment by Shokoufehsafa** [comment]
Yes I know - at least this could be on one method where you can copy and delete the object, hmm?

**Comment by harshavardhana** [comment]
> Yes I know - at least this could be on one method where you can copy and delete the object, hmm?

our APIs are an abstraction over S3 API for ease of use, i.e primitives - a move is not a primitive API it is your application logic.
