### ISSUE TITLE
What does GovernanceBypass do?

### ISSUE THREAD

**Issue by chenluo1112** [minio/minio-go#1737]
For example, the PNG file path in minio is test/childtest/abc.png, and only the abc.png file is available in childtest. When I use the RemoveObject method and set GovernanceBypass to true in (minio RemoveObjectOptions{}), does it remove only "abc.png" and leave its path "test/childtest/"? If not, what is the role of GovernanceBypass when it is true or false?

**Comment by klauspost** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-managing.html
