### ISSUE TITLE
undefined: io.NopCloser : Update version to next release on friday

### ISSUE THREAD

**Issue by Dev-vihan** [minio/minio-go#1747]
#17 6.651 # github.com/minio/minio-go/v7/pkg/signer
#17 6.651 /go/pkg/mod/github.com/minio/minio-go/v7@v7.0.46/pkg/signer/request-signature-streaming-unsigned-trailer.go:134:14: undefined: io.NopCloser
#17 6.651 /go/pkg/mod/github.com/minio/minio-go/v7@v7.0.46/pkg/signer/request-signature-streaming.go:282:14: undefined: io.NopCloser
#17 6.651 note: module requires Go 1.17

**Comment by klauspost** [comment]
Upgrade Go.

**Comment by Dev-vihan** [comment]
This error into Go version  1.18

**Comment by klauspost** [comment]
@Dev-vihan It was added in Go 1.16: https://pkg.go.dev/io#NopCloser
