### ISSUE TITLE
ListObjects: How to obtain all object files in the bucket root directory by page.

### ISSUE THREAD

**Issue by imkos** [minio/minio-go#1748]
```
minio.ListObjectOptions{
  WithVersions: true,
  // WithMetadata: true,
  Prefix:     "",
  StartAfter: "",
  UseV1:      true,
  MaxKeys:    20,
  // Recursive: true,
  // Recursive:    false,
}
```

Currently Prefix: "", or Prefix: "/", the order of the result sets of the two queries is different. And the results are not sorted.

2 instances, 8 directories, the ListObjects API is very slow when getting a list of more than 1k object files

**Comment by klauspost** [comment]
This is not a file system. Prefix `/` will list only objects that have `/` as the first character. On MinIO this is not allowed.

See [documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html) on how prefixes and delimiters work.

Listing depends on the speed of the backend.

**Comment by imkos** [comment]
minio-go/v7:    Unable to set delimiter.

**Comment by klauspost** [comment]
The "Recusive" does this for you.

**Comment by imkos** [comment]
I want to list all objects in the root directory of the bucket in pages. I set Prefix: "", but the results are returned randomly, and the order of the returned results is not the same after multiple queries.

Recursive: It is used to list all subdirectory structures. It is not a mark key

**Comment by klauspost** [comment]
Order is fixed.

`StartAfter` allows you to specify an object to start listing after.
