### ISSUE TITLE
[multipartUpload] pass PutObjectOptions when completeMultipartUpload

### ISSUE THREAD

**Issue by renyijiu** [minio/minio-go#1750]
```go
	client.MIClient.TraceOn(os.Stdout)
	_, err = client.MIClient.FPutObject(context.Background(), uri.Bucket, uri.Key, f,
		minio.PutObjectOptions{DisableMultipart: false, UserTags: userTags})
	if err != nil {
		log.Error(err)
		return err
	}
```

I have some code that uses minio multipart upload and passes some userTags, then the server reads the relevant userTags when receive `completeMultipartUpload` request. But when i test [the code](https://github.com/minio/minio-go/blob/a6e4bc895c9637452386222f1227b4e528bd9006/api-put-object-multipart.go#L203-L212) that found no tags data. Then I read the source code and found that the `PutObjectOptions` message was reset on the `completeMultipartUpload` request.

Questions:
1. Why reset PutObjectOptions when send `completeMultipartUpload` request
2. Could add a flag to pass userTags or metadata  when send `completeMultipartUpload` request?

**Comment by harshavardhana** [comment]
You need to fix your server to handle tags in newMultipartUpload()
