### ISSUE TITLE
reademe, quickstart is outdated

### ISSUE THREAD

**Issue by Kuma4K** [minio/minio-go#1751]
"go get" is no longer supported outside a module since go1.18

use "go install" instead.

"go install github.com/minio/minio-go@latest" 
error: package github.com/minio/minio-go is not a main package

"go install github.com/minio/minio-go/v7@latest"
error: package github.com/minio/minio-go/v7 is not a main package

**Comment by klauspost** [comment]
You use `go get` to add it to your module. The readme is fine.

**Comment by harshavardhana** [comment]
This is an SDK you need to depend on it, so you need to go get under your project.

go install is meant for standalone programs like mc or minio
