### ISSUE TITLE
Why does MinIO not support overriding the Response Header value when calling GetObject?

### ISSUE THREAD

**Issue by reedchan7** [minio/minio-go#1755]
MinIO's GetObject Option only supports passing in Request Headers, not response-header parameters to override Response Headers, whereas Amazon S3's documentation indicates that such parameters are supported.

MinIO's GetObject Documentation:

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/49066821/212457769-6a06a318-ffb5-4bb2-bb08-84905cf145dc.png">

Amazon S3 Documentation:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/49066821/212457797-0a96412e-13ba-44de-b0ff-2e049adc338e.png">

Request Syntax:

```
GET /Key+?partNumber=PartNumber&response-cache-control=ResponseCacheControl&response-content-disposition=ResponseContentDisposition&response-content-encoding=ResponseContentEncoding&response-content-language=ResponseContentLanguage&response-content-type=ResponseContentType&response-expires=ResponseExpires&versionId=VersionId HTTP/1.1
```

Now, let's look into the code of MinIO Go SDK, we can find that only the parameters of versionId and PartNumber are supported while building HTTP Request, while other parameters are not supported. 

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/49066821/212457817-70f83746-98f0-4c9e-9a0a-00aba65057a2.png">

What considerations are behind this? When will this feature be supported?

MinIO Go SDK Version: `v7.0.45`

**Comment by klauspost** [comment]
@reedchan7 Seems like we have an [xy problem](https://xyproblem.info/)

If you describe what you are trying to achieve, instead of a solution to an unknown problem it would be a lot easier to evaluate.

response-content-type, response-content-language, response-content-disposition, response-content-encoding does not affect anything, since it would only make sense in a browser. You are receiving data back as a stream, so none of these matter.

If you are concerned about the headers returned, why not just ignore them, instead of manually overriding?

**Comment by reedchan7** [comment]
@klauspost 

We will provide services both on the command-line terminal and the web browser, so even though these Headers may not be effective on the command-line terminal, they are still useful on the browser, including Expires and Content-Disposition, etc.

Moreover, we have connected to several object storage services, such as Aliyun OSS, Tencent Cloud COS, and MinIO, we may extend to Amazon S3 and others. Therefore, we have abstracted the APIs of these services, however, this API behaves differently, hence the confusion above.

However, I don't think this is a big problem now. If we have the requirement, I have forked a copy and implemented the coverage of these response-* headers. Later, if we think these headers are not important anymore, we can remove the related logic and switch back to your official implementation.

Thank you for your reply and assistance!

**Comment by harshavardhana** [comment]
Response changes for standard header types are provided via presigned URLs for GetObject this has been supported since day 1.

Use presignedGet API for what you want.

**Comment by klauspost** [comment]
@reedchan7 Makes sense. I don't see any issue with implementing them. They can easily be added without breaking compatibility.

The easiest would probably be to just add them as [supportedHeaders](https://github.com/minio/minio-go/blob/8c4c0768b1b1d29b52457d8e048144a8e2901009/utils.go#L464)

Then `(*GetObjectOptions).Set("Response-Content-Type", "text/plain")` can be used to set it. You are welcome to send a PR that adds those fields.

@harshavardhana This is something else.

**Comment by reedchan7** [comment]
@klauspost I did this by adding a reqParams to GetObjectOptions and then adding some methods, similar to the presignedGet API. Is this okay? [Support passing in a URL query string in GetObjectOptions](https://github.com/reedchan7/minio-go-sdk/commit/028eb52fb81f931fa3ca2ac287291282c95e56e9)

**Comment by harshavardhana** [comment]
> @klauspost I did this by adding a reqParams to GetObjectOptions and then adding some methods, similar to the presignedGet API. Is this okay? [Support passing in a URL query string in GetObjectOptions](https://github.com/reedchan7/minio-go-sdk/commit/028eb52fb81f931fa3ca2ac287291282c95e56e9)

@reedchan7 that is the correct way to do it.

**Comment by reedchan7** [comment]
@klauspost @harshavardhana Do you need a PR?

**Comment by klauspost** [comment]
@reedchan7 Yes, though un-export `ToQueryValues` and remove the pointer change on `func (o *GetObjectOptions) Header()` - that is a potentially breaking change.

**Comment by reedchan7** [comment]
@klauspost @harshavardhana Here is the PR: https://github.com/minio/minio-go/pull/1756

I set `ToQueryValues` to private, and rollback `func (o *GetObjectOptions) Header()` to `func (o GetObjectOptions) Header()`  (Although this would warn: "Struct Client has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation.").

I add a `supportedQueryValues` just like your [supportedHeaders](https://github.com/minio/minio-go/blob/8c4c0768b1b1d29b52457d8e048144a8e2901009/utils.go#L464).
When `SetReqParam` or `AddReqParam` method is invoked, the `isStandardQueryValue` function would be called to check if the key passed in by the user is supported.

And then I wrote an example.

Please review, thanks.
