### ISSUE TITLE
Tests fail with Go1.20 (decode time in RFC3339 format)

### ISSUE THREAD

**Issue by zhsj** [minio/minio-go#1759]
```
zsj@debian:/tmp/minio-go/pkg/credentials$ go test -run TestIAMIsExpired
/latest/api/token
PUT
/latest/meta-data/iam/security-credentials/
GET
/latest/meta-data/iam/security-credentials/RoleName
GET
--- FAIL: TestIAMIsExpired (0.00s)
    iam_aws_test.go:261: credentials.ec2RoleCredRespBody.LastUpdated: unmarshalerDecoder: parsing time "2009-11-23T0:00:00Z" as "2006-01-02T15:04:05Z07:00": cannot parse "0" as "15", error found in #10 byte of ...|T0:00:00Z"
        }|..., bigger context ...|1:51:37Z",
          "LastUpdated" : "2009-11-23T0:00:00Z"
        }|...
FAIL
exit status 1
FAIL    github.com/minio/minio-go/v7/pkg/credentials    0.006s
```

I find these are decoded by github.com/json-iterator/go, which causes this error. But I also find this project uses std encoding/json as well. Maybe change to std library for comparability?

**Comment by klauspost** [comment]
Unless this is documented as breaking, it seems more like this is a problem with Go 1.20 than anything else.

Are you using RC3?

**Comment by klauspost** [comment]
I can confirm this happens on RC3. I will see if I can make a reproducer and report it upstream. Go should not break on upgrades like this.

**Comment by klauspost** [comment]
Appears it is intentional breaking change: https://github.com/golang/go/issues/57897

**Comment by zhsj** [comment]
I see it's reverted in go1.20 release branch.
