### ISSUE TITLE
mcli fails on CEPH S3 versioned APIs - 

### ISSUE THREAD

**Issue by jocutajar** [minio/minio-go#1760]
Hi team,

I'm running mcli against CEPH/S3 API and while the simple commands work fine, the more advanced ones fail with the same error: unrecognized option:Tenant. 

`mc du --versions alias/mybucket`
> mc: <ERROR> Failed to find disk usage of `alias/mybucket` recursively. unrecognized option:Tenant

It works fine without `--versions`. Same for `rm`

`mc ls --rewind 1d alias/mybucket`
> mc: <ERROR> Unable to list folder. unrecognized option:Tenant

Again, it works fine without `--rewind 1d`

I understand that CEPH/S3 is not explicitly supported. It would be nice though to have one tool to rule them all and fixing this looks like a tiny change.

A colleague of mine identified [the line responsible for the printout](https://github.com/minio/minio-go/blob/f54fa21d32c040f6b33ac949b72c58bcea5d0669/api-s3-datatypes.go#L181). We would appreciate if either this specific `Tenant` tagName would be accepted and ignored or if any unknown tagName was treated as a warning. Or something similar. I haven't tested this through, other dragons may crop up.

Thank you.

`mc --version`
> mc version RELEASE.2023-01-11T03-14-16Z (commit-id=14c2e506fa78b53fb6db88bcf87d8f6d3fb6989e)
> Runtime: go1.19.4 linux/amd64
> Copyright (c) 2015-2023 MinIO, Inc.
> License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

`mc du --versions --debug alias/mybucket`
> mc: <DEBUG> GET /mybucket/?location= HTTP/1.1
> Host: alias.example.com
> User-Agent: MinIO (linux; amd64) minio-go/v7.0.46 mc/RELEASE.2023-01-11T03-14-16Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20230119/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
> X-Amz-Date: 20230119T214823Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Content-Length: 134
> Date: Thu, 19 Jan 2023 21:48:23 GMT
> X-Amz-Request-Id: tx000004b1978433de85ffe-0063c9baa7-18f8b93-default
> 
> mc: <DEBUG> TLS Certificate found: 
> mc: <DEBUG>  >> Expires: 2025-02-08 14:53:17 +0000 UTC
> mc: <DEBUG> Response Time:  49.813025ms
> 
> mc: <DEBUG> HEAD /mybucket/ HTTP/1.1
> Host: alias.example.com
> User-Agent: MinIO (linux; amd64) minio-go/v7.0.46 mc/RELEASE.2023-01-11T03-14-16Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20230119/default/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> X-Amz-Date: 20230119T214823Z
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Date: Thu, 19 Jan 2023 21:48:23 GMT
> X-Amz-Request-Id: tx000004ce044837be46df6-0063c9baa7-1871fea-default
> X-Rgw-Bytes-Used: 0
> X-Rgw-Object-Count: 0
> Content-Length: 0
> 
> mc: <DEBUG> TLS Certificate found: 
> mc: <DEBUG>  >> Expires: 2025-02-08 14:53:17 +0000 UTC
> mc: <DEBUG> Response Time:  16.962915ms
> 
> mc: <DEBUG> GET /mybucket/?delimiter=&encoding-type=url&prefix=&versions= HTTP/1.1
> Host: alias.example.com
> User-Agent: MinIO (linux; amd64) minio-go/v7.0.46 mc/RELEASE.2023-01-11T03-14-16Z
> Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20230119/default/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
> X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
> X-Amz-Date: 20230119T214823Z
> Accept-Encoding: gzip
> 
> mc: <DEBUG> HTTP/1.1 200 OK
> Transfer-Encoding: chunked
> Content-Type: application/xml
> Date: Thu, 19 Jan 2023 21:48:23 GMT
> X-Amz-Request-Id: tx00000e155508bcae46417-0063c9baa7-18fb2fb-default
> 
> mc: <DEBUG> TLS Certificate found: 
> mc: <DEBUG>  >> Expires: 2025-02-08 14:53:17 +0000 UTC
> mc: <DEBUG> Response Time:  22.739659ms
> 
> mc: <ERROR> Failed to find disk usage of `alias/mybucket` recursively. unrecognized option:Tenant
>  (1) du-main.go:161 cmd.du(..) Tags: [alias/mybucket]
>  (0) client-s3.go:1869 cmd.(*S3Client).versionedList(..)
>  Release-Tag:RELEASE.2023-01-11T03-14-16Z | Commit:14c2e506fa78 | Host:myhost | OS:linux | Arch:amd64 | Lang:go1.19.4 | Mem:2.6 MB/21 MB | Heap:2.6 MB/7.8 MB
>

**Comment by harshavardhana** [comment]
Ceph is adding extended information here breaking the XML parsing.

They need to fix their response, the API is incompatible here with AWS S3 response.

**Comment by harshavardhana** [comment]
mc is meant to work with AWS S3 and MinIO first - if it does it satisfies it's scope.

We can't keep adding support for other implementations that make unexpected changes. We simply do not have the bandwidth to cater for those vendors.
