### ISSUE TITLE
io.Writer for Upload operations

### ISSUE THREAD

**Issue by safaci2000** [minio/minio-go#1762]
If there's a better medium than creating an issue to ask a question please let me know.

I'm wondering if there is a way to get a io.Writer interface back on an upload operation, or have the ability to stream the writes rather then needing to do a single operation where we already know the full size of the data being written.

Currently, I'm creating a temporary file and then uploading the file to the storage backend.  I was wondering if it would be possible to avoid the temporary file and simply have an open connection to write data till a Close is invoked?  Maybe a WriteCloser would make more sense?  

Would this be possible (aka needs patch/design choice) or is this an limitation of how block storage works?

**Comment by harshavardhana** [comment]
> I'm wondering if there is a way to get a io.Writer interface back on an upload operation, or have the ability to stream the writes rather then needing to do a single operation where we already know the full size of the data being written.

why would you need to do that you can write your content to io.Writer and send us the io.Reader - passing io.Writer to upload is an anti-pattern here.

**Comment by safaci2000** [comment]
I have a process that is essentially doing a merge sort of multiple readers and writing to what ideally would be a S3 compatible block storage.  

so as the data is being processed I'm writing to an io.Writer that points to a local file.  I was looking to see if there was a way to write directly to the cloud, bypassing the local writes. 

If that isn't supported or an anti-pattern that's fine. I was just making sure there weren't some existing patterns that I should be using that I over looked.

**Comment by klauspost** [comment]
@safaci2000 You can use `io.Pipe` to get a `io.Writer` which is you can write data to in another goroutine.

S3 has only limited streaming uploads, and requires to know the size of each uploaded part. However, if you provide `size = -1` and set an appropriate part size minio-go will buffer a part and upload it when filled or EOF. Note that if you exceed 10000 parts (S3 limit) your upload will fail.

**Comment by csg33k** [comment]
Thank you for that. That's very helpful and good to know!
