### ISSUE TITLE
High Memory usage in v7.0.37

### ISSUE THREAD

**Issue by mnhaque** [minio/minio-go#1780]
I was earlier using aws s3 for storage and recently switched to minio.
As soon as i start using putObject operation my cpu and memory increase to 4 GB for 500 mb worth files

**Comment by klauspost** [comment]
There are a million PutObject combinations. Some of them require buffering.

Could you provide a reproducer on how you are using the code, so we can see which parameters you are providing (also, if your source provides seeking, ie all interfaces it supports).

**Comment by klauspost** [comment]
You problem must be elsewhere, or you should upgrade. This is a repro attempt on the latest version:

```
package main

import (
	"bytes"
	"context"
	"fmt"
	"runtime"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	fileData := make([]byte, 1<<10)
	c, err := minio.New("127.0.0.1:9001", &minio.Options{
		Creds: credentials.NewStaticV4("minio", "minio123", ""),
	})
	if err != nil {
		panic(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	i := 0
	for {
		runtime.GC()
		var mem runtime.MemStats
		runtime.ReadMemStats(&mem)
		fmt.Printf("%d: Mem in use: %.02f MiB\n", i, float64(mem.HeapInuse)/(1<<20))
		file := bytes.NewReader(fileData)
		opts := minio.PutObjectOptions{}
		_, err := c.PutObject(ctx, "testbucket", "something", file, file.Size(), opts)
		if err != nil {
			panic(err)
		}
		i++
		// Retry until killed....
	}
}
```

Memory remains stable at ~1.7MB. Here after 6000 iterations:

```
6616: Mem in use: 1.70 MiB
6617: Mem in use: 1.70 MiB
6618: Mem in use: 1.74 MiB
```
