### ISSUE TITLE
ObjectInfo does not return UserTags

### ISSUE THREAD

**Issue by M0rdecay** [minio/minio-go#1787]
For example:
```go
import "github.com/minio/minio-go/v7"

....

	object, err := r.db.GetObject(ctx, bucket, name, minio.GetObjectOptions{})

	stat, err := object.Stat()
	println(len(stat.UserTags)) // <- 0
	println(stat.UserTagCount) // <- 1
```
A similar result in `StatObject`

Object tags in browser:
![image](https://user-images.githubusercontent.com/50422107/223977289-9f67b7b5-bd3f-4c14-a571-8ed44d1a9657.png)

**Comment by harshavardhana** [comment]
UserTags are returned via GetObjectTags @M0rdecay - Tags unfortunately are not returned as part of HEAD/GET call.
