### ISSUE TITLE
Check if object is a directory

### ISSUE THREAD

**Issue by ilyazr** [minio/minio-go#1788]
In Java or Python API there is a special method for checking whether an object is a directory [(link)](https://minio-java.min.io/io/minio/messages/Item.html#isDir--). 

## Simple java example
```java
Iterable<Result<Item>> results = minioClient.listObjects(
                ListObjectsArgs.builder().bucket("my-bucketname").build());
for (Result<Item> res: results) {
    Item obj = res.get();
    boolean isDir = obj.isDir();
}
```
In the Go client I haven't been able to find a similar method for that check.
Is there a different technique for this or could it be done in a different way?
Anyway, it would be great to have a separate method for this purpose.

**Comment by klauspost** [comment]
Just check if the key ends with `/`.

**Comment by ilyazr** [comment]
I have ended up with the exact solution. Thank you!
