### ISSUE TITLE
bug: retainUntilDate still pointing to old format i.e opts.RetainUntilDate.Format(time.RFC3339)

### ISSUE THREAD

**Issue by varunjain0606** [minio/minio-go#1789]
I am getting the following error when trying to use the latest minio client

`"error": "Error response code InvalidArgument."`

The reason I presume is that the server changes have been made https://github.com/minio/minio/pull/15741/files
and the format is pointing to iso8601TimeFormat while the client here has the original format

https://github.com/minio/minio-go/blob/5d09d8f78bdddce66b1581685338b400c5df07ab/api-put-object.go#L159

**Comment by vadmeste** [comment]
@varunjain0606 can you give more about how to reproduce this ?

**Comment by harshavardhana** [comment]
@varunjain0606 please send us a reproducer. Closing this issue.
