### ISSUE TITLE
how to change host  when i use PresignedGetObject?

### ISSUE THREAD

**Issue by dahvlhldle** [minio/minio-go#1790]
the endpointURL is k8s inner host.
in sdk, the host is `host := c.endpointURL.Host` ,how to change it host=localhost:8080
``` 
func (c *Client) makeTargetURL(bucketName, objectName, bucketLocation string, isVirtualHostStyle bool, queryValues url.Values) (*url.URL, error) {
	host := c.endpointURL.Host
```
thanks

**Comment by klauspost** [comment]
Create a client with the host you want.

**Comment by GiedriusS** [comment]
I have a similar question. What to do if, for example, Ceph is configured with:
```
  rgw dns name = a.b.consul
```

But we want to access it from another DC i.e. DNS name becomes `a.b.dc1.consul`. Ceph expects requests signed for Host `a.b.consul` but minio-go signs requests for `a.b.dc1.consul`. It would be tricky to change the Ceph configuration now so we'd like to avoid it. Would you be open to adding the ability to override the host header, @klauspost? Or perhaps there is some other solution?

**Comment by vadmeste** [comment]
PresignedGetObject() can be an offline operation if the cluster region is known in advance. In that case, you can specify any endpoint you want. So, you just need to set Region field in &minio.Options{} when initializing MinIO client.

**Comment by dahvlhldle** [comment]
> PresignedGetObject() can be an offline operation if the cluster region is known in advance. In that case, you can specify any endpoint you want. So, you just need to set Region field in &minio.Options{} when initializing MinIO client.

its work!
