### ISSUE TITLE
PutObject checksums change in 7.0.37 broke Backblaze b2 support

### ISSUE THREAD

**Issue by DarkKirb** [minio/minio-go#1791]
With #1690, the default behavior of PutObject changed in a way that is incompatble with Backblaze’s S3-compatible API.

If PutObject is configured to not send a traditional MD5 checksum (`SendContentMd5`), PutObject will add an `x-amz-checksum-algorithm` header to the request. [In the documentation](https://www.backblaze.com/b2/docs/s3_compatible_api.html), backblaze b2 explicitely lists this header as unsupported, and returns an error if you send this header.

The workaround to this issue is to set SendContentMd5 to true in PutObject options

**Comment by klauspost** [comment]
Ask Backblaze to ignore the header if they don't support it. Backblaze's API is not S3 compatible, and more and more stuff will just break if they don't either ignore it or support it.

It is not our job to work around issues with third part S3 implementations. We target AWS S3 and MinIO. You are welcome to send a PR that adds `DisableChecksum bool` to `PutObjectOptions`. If you can do it cleanly we might consider adding it.

**Comment by harshavardhana** [comment]
> With #1690, the default behavior of PutObject changed in a way that is incompatble with Backblaze’s S3-compatible API.
> 
> If PutObject is configured to not send a traditional MD5 checksum (`SendContentMd5`), PutObject will add an `x-amz-checksum-algorithm` header to the request. [In the documentation](https://www.backblaze.com/b2/docs/s3_compatible_api.html), backblaze b2 explicitely lists this header as unsupported, and returns an error if you send this header.
> 
> The workaround to this issue is to set SendContentMd5 to true in PutObject options

Problem is @DarkKirb most S3 API is a moving train, backblaze needs to catch up. Our SDKs would try to work AWS S3 first.

You should follow up with them and ask for the relevant changes.

**Comment by DarkKirb** [comment]
I’m kindly asking you to reconsider, as this would be the only s3 sdk i have ever interacted with that requires recent additions to the s3 API, publishes a breaking change in a micro release *and* makes it a matter of policy to not support S3 providers that aren’t amazon or minio. Additionally said breaking change broke uploading files with any minio service that, at the time, was running a 16 day or older version of it.

Adding a DisableChecksum option will not change the fact that a user of third party s3 providers will have to patch whatever programs they use to support their s3 storage provider, even if the program only uses a universally supported subset of the s3 API. I believe that a service is still s3 compatible even if they don’t support all of the functionality.

To quickly compare it to another well-known SDK for S3, amazon’‘s official S3 SDKs have no issues uploading files to backblaze b2, or most other providers. Amazon has a financial incentive to not support 3rd party services at all. Meanwhile this project directly claims to support “any Amazon S3 compatible object storage”.

I’d argue S3’s API is very stable. There is absolutely nothing requiring you to mandate features in basic library functionality that has barely been added to your own implementation of the S3 API.

**Comment by klauspost** [comment]
> I’m kindly asking you to reconsider

As I wrote you are welcome to submit a Pull Request with a minimal, tested change. If you can satisfy these criteria we will likely accept it.

**Comment by harshavardhana** [comment]
> I’m kindly asking you to reconsider, as this would be the only s3 sdk i have ever interacted with that requires recent additions to the s3 API, publishes a breaking change in a micro release _and_ makes it a matter of policy to not support S3 providers that aren’t amazon or minio. Additionally said breaking change broke uploading files with any minio service that, at the time, was running a 16 day or older version of it.
> 

We really don't have the bandwidth to test and figure out the nuances of other S3 compatible vendors.

If it works with AWS S3 - then the scope of this library ends there. Our expectation with other vendors is that they follow what is published by AWS S3 and support it. We expect the code to work via S3 spec contract not via adding vendor specific patches or hacks.

I would argue Backblaze is breaking applications here. A sever needs to honor the published standard, and it isn't that this came out yesterday. 

https://aws.amazon.com/blogs/aws/new-additional-checksum-algorithms-for-amazon-s3/ 

This feature has been out for more than a year, we expect S3 compatible vendors to have followed the new changes.

Beyond that bring a new option if needed to optionally turn off these headers, we shall happily accept it.
