### ISSUE TITLE
ListObjects does not parse metadata

### ISSUE THREAD

**Issue by max0ne** [minio/minio-go#1797]
Hi, I noticed 2 issues using metadata:

1. `ListObjects` does not properly parses metadata from XML response. When I set `WithMetadata` to `true`, I'd expect all `UserMetadata` I previously returns. What I see is it returns metadata as a map of empty string
  ```
  map[:]
  ```

2. `StatObject` is a workaround I found to get object metadata, however it also doesn't work perfectly. It parses metadata from response header, which capitalizes keys:
  ```
  map[Foo:bar One:uno dos]
  ```

**Comment by max0ne** [comment]
This gist reproduces it
https://gist.github.com/max0ne/3bd6471f320c7d6cbaa007ba201196bd

I'm using minio-go `v7.0.50`

**Comment by harshavardhana** [comment]
it is fixed in #1795
