### ISSUE TITLE
 Tag restrictions are not compatible with AWS S3

### ISSUE THREAD

**Issue by ChengHaoHappy** [minio/minio-go#1798]
@harshavardhana  I found that in the AWS documentation, tag restrictions that allowed characters across services are: letters (a-z, A-Z), numbers (0-9), and spaces representable in UTF-8, and the following characters: + - = . _ : / @. , but in the tag.go, the restrictions is ' regexp.MustCompile(`^[a-zA-Z0-9-+\-._:/@ ]+$`) '  ,  and does not contain "=". This causes the Tag after Base64 encoding to be invalid.
https://github.com/minio/minio-go/blob/master/pkg/tags/tags.go#L72

**Comment by harshavardhana** [comment]
No they are not, AWS tag restrictions for S3 and EC2 are different.

Read the comments, we tested this thoroughly. Their documentation is confusing does not reflect how the API behaves.
