### ISSUE TITLE
endpoint hope domain+path or through nginx

### ISSUE THREAD

**Issue by foreverrice** [minio/minio-go#1799]
Hello, I want to call PresignedGetObject, but I cannot obtain the file by forwarding it to ip+port through nginx. The signature verification will fail, and the company does not allow opening new domain names.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/33533816/229723095-6501e68f-8a66-4d90-9481-cb110f14ca69.png">
into prodution env
![image](https://user-images.githubusercontent.com/33533816/229724077-f9ae6755-0e2d-4caa-a8d1-148e90bb9407.png)

I hope the domain name and routing can be reached to the presignedURL through nginx, but I haven't found a suitable method

**Comment by harshavardhana** [comment]
You need to generate presigned URL for the nginx endpoint proxying MinIO.

**Comment by foreverrice** [comment]
> You need to generate presigned URL for the nginx endpoint proxying MinIO.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/33533816/229725426-e8cddb4b-41f4-4e89-aa69-f48156ec9985.png">
But it's wrong.I must IP + Port Or DOMAIN

**Comment by foreverrice** [comment]
> You need to generate presigned URL for the nginx endpoint proxying MinIO.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/33533816/229725754-212d2167-5187-47cb-80ff-5f721a24243c.png">
But it's wrong. I only use ip +port or domain.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/33533816/229726052-8f149194-f910-4116-a24a-c453db625e2a.png">

**Comment by klauspost** [comment]
S3 endpoint cannot be on a subpath `/objectbrowser`.

**Comment by Shashankft9** [comment]
@klauspost in our case, minio is running on some domain like "abc.com", but we are proxying the request from "def.com/minio" to "abc.com" and rewriting the uri to "/" (using Istio VirtualService).
Is there some technical reason why such a thing would not be allowed in the client?

**Comment by harshavardhana** [comment]
> [@klauspost](https://github.com/klauspost) in our case, minio is running on some domain like "abc.com", but we are proxying the request from "def.com/minio" to "abc.com" and rewriting the uri to "/" (using Istio VirtualService). Is there some technical reason why such a thing would not be allowed in the client?

Yes signature v4 does not allow that.
