### ISSUE TITLE
How to perform nginx rewrite and forwarding on the mini console?

### ISSUE THREAD

**Issue by foreverrice** [minio/minio-go#1801]
docker run:
<img width="873" alt="image" src="https://user-images.githubusercontent.com/33533816/230263877-3c56d4fc-3530-4b36-8833-49633a1e9037.png">

my nginx conf:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/33533816/230263389-bfc46c0c-7fa1-4a43-8426-2e75b57ab2d1.png">
minio console display:
![image](https://user-images.githubusercontent.com/33533816/230263452-bf24d862-557c-466f-af63-6a660c196201.png)
Company need rewrite to path "/minio"

**Comment by harshavardhana** [comment]
You should enable MINIO_BROWSER_REDIRECT_URL this needs to point to the the console endpoint along with the path resource.
