### ISSUE TITLE
putObjectMultipartNoStream doesn't properly abort upload

### ISSUE THREAD

**Issue by raver119** [minio/minio-go#1806]
Minio client tries to use multipart upload automatically if object is too big.

In `putObjectMultipartNoStream` function used for such upload, multipart upload is created, and object is uploaded in chunks.
In case of failure, this function is supposed to abort the upload and do the cleanup:
```
defer func() {
      if err != nil {
	      c.abortMultipartUpload(ctx, bucketName, objectName, uploadID)
      }
}()
```

But, it's only triggeded if err != nil.  So, if error is happening during actual upload (for any reason), abortMultipartUpload is never invoked:

```
objPart, uerr := c.uploadPart(ctx, p)
if uerr != nil {
	return UploadInfo{}, uerr
}
```

In this case err will be nil, so abort will be skipped, leaving already uploaded parts intact.

**Comment by klauspost** [comment]
Did you check this theory?

AFAICT when doing `return UploadInfo{}, uerr` uerr is assigned to err (which is not shadowed) before the defer call, so `abortMultipartUpload` should be called appropriately.

**Comment by raver119** [comment]
uerr is not assigned to err, I've provided the code snipped in the original post.
Here's link to the code: https://github.com/minio/minio-go/blob/master/api-put-object-streaming.go#L392-L395
As you can see there, uerr is instantiated on line 392 and returned on line 394. It's not assigned to err.

**Comment by klauspost** [comment]
@raver119 See this example: https://go.dev/play/p/zOqbaWjqjI-

When the function returns it assigns `uerr` to `err`, THEN it calls the deferred function.

**Comment by raver119** [comment]
Ahh, you're right. My bad.
