### ISSUE TITLE
Stat does not return part information

### ISSUE THREAD

**Issue by klauspost** [minio/minio-go#1814]
Executing `StatObject` ignores `PartNumber` parameter (and anything added to GetObjectOptions.reqParams).

As far as I can tell this means that `StatObject` cannot be used to get multipart information.

Setting `urlValues := opts.toQueryValues()` in [Client.StatObject](https://github.com/minio/minio-go/blob/c6319beb6b277517add0d9f7d04200cbf7438f90/api-stat.go#L77) fixes this, but seems to risky for regressions.

**Comment by harshavardhana** [comment]
@klauspost it shouldn't be since no one really set PartNumber to get part specific stat() yet.

So it should be fine to start supporting it @klauspost
