### ISSUE TITLE
How to provide io.Reader to PutObjectOptions.Progress?

### ISSUE THREAD

**Issue by licf12138** [minio/minio-go#1818]
I am a newer to minio.I want to fetch the progress in the FPutObject method process.I just know I should provide a io.Reader to minio.PutObjectOptions{Progress: xxxxx}.Would anyone tell me how to operate?An example will be appreciate! Thanks!

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-go/blob/master/examples/s3/putobject-progress.go

**Comment by licf12138** [comment]
Is there any minio example? Not s3 exmple.Thanks!

**Comment by harshavardhana** [comment]
> Is there any minio example? Not s3 exmple.Thanks!

You replace the endpoint with MinIO **sigh**

**Comment by licf12138** [comment]
I got it! It works well.
