### ISSUE TITLE
How to get the real-time progress in CopyObject operation?

### ISSUE THREAD

**Issue by licf12138** [minio/minio-go#1822]
I see the code in apt-copy-object.go:
	// Update the progress properly after successful copy.
	if dst.Progress != nil {
		io.Copy(io.Discard, io.LimitReader(dst.Progress, dst.Size))
	}
Does it update the progress in the end?
My file is always large,I need the real-time progress in copy object operation.
How to get it?
Thangks!

**Comment by harshavardhana** [comment]
CopyObject is server side, there is no progress possible.

**Comment by licf12138** [comment]
Ok.What does the dst.Progress to do ? Is there any use?

**Comment by klauspost** [comment]
@licf12138 No.
