### ISSUE TITLE
Return metadata in GetObject

### ISSUE THREAD

**Issue by pjmuller** [minio/minio-go#1836]
When doing GetObject in s3, the API returns the meta (like UserMetadata) attributes via response headers.
However using minio's  GetObject we can only retrieve the object body and need to do a separate StatObject API call to get the meta.

Is there a way to do this via 1 API call instead of 2?

**Comment by klauspost** [comment]
GetObject returns an Object, which has a [Stat](https://pkg.go.dev/github.com/minio/minio-go#Object.Stat) method. 

If this is called *after* the object has been read from, it will use the data from the GetObject call, otherwise it does a HeadObject.
