### ISSUE TITLE
HealthCheck never returns an error

### ISSUE THREAD

**Issue by Mirco91** [minio/minio-go#1840]
Hello everyone,

when I don't start my minio docker container, the HealthCheck never returns an error, hinting that the service / container might be down.

<img width="1338" alt="Bildschirmfoto 2023-06-15 um 17 23 12" src="https://github.com/minio/minio-go/assets/14868339/587697e1-e72f-4e6e-a670-0bed322573e1">

I'm using the following code to verify if the minio server / s3 server is running.

In my setup.go function:

```
minioClient, err := minio.New("localhost:9000", &minio.Options{
	Creds:  credentials.NewStaticV4(<VALID_ACCESS_KEY_ID>, <VALID_SECRET_ACCESS_KEY>, ""),
	Secure: false
})

// ... some other setup stuff ...

s3HealthCheck := NewS3HealthCheck(minioClient)
err := s3HealthCheck.Health()
if err != nil {
	panic(fmt.Errorf("s3 service encountered an error: %w", err))
}

```

in my check.go

```
type S3HealthCheck struct {
	client *minio.Client
}

func NewS3HealthCheck(minioClient *minio.Client) *S3HealthCheck {
	return &S3HealthCheck{
		client: minioClient,
	}
}

func (check *S3HealthCheck) Health() error {
	cancelFunc, err := check.client.HealthCheck(time.Second * 5)
	defer cancelFunc()
	fmt.Printf("S3 Health Error: %v\n", err)
	fmt.Printf("IS_OFFLINE: %v\n", check.client.IsOffline())
	fmt.Printf("IS_ONLINE: %v\n", check.client.IsOnline())
	if err != nil {
		return fmt.Errorf("s3 unavailable")
	}
	return nil
}
```

<img width="158" alt="Bildschirmfoto 2023-06-15 um 17 26 59" src="https://github.com/minio/minio-go/assets/14868339/e157ca4e-d85f-4d7c-bba3-118694f0d7af">

When I go to localhost:9090 the server is, as I expected, not available.
Since my colleagues were as surprised as I'm we decided to open an issue. Has anyone a clue what I'm missing / doing wrong?

Best regards,
Mirco

**Comment by klauspost** [comment]
@Mirco91 Calling `HealthCheck` merely starts an continuous async health check. It assumes the client to be online until a non-successful health check marks it offline.

This function does does not tell you the initial state. 

I will submit a patch that actually does that, though. Not sure it we want to add that, but it seems the most reasonable to me.

**Comment by Mirco91** [comment]
Thank you very much for your reply, @klauspost 
What would be the best way to use the HealthCheck in this case, to wait for a non-successful health check? 
I thought the health check might return an error when using minio-go functions, they "only" panic but the health check is (seemingly) still successful.

Alternatively is there some kind of "Ping()"-method to get this non-successful health check?

**Comment by klauspost** [comment]
@Mirco91 There is no such S3 function. As you can see we use `GetBucketLocation` for that.
