### ISSUE TITLE
net/http: HTTP/1.x transport connection broken: http: ContentLength=5256549 with Body length 0

### ISSUE THREAD

**Issue by Luxiaodai1111** [minio/minio-go#1845]
on CentOS7，I use the PutObject API to upload my data regularly, about every 10s like this ↓

`client.PutObject(context.Background(), bucket, object, reader, 5217066, PutObjectOptions{DisableContentSha256: true}`

From time to time an error will appear, perhaps once every few days like this ↓

`upload object error:Put \"http://127.0.0.1:19000/000-19534/2/168771633.mp4\": net/http: HTTP/1.x transport connection broken: http: ContentLength=5256549 with Body length 0`

but in my log, the data has been read and sized correctly ↓
> net/http: HTTP/1.x transport connection broken: http: ContentLength=5217066 with Body length 0" len=0 readFinished=true readHistory="[32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 32768 6954 -1]" writeFinished=true

What is the cause of this? Thank you very much for your help.

**Comment by jiuker** [comment]
@Luxiaodai1111 Has the reader already been read?

**Comment by Luxiaodai1111** [comment]
> 

Yes, the array above is the amount of data read by each call to the reader, I calculated it to be exactly the specified size, and the ContentLength is correct, but the body is empty.
If the data is not read, the http ContentLength should not be updated correctly either

**Comment by jiuker** [comment]
> `upload object error:Put \"http://127.0.0.1:19000/000-19534/2/168771633.mp4\": net/http: HTTP/1.x transport connection broken: http: ContentLength=5256549 with Body length 0`

Use file.State() to get size instead. Don't read data before call Api.

**Comment by Luxiaodai1111** [comment]
> > `upload object error:Put \"http://127.0.0.1:19000/000-19534/2/168771633.mp4\": net/http: HTTP/1.x transport connection broken: http: ContentLength=5256549 with Body length 0`
> 
> Use file.State() to get size instead. Don't read data before call Api. @Luxiaodai1111

@jiuker My data is in memory, it's an array, not a specific file

**Comment by jiuker** [comment]
@Luxiaodai1111 I prefer to believe that there is something wrong with the way you handle it that causes no data inside the reader. Maybe you can wrap the reader yourself and see if it just doesn't have data when you read it.

**Comment by harshavardhana** [comment]
@Luxiaodai1111 you have to pass the Reader to PUT - the reader has seeked to EOF it has nothing to do with your buffer. So you need to see if you are making sure to Seek back the buffer properly.

**Comment by Luxiaodai1111** [comment]
> @Luxiaodai1111 you have to pass the Reader to PUT - the reader has seeked to EOF it has nothing to do with your buffer. So you need to see if you are making sure to Seek back the buffer properly.

I really haven't implemented the Seek method

I found out that sdk determines retryable by determining if the Seek method is implemented, I don't implement the Seek method myself, but the hook does it for me and it doesn't report an error, is that a bit obscure here

> func (hr *hookReader) Seek(offset int64, whence int) (n int64, err error) {
	hr.mu.Lock()
	defer hr.mu.Unlock()

	// Verify for source has embedded Seeker, use it.
	sourceSeeker, ok := hr.source.(io.Seeker)
	if ok {
		n, err = sourceSeeker.Seek(offset, whence)
		if err != nil {
			return 0, err
		}
	}

	if hr.hook != nil {
		// Verify if hook has embedded Seeker, use it.
		hookSeeker, ok := hr.hook.(io.Seeker)
		if ok {
			var m int64
			m, err = hookSeeker.Seek(offset, whence)
			if err != nil {
				return 0, err
			}
			if n != m {
				return 0, fmt.Errorf("hook seeker seeked %d bytes, expected source %d bytes", m, n)
			}
		}
	}

	return n, nil
}

**Comment by jiuker** [comment]
@kaankabalak Please provide a streamlined version of your upload code? What version of minio-go are you using?

**Comment by harshavardhana** [comment]
its @Luxiaodai1111 ^^

**Comment by Luxiaodai1111** [comment]
@jiuker sdk version is release 7.0.56

Here is my previous implementation of the reader, which only starts reading when writeFinished is updated to true by other goroutine, and r.buf is a piece of data in memory.

func (r *RaWBuf) Read(p []byte) (n int, err error) {
	if r.readFinished {
		return 0, io.EOF
	}

	if !r.writeFinished {
		return 0, nil
	}

	n = copy(p, r.buf)
	if n < len(r.buf) {
		r.buf = r.buf[n:]
	} else {
		r.buf = nil
		r.readFinished = true
	}
	return n, nil
}


Here is how I call it ↓

`_, err := client.PutObject(context.Background(), bucketname, filename, r, int64(len(r.buf)), minio.PutObjectOptions{DisableContentSha256: true})`

**Comment by jiuker** [comment]
I don't think both return 0,nil is a good idea. @Luxiaodai1111

**Comment by jiuker** [comment]
Easy to reproduce
```go
package main

import (
	"bytes"
	"context"
	"crypto/rand"
	"fmt"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
	"io"
	"log"
)

func main() {
	fmt.Println(upload())
}

type wrapReader struct {
	count int
	r     io.Reader
}

func (w *wrapReader) Read(p []byte) (n int, err error) {
	defer func() {
		w.count++
	}()
	if w.count == 0 {
		return 1, nil
	}
	if w.count == 1 {
		return 0, io.EOF
	}
	return w.r.Read(p)
}

var _ io.Reader = &wrapReader{}

func upload() (string, error) {
	endpoint := "127.0.0.1:9000"
	accessKeyID := "minioadmin"
	secretAccessKey := "minioadmin"
	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:              credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure:             false,
		Transport:          nil,
		Region:             "",
		BucketLookup:       0,
		CustomRegionViaURL: nil,
		TrailingHeaders:    false,
		CustomMD5:          nil,
		CustomSHA256:       nil,
	})
	if err != nil {
		log.Fatalln(err)
	}
	lens := 5217066
	p := make([]byte, lens)
	_, err = rand.Read(p)
	if err != nil {
		log.Fatalln(err)
	}
	r := &wrapReader{r: bytes.NewReader(p)}
	_, err = minioClient.PutObject(
		context.Background(),
		"mytest",
		"sometestUpdate",
		r,
		int64(lens),
		minio.PutObjectOptions{
			DisableContentSha256: true,
		})

	if err != nil {
		log.Println("upload minio err", err)
		return "", err
	}

	return "", nil
}
```
Your code is not thread-safe and returns an incorrect state.

**Comment by klauspost** [comment]
To summarize: 

* The Reader provided *must* provide exact the number of bytes in size before it returns `io.EOF`.
* If the Reader provided supports `io.Seeker` it must support it properly, or expect errors.
* `return 0, nil` is very bad practice, and will either result in seemingly random errors or hot loops. Use proper synchronization.

**Comment by Luxiaodai1111** [comment]
thanks for your help

**Comment by Luxiaodai1111** [comment]
> Easy to reproduce
> 
> ```go
> package main
> 
> import (
> 	"bytes"
> 	"context"
> 	"crypto/rand"
> 	"fmt"
> 	"github.com/minio/minio-go/v7"
> 	"github.com/minio/minio-go/v7/pkg/credentials"
> 	"io"
> 	"log"
> )
> 
> func main() {
> 	fmt.Println(upload())
> }
> 
> type wrapReader struct {
> 	count int
> 	r     io.Reader
> }
> 
> func (w *wrapReader) Read(p []byte) (n int, err error) {
> 	defer func() {
> 		w.count++
> 	}()
> 	if w.count == 1 {
> 		return 0, io.EOF
> 	}
> 	return w.r.Read(p)
> }
> 
> var _ io.Reader = &wrapReader{}
> 
> func upload() (string, error) {
> 	endpoint := "127.0.0.1:9000"
> 	accessKeyID := "minioadmin"
> 	secretAccessKey := "minioadmin"
> 	// Initialize minio client object.
> 	minioClient, err := minio.New(endpoint, &minio.Options{
> 		Creds:              credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
> 		Secure:             false,
> 		Transport:          nil,
> 		Region:             "",
> 		BucketLookup:       0,
> 		CustomRegionViaURL: nil,
> 		TrailingHeaders:    false,
> 		CustomMD5:          nil,
> 		CustomSHA256:       nil,
> 	})
> 	if err != nil {
> 		log.Fatalln(err)
> 	}
> 	lens := 5217066
> 	p := make([]byte, lens)
> 	_, err = rand.Read(p)
> 	if err != nil {
> 		log.Fatalln(err)
> 	}
> 	r := &wrapReader{r: bytes.NewReader(p)}
> 	_, err = minioClient.PutObject(
> 		context.Background(),
> 		"mytest",
> 		"sometestUpdate",
> 		r,
> 		int64(lens),
> 		minio.PutObjectOptions{
> 			DisableContentSha256: true,
> 		})
> 
> 	if err != nil {
> 		log.Println("upload minio err", err)
> 		return "", err
> 	}
> 
> 	return "", nil
> }
> ```
> 
> Your code is not thread-safe and returns an incorrect state. Will show like this
> 
> ```
> API server listening at: 127.0.0.1:54283
> 2023/06/29 22:14:24 upload minio err Put "http://127.0.0.1:9000/mytest/sometestUpdate": net/http: HTTP/1.x transport connection broken: http: ContentLength=5217066 with Body length 0
>  Put "http://127.0.0.1:9000/mytest/sometestUpdate": net/http: HTTP/1.x transport connection broken: http: ContentLength=5217066 with Body length 0
> ```
> 
> @Luxiaodai1111 Usually such random errors occur mostly on thread safety. Something wrong with:
> 
> ```go
> func (r *RaWBuf) Read(p []byte) (n int, err error) {
> ```
> 
> Enjoy ^^

The rest of my code has logic to ensure consistency, so maybe there's a problem here and it's not elegantly written, but I think the problem is that the PUT interface requires a reader to be passed in, but inside the sdk it wraps the hook and calls the seek method, so that the data can't be read again when the sdk retries internally, but the actual reader pass doesn't tell me that I should implement the seek method, so wouldn't it be more appropriate to have a ReadSeeker entry here?

**Comment by jiuker** [comment]
@Luxiaodai1111 You don't implement the method and won't go through that logic. You can debug in and see what is the upper level function that calls you this reader?

**Comment by Luxiaodai1111** [comment]
in putObject function,my reader not implement Seek 

func (c *Client) putObject(ctx context.Context, bucketName, objectName string, reader io.Reader, size int64, opts PutObjectOptions) (info UploadInfo, err error) {
	...

	var readSeeker io.Seeker
	if size > 0 {
		if isReadAt(reader) && !isObject(reader) {
			seeker, ok := reader.(io.Seeker)
			if ok {
				offset, err := seeker.Seek(0, io.SeekCurrent)
				if err != nil {
					return UploadInfo{}, errInvalidArgument(err.Error())
				}
				reader = io.NewSectionReader(reader.(io.ReaderAt), offset, size)
				readSeeker = reader.(io.Seeker)
			}
		}
	}

	var md5Base64 string
	if opts.SendContentMd5 {
		// Calculate md5sum.
		hash := c.md5Hasher()

		if readSeeker != nil {
			if _, err := io.Copy(hash, reader); err != nil {
				return UploadInfo{}, err
			}
			// Seek back to beginning of io.NewSectionReader's offset.
			_, err = readSeeker.Seek(0, io.SeekStart)
			if err != nil {
				return UploadInfo{}, errInvalidArgument(err.Error())
			}
		} else {
			// Create a buffer.
			buf := make([]byte, size)

			length, err := readFull(reader, buf)
			if err != nil && err != io.ErrUnexpectedEOF && err != io.EOF {
				return UploadInfo{}, err
			}

			hash.Write(buf[:length])
			reader = bytes.NewReader(buf[:length])
		}

		md5Base64 = base64.StdEncoding.EncodeToString(hash.Sum(nil))
		hash.Close()
	}

	// Update progress reader appropriately to the latest offset as we
	// read from the source.
	progressReader := newHook(reader, opts.Progress)

	// This function does not calculate sha256 and md5sum for payload.
	// Execute put object.
	return c.putObjectDo(ctx, bucketName, objectName, progressReader, md5Base64, "", size, opts)
}


but the newHook implemented,So in the later judgement he thinks I have the seek method,so seek will return 0,nil:

func (hr *hookReader) Seek(offset int64, whence int) (n int64, err error) {
	hr.mu.Lock()
	defer hr.mu.Unlock()

	// Verify for source has embedded Seeker, use it.
	sourceSeeker, ok := hr.source.(io.Seeker)
	if ok {
		n, err = sourceSeeker.Seek(offset, whence)
		if err != nil {
			return 0, err
		}
	}

	if hr.hook != nil {
		// Verify if hook has embedded Seeker, use it.
		hookSeeker, ok := hr.hook.(io.Seeker)
		if ok {
			var m int64
			m, err = hookSeeker.Seek(offset, whence)
			if err != nil {
				return 0, err
			}
			if n != m {
				return 0, fmt.Errorf("hook seeker seeked %d bytes, expected source %d bytes", m, n)
			}
		}
	}

	return n, nil
}

**Comment by jiuker** [comment]
@Luxiaodai1111 As long as the active return '0,io.EOF' before returning  to read all , this can lead to this problem, which is the most fundamental. So you need to start here and our sdk will not have random problems. You interrupt directly inside your reader's Read function to see the overall logic first.

**Comment by harshavardhana** [comment]
Seeker is not explicitly needed. That is not the issue here. Your reader implementation is wrong that's all.
