### ISSUE TITLE
Core client with options support

### ISSUE THREAD

**Issue by zalegrala** [minio/minio-go#1856]
I'm trying to get a little more clever about the use of the minio client in order to make fewer API calls against S3.

I see that there is a `ListObjectsOptions` available with a `Recursive` option, but this doesn't seem to be available to the `Core` object.  Is there a way that users of the `Core` client can make use of the recursive functionality in the standard client options?

Alternatively, I'm looking for some kind of wildcard or matching, which seems to be supported on the API, but perhaps not in the client.  

Advice here would be appreciated.

**Comment by harshavardhana** [comment]
Core Client is not the contract API that would work in the same manner as the actual abstracted API and can break at any time.

Core.listObjects() you perform lower level calls such as setting delimiter - recursive=true or false is just that adding a delimiter or not.

**Comment by zalegrala** [comment]
Thanks for the response @harshavardhana.  So you are suggesting that if we don't include a delimiter in the call, then we will get recursive results?

**Comment by harshavardhana** [comment]
> Thanks for the response @harshavardhana. So you are suggesting that if we don't include a delimiter in the call, then we will get recursive results?

Yep

**Comment by zalegrala** [comment]
Perfect, this is working well.  Thank you for the information.

**Comment by klauspost** [comment]
Core is with no seatbelt.
