### ISSUE TITLE
Multipart presigned support?

### ISSUE THREAD

**Issue by adamsch1** [minio/minio-go#1859]
Howdy,

Sorry for opening an issue, I did not find a discord or forum anyplace.  I am wondering if Minio client support pre-signed multipart uploads?  

I see that it is possible with, say, boto3 and it appears to be possible with the older version of AWS for go but their recent library does not seem to advertise supporting it.  

I'm currently using Minio but found the need to support this for larger file uploads.

Thank you!

**Comment by harshavardhana** [comment]
You need to use https://pkg.go.dev/github.com/minio/minio-go/v7#Client.Presign to generate any kind of presigned URLs you want. 

https://pkg.go.dev/github.com/minio/minio-go/v7#Client.PresignHeader
