### ISSUE TITLE
Put "http://xxx.s3.dualstack.yyy.amazonaws.com/zzz": readfrom tcp 10.0.187.231:45320->54.231.128.26:80: http: ContentLength=14403 with Body length 0

### ISSUE THREAD

**Issue by e200** [minio/minio-go#1864]
## Expected Behavior
It should upload the files to AWS S3 bucket

## Current Behavior
It generates the following error `Put "http://xxx.s3.dualstack.yyy.amazonaws.com/zzz": readfrom tcp 10.0.187.231:45320->54.231.128.26:80: http: ContentLength=14403 with Body length 0`

## Steps to Reproduce (for bugs)
This is basically my code:

```golang
package main

import (
	"bytes"
	"context"
	"log"
	"sync"

	"github.com/google/uuid"
	"github.com/mazen160/go-random"
	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	awsConfig := &minio.Options{
		Region: "region",
		Creds:  credentials.NewIAM(""),
	}

	minioClient, err := minio.New("s3.amazonaws.com", awsConfig)
	if err != nil {
		log.Fatal(err)
	}

	var wg sync.WaitGroup

	wg.Add(300)

	for i := 0; i < 300; i++ {
		go func() {
			wg.Done()

			content, err := random.Bytes(2 * 1024 * 1024) // 2mb of data
			if err != nil {
				log.Fatal(err)
			}

			buffer := bytes.NewBuffer(content)

			uuid, _ := uuid.NewRandom()

			_, err = minioClient.PutObject(
				context.Background(),
				"bucketName",
				uuid.String(),
				buffer,
				int64(buffer.Len()),
				minio.PutObjectOptions{},
			)
			if err != nil {
				log.Default().Println(err) // Put "http://xxx.s3.dualstack.yyy.amazonaws.com/zzz": readfrom tcp ip_address:45320->ip_address:80: http: ContentLength=14403 with Body length 0
			}
		}()
	}

	wg.Wait()
}
```

## Context
We are uploading many files concurrently to a S3 bucket. Works good locally, the problem occurs only in the staging and production environments

## Your Environment
- github.com/minio/minio-go/v7 v7.0.61
- go 1.20.6
- AWS EKS

**Comment by e200** [comment]
I have updated my code.

**Comment by harshavardhana** [comment]
You also are rewriting the same object 300 times concurrently, is that the expected workload pattern?

**Comment by e200** [comment]
No, it is not the expected workload pattern. As I wrote before, this is just a code to help you reproduce the error and since it needs a setup with a real connection to a S3 bucket, I left some things in the code to be updated to conform to your test environment.

For example, you may want to use real files instead of arbitrary random bytes to upload to S3, you may also change the bucket name which is obviously a placeholder value.

I can't give you a code that is 100% accurate in this case because it works well using localstack locally, but generates the provided error when connecting to S3 in these conditions.

I've updated the code to generate a random uuid for each uploaded file.

**Comment by harshavardhana** [comment]
I ran the code, I can't see any problems locally.

**Comment by e200** [comment]
Did you connect to an AWS S3 bucket?

**Comment by harshavardhana** [comment]
Yes AWS S3 bucket in us-east-1, us-west-1 and eu-central.

I think you have some local networking issues. Uploading 300*2 concurrent connections requires that you have 600MiB worth of bandwidth.

**Comment by e200** [comment]
This is really weird. It runs fine locally, but get this error when running on EKS. It is even worse because the same doesn't happen if I replace this package by AWS SDK and use its equivalent upload method.

Can you share with me your config?

I'm trying to understand what the bandwidth has to do with http redirect issues.

**Comment by harshavardhana** [comment]
Everything is same just the change is static credentials.

**Comment by harshavardhana** [comment]
Are your buckets not in the same region as your region specified in the awsConfig

**Comment by e200** [comment]
Yes, they are. But I will remove the region just to make sure and try again.
