### ISSUE TITLE
Unable to authenticate using node role

### ISSUE THREAD

**Issue by coufalja** [minio/minio-go#1866]
Cause and effect:
During the investigation of https://github.com/grafana/tempo/issues/2743 I was able to track down the problem to specific commits in mino-go https://github.com/minio/minio-go/pull/1626 and https://github.com/minio/minio-go/pull/1682.
Those two together causes us not being able to authenticate, and subsequent Tempo error. 

If that is expected behavior (as it seems according to this Cortex commit https://github.com/cortexproject/cortex/pull/4897) the issue lies in the usage of the library.

**Comment by parshnt** [comment]
@coufalja - was there any progress on the issue?

I believe that the changes introduced in #1682 are causing the issue where if IMDSv2 is disabled, an error is raised. whereas earlier the same error was ignored. this is preventing the use of IMDSv1 as well - as the request to generate role creds is made afterwards.

https://github.com/minio/minio-go/pull/1682/files#diff-8a37275f64c96a9a71f11eb6008f45f1f764384f3ae02f685e3013af1d7f79b5L292

**Comment by harshavardhana** [comment]
I will check on the fix.

**Comment by coufalja** [comment]
I ended up doing the fix in Tempo itself https://github.com/grafana/tempo/pull/2760 as I thought this was an intended behavior.

**Comment by parshnt** [comment]
@harshavardhana - incase of IMDSv2 is disabled. we are seeing an error thrown:
`Put "http://169.254.169.254/latest/api/token": context deadline exceeded`

I believe #1682 might've introduced this issue

**Comment by parshnt** [comment]
@harshavardhana - let me know if I can help with the fix, will create a PR.

**Comment by harshavardhana** [comment]
@parshnt please look at the PR https://github.com/minio/minio-go/pull/1877 and see if this fixes your problem.

**Comment by parshnt** [comment]
@harshavardhana - LGTM
