### ISSUE TITLE
Sponsored issue: MinIO Support Request

### ISSUE THREAD

**Issue by oneincboy** [minio/minio-go#1882]
## Priority Support

- @oneincboy is using  [Mintycode](https://mintycode.io) to fund this issue.
- You can receive ![amount](https://imageupload.io/ib/zwkd2EaAY6YpPsg_1693209112.png) if you provide priority support to @oneincboy. 
- To view the support request and terms go to  [Mintycode](https://mintycode.io/profile?action=CREATOR_SUPPORT_MODAL&requestId=c4034fd3-d17c-4df0-91c7-b67f4f9f1ad3&owner=minio&name=minio-go).
- Thank you in advance for helping.

[![mintycode](https://imageupload.io/ib/LvxMwrPxam1JW9e_1693210482.png)](https://mintycode.io)

**Comment by harshavardhana** [comment]
No solicitations allowed, please report directly here if there is an issue that you wish to report.
