### ISSUE TITLE
ConcurrentStreamParts Unable to close ？

### ISSUE THREAD

**Issue by beck-8** [minio/minio-go#1892]
```go
_, err = dst.PutObject(ctx, dst_bucket, path.Join(dst_prefix, object.Key), reader, object.Size, minio.PutObjectOptions{PartSize: 1 * 1024 * 1024 * 1024, ConcurrentStreamParts: false, NumThreads: 8})
```
I am using the sdk intranet S3 to transfer 32G files to S3. I found that when ConcurrentStreamParts=false, it also takes up a lot of memory. I really don't want to take up memory, and it should be very inefficient to use memory. 
Did I overlook any parameters?

**Comment by klauspost** [comment]
Solution is to not use ConcurrentStreamParts if you are memory sensitive.

**Comment by beck-8** [comment]
I find it `DisableMultipart`
Turn it off and it won't take up any memory at all.And the rate is very fast.
