### ISSUE TITLE
The credentials::IAM implementation doesn't work for multiple regions

### ISSUE THREAD

**Issue by deepakgupta33** [minio/minio-go#1899]
Our services need to interact with AWS in a way that we need to access AWS services across multiple regions from a pod running from a specific region.j

Even though the implementation accepts an `endpoint` param, the same param is used as IAM, STS and ECS role endpoint and if the endpoint isn't provided the IPs are hardcoded.
https://github.com/minio/minio-go/blob/master/pkg/credentials/iam_aws.go#L62

How do I use this implementation to create minio clients that can access services in other region/s?

**Comment by harshavardhana** [comment]
Write your own credential provider https://github.com/minio/minio-go/blob/master/pkg/credentials/credentials.go#L51
