### ISSUE TITLE
The program crashed when creating the bucket and why it is necessary to splice an http:// to the endpoint. Why not first determine the splicing process?

### ISSUE THREAD

**Issue by rs0d** [minio/minio-go#1920]
![1](https://github.com/minio/minio-go/assets/34772657/c2ade8c6-4486-4fa3-b0e4-29eea16164ac)
![2](https://github.com/minio/minio-go/assets/34772657/4b0a592a-9aca-46e0-8d16-58a81673f3ce)
![3](https://github.com/minio/minio-go/assets/34772657/a1b4ea74-d967-415d-ad34-1c54665f077e)
![4](https://github.com/minio/minio-go/assets/34772657/d45a45ae-d68b-4948-b4e8-18e5472bfad2)

**Comment by rs0d** [comment]
When I pass MINIO_ENDPOINT=http://127.0.0.1:9000, it prompts Endpoint url cannot have fully qualified paths. In utils.go lines 110 to 116, the splicing protocol will be spliced. Why not judge the splicing first?

**Comment by rs0d** [comment]
Using minioClient.MakeBucket(ctx, bucketName, minio.MakeBucketOptions{Region: location}) to create a bucket, the application crashes

**Comment by rs0d** [comment]
![333](https://github.com/minio/minio-go/assets/34772657/aeb17125-ebcd-41e9-ac39-17037bf2b096)
c.bucketLocCache.Set   panic: runtime error: invalid memory address or nil pointer dereference                                                                         
        panic: runtime error: invalid memory address or nil pointer dereference

**Comment by klauspost** [comment]
A) Check the errors returned. You are clearly ignoring an error returned from `minio.New`.
B) Endpoints are passed without scheme as it is clear from the [example](https://github.com/minio/minio-go?tab=readme-ov-file#initialize-a-minio-client-object).
