### ISSUE TITLE
How disable chunks encoding?

### ISSUE THREAD

**Issue by kolesnevg** [minio/minio-go#1922]
Hi, we need upload 600Mb (plain text) files to Google Cloud S3, but if then I try download any file - it will contain "chunk-signature=", can we disable it or may othe workaround?

Thank you

**Comment by vilmosnagy** [comment]
@kolesnevg what was the solution in your case? thanks

**Comment by kolesnevg** [comment]
Hi, we use minio client for S3 communication
`
client.FPutObject(ctx, bucket, object_name, file_path, minio.PutObjectOptions{
		DisableContentSha256: true, //THIS OPTION))
})
`

**Comment by vilmosnagy** [comment]
@kolesnevg thanks. we've run into a very similar behavior with argo-workflows, the `DisableContentSha256` could be a solution. See the issue above for details.
