### ISSUE TITLE
RemoveObject() does not work as i expect!

### ISSUE THREAD

**Issue by tahadostifam** [minio/minio-go#1947]
**Hello MinIO!** 👋

I'm currently attempting to remove an object from my bucket, and it appears that the removal was successful. However, I've noticed that the parent directory of my file and the file too is not being removed from the Docker volume named `minio_data`. Is this behavior expected? I suspect that the `RemoveObject(...)` operation only unlinks the file without removing the entire directory and files inside.

Please help me.🙏

![image](https://github.com/minio/minio-go/assets/72092675/3377ac56-da62-4c52-8cbd-3305a16043a1)

**Comment by klauspost** [comment]
The documentation says `RemoveObject removes an object from a bucket`. 

It does not imply that it removes multiple objects based on a prefix as you expect. Use [ListObjects](https://pkg.go.dev/github.com/minio/minio-go/v7#Client.ListObjects) with a prefix and [RemoveObjects](https://pkg.go.dev/github.com/minio/minio-go/v7#Client.RemoveObjects) if that is what you want.

**Comment by tahadostifam** [comment]
But i did not told i want to remove multiple objects.
I said i the object-file is not removing from the desk! 
Can i convey my meaning?

**Comment by klauspost** [comment]
There is no concept of directories/folders in S3. 

There is prefixes - and some applications creates a objects that have a slash at the end. Prefixes disappear when there are no objects with that prefix - and objects that creates fake directories will need to be deleted as all regular objects.

**Comment by tahadostifam** [comment]
I think i found the problem!😃
`Object Locking` option in the `MinIO-Console` was preventing of removing object.

Thank you sir @klauspost.❤️🌺
