### ISSUE TITLE
Retrieve object metadata on GCS

### ISSUE THREAD

**Issue by pierre-b** [minio/minio-go#1951]
Hello guys,

I'm using the "S3 compatibility mode" with a GCS bucket.

Objects are listed but without their `Content-Type` & custom metadata key-value pairs.

Is the golang Minio client able to retrieve this metadata please?

Thanks for your help

**Comment by harshavardhana** [comment]
GCP doesn't provide this information we only provide what we can see as per the S3 spec.

**Comment by pierre-b** [comment]
Thanks for the fast answer! it wasn't in the docs so at least we have a record here for other people!
