### ISSUE TITLE
Some security issues about this project.

### ISSUE THREAD

**Issue by sy2339226** [minio/minio-go#1957]
I am a security researcher and recently used our designed Golang code scanning tool during security audits. During this process, I regretfully discovered some vulnerabilities in your project that may affect security. I've described these issues in the attachment.Looking forward to your reply.
[details.pdf](https://github.com/minio/minio-go/files/15091754/details.pdf)

**Comment by klauspost** [comment]
You clearly took no time to understand the context of what you are reporting. Please stop wasting our time.
