### ISSUE TITLE
PutObject with expires invalid

### ISSUE THREAD

**Issue by zxs943023403** [minio/minio-go#1965]
I putobject to minio with expires,but file did not delete after expires.
client version:github.com/minio/minio-go/v7 v7.0.70,
minio version:RELEASE.2024-05-10T01-41-38Z
my code:
	uploadInfo, err := minioClient.PutObject(ctx, bucketName, objectName, file, fileSize,
		minio.PutObjectOptions{Expires: time.Now().AddDate(0, 0, 1), ContentType: contentType})
which means this file will expire one day later.
is there something wrong with my code?

**Comment by klauspost** [comment]
`Expires` is a [cache header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires). It does not set when the object should expire - that functionality does not exist in S3.
