### ISSUE TITLE
Suggestion : We should default to not using s3 dual stack urls and setting the flag as false by default, considering the inability to use vpc private link in this case

### ISSUE THREAD

**Issue by rohan-changejar** [minio/minio-go#1972]
https://github.com/minio/minio-go/blob/0b004e328e1e6d2b9d7d1689ea9dd71b3cf0fa74/api.go#L168

As referenced in this line of code, I would strongly suggest to default this flag to false, considering vpc private link is not supported for the same. The cost implication on projects that are being used at scale with this change, is immense. 

https://github.com/grafana/tempo/issues/3720
https://github.com/grafana/mimir/pull/8405
<img width="797" alt="image" src="https://github.com/minio/minio-go/assets/83759161/b408ae3c-e0ef-4551-8db0-8c37472d55ac">

This issue causes all s3 traffic to be routed through public internet, increasing data transfer costs immensely.

Happy to contribute and raise a pr to change this default and also open to discussion around the  same.

**Comment by sidharthk98** [comment]
+1, Couldn't agree better.

**Comment by harshavardhana** [comment]
Defaults won't change until we make any breaking changes such as v8. You can disable dual stack as needed when required.

**Comment by pvlkov** [comment]
@harshavardhana Hey, could you please explain how to disable dualstack? From this code I see that setting s3DualStackEnabled = true is hardcoded.

**Comment by sidharthk98** [comment]
@pvlkov You could make use of `enable_dual_stack: <bool>` flag to disable dualstack
https://arc.net/l/quote/jualxkmz

**Comment by rohan-changejar** [comment]
Would also like to know why the decision to set it to true was taken, is this prescribed by any AWS api standards and so on ?

**Comment by klauspost** [comment]
If you can contribute a PR that allows what you want without affecting any existing code, we will consider it. Feel free to reference this issue. Closing this, as it just noise at this point.
