### ISSUE TITLE
how to set or get metadata?

### ISSUE THREAD

**Issue by shengyun1992** [minio/minio-go#1973]

**Comment by klauspost** [comment]
[PutObjectOptions](https://pkg.go.dev/github.com/minio/minio-go/v7#PutObjectOptions).UserMetadata

[StatObject](https://pkg.go.dev/github.com/minio/minio-go/v7#Client.StatObject) -> [ObjectInfo](https://pkg.go.dev/github.com/minio/minio-go/v7#ObjectInfo).UserMetadata (comment is only true for listing).

**Comment by shengyun1992** [comment]
i want to use http put to to it
![Uploading tttttttttt.jpg…]()
