### ISSUE TITLE
Vulnerabilities due to old go version

### ISSUE THREAD

**Issue by imvtsl** [minio/minio-go#1975]
I ran govulncheck on this repository. Result of this command at the end. As we can see, there are potential vulnerabilities in this repository due to the Go standard library.
I see that we use Go version 1.21.0 which was released almost a year ago (2023-08-08). Can we update this repository to use the latest Go version.

**Option 1**: The latest Go version is 1.22.4. We can update to this. This involves upgrading the major version from 21 to 22. 
**Option 2**:  If not upgrading the major version, can we at least upgrade to 1.21.11. This is the latest minor version for 1.21.

I can create a PR with the changes. Please let me know which option we want to proceed with.

>  govulncheck -show verbose ./...
Scanning your code and 164 packages across 10 dependent modules for known vulnerabilities...

Fetching vulnerabilities from the database...

Checking the code against the vulnerabilities...

=== Symbol Results ===

Vulnerability #1: GO-2024-2887
    Unexpected behavior from Is methods for IPv4-mapped IPv6 addresses in
    net/netip
  More info: https://pkg.go.dev/vuln/GO-2024-2887
  Standard library
    Found in: net/netip@go1.21.1
    Fixed in: net/netip@go1.21.11
    Example traces found:
      #1: pkg/credentials/iam_aws.go:445:28: credentials.isLoopback calls net.LookupHost, which eventually calls netip.Addr.IsLoopback
      #2: pkg/credentials/iam_aws.go:445:28: credentials.isLoopback calls net.LookupHost, which eventually calls netip.Addr.IsMulticast

Vulnerability #2: GO-2024-2687
    HTTP/2 CONTINUATION flood in net/http
  More info: https://pkg.go.dev/vuln/GO-2024-2687
  Standard library
    Found in: net/http@go1.21.1
    Fixed in: net/http@go1.21.9
    Example traces found:
      #1: api-get-options.go:86:35: minio.GetObjectOptions.Set calls http.CanonicalHeaderKey
      #2: pkg/credentials/sts_ldap_identity.go:151:26: credentials.LDAPIdentity.Retrieve calls http.Client.Do
      #3: api-put-object-fan-out.go:117:16: minio.Client.PutObjectFanOut calls http.Header.Add
      #4: api-put-object-multipart.go:392:14: minio.Client.completeMultipartUpload calls http.Header.Del
      #5: utils.go:260:24: minio.ToObjectInfo calls http.Header.Get
      #6: api-list.go:716:15: minio.ListObjectsOptions.Set calls http.Header.Set
      #7: pkg/credentials/sts_ldap_identity.go:144:29: credentials.LDAPIdentity.Retrieve calls http.NewRequest
      #8: api.go:796:39: minio.Client.newRequest calls http.NewRequestWithContext
      #9: api.go:493:42: minio.Client.dumpHTTP calls httputil.DumpRequestOut, which eventually calls http.ReadRequest
      #10: api.go:511:41: minio.Client.dumpHTTP calls httputil.DumpResponse, which calls http.Response.Write
      #11: api.go:493:42: minio.Client.dumpHTTP calls httputil.DumpRequestOut, which calls http.Transport.CloseIdleConnections
      #12: api.go:493:42: minio.Client.dumpHTTP calls httputil.DumpRequestOut, which calls http.Transport.RoundTrip
      #13: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.body.Close
      #14: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.body.Read
      #15: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.bodyEOFSignal.Close
      #16: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.bodyEOFSignal.Read
      #17: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls io.LimitedReader.Read, which calls http.bodyLocked.Read
      #18: checksum.go:141:19: minio.ChecksumType.ChecksumReader calls io.Copy, which eventually calls http.bufioFlushWriter.Write
      #19: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.cancelTimerBody.Close
      #20: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.cancelTimerBody.Read
      #21: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.gzipReader.Close
      #22: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.gzipReader.Read
      #23: utils.go:640:33: minio.IsNetworkOrHostDown calls http.http2ConnectionError.Error
      #24: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2ErrCode.String
      #25: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2FrameHeader.String
      #26: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2FrameType.String
      #27: utils.go:640:33: minio.IsNetworkOrHostDown calls http.http2GoAwayError.Error
      #28: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2Setting.String
      #29: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2SettingID.String
      #30: utils.go:640:33: minio.IsNetworkOrHostDown calls http.http2StreamError.Error
      #31: api-putobject-snowball.go:229:13: minio.Client.PutObjectsSnowball calls bufio.Writer.Flush, which calls http.http2chunkWriter.Write
      #32: utils.go:640:33: minio.IsNetworkOrHostDown calls http.http2connError.Error
      #33: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2duplicatePseudoHeaderError.Error
      #34: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.http2gzipReader.Close
      #35: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.http2gzipReader.Read
      #36: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2headerFieldNameError.Error
      #37: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2headerFieldValueError.Error
      #38: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2pseudoHeaderError.Error
      #39: api-putobject-snowball.go:229:13: minio.Client.PutObjectsSnowball calls bufio.Writer.Flush, which calls http.http2stickyErrWriter.Write
      #40: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.http2transportResponseBody.Close
      #41: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.http2transportResponseBody.Read
      #42: api-get-object.go:532:43: minio.Object.Seek calls fmt.Sprintf, which eventually calls http.http2writeData.String
      #43: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.persistConn.Read
      #44: checksum.go:141:19: minio.ChecksumType.ChecksumReader calls io.Copy, which eventually calls http.persistConnWriter.ReadFrom
      #45: api-putobject-snowball.go:229:13: minio.Client.PutObjectsSnowball calls bufio.Writer.Flush, which calls http.persistConnWriter.Write
      #46: pkg/signer/request-signature-streaming.go:402:31: signer.StreamingReader.Close calls http.readTrackingBody.Close
      #47: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.readTrackingBody.Read
      #48: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.readWriteCloserBody.Read
      #49: utils.go:640:33: minio.IsNetworkOrHostDown calls http.transportReadFromServerError.Error

Vulnerability #3: GO-2024-2600
    Incorrect forwarding of sensitive headers and cookies on HTTP redirect in
    net/http
  More info: https://pkg.go.dev/vuln/GO-2024-2600
  Standard library
    Found in: net/http@go1.21.1
    Fixed in: net/http@go1.21.8
    Example traces found:
      #1: pkg/credentials/sts_ldap_identity.go:151:26: credentials.LDAPIdentity.Retrieve calls http.Client.Do, which eventually calls cookiejar.Jar.Cookies
      #2: pkg/credentials/sts_ldap_identity.go:151:26: credentials.LDAPIdentity.Retrieve calls http.Client.Do, which eventually calls cookiejar.Jar.SetCookies
      #3: pkg/credentials/sts_ldap_identity.go:151:26: credentials.LDAPIdentity.Retrieve calls http.Client.Do

Vulnerability #4: GO-2024-2599
    Memory exhaustion in multipart form parsing in net/textproto and net/http
  More info: https://pkg.go.dev/vuln/GO-2024-2599
  Standard library
    Found in: net/textproto@go1.21.1
    Fixed in: net/textproto@go1.21.8
    Example traces found:
      #1: api.go:493:42: minio.Client.dumpHTTP calls httputil.DumpRequestOut, which eventually calls textproto.Reader.ReadLine
      #2: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.body.Read, which eventually calls textproto.Reader.ReadMIMEHeader

Vulnerability #5: GO-2024-2598
    Verify panics on certificates with an unknown public key algorithm in
    crypto/x509
  More info: https://pkg.go.dev/vuln/GO-2024-2598
  Standard library
    Found in: crypto/x509@go1.21.1
    Fixed in: crypto/x509@go1.21.8
    Example traces found:
      #1: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.readWriteCloserBody.Read, which eventually calls x509.Certificate.Verify

Vulnerability #6: GO-2023-2382
    Denial of service via chunk extensions in net/http
  More info: https://pkg.go.dev/vuln/GO-2023-2382
  Standard library
    Found in: net/http/internal@go1.21.1
    Fixed in: net/http/internal@go1.21.5
    Example traces found:
      #1: pkg/signer/request-signature-streaming.go:344:36: signer.StreamingReader.Read calls http.body.Read, which eventually calls internal.chunkedReader.Read

Vulnerability #7: GO-2023-2185
    Insecure parsing of Windows paths with a \??\ prefix in path/filepath
  More info: https://pkg.go.dev/vuln/GO-2023-2185
  Standard library
    Found in: internal/safefilepath@go1.21.1
    Fixed in: internal/safefilepath@go1.21.4
    Platforms: windows
    Example traces found:
      #1: pkg/credentials/file_aws_credentials.go:117:25: credentials.FileAWSCredentials.Retrieve calls exec.Cmd.Output, which eventually calls filepath.Abs
      #2: pkg/credentials/file_aws_credentials.go:117:25: credentials.FileAWSCredentials.Retrieve calls exec.Cmd.Output, which eventually calls filepath.Abs
      #3: pkg/credentials/file_aws_credentials.go:116:22: credentials.FileAWSCredentials.Retrieve calls exec.Command, which calls filepath.Base
      #4: pkg/credentials/file_aws_credentials.go:116:22: credentials.FileAWSCredentials.Retrieve calls exec.Command, which calls filepath.Base
      #5: pkg/credentials/file_aws_credentials.go:84:30: credentials.FileAWSCredentials.Retrieve calls filepath.Join
      #6: pkg/credentials/file_aws_credentials.go:84:30: credentials.FileAWSCredentials.Retrieve calls filepath.Join
      #7: api-get-object-file.go:57:32: minio.Client.FGetObject calls filepath.Split
      #8: api-get-object-file.go:57:32: minio.Client.FGetObject calls filepath.Split
      #9: pkg/credentials/file_aws_credentials.go:117:25: credentials.FileAWSCredentials.Retrieve calls exec.Cmd.Output, which eventually calls filepath.VolumeName
      #10: pkg/credentials/file_aws_credentials.go:117:25: credentials.FileAWSCredentials.Retrieve calls exec.Cmd.Output, which eventually calls filepath.VolumeName

=== Package Results ===

Vulnerability #1: GO-2023-2186
    Incorrect detection of reserved device names on Windows in path/filepath
  More info: https://pkg.go.dev/vuln/GO-2023-2186
  Standard library
    Found in: path/filepath@go1.21.1
    Fixed in: path/filepath@go1.21.4

Vulnerability #2: GO-2023-2102
    HTTP/2 rapid reset can cause excessive work in net/http
  More info: https://pkg.go.dev/vuln/GO-2023-2102
  Standard library
    Found in: net/http@go1.21.1
    Fixed in: net/http@go1.21.3

=== Module Results ===

Vulnerability #1: GO-2024-2888
    Mishandling of corrupt central directory record in archive/zip
  More info: https://pkg.go.dev/vuln/GO-2024-2888
  Standard library
    Found in: stdlib@go1.21.1
    Fixed in: stdlib@go1.21.11

Vulnerability #2: GO-2024-2610
    Errors returned from JSON marshaling may break template escaping in
    html/template
  More info: https://pkg.go.dev/vuln/GO-2024-2610
  Standard library
    Found in: stdlib@go1.21.1
    Fixed in: stdlib@go1.21.8

Vulnerability #3: GO-2024-2609
    Comments in display names are incorrectly handled in net/mail
  More info: https://pkg.go.dev/vuln/GO-2024-2609
  Standard library
    Found in: stdlib@go1.21.1
    Fixed in: stdlib@go1.21.8

Your code is affected by 7 vulnerabilities from the Go standard library.
This scan also found 2 vulnerabilities in packages you import and 3
vulnerabilities in modules you require, but your code doesn't appear to call
these vulnerabilities.

**Comment by marktheunissen** [comment]
`go.mod` is the minimum Go version. See https://go.dev/doc/modules/gomod-ref#go

That means that a user of `minio-go` who compiles it with Go 1.22 (or whatever the latest is) will not be affected by vulnerabilities in the Go standard library of an older version.

**Comment by marktheunissen** [comment]
Also FYI:

```
~/src/minio-go on master ❯ govulncheck -show verbose ./...
Scanning your code and 167 packages across 10 dependent modules for known vulnerabilities...

Fetching vulnerabilities from the database...

Checking the code against the vulnerabilities...

No vulnerabilities found.
```

```
~/src/minio-go on master ❯ go version
go version go1.22.4 darwin/arm64
```

**Comment by imvtsl** [comment]
Makes sense. I am using go 1.21.1
So go.mod only defines the minimum version of Go that's compatible with the repository. Output of govulncheck depends on the version used by the end-user.
Out of curiosity, how do we decide on the minimum Go version for this repository? When do we decide to update it?

**Comment by marktheunissen** [comment]
> Makes sense. I am using go 1.21.1

Yes you need to upgrade :)

> So go.mod only defines the minimum version of Go that's compatible with the repository. Output of govulncheck depends on the version used by the end-user.

Correct

> When do we decide to update it?

When we use a new feature of the Go language that is only available in the latest release, e.g. the stdlib might add a function that we use. Then we need to bump this version number

**Comment by imvtsl** [comment]
Thank you for the clarifications!!
