### ISSUE TITLE
How to modify metadata when uploading files in the following way

### ISSUE THREAD

**Issue by shengyun1992** [minio/minio-go#1976]
url, err := minioClient.PresignedPutObject(context, "test-fei", "developer/1.mp4", time.Second*300)
	if err != nil {
		fmt.Println("PresignedGetObject error:", err)
	}

	//log.Printf("%#v\n", minioClient) // minioClient is now set up

	filePath := "/Users/liyuhang/go/src/test/1.mp4"

	file, err := os.Open(filePath)
	if err != nil {
		fmt.Println("Error opening file:", err)
		return
	}
	defer file.Close()

	data, err := ioutil.ReadAll(file)
	if err != nil {
		fmt.Println("Error reading file:", err)
		return
	}

	req, err := http.NewRequest("PUT", url.String(), bytes.NewBuffer(data))
	if err != nil {
		fmt.Println("Error creating request:", err)
		return
	}

**Comment by klauspost** [comment]
Use [PutObject](https://pkg.go.dev/github.com/minio/minio-go/v7#Client.PutObject).

Read through the docs and see the example. This is basic stuff.
