### ISSUE TITLE
Localhost driver?

### ISSUE THREAD

**Issue by ivanjaros** [minio/minio-go#1979]
I would like to use directory on a local drive as bucket for testing and developing purposes to avoid accruing unnecessary bills from paid storage service and to be able to test locally without internet connection. I do not want to mock the client though or turn it into a swappable interface. Is there any way minio client could be considered for local storage somehow? I could detect the "local" credentials when initiating the client, so it's mostly a matter of telling the client to actually use a local directory and discard remote connection altogether. I also do not want to be running fake s3 server locally to provide s3 api compatibility. I really just want the client to just work with local directory.

**Comment by klauspost** [comment]
Install MinIO or another S3 compatible server locally. There is no other option.
