### ISSUE TITLE
OOM when transfer big size file from minio to minio

### ISSUE THREAD

**Issue by wangs70** [minio/minio-go#1983]
We created a tool which use the minio-go to tranfer files from minio to minio. But we met a issue is that when we transfer the big size file(over 5GB), always failed with OOM. I checked the mem usage of our golang code with pprof. it show as below:

![image](https://github.com/minio/minio-go/assets/148205956/bc61bf89-9efd-4b8d-be29-170c110d6149)

**Comment by klauspost** [comment]
Yes. What part of [the documentation](https://pkg.go.dev/github.com/minio/minio-go/v7#PutObjectOptions) is unclear?

```
	// ConcurrentStreamParts will create NumThreads buffers of PartSize bytes,
	// fill them serially and upload them in parallel.
```

**Comment by wangs70** [comment]
we use it as comments, code as below, and i passed the file size to the function PutObject, but the function “[putObjectMultipartStreamParallel](https://github.com/minio/minio-go/blob/66ba593a19a7a9d1c302ff2b5c05bf17d73a0d1f/api-put-object-streaming.go#L478)” did not use this size and instead used '-1'. I am not sure if it cause the large memory usage. and how to use it. 
```
putopt := minio.PutObjectOptions{
ConcurrentStreamParts: true,
NumThreads: uint(base.S3MinioDownloadConcurrency),
}

// add mime type
mime := CheckMimeType(filename)
if mime != "" {
putopt.ContentType = mime
}

	info, err := client.PutObject(context.Background(), bucket, path, reader, size, putopt)
```

**Comment by wangs70** [comment]
why the function “https://github.com/minio/minio-go/blob/6c2c69f9e8f50b2f65a337ec5e98044e9d558e79/api-put-object-streaming.go#L478” use '-1' as file size not real file size? @klauspost
