### ISSUE TITLE
OpenTelemetry Tracing

### ISSUE THREAD

**Issue by romanchechyotkin** [minio/minio-go#1991]
Feature proposal: add support for OpenTelemetry Tracing in API commands, is it a good idea to implemenet in this lib

**Comment by harshavardhana** [comment]
> Feature proposal: add support for OpenTelemetry Tracing in API commands, is it a good idea to implemenet in this lib

why?

**Comment by romanchechyotkin** [comment]
I needed to implement tracing in system and minio is a part in the system, but since there is not support from the box, i did my own wrapper
i suppose i could help potential users dont think about that

**Comment by klauspost** [comment]
You can provide custom HTTP transports in [Options](https://pkg.go.dev/github.com/minio/minio-go/v7#Options), which seems like a natural place to have tracing.

**Comment by harshavardhana** [comment]
> You can provide custom HTTP transports in [Options](https://pkg.go.dev/github.com/minio/minio-go/v7#Options), which seems like a natural place to have tracing.

This.
