### ISSUE TITLE
Add OpenID setup

### ISSUE THREAD

**Issue by KarlisAG** [minio/minio-go#2004]
I have a question if it would be possible to add capabilities to this SDK that would go outside buckets? We run MinIO in Kubernetes and use the `minio-operator`, but many configurations can't be done in nice automatic fashion, without running the `mc` cli. We started to use crossplane MinIO provider, but it also is limited to the same features, as it uses this SDK. 

It would be great if that provider could be extended to have the same capabilities as running `mc idp openid`, so the controller would take care of it. Is it out of scope of this project to also manage other parts of MinIO tenants? If it is, do you know if there are any other tools or go frameworks that could help here or would we be forced to just wrap the `mc` cli in our go code to invoke the commands as we want inside the Kubernetes cluster?

**Comment by klauspost** [comment]
You are looking for this package: github.com/minio/madmin-go

You can see how OpenID is implemented here: https://github.com/minio/mc/blob/master/cmd/idp-openid-subcommands.go
