### ISSUE TITLE
get file in a .zip object like mc cp --zip

### ISSUE THREAD

**Issue by KirigiriSuzumiya** [minio/minio-go#2011]
Is it possible to extract files from a .zip archive on MinIO like `mc cp --zip` using go sdk?

**Comment by klauspost** [comment]
Mc uses `minio-go` :)

Here are the relevant code sections:

Listing: https://github.com/minio/mc/blob/be874766a7dfcb0f836b6f1ed577a2d49dc42249/cmd/client-s3.go#L1568-L1575
GetObject: https://github.com/minio/mc/blob/be874766a7dfcb0f836b6f1ed577a2d49dc42249/cmd/client-s3.go#L891-L893
Stat: https://github.com/minio/mc/blob/be874766a7dfcb0f836b6f1ed577a2d49dc42249/cmd/client-s3.go#L1657-L1660
