### ISSUE TITLE
Allow redirection with configurable parameter 

### ISSUE THREAD

**Issue by shivakumargowda12** [minio/minio-go#2016]
Its more of a suggestion than any issue/improvement.

Handling HTTP Redirect error is an important feature and widely used.
We clearly understand the intention to remove redirect handling support completely - https://github.com/minio/minio/issues/13918.

Although, it fixed the issue faced during AWS S3 resource access across regions.
Minio Client SDK is being widely used for other Object Store vendors as well, which is not completely dependent on Regions.

My suggestion here is, why cant we make **Redirection Handling** as an optional configurable feature in minio-go (**Setting Disabled by Default**), so that whoever wants to make use of redirection they can continue using that feature without any hassle.

So, the changes needed would be simple
 - Reverting back the changeset - https://github.com/minio/minio-go/pull/1601
 - Add a configuration setting in minio to enable/disable redirect handling. (Disabled by default)
 - Add a check at redirection flow and proceed based on the config parameter

**Comment by harshavardhana** [comment]
Redirection support is not part of S3 API and is out of scope for this SDK. Let me know if this supported in AWS SDK if yes we can bring it back otherwise sorry.
