### ISSUE TITLE
Using an incorrect URL in gin

### ISSUE THREAD

**Issue by wchimeh** [minio/minio-go#2018]
When using the PresignedGetObject method in gin to retrieve a URL, the '/' will change to%! F(MISSING).

    http://127.0.0.1:9000/media/zzz/20241114151657989536.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ZVF8VV2KKWH687VZ41MY%!F(MISSING)20241114%!F(MISSING)us-east-1%!F(MISSING)s3%!F(MISSING)aws4_request&X-Amz-Date=20241114T100523Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=2f38c283e849e5dded166cbc08ba0dc66b5ce7cf666e0a074fa5ca041780ba38

How can I get a correct URL.

**Comment by klauspost** [comment]
Could you post reproducer code?

**Comment by wchimeh** [comment]
> 您可以发布复现器代码吗？
I am using example code.

    func GetImg(c *gin.Context) {
	    endpoint := "127.0.0.1:9000"
	    accessKeyID := "ZVF8VV2KKWH687VZ41MY"
	    secretAccessKey := "Vya75gyOQmAWnNKVkuLvwendrpaJDswK0LinK"
	    useSSL := false
    
	    // Initialize minio client object.
	    minioClient, err := minio.New(endpoint, &minio.Options{
		    Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		    Secure: useSSL,
	    })
	    if err != nil {
		    fmt.Println(err)
	    }
    
	    presignedURL, err := minioClient.PresignedGetObject(context.Background(), "media", "zzz/20241114151657989536.png", time.Second*24*60*60, nil)
	    if err != nil {
		    fmt.Println(err)
	    }
	    fmt.Println("Successfully generated presigned URL", presignedURL)
    
	    c.String(200, "ok")
    
    }



I see that line 218 of the source code "request-siignature-v4. go" file, which reads "credential:=GetCredentia (accessKeyID, location, t, ServiceTypeS3)", concatenates strings with "/", and then line 234, which reads "req. URL. RawQuery=query. Encode()", converts "/" to%! F(MISSING)

**Comment by klauspost** [comment]
```
func TestA(t *testing.T) {
	endpoint := "play.min.io"
	accessKeyID := "Q3AM3UQ867SPQQA43P2F"
	secretAccessKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
	useSSL := true

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		fmt.Println(err)
	}

	presignedURL, err := minioClient.PresignedGetObject(context.Background(), "media", "zzz/20241114151657989536.png", time.Second*24*60*60, nil)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("Successfully generated presigned URL", presignedURL)
}
```

Returns...

```
Successfully generated presigned URL https://play.min.io/media/zzz/20241114151657989536.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20241114%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241114T120858Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=660f9044c2d169476864397335e89ee513a13e008d2cbf19ff43e183c9222057
```

Seems like you are messing up the url in your code.

**Comment by wchimeh** [comment]
> ```
> func TestA(t *testing.T) {
> 	endpoint := "play.min.io"
> 	accessKeyID := "Q3AM3UQ867SPQQA43P2F"
> 	secretAccessKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
> 	useSSL := true
> 
> 	// Initialize minio client object.
> 	minioClient, err := minio.New(endpoint, &minio.Options{
> 		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
> 		Secure: useSSL,
> 	})
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 
> 	presignedURL, err := minioClient.PresignedGetObject(context.Background(), "media", "zzz/20241114151657989536.png", time.Second*24*60*60, nil)
> 	if err != nil {
> 		fmt.Println(err)
> 	}
> 	fmt.Println("Successfully generated presigned URL", presignedURL)
> }
> ```
> 
> 返回...
> 
> ```
> Successfully generated presigned URL https://play.min.io/media/zzz/20241114151657989536.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20241114%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241114T120858Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=660f9044c2d169476864397335e89ee513a13e008d2cbf19ff43e183c9222057
> ```
> 
> 看起来你代码中的 URL 被搞乱了。

Thank you, I have found the reason for my error code. It was caused by using fresh hot loading. I used go run main.go to start the service without any problems
