### ISSUE TITLE
Should 408 be a retryable status code?

### ISSUE THREAD

**Issue by m90** [minio/minio-go#2035]
I'm consuming package `minio-go` in a tool that interfaces with various S3 compatible storages. An [issue was raised](https://github.com/offen/docker-volume-backup/issues/505) about Backblaze R2 responding `408 Request Timeout` from time to time.

[408 is specified](https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.7) as something that is potentially retryable:

> If the client has an outstanding request in transit, the client MAY repeat that request on a new connection

Looking at the current list of retryable status codes in this package, it seems 408 is not considered retryable: https://github.com/minio/minio-go/blob/ffa2ddd6f2b41e522235a3c61fb4ff5910a842d7/retry.go#L113-L123

Is there anything from your end that advises against adding it to the list? Happy to do it in a PR if it makes sense, but wanted to open an issue first before opening the PR.

**Comment by harshavardhana** [comment]
408 is not part of S3 API @m90 so we didn't any retry for those codes.

**Comment by m90** [comment]
It looks as if 520 is something Cloudflare specific as well? Would you prefer not to include 408 still? Happy either way.

**Comment by harshavardhana** [comment]
> It looks as if 520 (which is retried) is something [Cloudflare specific](https://github.com/minio/minio-go/pull/1935) as well? Would you prefer not to include 408 still? Happy either way.

Feel free to add 408 in this list as a PR thanks.
