### ISSUE TITLE
google storage public share url for object ?

### ISSUE THREAD

**Issue by lundin** [minio/minio-go#252]
Hello!
Thanks for minio, it works great. I have one question. When creating a bucket with 
gceClient.MakeBucket("user-1234","public-read")

objects that are being PUT in that still has no default public URL, i have to enable it in the gce console. Any idea how to enable that by default ?

I tried adding, after looking into some google migration docs add a 
r.req.Header.Set("x-goog-acl", "public-read") to the *Request when building the request in the s3 api go source file but to no avail  =(

Thanks!

**Comment by harshavardhana** [comment]
> gceClient.MakeBucket("user-1234","public-read")

It could be that the canned ACL's do not work properly for Google Cloud. Let me verify.

**Comment by lundin** [comment]
Thank you harshavardhana, the gc docs seems to indicate that there is a distinct difference between acl for the bucket and the individual objects which do not inherit the bucket setting if i understand it correctly. But every object is supposed to have ACL settings as well, hence i tried to add the header for every put request as well. But i think one would like to modify the entity to allUsers..however that might be the same as a pre-defined ACL "public-read".

**Comment by harshavardhana** [comment]
> Thank you harshavardhana, the gc docs seems to indicate that there is a distinct difference between acl for the bucket and the individual objects which do not inherit the bucket setting if i understand it correctly

Yes that is the right interpretation the reasoning is that we don't have an exposed API to add Object ACL's. We deliberately avoided this since 'minio' server inherits canned ACL's to all its objects.  It was done to simplify the ACL style. 

We will discuss with in the team to see if we can achieve this.

**Comment by harshavardhana** [comment]
> Thank you harshavardhana, the gc docs seems to indicate that there is a distinct difference between acl for the bucket and the individual objects which do not inherit the bucket setting if i understand it correctly. But every object is supposed to have ACL settings as well, hence i tried to add the header for every put request as well. But i think one would like to modify the entity to allUsers..however that might be the same as a pre-defined ACL "public-read".

Another easier approach is to just use Presigned URLs you can definitely use `mc share download <url>`.

**Comment by harshavardhana** [comment]
We decided to not implement Object ACL's, Presigned URL's serve the same purpose and are better.
