### ISSUE TITLE
amazon keys

### ISSUE THREAD

**Issue by joeblew99** [minio/minio-go#277]
wondering how to use this package, and get the keys from the environment.

**Comment by krishnasrinivas** [comment]
Do you mean like this:
```go
s3Client, err := minio.New("s3.amazonaws.com", os.Getenv("ACCESSKEY"), os.Getenv("SECRETKEY"), false)
```

**Comment by harshavardhana** [comment]
> wondering how to use this package, and get the keys from the environment.

As @krishnasrinivas suggested.
