### ISSUE TITLE
Bug: ReadAt() returns EOF

### ISSUE THREAD

**Issue by fd0** [minio/minio-go#279]
Hi, during development on https://github.com/restic/restic/pull/366 I came across strange behaviour: Calling `ReadAt()` with a small buffer (e.g. 512 byte) and a larger offset (e.g. 32k) in a larger file (e.g. 500KiB) correctly reads the 512 byte, but also returns an EOF error.

According to the spec for `io.ReaderAt` this may only be the case when the last 512 bytes in the resource are read, but here I read 512 from the middle of the file, so the EOF is wrong.

I wrote a small program which demonstrates this on `play.minio.io` https://gist.github.com/7dbbef2dd5e78bbf8723

The output is:

    $ go run s3bug.go
    len = 513767
    n 513767, err <nil>
    size 513767, err <nil>
    ReadAt(len(buf) 512, offset 32000)
    m 512, err EOF

I think this is a bug :)

ping @harshavardhana

**Comment by krishnasrinivas** [comment]
@fd0 thanks this is a bug.

in GetObjectPartial()

```go
				httpReader, _, err := c.getObject(bucketName, objectName, req.Offset, int64(length))

```

We'll get back on this soon.

**Comment by fd0** [comment]
It maybe is a good idea to also add a test for this...

**Comment by harshavardhana** [comment]
> It maybe is a good idea to also add a test for this...

Sure @fd0 we will add, thank you for reporting and taking time to test.
