### ISSUE TITLE
Fix for #279 introduced new bug: Only null-bytes are returned.

### ISSUE THREAD

**Issue by fd0** [minio/minio-go#284]
Hi again,

Unfortunately the fix for #279 introduced an even graver bug: Instead of the content, only zero bytes are returned. I've updated the small program to reproduce that at https://gist.github.com/fd0/7dbbef2dd5e78bbf8723, sample output:

    $ go run s3bug.go

    bucket create error: The requested bucket name is not available.
    len = 228072
    n 228072, err <nil>
    size 228072, err <nil>
    ReadAt(len(buf2) 512, offset 32000)
    m 512, err <nil>
    ([]uint8) (len=512 cap=196072) {
     00000000  bf d2 3a 26 7e 1e 93 7c  36 ed 68 30 85 8e 87 3b  |..:&~..|6.h0...;|
     00000010  85 02 69 a2 0a 5e e6 a3  67 60 ce 1b a1 c1 4c 74  |..i..^..g`....Lt|
     00000020  bb a8 c0 d0 ca 7a 5f b1  56 31 56 1b 8b 44 e7 06  |.....z_.V1V..D..|
     00000030  4e 64 f0 5a 61 21 cd 8d  05 d9 c1 28 81 ec 8b d6  |Nd.Za!.....(....|
     00000040  82 4d 76 e0 9b f3 2f 85  ee e9 0f dc 33 ca d7 e7  |.Mv.../.....3...|
     00000050  5e 03 69 ed 3d 78 42 d9  d7 1b 75 c0 f8 a0 34 ff  |^.i.=xB...u...4.|
     00000060  44 23 69 1d 76 40 b9 1f  67 fd 1a b0 f5 38 6d 59  |D#i.v@..g....8mY|
     00000070  4e 37 2c 5c dd 71 29 3a  45 f2 48 e3 80 c6 97 b0  |N7,\.q):E.H.....|
     00000080  32 86 94 ba 78 8e e8 88  bc 9e e9 3e 27 53 17 4e  |2...x......>'S.N|
     00000090  21 04 c5 bb 7e 2c 1a 94  08 9d 98 2e db 9b c6 be  |!...~,..........|
     000000a0  3a f6 64 74 19 59 b6 c3  72 f4 a5 e0 ba 49 75 bc  |:.dt.Y..r....Iu.|
     000000b0  e8 75 75 48 85 33 7f f6  0f b1 71 cf 2f 04 62 06  |.uuH.3....q./.b.|
     000000c0  20 ba 8b de 5c 2a 1b 5f  d2 45 eb af 96 21 5b f4  | ...\*._.E...![.|
     000000d0  a2 7d 99 50 63 42 dd fc  fe e3 14 6e 50 72 ab 8e  |.}.PcB.....nPr..|
     000000e0  ff 8a 42 2e 03 ee 22 72  a3 5e d2 24 6f 40 55 2f  |..B..."r.^.$o@U/|
     000000f0  c9 38 5a 55 c9 22 9c 3a  99 ac 57 11 e4 bf ad a3  |.8ZU.".:..W.....|
     00000100  e8 cf 17 33 cf 01 7f cb  53 ad a1 e5 eb d1 2c 95  |...3....S.....,.|
     00000110  01 0e 62 17 fb b4 10 f8  1f ee 3a f3 be e4 aa a0  |..b.......:.....|
     00000120  9e 31 55 60 1c 07 b8 9e  8b ed f8 53 40 c4 19 98  |.1U`.......S@...|
     00000130  0a 9f d1 a9 f8 df 8f 91  24 54 e8 af 76 27 f1 c6  |........$T..v'..|
     00000140  dc 95 d9 94 88 f7 a0 b4  53 0a 0e 88 5d 22 b0 c0  |........S...]"..|
     00000150  d7 7f 9d 19 1c 24 ba 18  dd d6 31 b3 69 94 95 5f  |.....$....1.i.._|
     00000160  84 9c b8 2d a5 16 2a ba  de b2 98 16 f4 fc 49 69  |...-..*.......Ii|
     00000170  34 33 6e 2d f8 17 80 65  55 79 34 a7 c0 c6 a6 4d  |43n-...eUy4....M|
     00000180  e5 e9 64 15 0f b2 b3 e6  39 d9 9e e3 a4 28 35 6e  |..d.....9....(5n|
     00000190  14 7f 9b c7 34 bc 9e 9b  31 aa 23 2b 6d da 85 f9  |....4...1.#+m...|
     000001a0  8e e4 6d b4 e9 57 9f 10  9f 49 c2 7a a4 1a ff 5c  |..m..W...I.z...\|
     000001b0  54 bd d8 47 e3 ac 5b 22  00 e3 a7 e8 44 35 7f 07  |T..G..["....D5..|
     000001c0  e8 ff 25 9e 77 3e 3f 71  c9 93 07 31 01 c0 5a 7f  |..%.w>?q...1..Z.|
     000001d0  ab d4 bd e9 97 f9 59 a5  ef 4b c9 9a 3a b6 b4 ac  |......Y..K..:...|
     000001e0  e7 34 59 e9 0d 61 0f c6  63 69 7f 50 55 8f 05 5b  |.4Y..a..ci.PU..[|
     000001f0  da 8b 13 ec 02 1e e3 71  61 72 1d 6d 4e 1d ab 2b  |.......qar.mN..+|
    }
    ([]uint8) (len=512 cap=512) {
     00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000000e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000000f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000100  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000110  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000120  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000150  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000160  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000170  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000180  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     00000190  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000001a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000001b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000001c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000001d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000001e0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
     000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
    }

**Comment by krishnasrinivas** [comment]
bug was:
```go
size, err := io.CopyN(req.Buffer, httpReader, int64(length))
```

[NewBuffer](https://golang.org/pkg/bytes/#NewBuffer):
`
NewBuffer creates and initializes a new Buffer using buf as its initial contents. It is intended to prepare a Buffer to read existing data. It can also be used to size the internal buffer for writing. To do that, buf should have the desired capacity but a length of zero.
`

**Comment by fd0** [comment]
Thanks. Again, it would be a good idea to add a test... ;)

**Comment by harshavardhana** [comment]
> Thanks. Again, it would be a good idea to add a test... ;)

Sure we will, we did add - looks like we didn't have `crand.Reader` data in it :-)

**Comment by harshavardhana** [comment]
Thank you as usual @fd0
