### ISSUE TITLE
Tests fail against current master branch

### ISSUE THREAD

**Issue by arschles** [minio/minio-go#326]
I am on c5884ce9ce3ac73b025d0bc58c4d3d72870edc0b and get this test output:

```console
ENG000656:minio-go aaronschlesinger$ go test -race ./...
--- FAIL: TestMakeBucketErrorV2 (2.05s)
	api_functional_v2_test.go:65: Error: Anonymous access is forbidden for this operation gx5xrbpfiso4r33klhomnhnouvophm
--- FAIL: TestGetObjectClosedTwiceV2 (0.19s)
	api_functional_v2_test.go:112: Error: Anonymous access is forbidden for this operation 34jrkpn5lgynk92oah2svn4qcfe4fn
--- FAIL: TestRemovePartiallyUploadedV2 (0.10s)
	api_functional_v2_test.go:197: Error: Anonymous access is forbidden for this operation bjz5zvcro11h95phaa3msl4f3dwkm6
--- FAIL: TestResumbalePutObjectV2 (0.15s)
	api_functional_v2_test.go:264: Error: Anonymous access is forbidden for this operation k1154pqzhmzhd5x52hlecczh5hs2oi
--- FAIL: TestResumableFPutObjectV2 (0.10s)
	api_functional_v2_test.go:375: Error: Anonymous access is forbidden for this operation 5vs5xutzqcv4gov2ubju9lpixigoil
--- FAIL: TestMakeBucketRegionsV2 (0.11s)
	api_functional_v2_test.go:451: Error: Anonymous access is forbidden for this operation obtghc94f5il2j5qo5umq26nbp4o4q
--- FAIL: TestResumablePutObjectV2 (0.11s)
	api_functional_v2_test.go:503: Error: Anonymous access is forbidden for this operation 5mmab9zziw5x2bpdmsipgsosm1yh2l
--- FAIL: TestGetObjectReadSeekFunctionalV2 (0.11s)
	api_functional_v2_test.go:567: Error: Anonymous access is forbidden for this operation hyef3cusj02lyeyw0etvjsfy19r4i6
--- FAIL: TestGetObjectReadAtFunctionalV2 (0.13s)
	api_functional_v2_test.go:681: Error: Anonymous access is forbidden for this operation m2wozuulnu9l6s92qs6wklxbgfggtr
--- FAIL: TestFunctionalV2 (0.11s)
	api_functional_v2_test.go:822: Error: Anonymous access is forbidden for this operation f0jibm0azy1gcrad5kqf03fc40j6j5
--- FAIL: TestMakeBucketError (0.12s)
	api_functional_v4_test.go:89: Error: Anonymous access is forbidden for this operation 6ov9dlm6rq3unimnkd25ieg9ulr2wy
--- FAIL: TestMakeBucketRegions (0.11s)
	api_functional_v4_test.go:135: Error: Anonymous access is forbidden for this operation yg5je0sr60qv4mfct1osknds4aqk2w
--- FAIL: TestGetObjectClosedTwice (0.11s)
	api_functional_v4_test.go:187: Error: Anonymous access is forbidden for this operation 2zo2q0gkrh1hodjdeifvali6gtacoa
--- FAIL: TestRemovePartiallyUploaded (0.21s)
	api_functional_v4_test.go:272: Error: Anonymous access is forbidden for this operation r0a9gy36pimbhorvgvmcdvdmt5nw9d
--- FAIL: TestResumbalePutObject (0.11s)
	api_functional_v4_test.go:342: Error: Anonymous access is forbidden for this operation 5rlsuspt1n4v05h6ph4pvaxux3lwya
--- FAIL: TestResumableFPutObject (0.11s)
	api_functional_v4_test.go:452: Error: Anonymous access is forbidden for this operation gn4mdbej9ewz5rzs4obavftv1ezomv
--- FAIL: TestResumablePutObject (0.18s)
	api_functional_v4_test.go:532: Error: Anonymous access is forbidden for this operation scv0rmlyub39kjmkdbjgpibvgbpnkm
--- FAIL: TestGetObjectReadSeekFunctional (0.11s)
	api_functional_v4_test.go:596: Error: Anonymous access is forbidden for this operation txkeaboi3bois3rrl6l3wmzr1bw0pa
--- FAIL: TestGetObjectReadAtFunctional (0.10s)
	api_functional_v4_test.go:710: Error: Anonymous access is forbidden for this operation aibg3gdem9tll06fvxyuc5hn6huymh
--- FAIL: TestFunctional (0.11s)
	api_functional_v4_test.go:851: Error: Anonymous access is forbidden for this operation zq2ftf09vmhkqufy0m05zpa5gzir0n
FAIL
FAIL	github.com/minio/minio-go	4.469s
```

**Comment by harshavardhana** [comment]
> ENG000656:minio-go aaronschlesinger$ go test -race ./...
> --- FAIL: TestMakeBucketErrorV2 (2.05s)
>     api_functional_v2_test.go:65: Error: Anonymous access is forbidden for this operation gx5xrbpfiso4r33klhomnhnouvophm
> --- FAIL: TestGetObjectClosedTwiceV2 (0.19s)
>     api_functional_v2_test.go:112: Error: Anonymous access is forbidden for this operation 34jrkpn5lgynk92oah2svn4qcfe4fn
> --- FAIL: TestRemovePartiallyUploadedV2 (0.10s)
>     api_functional_v2_test.go:197: Error: Anonymous access is forbidden for this operation bjz5zvcro11h95phaa3msl4f3dwkm6
> --- FAIL: TestResumbalePutObjectV2 (0.15s)
>     api_functional_v2_test.go:264: Error: Anonymous access is forbidden for this operation k1154pqzhmzhd5x52hlecczh5hs2oi
> --- FAIL: TestResumableFPutObjectV2 (0.10s)
>     api_functional_v2_test.go:375: Error: Anonymous access is forbidden for this operation 5vs5xutzqcv4gov2ubju9lpixigoil
> --- FAIL: TestMakeBucketRegionsV2 (0.11s)
>     api_functional_v2_test.go:451: Error: Anonymous access is forbidden for this operation obtghc94f5il2j5qo5umq26nbp4o4q
> --- FAIL: TestResumablePutObjectV2 (0.11s)
>     api_functional_v2_test.go:503: Error: Anonymous access is forbidden for this operation 5mmab9zziw5x2bpdmsipgsosm1yh2l
> --- FAIL: TestGetObjectReadSeekFunctionalV2 (0.11s)
>     api_functional_v2_test.go:567: Error: Anonymous access is forbidden for this operation hyef3cusj02lyeyw0etvjsfy19r4i6
> --- FAIL: TestGetObjectReadAtFunctionalV2 (0.13s)
>     api_functional_v2_test.go:681: Error: Anonymous access is forbidden for this operation m2wozuulnu9l6s92qs6wklxbgfggtr
> --- FAIL: TestFunctionalV2 (0.11s)
>     api_functional_v2_test.go:822: Error: Anonymous access is forbidden for this operation f0jibm0azy1gcrad5kqf03fc40j6j5
> --- FAIL: TestMakeBucketError (0.12s)
>     api_functional_v4_test.go:89: Error: Anonymous access is forbidden for this operation 6ov9dlm6rq3unimnkd25ieg9ulr2wy
> --- FAIL: TestMakeBucketRegions (0.11s)
>     api_functional_v4_test.go:135: Error: Anonymous access is forbidden for this operation yg5je0sr60qv4mfct1osknds4aqk2w
> --- FAIL: TestGetObjectClosedTwice (0.11s)
>     api_functional_v4_test.go:187: Error: Anonymous access is forbidden for this operation 2zo2q0gkrh1hodjdeifvali6gtacoa
> --- FAIL: TestRemovePartiallyUploaded (0.21s)
>     api_functional_v4_test.go:272: Error: Anonymous access is forbidden for this operation r0a9gy36pimbhorvgvmcdvdmt5nw9d
> --- FAIL: TestResumbalePutObject (0.11s)
>     api_functional_v4_test.go:342: Error: Anonymous access is forbidden for this operation 5rlsuspt1n4v05h6ph4pvaxux3lwya
> --- FAIL: TestResumableFPutObject (0.11s)
>     api_functional_v4_test.go:452: Error: Anonymous access is forbidden for this operation gn4mdbej9ewz5rzs4obavftv1ezomv
> --- FAIL: TestResumablePutObject (0.18s)
>     api_functional_v4_test.go:532: Error: Anonymous access is forbidden for this operation scv0rmlyub39kjmkdbjgpibvgbpnkm
> --- FAIL: TestGetObjectReadSeekFunctional (0.11s)
>     api_functional_v4_test.go:596: Error: Anonymous access is forbidden for this operation txkeaboi3bois3rrl6l3wmzr1bw0pa
> --- FAIL: TestGetObjectReadAtFunctional (0.10s)
>     api_functional_v4_test.go:710: Error: Anonymous access is forbidden for this operation aibg3gdem9tll06fvxyuc5hn6huymh
> --- FAIL: TestFunctional (0.11s)
>     api_functional_v4_test.go:851: Error: Anonymous access is forbidden for this operation zq2ftf09vmhkqufy0m05zpa5gzir0n
> FAIL

Do you have access keys set?  

```
os.Getenv("ACCESS_KEY"),
os.Getenv("SECRET_KEY"),
```

You should run the shorter version to avoid functional tests. "go test -short -race"

**Comment by harshavardhana** [comment]
> Do you have access keys set?
> 
> os.Getenv("ACCESS_KEY"),
> os.Getenv("SECRET_KEY"),

BTW you need S3 access to test functional tests, that is why - "Anonymous access is forbidden for this operation 5vs5xutzqcv4gov2ubju9lpixigoil"

**Comment by harshavardhana** [comment]
> BTW you need S3 access to test functional tests, that is why - "Anonymous access is forbidden for this operation 5vs5xutzqcv4gov2ubju9lpixigoil"

This is expected for full functional tests, as practice for just running unit tests it should be run as "go test -race -short"  - so closing this issue.

**Comment by arschles** [comment]
>BTW you need S3 access to test functional tests, that is why - "Anonymous access is forbidden for this operation 5vs5xutzqcv4gov2ubju9lpixigoil"

Ah, I missed that part. Some documentation in the README indicating that requirement would be very helpful, since that's a significant one.

**Comment by harshavardhana** [comment]
> Ah, I missed that part. Some documentation in the README indicating that requirement would be very helpful, since that's a significant one.

Yeah absolutely will add that.

**Comment by arschles** [comment]
Thanks!
