### ISSUE TITLE
request: Add support of redirected to the correct endpoint

### ISSUE THREAD

**Issue by vshalts** [minio/minio-go#332]
When bucket located in non-Standard US region and policy not allow getBucketLocation then request send us-east-1 and s3 responds with
>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

In such case minio-go may try to retry and redirect all future request to correct endpoint suggested by s3.

https://github.com/restic/restic/issues/388#issuecomment-182318912

**Comment by harshavardhana** [comment]
Thanks for creating this @vshalts . We will see how we can address this.

**Comment by harshavardhana** [comment]
@vshalts - not able to reproduce this with our s3 accounts, does this require an account policy? instead of bucket policy? 

Can you share a sample configuration when you reproduced the issue? . Thanks

**Comment by vshalts** [comment]
I can reproduce it with latest restic right now with such setup:
amazon s3 setup:
```
Bucket: 	work.backup.vshalts.com
Region: 	Frankfurt
```

Policy defined as Inline Policies at the level of user:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::work.backup.vshalts.com",
                "arn:aws:s3:::work.backup.vshalts.com/*"
            ]
        }
    ]
}
```
command:
>restic -r s3://s3.amazonaws.com/work.backup.vshalts.com/restic check --no-lock

will return
>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

If I will change policy to
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:GetObjectVersionAcl",
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::work.backup.vshalts.com",
                "arn:aws:s3:::work.backup.vshalts.com/*"
            ]
        }
    ]
}
```

then it will work fine.

Or another way to reproduce it is to make mistake in bucket name in policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::work2.backup.vshalts.com",
                "arn:aws:s3:::work2.backup.vshalts.com/*"
            ]
        }
    ]
}
```

If need I can probably setup some little demo backup for you (with read-only policy as in first example).

**Comment by harshavardhana** [comment]
Thanks @vshalts - i was able to do it with user policy.
