### ISSUE TITLE
api: replicating the mc commands ? For example the "mirror" command

### ISSUE THREAD

**Issue by joeblew99** [minio/minio-go#362]
I use mc for design time terminal operations and its awesome.

i also need to do the same calls at runtime in my golang projects, and i was wondering if there is any plan to support the exact same commands ? It would make it really nice experience.
The big one for me is the "mirror command".

I know that minio-go needs to have extra commands like policy setting etc etc.

thanks in advance.

**Comment by harshavardhana** [comment]
> I use mc for design time terminal operations and its awesome.
> 
> i also need to do the same calls at runtime in my golang projects, and i was wondering if there is any plan to support the exact same commands ? It would make it really nice experience.
> The big one for me is the "mirror command".
> 
> I know that minio-go needs to have extra commands like policy setting etc etc.
> 
> thanks in advance.

It is good to see this interest from you @joeblew99 - but the concern is really that scope of 'minio-go' ends at Put/Get - what we can do is work on 'mirror' library which can have simple API's to do this. 

Putting this for discussion.

**Comment by joeblew99** [comment]
A library with mirror would be great. thanks.
Do you think it works to also match the other commands in the mc tool ?

**Comment by harshavardhana** [comment]
> A library with mirror would be great. thanks.
> Do you think it works to also match the other commands in the mc tool ?

I don't know all the functionality, since that would be overkill.

**Comment by harshavardhana** [comment]
This is out of scope of minio-go for now, closing.
