### ISSUE TITLE
Resumable upload and upload-url

### ISSUE THREAD

**Issue by remohammadi** [minio/minio-go#374]
To upload a file from an unauthorized device, [this Google tutorial suggests](https://cloud.google.com/solutions/mobile/image-management-mobile-apps-grpc#upload-photos) to start the upload from the server with an empty object, and then pass the upload url to the client.

I like to work on it to make it possible with minio-go. But I'm not sure if it's possible to implement it without changing the api signature. The return values of `PutObject ` function are limited. Do you have any suggestion?

**Comment by harshavardhana** [comment]
> To upload a file from an unauthorized device, this Google tutorial suggests to start the upload from the server with an empty object, and then pass the upload url to the client.
> 
> I like to work on it to make it possible with minio-go. But I'm not sure if it's possible to implement it without changing the api signature. The return values of PutObject function are limited. Do you have any suggestion?

Thanks @remohammadi that is nice to know that you wish to contribute.  But we do not support full fledged Google Cloud API's so it won't be possible to do it in minio-go at the moment.  'minio-go' only speaks S3 and uses Google Cloud's S3 front end to talk to 'Google Cloud Storage'.

**Comment by harshavardhana** [comment]
Closing this issue - out of scope for minio-go.
