### ISSUE TITLE
Change insecure variable to secure

### ISSUE THREAD

**Issue by deekoder** [minio/minio-go#397]
According to our discussions : If language supports default params without asking the user to pass them, use it. Otherwise force user to pass the default.

**Comment by jephir** [comment]
I think you may want to have two methods instead, like `minio.NewSecure` and `minio.NewInsecure`. Boolean parameters make it difficult to understand what the parameter does at a glance.

**Comment by ptrimble** [comment]
I agree. Separate methods makes the most sense to me as a new user.

**Comment by abperiasamy** [comment]
+1

**Comment by GarimaKapoor** [comment]
@deekoder is this issue still valid?

**Comment by harshavardhana** [comment]
> @deekoder is this issue still valid?

This stale closing this.

**Comment by ptrimble** [comment]
For the record, I believe the default was set to 'secure', i.e. HTTPS. You need to override if you want to make it 'insecure' (which makes sense to me). 👍
