### ISSUE TITLE
Example update: presignedgetobject.go 

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-go#418]
We need to add/implement API example in `presignedgetobject.go`  to accept 'curl' command. It currently requires web browser.

**Comment by vadmeste** [comment]
@koolhead17, probably I didn't understand your point but curl is already working fine with the generated presigned get object urls.

**Comment by harshavardhana** [comment]
> @koolhead17, probably I didn't understand your point but curl is already working fine with the generated presigned get object urls.

I think @koolhead17 is asking that we print 'curl' command.

**Comment by harshavardhana** [comment]
Is this still valid @koolhead17 ?

**Comment by harshavardhana** [comment]
Closing .this as not valid. please re-open if its still an issue.
