### ISSUE TITLE
PresignedPutObject with Content-Type

### ISSUE THREAD

**Issue by fenderle** [minio/minio-go#433]
How can I specify a Content-Type header for the presigned PUT URL? Ceph's S3 gateway requires a Content-Type, otherwise it refuses the Upload.

Is it possible at all?

**Comment by fenderle** [comment]
As it turns out AWS V2 presigned url signatures should also include Content-Type headers, amongst others, if the client supplies them. (see [S3 API](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth))

To make this work the `PresignedPutObject()` could be modified to accept user supplied headers which are then included in the hashing. But this breaks the established API.

However I would prefer a mechanism similar to the `NewPostPolicy()/PresignedPostPolicy()` calls. A new function `NewPutPolicy()` could return a struct which could offer `SetContentType()`, `SetContentMd5()` function calls, etc. The policy could then be supplied to `PresignedPutPolicy()`. Maybe the naming is less ideal.

**Comment by harshavardhana** [comment]
@fenderle this should work fine if you use Signature v4 presignedPutObject() and set the Content-Type properly. We are not going to be enhancing this just to Signature V2 as it might just incur wrong API structure. 

Closing this for now.
