### ISSUE TITLE
BucketExists error return is not sufficient

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-go#466]
```
err := minioClient.BucketExists("mybucket")
if err != nil {
    f mt.Println(err)
    return
}
```

There is no way to find out if the bucket did not exist or some other genuine error (like auth error) happened.

i think a better API is:
```
exists, err := minioClient.BucketExists("mybucket")
```

related issue in minio-js https://github.com/minio/minio-js/issues/440

**Comment by harshavardhana** [comment]
> err := minioClient.BucketExists("mybucket")
> if err != nil {
>     f mt.Println(err)
>     return
> }
> There is no way to find out if the bucket did not exist or some other genuine error (like auth error) happened.
> 
> i think a better API is:
> 
> exists, err := minioClient.BucketExists("mybucket")

It was mistake we did long time ago, we can change it - this would break API we need to bump the version.

**Comment by awwalker** [comment]
If this is going to be done will #397 be done at the same time?

**Comment by harshavardhana** [comment]
> If this is going to be done will #397 be done at the same time?

This would be a breaking change so we will have to bump up the version number.
