### ISSUE TITLE
httpReader can be closed when no reference on minio.Object

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-go#467]
To avoid bugs like this: https://github.com/restic/restic/pull/552
we can automatically do httpReader.Close() when minio.Object is garbage collected.

**Comment by harshavardhana** [comment]
> To avoid bugs like this: restic/restic#552
> we can automatically do httpReader.Close() when minio.Object is garbage collected.

What we can do is something like this. 

```
runtime.SetFinalizer(obj, (*obj).close)
```

But it advised not to do these things, applications have to handle this.

**Comment by krishnasrinivas** [comment]
> But it advised not to do these things, applications have to handle this.

That is true, golang guys might decide to deprecate SetFinalizer.

Looks like there is no other way.
