### ISSUE TITLE
getBucketLocation should do 'UNSIGNED-PAYLOAD' for https as well

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-go#473]
minio-go is not doing UNSINGED-PAYLOAD for getbucketlocation

**Comment by vadmeste** [comment]
I tested with `UNSIGNED-PAYLOAD` and it works fine. However before that, I noticed this text, in the link: 
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

The x-amz-content-sha256 header is required for all AWS Signature Version 4 requests. It provides a hash of the request payload. If there is no payload, you *must* provide the hash of an empty string.

Am I missing something?

**Comment by harshavardhana** [comment]
> I tested with UNSIGNED-PAYLOAD and it works fine. However before that, I noticed this text, in the link: 
> http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html
> 
> The x-amz-content-sha256 header is required for all AWS Signature Version 4 requests. It provides a hash of the request payload. If there is no payload, you must provide the hash of an empty string.
> 
> Am I missing something?

yes 'UNSIGNED-PAYLOAD' should be added for https requests only. This is what aws-sdk tools actually do.  Checksum is only calculated for 'insecure' connections. Current code already does this if you do 'mc ls --debug play'  - only missing is `getBucketLocation`
