### ISSUE TITLE
Limit offset pagination

### ISSUE THREAD

**Issue by fdhadzh** [minio/minio-go#498]
How i can do "limit offset pagination" in `ListObjects` or `ListBuckets`?

Now i have code like this:

ListObjects:
```go
if offset <= point && point < limit {
    ...

    point++
} else {
    done <- struct{}{}
}
```

ListBuckets:
```go
if offset <= point && point < limit {
    ...
    point++
} else {
    break
}
```

**Comment by harshavardhana** [comment]
We dont expose such an API but if you are  interested we have an example https://github.com/minio/minio-go/blob/master/examples/s3/listobjects-N.go
