### ISSUE TITLE
Add missing docs for SetAppInfo, SetCustomTransport, TraceOn and TraceOff

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-go#503]

**Comment by koolhead17** [comment]
Also add ``--insecure`` flag for ``mc`` with self signed ``SSL``

**Comment by GarimaKapoor** [comment]
@koolhead17 are you working on this issue?

**Comment by koolhead17** [comment]
Yes, @GarimaKapoor will be working on this

**Comment by krisis** [comment]
@koolhead17 adding --insecure flag for mc should be opened against github.com/minio/mc repo.

**Comment by koolhead17** [comment]
@krisis yep. It is not needed, we have got it added to minio client docs.

@GarimaKapoor I have documented these flags https://github.com/koolhead17/test/blob/master/docs/minio-client-flags.md  AB suggested, individual language maintainers should work on it.
