### ISSUE TITLE
Parse endpoint URL once and save it in *minio.Client

### ISSUE THREAD

**Issue by Garfiled** [minio/minio-go#530]
Hi:
    I am just learning yours project
    I am confused with api-put-bucket.go  MakeBucket() call isValidBucketName() to validate the input arguments and call makeBucketRequest() to make a httprequest

  but come into makeBucketRequest()  again call isValidBucketName()  here is repeat ??
  and in makeBucketRequest()
  targetURL, err := url.Parse(c.endpointURL)   the client is init from the New  here to parse it why ??

**Comment by harshavardhana** [comment]
> but come into makeBucketRequest() again call isValidBucketName() here is repeat ??

This is because each function its own function validation independently. To avoid this we need to keep a validated form of a BucketType. Any changes here are welcome. 

> targetURL, err := url.Parse(c.endpointURL) the client is init from the New here to parse it why ??

This needs to be changed to store parsed URL directly.   This is a trivial change.
