### ISSUE TITLE
Ohio Region (US East 2) 

### ISSUE THREAD

**Issue by MatthewVance** [minio/minio-go#536]
AWS recently launched a new Ohio region as detailed [here](https://aws.amazon.com/blogs/aws/now-open-aws-us-east-ohio-region/). It looks like the following might need to be added to [s3-endpoints.go](https://github.com/minio/minio-go/blob/master/s3-endpoints.go) to support it.

`"us-east-2":      "s3-us-east-2.amazonaws.com",`

**Comment by koolhead17** [comment]
This can be closed via https://github.com/minio/minio-go/pull/544

**Comment by MatthewVance** [comment]
Thanks!
