### ISSUE TITLE
getReaderSize() returns wrong size for non regular files 

### ISSUE THREAD

**Issue by xxorde** [minio/minio-go#552]
The function  `getReaderSize(reader io.Reader) (size int64, err error)` from `api-put-object.go` returns the wrong size for non regular files on linux systems.

The problem can be demonstrated with pipes.
```
cmd := exec.Command("uptime")
stdout, err := cmd.StdoutPipe()
...
n, err := minioClient.PutObject(bucket, filename, stdout, "")
```

A full demonstration can be found here: https://github.com/xxorde/minio-go-bug

An ugly hotfix can be found here: https://github.com/xxorde/minio-go/commit/a0e2ffa2317f292f7c9f02c3b2bf6dc111c71766

Thanks to @harshavardhana and @vadmeste for discussing the problem (https://gitter.im/minio/minio).

**Comment by harshavardhana** [comment]
Fixed by #551
