### ISSUE TITLE
potential resource leak because res.Body is not closed

### ISSUE THREAD

**Issue by Kane-Sendgrid** [minio/minio-go#560]
https://github.com/minio/minio-go/pull/559

**Comment by harshavardhana** [comment]
@Kane-Sendgrid is there an issue still?

**Comment by Kane-Sendgrid** [comment]
@harshavardhana just was checking this line - https://github.com/minio/minio-go/blob/master/api.go#L503, res.Body gets overwritten with NopCloser, what happens to original res.Body?

**Comment by harshavardhana** [comment]
> @harshavardhana just was checking this line - https://github.com/minio/minio-go/blob/master/api.go#L503, res.Body gets overwritten with NopCloser, what happens to original res.Body?

You are right looks like a bug.

**Comment by harshavardhana** [comment]
Fixed by #561
