### ISSUE TITLE
Hard to configure bucket location for Amazon S3 Acceleration

### ISSUE THREAD

**Issue by stanhu** [minio/minio-go#576]
Amazon S3 Acceleration buckets need to have the proper location (e.g. `us-west-1`), but currently the Minio Golang library  tries to figure out based on a lookup from the bucket name. However, in the S3 Acceleration case, the location lookup to `bucketname.s3-accelerate.amazonaws.com` results in a 400 Bad Request, which causes the default to be set to `us-east-1`.

One way to improve this is to allow the client to set a default bucket location for the client. Thoughts?

**Comment by harshavardhana** [comment]
> One way to improve this is to allow the client to set a default bucket location for the client. Thoughts?

We won't be doing that we will find a new way to address this.  For accelerate endpoint the same technique can be used which we did with regular endpoints.

**Comment by stanhu** [comment]
>  For accelerate endpoint the same technique can be used which we did with regular endpoints.

Would you mind clarifying what this technique? I think the current technique attempts to look up the bucket region by asking the endpoint, but this doesn't work with the accelerate endpoint.

**Comment by harshavardhana** [comment]
> Would you mind clarifying what this technique? I think the current technique attempts to look up the bucket region by asking the endpoint, but this doesn't work with the accelerate endpoint.

It won't we fallback to s3.amazonaws.com to get the region and then replace with accelerate endpoint - transparently.
