### ISSUE TITLE
minio on Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by gigenthomas** [minio/minio-go#578]
I am trying to compile from source on Raspberry Pi 3 Model B 

go version go1.6.2 linux/arm

I get the following errors when I run  -go get -u github.com/minio/minio. Any help is greatly appreciated. Thanks !!

src/github.com/minio/minio/vendor/github.com/golang/snappy/decode.go:65: undefined: decode
src/github.com/minio/minio/vendor/github.com/golang/snappy/encode.go:35: undefined: emitLiteral
src/github.com/minio/minio/vendor/github.com/golang/snappy/encode.go:37: undefined: encodeBlock

**Comment by balamurugana** [comment]
We have moved to go v1.7. the latest 1.7.4 is preferred.  Could you please try the version?

**Comment by harshavardhana** [comment]
> src/github.com/minio/minio/vendor/github.com/golang/snappy/decode.go:65: undefined: decode
> src/github.com/minio/minio/vendor/github.com/golang/snappy/encode.go:35: undefined: emitLiteral
> src/github.com/minio/minio/vendor/github.com/golang/snappy/encode.go:37: undefined: encodeBlock

Looks like a server side issue, we don't support go1.6 anymore.  Please upgrade to go1.7.x

**Comment by gigenthomas** [comment]
Upgraded to go 1.7.4 and get the same error. It looks like the Kafka support that was added breaks the build on arm.See attached image

pi@:~ $ go version
go version go1.7.4 linux/arm
pi@:~ $ 
pi@:~ $ go get -u github.com/minio/minio
# github.com/minio/minio/vendor/github.com/golang/snappy
work/src/github.com/minio/minio/vendor/github.com/golang/snappy/decode.go:65: undefined: decode
work/src/github.com/minio/minio/vendor/github.com/golang/snappy/encode.go:35: undefined: emitLiteral
work/src/github.com/minio/minio/vendor/github.com/golang/snappy/encode.go:37: undefined: encodeBlock
pi@:~ $ 


![golang](https://cloud.githubusercontent.com/assets/3069429/21297711/6eeb80d4-c539-11e6-899d-3e552dd4f901.png)

**Comment by balamurugana** [comment]
@gigenthomas could you revert the PR locally at your side and try again?  Unfortunately I don't have `Raspberry Pi 3 Model B` handy.

**Comment by gigenthomas** [comment]
Yes, will do. Might take be a day or 2 to get back to this. Thank you for your prompt response.

**Comment by harshavardhana** [comment]
> Yes, will do. Might take me a day or 2 before I can get back to this. Thank you for your prompt response.

We will fix this, thanks for letting us know.
