### ISSUE TITLE
Support for Amazon Acceleration Endpoint?

### ISSUE THREAD

**Issue by fd0** [minio/minio-go#585]
Hi,

restic received [a support request](https://github.com/restic/restic/issues/707) for Amazon Acceleration Endpoints. Does minio-go support that? What needs to be specified as the `endpoint` string in `New()` to access such a special endpoint?

Here's some background: http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html

Thanks!

**Comment by harshavardhana** [comment]
Its not supported yet @fd0 , requires some changes on how we construct the S3 virtual host style URL. We will work on supporting it soon.

**Comment by fd0** [comment]
Cool, thanks!

**Comment by mtfelian** [comment]
Thanks!

**Comment by harshavardhana** [comment]
ping @fd0 can you validate this - http://docs.minio.io/docs/golang-client-api-reference#SetS3TransferAccelerate
