### ISSUE TITLE
Use GetObject with http.ServeContent without a complete read into a buffer

### ISSUE THREAD

**Issue by hexadecy** [minio/minio-go#593]
### Use Case
Play and seek an audio file

### Current workaround
```
object, _ := cs3.GetObject(bucketName, objectname)
defer object.Close()

fileInfo, _ := object.Stat()
buffer := make([]byte, fileInfo.Size)
object.Read(buffer)
http.ServeContent(rw, req, objectname, time.Time{}, bytes.NewReader(buffer))
```
### Expected to work
```
object, _ := cs3.GetObject(bucketName, objectname)
defer object.Close()
http.ServeContent(rw, req, objectname, time.Time{}, object)
```

### Possible cause
http.ServeContent uses a seek to the end of the content to determine its size.
`size, err := content.Seek(0, io.SeekEnd)`

**Comment by harshavardhana** [comment]
Thanks looks we will fix it @hexadecy

**Comment by vadmeste** [comment]
I'll take this @harshavardhana if you didn't start on it yet.

**Comment by harshavardhana** [comment]
All yours @vadmeste

**Comment by vadmeste** [comment]
This works with Minio server but not with Amazon S3.

```
package main

import (
	"log"
	"net/http"
	"time"

	minio "github.com/minio/minio-go"
)

func main() {
	s3Client, err := minio.New("play.minio.io:9000", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG", true)
	if err != nil {
		log.Fatalln(err)
	}

	reader, err := s3Client.GetObject("vadmeste", "object")
	if err != nil {
		log.Fatalln(err)
	}
	defer reader.Close()

	http.ListenAndServe(":8080", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.ServeContent(w, r, "object", time.Now(), reader)
	}))

}
```

`curl http://localhost:8080/` to test.

**Comment by vadmeste** [comment]
Actually it works also with Amazon S3, but any silly error will show `seeker can't seek`

@hexadecy, what error do you see when you run your code ?

**Comment by hexadecy** [comment]
Tested on Chrome 55 / Windows 10 / AngularJS
I see that the get xhr failed and no total time to play in [videogular](http://www.videogular.com/)
I think it's how the media is played, and it result in an over seek.

Fix for Swift:
https://github.com/ncw/swift/commit/e04bc1faabb161e03bcd91355fe2362effaad37f
Test Unit for that special case:
https://github.com/ncw/swift/commit/cefd25ce9a2fdb37e4deecc743a2c58cafecdf3f

**Comment by vadmeste** [comment]
@hexadecy, I've installed videogular and I connected it with the code above. The latter streams an mp4 file. Now, I can say that it doesn't work all the times. I will investigate further (most probably a bug in the coordination between Seek() and Read() calls)

Also can you search for the exact error in your side, Developer tools in your browser can help you, you can probably see something in Network tab

**Comment by hexadecy** [comment]
Sadly no error code or message:
![image](https://cloud.githubusercontent.com/assets/10960108/21907551/f91cae88-d8dd-11e6-800e-bf3d7e749dee.png)

With Fiddler:
The raw data begin with OggS in the working version and bytes count is 23 407 bytes, the other one have only 22 895 bytes.

**Response:**
HTTP/1.1 206 Partial Content
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Content-Length: 23407
Content-Range: bytes 0-23406/23407
Content-Security-Policy: default-src 'self'; 		script-src 'self' https://www.google-analytics.com https://maps.googleapis.com 'unsafe-eval'; 		style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; 		img-src 'self' data: https://csi.gstatic.com https://www.google-analytics.com https://maps.gstatic.com https://maps.googleapis.com; 		connect-src 'self' data: wss:; 		font-src 'self' https://fonts.gstatic.com; 		child-src 'self' blob:; 		object-src 'self'; 		media-src 'self'; 		report-uri /reportcsp
Content-Type: application/ogg
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubdomains
Vary: Origin
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Date: Thu, 12 Jan 2017 20:41:41 GMT

  {   { a^!硓 { břr { !  1蝃 {   s 9  { A   {^1靣^{ % Bꥤ {   {   {   {   {   j   {   {   {   {   { АU    a6 qǤ  {a ' i   { g

**Comment by vadmeste** [comment]
@hexadecy, can you manage to patch your existing minio-go directory with this one http://paste.ubuntu.com/23792670/ and test again in your environment ?

**Comment by hexadecy** [comment]
LGTM. Seeking is working with 10 seconds and 30 minutes ogg vorbis.

**Comment by harshavardhana** [comment]
Closing this as fixed by #599

**Comment by krishnasrinivas** [comment]
@hexadecy note that you don't have to proxy S3 requests through your web server. The client can directly talk to S3 server using http.

**Comment by 4n70w4** [comment]
v1.30.9 the same problem `seeker can't seek`
