### ISSUE TITLE
Expiry cannot be larger than 7 days

### ISSUE THREAD

**Issue by breml** [minio/minio-go#594]
Our S3 backend does allow much larger expiry periods for shared URLs. Why is this 7 days limit hard coded into this library?

https://github.com/minio/minio-go/blob/master/utils.go#L143-L145

**Comment by harshavardhana** [comment]
@breml Expiry of 7days is an S3 API limit - we are following S3 standards http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html.

**Comment by harshavardhana** [comment]
Closing as answered.
