### ISSUE TITLE
README: Link to godoc for minio-go

### ISSUE THREAD

**Issue by mcandre** [minio/minio-go#596]
Please make it easier for users to find the ordinary Go docs for the minio-go package, such as by dropping a link to https://godoc.org/github.com/minio/minio-go in the README.

**Comment by harshavardhana** [comment]
> Please make it easier for users to find the ordinary Go docs for the minio-go package, such as by dropping a link to https://godoc.org/github.com/minio/minio-go in the README.

We have them documented here with examples http://docs.minio.io/docs/python-client-api-reference .
