### ISSUE TITLE
Clarify: Is a minio Client thread-safe?

### ISSUE THREAD

**Issue by mcandre** [minio/minio-go#598]
Are minio client objects thread-safe? Or are users perhaps encouraged to create one client instance per goroutine?

**Comment by harshavardhana** [comment]
> Are minio client objects thread-safe? Or are users perhaps encouraged to create one client instance per goroutine?

You are expected to hold locks in your application and share the same minio client object. @mcandre

**Comment by krishnasrinivas** [comment]
>> Are minio client objects thread-safe? Or are users perhaps encouraged to create one client instance per goroutine?

> You are expected to hold locks in your application and share the same minio client object. @mcandre

In other words, minio-client object is thread safe.

**Comment by dbregman** [comment]
@harshavardhana says "you are expected to hold locks" translation: NOT threadsafe.
then @krishnasrinivas quotes this saying "In other words, minio-client object is thread safe."

Super confusing contradictory answers. Please clarify:
1) Is locking needed to use a client object safely from multiple threads
2) Are multiple client objects required for concurrent requests

If this is documented somewhere, I cannot find it.

**Comment by krishnasrinivas** [comment]
Sorry for the confusion!

> * Is locking needed to use a client object safely from multiple threads

Locking is not needed to use a client object safely from multiple threads

> 2\. Are multiple client objects required for concurrent requests

No. You can use the same client object for concurrent requests.

**Comment by dbregman** [comment]
@krishnasrinivas thank you for the clarification :) It might be good to mention this in the docs too.
