### ISSUE TITLE
generating wron HMAC for version 2

### ISSUE THREAD

**Issue by kofemann** [minio/minio-go#600]
I am trying to use client with s3 server getting authentication error. It looks like client generates request like
**/bucket/?location=**, but calculates HMAC for request **/bucket/?location**

is it server problem or client issue?

**Comment by harshavardhana** [comment]
@kofemann what is the s3 server in question here?

**Comment by harshavardhana** [comment]
Works perfectly fine with S3 i.e (s3.amazonaws.com) - it must be a server problem. 

```
 mc ls --debug s3-v2/andoria
mc: <DEBUG> GET /andoria/?location= HTTP/1.1
Host: s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/2017-01-27T04:44:18Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Thu, 02 Feb 2017 20:03:14 GMT
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 02 Feb 2017 20:03:16 GMT
Server: AmazonS3
X-Amz-Id-2: Wu7jP4QbTBR2pL8tfY5Mi9Gj7+ehk1JiCNnFmr0iKk4MtHA3EfL0m9YY//9xZB/CZ7RhW0iXCAk=
X-Amz-Request-Id: 2A112BEDCB2FAE24

mc: <DEBUG> Response Time:  1.473815058s

mc: <DEBUG> HEAD / HTTP/1.1
Host: andoria.s3.amazonaws.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3 mc/2017-01-27T04:44:18Z
Authorization: AWS **REDACTED**:**REDACTED**
Date: Thu, 02 Feb 2017 20:03:15 GMT
Expect: 100-continue

mc: <DEBUG> HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 02 Feb 2017 20:03:17 GMT
Server: AmazonS3
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: Q4s5nFQxq8zjaCCH/rXLloD3Q2z70uCBcKXGkiJL1lYna41wU4vjg3JEW1kHJXloeaM2UcPKNxw=
X-Amz-Request-Id: 6743692D34B1C3F3


mc: <DEBUG> Response Time:  720.839015ms
```

**Comment by kofemann** [comment]
this is cynnyspace.com.
Is there any doc which describes for to calculate for in case of option without value?
The only docu I found is http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html, which talks about **/?location**

**Comment by harshavardhana** [comment]
> this is cynnyspace.com.
> Is there any doc which describes for to calculate for in case of option without value?
> The only docu I found is http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETlocation.html, which talks about /?location

HTTP spec dictates that any query param for example "localtion=" is same as "location" and vice versa. So this should be honored and it is rightly honored by AWS S3.  This also means that the S3 server you are using is not HTTP spec compatible.

**Comment by kofemann** [comment]
ok, I will ping server provider..

**Comment by krishnasrinivas** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html mandates that `=` should be used for signature calculation even if no query value is present:

```
When a request targets a subresource, the corresponding query parameter value will be an empty string (""). For example, the following URI identifies the ACL subresource on the examplebucket bucket:

http://s3.amazonaws.com/examplebucket?acl 

The CanonicalQueryString in this case is as follows:
URI-encode("acl") + "=" + ""
```

**Comment by kofemann** [comment]
just be make it clear: the issue is on the server side?

**Comment by harshavardhana** [comment]
Yep @kofemann
