### ISSUE TITLE
Last-Modified time format not recognized

### ISSUE THREAD

**Issue by kofemann** [minio/minio-go#604]
---------START-HTTP---------
GET /vol1/00002A2B43EC8E8B4638962F19735E0DF4F0 HTTP/1.1
Host: cy1.cynnyspaces3.com
User-Agent: Minio (linux; amd64) minio-go/2.0.3
Authorization: AWS **REDACTED**:**REDACTED**
Date: Sun, 05 Feb 2017 13:21:54 GMT
Expect: 100-continue
Accept-Encoding: gzip

I am getting this error and report is as log message suggest
(Last-Modified time format not recognized. Please report this issue at https://github.com/minio/minio-go/issues.)

HTTP/2.0 200 OK
Content-Length: 1111694
Access-Control-Allow-Credentials: true
Cache-Control: undefined
Content-Transfer-Encoding: binary
Content-Type: octet/stream
Date: Sun, 05 Feb 2017 13:21:55 GMT
Etag: ""
Server: nginx
Vary: Origin
X-Debug-Cyn-Domain: morphcast.com
X-Debug-Cyn-Ep-Trace-Info: 636|636
X-Debug-Cyn-Hash: f1108683da208c257e173b48398d723289ea7308
X-Debug-Cyn-Microserver-Ip: 2a01:84a0:1001:a001::30:7
X-Debug-Cyn-Region-Id: 1
X-Debug-Cyn-Trace-Info-Header: null
X-Debug-Cyn-Version: 11.532
X-Debug-Rp-Request-Time: 0.648
X-Powered-By: Express
---------END-HTTP---------

**Comment by harshavardhana** [comment]
Looks like cyn is not sending LastModified.. this should be sent by an S3 API compatible server.

**Comment by kofemann** [comment]
Yes, but should  the GET request fail if last modification time is not
provided?

-kofemann
/** caffeinated mutations of the core personality */

**Comment by harshavardhana** [comment]
Yes definitely S3 mandates this we can relax it but it is something all S3 providers provide. I don't see why cyn should be treated any special.

**Comment by kofemann** [comment]
doggy: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
