### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by mcandre** [minio/minio-go#605]
S3 offers REST API methods for assigning tags to objects, which is helpful for nonhierarchical object organization. Could minio(-go) expose a similar capability?

http://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html

**Comment by harshavardhana** [comment]
minio-go APIs are meant for simple usage, S3 specific features like tagging you should use aws-sdk-go, our plan is to reduce S3 APIs not expand them. 

Tags are ideal to be part of application and it's database. Storage should deal with data and it's safety.

**Comment by GregorioDiStefano** [comment]
FWIW, this feature isn't supported, but trying to modify the object by adding tags actually truncates the file with an XML file describing the tags.

**Comment by maniankara** [comment]
@harshavardhana S3 has realised the benefit of tags, earlier the better for you guys :)
Otherwise, I loved minio !

**Comment by Cinerar** [comment]
if this comment is true https://github.com/minio/minio/issues/5139#issuecomment-485520789 shouldnt this issue be reopened?

**Comment by harshavardhana** [comment]
> if this comment is true [minio/minio#5139 (comment)](https://github.com/minio/minio/issues/5139#issuecomment-485520789) shouldnt this issue be reopened?

The issue is for lifecycle @Cinerar not tags
