### ISSUE TITLE
multi-part upload chunk size hardcoded

### ISSUE THREAD

**Issue by kofemann** [minio/minio-go#606]
It is currently hard coded to 64MB. Is it possible to make it configurable?

**Comment by krisis** [comment]
@kofemann It isn't configurable. Could you explain why you require to change the upload part size? How is 64MB upload part size affecting your use-case?

**Comment by kofemann** [comment]
there are some (at lease one https://www.cynnyspace.com/) which uses smaller chunk sizes. As there is no auto-discovery mechanism for that (at least not an official one http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html) a configuration option will allow to use minio-go with cynnyspace end-point.

**Comment by krisis** [comment]
@kofemann Amazon S3 spec doesn't care about the upload parts size as long as they are larger than 5MB. Each part uploaded provides its size via ``Content-Length`` header as part of the UploadPart API request. If cynnyspace is S3 compatible, it shouldn't matter what upload part sizes minio-go uses for each part.

**Comment by harshavardhana** [comment]
> @kofemann Amazon S3 spec doesn't care about the upload parts size as long as they are larger than 5MB. Each part uploaded provides its size via Content-Length header as part of the UploadPart API request. If cynnyspace is S3 compatible, it shouldn't matter what upload part sizes minio-go uses for each part.

Closing this as upstream bug.
