### ISSUE TITLE
PutObject throws error from AWS SDK

### ISSUE THREAD

**Issue by drgomesp** [minio/minio-go#633]
When trying to `PutObject`, I'm getting the following message from AWS SDK:

`A header you provided implies functionality that is not implemented`

Possibly related to https://github.com/aws/aws-sdk-go/issues/122

Any ideas?

**Comment by balamurugana** [comment]
@drgomesp 

* If you are using minio server and awk-sdk-go, please provide minio version, setup type you use and awk-sdk-go version.

* If you are using minio-go with amazon s3, please use `TraceOn()` and provide the output.

**Comment by drgomesp** [comment]
@balamurugana thanks for the reply.

I'm using the latter. What should I pass onto `TraceOn`?

**Comment by balamurugana** [comment]
@drgomesp for minio-go tracing, refer http://docs.minio.io/docs/golang-client-api-reference#TraceOn

**Comment by drgomesp** [comment]
This is what I'm getting:

```http
---------START-HTTP---------
PUT /mongodb/00010110.json HTTP/1.1
Host: pf-mongodb-backup.s3-ap-southeast-1.amazonaws.com
User-Agent: Minio (darwin; amd64) minio-go/2.0.3
Content-Length: 0
Authorization: #####
Content-Md5: 1B2M2Y8AsgTpgAmY7PhCfg==
Content-Type: application/octet-stream
Expect: 100-continue
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170330T094611Z
Accept-Encoding: gzip

HTTP/1.1 501 Not Implemented
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Thu, 30 Mar 2017 09:46:11 GMT
Server: AmazonS3
X-Amz-Id-2: Tt7eks5WnICUgCHv96Gc5vNtoxjjhNwjnIEq2U5umrLKnXOlFhXGmB9cGWI2u1QA+AnNwwywkCA=
X-Amz-Request-Id: A568F217B5E2F1A2

14d
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Header>Transfer-Encoding</Header><RequestId>A568F217B5E2F1A2</RequestId><HostId>Tt7eks5WnICUgCHv96Gc5vNtoxjjhNwjnIEq2U5umrLKnXOlFhXGmB9cGWI2u1QA+AnNwwywkCA=</HostId></Error>
0
---------END-HTTP---------
```

**Comment by vadmeste** [comment]
@drgomesp, looks like the bug is fixed in the last master, can you test with it ?

**Comment by harshavardhana** [comment]
> Expect: 100-continue
> 
> HTTP/1.1 501 Not Implemented

This is because of the `Expect` header new S3 endpoints don't yet support this.

**Comment by harshavardhana** [comment]
@drgomesp can you apply this PR locally and test out for us?  https://github.com/minio/minio-go/pull/640

Thanks.

**Comment by drgomesp** [comment]
Apparently the issue happened because the file was empty. It was a problem on my application level, but the error message was not very helpful. 

Can we try adding a more helpful feedback?

**Comment by harshavardhana** [comment]
We cannot server sent the error. We can't know what to say at this point in time. Because the error sent by server is arbitrary. So as a client we can't make sense of anything that went wrong.

**Comment by vadmeste** [comment]
@drgomesp, were you able to test with minio-go master ?

**Comment by deekoder** [comment]
@drgomesp  I will go ahead and close this issue. Please do reopen if you think we have not addressed this correctly.

**Comment by drgomesp** [comment]
@deekoder no problem. As I said before, I think we need a proper message when throwing this error. Otherwise, it works fine.
