### ISSUE TITLE
Example for Multipart upload 

### ISSUE THREAD

**Issue by lth2015** [minio/minio-go#645]
Where could I find the multipart upload example?

thank you!~

**Comment by donatello** [comment]
There are lots of examples linked in the readme - https://github.com/minio/minio-go#full-examples--file-object-operations

The library handles multipart and singlepart uploads uniformly with the same API.

**Comment by lth2015** [comment]
Thank you for you help.
All of examples were used in my learning environment, But I can't find a complete example about "multipart upload",  likes initiateMultipartUpload ... uploadPart ... completeMultipartUpload.

I working for a storage  wrapper service for our team, I provide a http service to serve object storage service for ceph object storage.  Clients need using "Multipart upload" feature to upload large files.

My apis like follows:

List all files: Get /api/v1/storage/:apiKey/files 
Upload a file: Post /api/v1/storage/:apiKey/files/upload
Stat a file: Get /api/v1/storage/:apiKey/files/:file/stat 
Rename a file: Post /api/v1/storage/:apiKey/files/:file/rename 
Download a file: Get /api/v1/storage/:apiKey/files/:file
**Multipart Upload a file: Post /api/v1/storage/:apiKey/files/:file/multipart**

Could you give me some advice about this usage?

Thank you very much~

**Comment by donatello** [comment]
@lth2015 With this library, you do not need to use separate initiate, uploadpart and completemultipart requests. The library takes care of this for you. You can just use the [FPutObject](https://docs.minio.io/docs/golang-client-api-reference#FPutObject) function. See the link for documentation and example.

**Comment by lth2015** [comment]
It's helpful, thanks~
