### ISSUE TITLE
minioClient.Object should validate ETag for new HTTP requests

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-go#656]
obj := minioClient.GetObject()

obj.Read(...)

Now `obj.readAt()` at a different offset will cause new HTTP request, we have now ensure that the referred object on the server side has not been replaced by verifying that the ETag is same.

**Comment by krisis** [comment]
@krishnasrinivas what is the error to be returned by minio-go if we find the ETag to be different?
