### ISSUE TITLE
Support new API GetObjectPartial with preconditions

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio-go#669]
Reference: https://github.com/minio/minio/issues/3521

We need the following API in minio-go to fix the race explained in the issue above:
```
GetObject(bucket, object string,  startRange, length int, preconditions map[string]string, writer io.Writer) (err error) {
}
```

**Comment by harshavardhana** [comment]
> GetObject(bucket, object string,  startRange, length int, preconditions map[string]string, writer io.Writer) (err error) {
> }

Does this go into Core API?

**Comment by krishnasrinivas** [comment]
> Does this go into Core API?

Yes, because client.GetObject returning client.Object ensures that ETag has not changed. So better keep "Client" simple and add this to Core
