### ISSUE TITLE
use upstream go-homedir

### ISSUE THREAD

**Issue by legrostdg** [minio/minio-go#684]
It would help Debian packaging of future versions of `minio-go` if it could use upstream https://github.com/mitchellh/go-homedir instead of https://github.com/minio-go/go-homedir (dependency introduced in 5d7ee332f6)

**Comment by harshavardhana** [comment]
> It would help Debian packaging of future versions of minio-go if it could use upstream https://github.com/mitchellh/go-homedir instead of https://github.com/minio-go/go-homedir (dependency introduced in 5d7ee33)

We use our own homedir for a bug fix which we wish to submit upstream in some time.

**Comment by legrostdg** [comment]
The fix is dated from 15 Feb 2016... Won't it be easier to do a pull-request now, before forgetting this again?

**Comment by harshavardhana** [comment]
We expect that @legrostdg users of this library just like all other go projects vendorize the dependency and all other dependencies presented by this project. Apps vendorize and stick to a commit or version - these apps are not expecting Debian to provide compiled packages for each of these. 

Closing this bug as not an issue packages should comply with with Go's build toolchain.

**Comment by legrostdg** [comment]
Unfortunately, that is contrary to the Debian policy. It explicitely avoids vendoring libraries and code duplication. Each dependency has to be packaged separately, and you can't have two packages with just a few lines of differences.
Is there a reason why you don't want to submit this fix upstream, so that all the users get the benefits?

**Comment by harshavardhana** [comment]
> Unfortunately, that is contrary to the Debian policy. It explicitely avoids vendoring libraries and code duplication

Yes but Debian policy is in conflict with how Go programs are supposed to be built.

> Is there a reason why you don't want to submit this fix upstream, so that all the users get the benefits?

A PR has been sent upstream.  

I see the package name choosen is this https://packages.debian.org/sid/golang-github-minio-minio-go-dev . 

Can you write down how a user would use this package with a simple program? You can use one of our standard examples https://github.com/minio/minio-go/blob/master/examples/s3/bucketexists.go - How do you ideally test this package? 

You can use our demo server credentials 

```
Endpoint: play.minio.io:9000
AccessKey: Q3AM3UQ867SPQQA43P2F  
SecretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
Secure: true
```
