### ISSUE TITLE
ETag Format 

### ISSUE THREAD

**Issue by laverite** [minio/minio-go#687]
I notice that minio-go strips the ETag returned by S3 of leading and trailing quotes per:

  https://github.com/minio/minio-go/blob/75a218a15d5413c9a961318160f4c12a29bf9147/api-get-object.go#L655

But then this transformed ETag is passed back to S3 on subsequent calls with a "If-Match:" condition.  This causes a "HTTP/1.1 412 Precondition Failed" response for me.  I can verify not stripping the quotes does work however.Is this expected?  One caveat is I'm not using AWS S3, but RiakCS S3 so I'm not sure how ETags with or without quotes are supposed to be handled.

**Comment by krishnasrinivas** [comment]
Looks like quotes is needed https://tools.ietf.org/html/rfc7232#page-13

We can behave how aws-sdks behave since http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html does not list an example. Thanks for pointing this out @laverite

**Comment by harshavardhana** [comment]
> But then this transformed ETag is passed back to S3 on subsequent calls with a "If-Match:" condition. This causes a "HTTP/1.1 412 Precondition Failed" response for me. I can verify not stripping the quotes does work however.Is this expected? One caveat is I'm not using AWS S3, but RiakCS S3 so I'm not sure how ETags with or without quotes are supposed to be handled.

S3 works fine with or without quotes and even Minio server does, primarily because we do strip them out before comparison. Now that looks like a server side implementation choice.. 

But as a client we will add the right values in accordance with RFC7232.
