### ISSUE TITLE
CopyObject Does not support metadata

### ISSUE THREAD

**Issue by tejaycar** [minio/minio-go#690]
As an api user
When I copy a library using CopyObject
I should be able to pass in arbitrary metadata to add to the request as headers
Specifically, I should be able to pass in `x-amz-server-side-encryption`

**Comment by deekoder** [comment]
This feature is in progress. Hopefully you will have this ability soon.

**Comment by tejaycar** [comment]
is there a branch I can look at or something?  I'm working on a PR for
Mattermost, and would like to have the code ready if you have a well
defined api for this.

**Comment by harshavardhana** [comment]
> is there a branch I can look at or something?  I'm working on a PR for
> Mattermost, and would like to have the code ready if you have a well
> defined api for this.

There is no change in API right now - there is a refactor https://github.com/minio/minio-go/pull/644 which would address this @tejaycar

**Comment by tejaycar** [comment]
@harshavardhana Perhaps I'm missing something, but I don't see how #644 address this.  It does allow setting one specific new metadata (byte range), but it does not allow other arbitrary ones.  In my case, I'd want to be able to add encryption headers to the copyConditions object (which is then poorly named because it no longer contains only copy conditions, it contains various other metadata elements).

Am I missing something?  Does the current proposal in #644 actually allow me to somehow add the encryption headers?

**Comment by harshavardhana** [comment]
What I am saying it will.

**Comment by tejaycar** [comment]
Ah, excellent.  Thanks.

**Comment by tejaycar** [comment]
@harshavardhana  any ETA on #644?

**Comment by harshavardhana** [comment]
> @harshavardhana any ETA on #644?

Its currently under review we will let you know soon.

**Comment by tejaycar** [comment]
You rock.  Thanks.

**Comment by tejaycar** [comment]
Now being solved by #715

**Comment by harshavardhana** [comment]
Fixed by #715
