### ISSUE TITLE
Example code for encrypted objects is out of date

### ISSUE THREAD

**Issue by tejaycar** [minio/minio-go#696]
The example code for put-encrypted-object and get-encrypted-object are out of date.  They do not use the encrypt package.

**Comment by vadmeste** [comment]
Thanks @tejaycar for reporting, I'll fix this.

**Comment by tejaycar** [comment]
@vadmeste  no need, I just submitted a PR for it.

**Comment by tejaycar** [comment]
except having 696 fix 697... that's not confusing :(
