### ISSUE TITLE
Closing encrypted objects

### ISSUE THREAD

**Issue by tejaycar** [minio/minio-go#698]
Looking at the code and the example for getEncryptedObject, it is clear that this method returns an io.Reader object.  However, the example doesn't show the reader being closed.  Does it not need closed, or is the example just missing it?

Thanks

**Comment by harshavardhana** [comment]
> Looking at the code and the example for getEncryptedObject, it is clear that this method returns an io.Reader object. However, the example doesn't show the reader being closed. Does it not need closed, or is the example just missing it?

@tejaycar thanks for opening the bug.. Looks like there is an issue. Close() should happen properly and it should be initiated by the caller. 

I see the bug, sending a fix.

**Comment by harshavardhana** [comment]
@tejaycar https://github.com/minio/minio-go/pull/699 is the fix can you help validate this?

**Comment by tejaycar** [comment]
My go experience is almost non-existent, but from what I can see that looks
pretty good.

**Comment by tejaycar** [comment]
@harshavardhana I'm new to this project, so I hope this doesn't come off as too unappreciative, but what kind of timeframe should I expect for this fix to be released?

**Comment by harshavardhana** [comment]
The fix is under review should be merged by no later than tomorrow. If no surprises.

**Comment by tejaycar** [comment]
That's awesome.  Thanks.

**Comment by harshavardhana** [comment]
Fixed in #699
