### ISSUE TITLE
Support for context.Context?

### ISSUE THREAD

**Issue by fd0** [minio/minio-go#700]
Hi,

are there plans to support request cancellation via `context.Context`? I'm currently in the progress of adding proper cancellation to restic, and I'd like to be able to cancel outgoing requests to the s3 backend...

Cheers,
Alex

**Comment by harshavardhana** [comment]
We will discuss this internally again. While there are some benefits of doing this. We are actually of the opinion that context package just complicates the codebase. 

Will let you know our final decision.

**Comment by harshavardhana** [comment]
This issue is not blocked any more.. We decided to implement `PutObjectWithContext()` and `GetObjectWithContext()` API.

**Comment by fd0** [comment]
Nice! I'm looking forward to it!
