### ISSUE TITLE
GCS via S3 compat mode: PROTOCOL ERROR via HTTP2

### ISSUE THREAD

**Issue by fd0** [minio/minio-go#712]
Hi,

running the restic integration tests with a GCS backend I'm seeing the following error (running from the top-level directory of the restic repo):

```
$ GOPATH=$PWD:$PWD/vendor go test -v -run 'S3/TestSave$' restic/backend/s3
[...]
tests.go:345: client.PutObject: Put https://restic-test-an.storage.googleapis.com/test-1497605230859660994/data/1b/1b06f7b567c7f267319bf39f28aa39461537550f0daf6b1c92564fdfb44dda05: stream error: stream ID 35; PROTOCOL_ERROR
```

restic is 6a948d5afd8c17475aa791c440bdc4472fef4884 (https://github.com/restic/restic/pull/1043)
minio-go (vendored) is f6d5df6b625c00c3180ec6c9240ea710620c7070

I've got no idea on how to debug this further. It looks like the server(?) may include an HTTP header value with invalid characters, e.g. LF or CR? https://github.com/grpc/grpc-go/issues/576

**Comment by harshavardhana** [comment]
Can you paste the client trace output ?

**Comment by fd0** [comment]
Sure: [error-log.txt](https://github.com/minio/minio-go/files/1081170/error-log.txt)

**Comment by harshavardhana** [comment]
Is it possible to reproduce with the same steps I did yesterday ? .

Is this with the PR which implements Size() method for the reader in restic ?

**Comment by fd0** [comment]
Let's meet on Slack, I'll show you.

**Comment by fd0** [comment]
Checkout the restic repository, switch to the branch `fix-gcs` (at commit `6a948d5afd8c17475aa791c440bdc4472fef4884` at the time of writing), then set the necessary environment variables:
```
$ export RESTIC_TEST_S3_KEY=<KEY> RESTIC_TEST_S3_SECRET=<SECRET> 
$ export RESTIC_TEST_S3_REPOSITORY=s3:https://storage.googleapis.com/<BUCKET>
```

Then run the test:
```
$ GOPATH=$PWD:$PWD/vendor go test -v -run 'S3/TestSave$' restic/backend/s3
```

**Comment by fd0** [comment]
I haven't been able to reproduce this outside of restic, sorry.

**Comment by fd0** [comment]
Ha, got it. The error I'm seeing is the http2 equivalent of this error: `Put http://restic-test-an.storage.googleapis.com/test-file-2596996162: http: ContentLength=1048453 with Body length 1048576`

**Comment by fd0** [comment]
The error can be produced when minio-go sends an invalid content length. It happens for example when you upload a file which has been seeked to some offset. Sample program: https://gist.github.com/3b935f152ea06221b43d6dc2cc8d3c3f

**Comment by fd0** [comment]
Turns out, minio-go first calls `Seek(0, 1)` to get the current position (presumably to compute the length of the object) and then calls `Seek(0, 0)` and starts reading from the beginning...  sample program: https://gist.github.com/181ccdb96ad52a1bd070cc1656c32058

For this I'm using minio-go d4a9d60c7f993ef3dfc53bb6864707394674d224.

**Comment by harshavardhana** [comment]
Fixed in master already. @fd0  - closing this bug. Please re-open if seen again.

**Comment by fd0** [comment]
I'll check, thank you!

**Comment by fd0** [comment]
Looks good!
