### ISSUE TITLE
ListBuckets() always sends a request with no region set

### ISSUE THREAD

**Issue by benpaxton-hf** [minio/minio-go#717]
https://github.com/minio/minio-go/commit/8c34cc49a0b000ebe755577feab802ee721535ed changed the behaviour of `newRequest()` to only use data retrieved from the `metadata` object; in the case of `ListBuckets()` this object [does not contain this data](https://github.com/minio/minio-go/blob/master/api-list.go#L40), so a request is sent with `region == ""`.

The Minio server (at least the version we're using) returns 400 Bad Request in this case:
```
<Error>
    <Code>AuthorizationQueryParametersError</Code>
    <Message>Error parsing the X-Amz-Credential parameter; the region is wrong;</Message>
    [...]
</Error>
```

Prior to the above commit, `newRequest()` defaulted to `us-east-1` or `cn-north-1`, overriding based on metadata rather than making metadata the only source - could this be restored? Perhaps something like:
```go
	var location string
	// Gather location only if bucketName is present.
 	if metadata.bucketName != "" && metadata.bucketLocation == "" {
		location, err = c.getBucketLocation(metadata.bucketName)
		if err != nil {
			return nil, err
		}
	} else if metadata.bucketLocation != "" {
		location = metadata.bucketLocation
	} else if s3utils.IsAmazonChinaEndpoint(c.endpointURL) {
		location = "cn-north-1"
	} else {
		location = "us-east-1"
	}
```

**Comment by harshavardhana** [comment]
> <Error>
>     <Code>AuthorizationQueryParametersError</Code>
>     <Message>Error parsing the X-Amz-Credential parameter; the region is wrong;</Message>
>     [...]
> </Error>

Not sure why this would fail works fine with play.minio.io and s3.amazonaws.com @benpaxton-hf - will check again.

**Comment by benpaxton-hf** [comment]
Looks like this may be due to us using an old version of the Minio server - the latest `master` seems OK. Will test more tomorrow.

**Comment by harshavardhana** [comment]
> Looks like this may be due to us using an old version of the Minio server - the latest master seems OK. Will test more tomorrow.

There is a bug with S3 fixing that now. Thanks for reporting @benpaxton-hf

**Comment by benpaxton-hf** [comment]
#720 fixes this on my end.
