### ISSUE TITLE
ListObjectsV2 causes endless loop > 1000 items

### ISSUE THREAD

**Issue by klingtnet** [minio/minio-go#719]
This is a copy of [#578](https://github.com/minio/minio-java/issues/578) from `minio-java` because the exact same problem occurs for `minio-go`.

**Comment by harshavardhana** [comment]
Looks like the implementation was copied from here.

**Comment by harshavardhana** [comment]
@klingtnet i am able to list more than 1000 objects

```
$ mc ls s3/harshavardhana/1000-objects/ -r | wc -l
4834
```

Can you provide a code snippet which reproduces this problem?

**Comment by harshavardhana** [comment]
```go
func main() {
	// Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-bucketname and my-prefixname
	// are dummy values, please replace them with original values.

	// Requests are always secure (HTTPS) by default. Set secure=false to enable insecure (HTTP) access.
	// This boolean value is the last argument for New().

	// New returns an Amazon S3 compatible client object. API compatibility (v2 or v4) is automatically
	// determined based on the Endpoint value.
	s3Client, err := minio.New("s3.amazonaws.com", "xxxxxx", "xxxxx", true)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Create a done channel to control 'ListObjects' go routine.
	doneCh := make(chan struct{})

	// Indicate to our routine to exit cleanly upon return.
	defer close(doneCh)

	//	s3Client.TraceOn(os.Stderr)

	// List all objects from a bucket-name with a matching prefix.
	for object := range s3Client.ListObjectsV2("harshavardhana", "1000-objects", true, doneCh) {
		if object.Err != nil {
			fmt.Println(object.Err)
			return
		}
		fmt.Println(object)
	}
	return
}
```

Not able to reproduce this on AWS S3. @klingtnet - are you seeing this on Minio server?

**Comment by klingtnet** [comment]
@harshavardhana Thanks for the quick response!

I used a ceph backend and calls to `ListObjectsV2` did not stop for some prefixes, with more than 1000 objects, in fact the list output run forever and showed the same 1000 objects.
You may have to return immediately if [the `NextContinuationToken` is empty](https://github.com/minio/minio-go/blob/master/api-list.go#L150-L153).

**Comment by harshavardhana** [comment]
> used a ceph backend and calls to ListObjectsV2 did not stop for some prefixes, with more than 1000 objects, in fact the list output run forever and showed the same 1000 objects.
> You may have to return immediately if the NextContinuationToken is empty.

Are you sure that ListObjectsV2 is supported by Ceph?

**Comment by harshavardhana** [comment]
> You may have to return immediately if the NextContinuationToken is empty.

No this is not what we should do it breaks S3 compatibility, according to S3 spec it should be set properly.  It is Truncated: [true|false] which breaks the loop.

**Comment by harshavardhana** [comment]
> You may have to return immediately if the NextContinuationToken is empty.
> No this is not what we should do it breaks S3 compatibility, according to S3 spec it should be set properly. It is Truncated: [true|false] which breaks the loop.

I think since the structure for ListObjectsV2 is very similar to ListObjectsV1 it doesn't fail when unmarshalling, so i guess we can do some validation at lower level and fail. 

Let me do this.. thanks @klingtnet

**Comment by klingtnet** [comment]
Thanks!

**Comment by harshavardhana** [comment]
> Thanks!

@klingtnet but i think you should be using ListObjectsV1 with Ceph - i don't think it supports V2 and perhaps not even returning an error.  So ideally its a server side problem but we can make sure we are not going through an infinite loop.

**Comment by klingtnet** [comment]
@harshavardhana Alright, I will try the V1 API and let you know if everything works.

**Comment by klingtnet** [comment]
Reverting to `ListObjects` from `ListObjectsV2` fixed the issue.
Thank you for implementing the additional validation.
