### ISSUE TITLE
Functional tests should use streaming

### ISSUE THREAD

**Issue by NitishT** [minio/minio-go#742]
Minio-go functional tests will be used in Mint framework to test Minio server. This calls for uniform usage of Files across Minio-SDK functional tests.

It was concluded that (https://github.com/minio/mint/pull/67/files)

- Tests should generate their own data by using input/output streams. These streams should be used for testing upload cases.

This makes tests flexible, removes too much dependency on /mint/data directory and reduces the size of `mint` Docker image.

Once these changes are done in minio-go, `mint` will be updated to use these test cases instead of maintaining copy of minio-go functional tests.

**Comment by harshavardhana** [comment]
This can be closed.

**Comment by NitishT** [comment]
Closing as fixed by #727

**Comment by harshavardhana** [comment]
Don't forget apply proper labels if the bugs are `fixed` as closed by a PR.

**Comment by harshavardhana** [comment]
Current implementation of 

```go
 // read data from file if it exists or optionally create a buffer of particular size                                                             
 func getDataBuffer(fileName string, size int) (buf []byte) {                                                                                     
         if _, err := os.Stat(getFilePath(fileName)); os.IsNotExist(err) {                                                                        
                 buf = bytes.Repeat([]byte(string('a')), size)                                                                                    
                 return                                                                                                                           
         }                                                                                                                                        
         buf, _ = ioutil.ReadFile(getFilePath(fileName))                                                                                          
         return                                                                                                                                   
 } 
``` 

Is actually not correct, we must have missed this during the review. Randomized data should be generated upon read but shouldn't be allocated in this manner. We need to fix it.

**Comment by harshavardhana** [comment]
This fixed @NitishT

**Comment by harshavardhana** [comment]
Oops wait fix is not merged yet https://github.com/minio/minio-go/pull/780
