### ISSUE TITLE
Unexpected Etag value when upload file size is bigger than 64M

### ISSUE THREAD

**Issue by Vesnica** [minio/minio-go#746]
When using `PutObject`(or `PutObjectStreaming`) to upload a file which size is bigger than 64M, the file's Etag value is incorrect, which should be in this form: `"e23d77f2fc5a76dca68ac17f1d8271f9"`, but actually it have a integer surffix, like this: `"c60dff9457dcd7c1b9be2883499b2b82-17"`. and from my observation, the surffix value is equal to the `(FILE SIZE) % 64M`.

Here is the sample code:

```
package main

import (
        "log"
	"os"

	"github.com/minio/minio-go"
)

func main() {
	endpoint := "10.62.88.176:9000"
	accessKeyID := "ACCESS_KEY_HERE"
	secretAccessKey := "SECRET_KEY_HERE"
	useSSL := false

	minioClient, err := minio.New(
		endpoint,
		accessKeyID,
		secretAccessKey,
		useSSL,
	)
	if err != nil {
		panic(err)
	}

	bucketName := "test"
	location := "us-east-1"

	err = minioClient.MakeBucket(bucketName, location)
	if err != nil {
		panic(err)
	}

	file, err := os.Open("SomeFileBiggerThan64M")
	if err != nil {
		panic(err)
	}
	defer file.Close()
	_, err := minioClient.PutObject(bucketName, file.Name(), file, "application/octet-stream")
	if err != nil {
		panic(err)
	}

	doneCh := make(chan struct{})
	defer close(doneCh)
	objectCh := minioClient.ListObjectsV2(bucketName, "", true, doneCh)
	for object := range objectCh {
		if object.Err != nil {
			panic(object.Err)
		}
		log.Println(object.Key)
		log.Println(object.ETag)
	}
}
```
Minio server version: 2017-06-13T19:01:01Z
Minio-go sdk version: master branch, commit id: 5ca66c9a35ba1cd674484be99dc97aa0973afe12

**Comment by krishnasrinivas** [comment]
@Vesnica when the file size is > 64 MB we use multipart upload. We behave how AWS-S3 behaves, i.e if you upload a multipart-object you will have an ETag that looks like `etag-N` where N is the number of parts.

You can check minio-go with AWS-S3 and observe that the behavior is same.

**Comment by harshavardhana** [comment]
Just expanding on what @krishnasrinivas already said - relevant explanation from AWS S3. Definition of ETag. 

``ETag``  - The entity tag is a hash of the object. The ETag reflects changes only to the contents of an object, not its metadata. The ETag may or may not be an MD5 digest of the object data. Whether or not it is depends on how the object was created and how it is encrypted as described below:Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-C or SSE-KMS, have ETags that are not an MD5 digest of their object data.If an object is created by either the Multipart Upload or Part Copy operation, the ETag is not an MD5 digest, regardless of the method of encryption

**Comment by Vesnica** [comment]
Okay, I think I can accept this explanation.

Is there any convenient way to get the big object md5sum? or I have to intercept the io.Read stream and calculate myself?

**Comment by harshavardhana** [comment]
> Is there any convenient way to get the big object md5sum? or I have to intercept the io.Read stream and calculate myself?

@Vesnica - you have to do it on the client side.

**Comment by Vesnica** [comment]
Got it. Closing
