### ISSUE TITLE
mustParseBool should default to false when string is empty

### ISSUE THREAD

**Issue by krisis** [minio/minio-go#751]
`mustParseBool` is a utility function that parses boolean value set in an shell environment variable. Most *nix shell programs leave environment variables unset to indicate false. So, `mustParseBool` should default to false when an empty string is passed.
E.g, If `ENABLE_HTTPS` environment variable is not set `mustParseBool(os.Getenv("ENABLE_HTTPS"))` should be false.

**Comment by vadmeste** [comment]
> E.g, ENABLE_HTTPS environment variable is not set mustParseBool(os.Getenv("ENABLE_HTTPS")) should be false.

I agree since this is only for testing..
