### ISSUE TITLE
tests: Each test should be self contained avoid having single initializers

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-go#756]
```sh
$ grep 'func test.' functional_tests.go  | grep minio.Client
func testComposeObjectErrorCasesWrapper(c *minio.Client) {
func testComposeMultipleSources(c *minio.Client) {
func testEncryptedCopyObjectWrapper(c *minio.Client) {
func testUserMetadataCopyingWrapper(c *minio.Client) {
```

**Comment by kannappanr** [comment]
None of these functions are called directly from main. There are functions in the test that does the same test. The only difference being that the client was instantiated using either version 2 or version 4 signature. Those functions then call these wrapper functions.

For e.g, we do not call testEncryptedCopyObjectWrapper directly from the main. Instead, we call either testEncryptedCopyObject or testEncryptedCopyObjectV2. So, 
there is no single initializer in the functional test program.

**Comment by harshavardhana** [comment]
> None of these functions are called directly from main. There are functions in the test that does the same test. The only difference being that the client was instantiated using either version 2 or version 4 signature. Those functions then call these wrapper functions.
> 
> For e.g, we do not call testEncryptedCopyObjectWrapper directly from the main. Instead, we call either testEncryptedCopyObject or testEncryptedCopyObjectV2. So,
> there is no single initializer in the functional test program.

Agreed. :+1:
