### ISSUE TITLE
Any way to validate PutObjectStreaming data?

### ISSUE THREAD

**Issue by sb10** [minio/minio-go#771]
I have used PutObjectStreaming for a few 10s of .gz files, without receiving any errors. Of these, 4 ended up being stored with the expected number of bytes, but were corrupt (gzip claimed they were 'not in gzip format'). Deleting and trying again solved the issue (ie. the source files were not corrupt).

Is there any way I can validate the data that got uploaded, without downloading it again? Perhaps involving the comparison of md5 checksums?

**Comment by harshavardhana** [comment]
That is strange @sb10 do you have sample code how are you uploading ?

**Comment by sb10** [comment]
It's a bit complicated, but it's something like:

    // a "start uploading" method
    {
        f.rpipe, f.wpipe = io.Pipe()
        ready, finished := r.uploadData(f.rpipe, path)
        <-ready
        f.writeComplete = finished
    }
    
    // a "stream data" method
    n, err := f.wpipe.Write(data) // repeated, for sequential chunks of data from the source file
    
    // a "finish up" method
    f.wpipe.Close()
    worked := <-f.writeComplete
    if worked {
        f.rpipe.Close()
    }
    f.wpipe = nil
    f.rpipe = nil
    debug.FreeOSMemory()
    
    // the uploadData method called earlier
    func (r *remote) uploadData(data io.ReadCloser, remotePath string) (ready chan bool, finished chan bool) {
        ready = make(chan bool)
        finished = make(chan bool)
        go func() {
            sentReady := make(chan bool)
            go func() {
                <-time.After(50 * time.Millisecond)
                ready <- true
                sentReady <- true
            }()
            
            _, err := r.client.PutObjectStreaming(r.bucket, remotePath, data)
            
            <-sentReady // in case PutObjectStreaming completes in less than 50ms
            if err == nil {
                finished <- true
            } else {
                data.Close()
                finished <- false
                r.DeleteIncompleteUpload(remotePath)
            }
        }()
        return
    }

Of course I could have a bug in my own real code, but this is a situation where a process is streaming a single file and I have checks that it is doing it in sequential chunks. (The real code also logs errors from minio.)

**Comment by balamurugana** [comment]
@sb10 are you using `PutObjectStreaming()` to upload various `*.gz` files in parallel?

**Comment by sb10** [comment]
@balamurugana No, as noted, this test was a single file.

I've been trying to replicate the error and just my luck I've been unable to so far. So either it was a freak event or it's rarer than it looked on my first run. If I manage to reliably replicate I'll post traces.

**Comment by balamurugana** [comment]
@sb10 understood.  It would be great to provide me the issue reproducer.

**Comment by sb10** [comment]
Sorry, this issue was entirely caused by my own code. It would still be good to know what md5-checking capability there is in minio-go for PutObjectStreaming and FPutObject.
