### ISSUE TITLE
S3 server at wasabi.com doesn't support streaming uploads from minio

### ISSUE THREAD

**Issue by mappu** [minio/minio-go#774]
Hi,

The S3 server at wasabi.com seems to not support streaming uploads from minio.

The upload succeeds, but, when downloading the file, it has an actually downloaded content like

```
1df;chunk-signature=0fe0ec35__________________(redacted)____________________b4bd5f30
my content here...
0;chunk-signature=eac700d9__________________(redacted)____________________b6091939
```

It probably would work fine if i used minio's non-streaming API instead.

But, is there anything minio can do? Somehow detect whether streaming is supported by this server, or, throw an error if the data is not streamed successfully?

Regards
mappu

CC @wasabi-tech @jcflowers

**Comment by mappu** [comment]
>**Not Supported in Wasabi**
>
>Wasabi does not support any form of chunked uploads, that is, transferring the payload in multiple chunks. To the best of our knowledge, none of the standard libraries used for AWS S3 use this feature. All requests for uploading data to Wasabi must be done in a single chunk.

**Comment by harshavardhana** [comment]
> Wasabi does not support any form of chunked uploads, that is, transferring the payload in multiple chunks. To the best of our knowledge, none of the standard libraries used for AWS S3 use this feature. All requests for uploading data to Wasabi must be done in a single chunk.

^^ This is a slightly incorrect assessment, indeed some libraries do not support yet. 

Chunked uploads are supported by default on

- aws-sdk-java
- aws-sdk-net
- aws-sdk-ios
- aws-sdk-android

In-fact you would need special options to turn these off. Other popular libraries such as fog - http://fog.io/ also have this as default behavior as well. 

Using chunked uploads is a more performant way to upload files to AWS S3 and Minio, allows for really small memory foot-print. Most other S3 clones support this as well such as Ceph, Scality S3 etc. It would be nicer for Wasabi to support it. 

You could just simply use minio.NewV2() for the time being - this would enable Signature V2 which defaults to the previous style of uploading - if Wasabi supports Signature V2 it would work fine @mappu

**Comment by wavejd** [comment]
hi all..thanks for the bring this topic up.  I work on the product team @ Wasabi and we will certainly give this feedback some thought and update the issue with our planned direction soon.
