### ISSUE TITLE
Get https://127.0.0.1:9000/: x509: certificate is valid for 127.0.0.1, not 127.0.0.1

### ISSUE THREAD

**Issue by billschen** [minio/minio-go#782]
I use minio server  on windows 7 64bit 
I follow the instruction [How to secure access to Minio server with TLS](https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls) and make https work on local like:
![del_60](https://user-images.githubusercontent.com/19528399/29075142-25898d8e-7c84-11e7-9313-0fcca2e04054.png)
Next I write go code to list bucket
`package main

import (
	"fmt"
	"github.com/minio/minio-go"
	"log"
)

func main() {
	// 练习性的，官方提供
	//endpoint := "play.minio.io:9000"
	//accessKeyID := "Q3AM3UQ867SPQQA43P2F"
	//secretAccessKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
	//useSSL := true
	// 自己的
	endpoint := "127.0.0.1:9000" // "127.0.0.1:9000"
	accessKeyID := "EE1XWJ2QV0OYOLJTLK7W"
	secretAccessKey := "zx70NL3M7px0NJIVT7kw/40bsJL5V/c5ZgM2e3QD"
	useSSL := true

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("%#v\n", minioClient) // minioClient is now setup
	log.Printf("listing bucket....")
	buckets, err := minioClient.ListBuckets()
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, bucket := range buckets {
		fmt.Println(bucket.Name)
	} // end for
}
`
When I run the code , return message:
Get https://127.0.0.1:9000/: x509: certificate is valid for 127.0.0.1, not 127.0.0.1
like:
![del_61](https://user-images.githubusercontent.com/19528399/29075286-78c1a48c-7c84-11e7-916b-3f24b74f8ba6.png)
@vadmeste   Could you help me~thank you

**Comment by vadmeste** [comment]
@billschen, the golang error message is weird: `x509: certificate is valid for 127.0.0.1, not 127.0.0.1`

It looks like a golang bug.

Can you paste your go version ? (`go version`)

**Comment by billschen** [comment]
@vadmeste ：
C:\Users\BJB70>go version
**go version go1.8.3 windows/amd64**

**Comment by vadmeste** [comment]
@billschen, in all cases, you should add some code in your go client to trust the certificate that you manually created (which is called a self signed certificate), you need to add the following code:

```
	caCert, err := ioutil.ReadFile("/home/vadmeste/.minio/certs/public.crt")
	if err != nil {
		log.Fatal(err)
	}
	rootCAs := x509.NewCertPool()
	rootCAs.AppendCertsFromPEM(caCert)

	transport := &http.Transport{
		TLSClientConfig: &tls.Config{RootCAs: rootCAs},
		Proxy: http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
		}).DialContext,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		DisableCompression:    true,
	}
	minioClient.SetCustomTransport(transport)
```

**Comment by billschen** [comment]
@harshavardhana , @vadmeste :+1:   Well done!
my self signed certificate work fine ,my all code 
`package main

import (
	"crypto/x509"
	"fmt"
	"github.com/minio/minio-go"
	"io/ioutil"
	"log"
	"net/http"
	"net"
	"crypto/tls"
	"time"
)

func main() {
	endpoint := "192.168.1.149:9000"
	accessKeyID := "EE1XWJ2QV0OYOLJTLK7W"
	secretAccessKey := "zx70NL3M7px0NJIVT7kw/40bsJL5V/c5ZgM2e3QD"
	useSSL := true
	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
	caCert, err := ioutil.ReadFile("C:\\Users\\BJB70\\.minio\\certs\\public.crt")
	if err != nil {
		log.Fatal(err)
	}
	rootCAs := x509.NewCertPool()
	rootCAs.AppendCertsFromPEM(caCert)

	transport := &http.Transport{
		TLSClientConfig: &tls.Config{RootCAs: rootCAs},
		Proxy:           http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: 30 * time.Second,
		}).DialContext,
		MaxIdleConns:          100,
		IdleConnTimeout:       90 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ExpectContinueTimeout: 1 * time.Second,
		DisableCompression:    true,
	}
	minioClient.SetCustomTransport(transport)

	if err != nil {
		log.Fatalln(err)
	}
	log.Printf("%#v\n", minioClient) // minioClient is now setup
	log.Printf("listing bucket....")
	buckets, err := minioClient.ListBuckets()
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, bucket := range buckets {
		fmt.Println(bucket.Name)
	} // end for
}
`
the code run well:
![del_50](https://user-images.githubusercontent.com/19528399/29101292-d03ef7be-7ce3-11e7-9154-3659561dc518.png)
