### ISSUE TITLE
how to put a string to bucket?

### ISSUE THREAD

**Issue by billschen** [minio/minio-go#783]
I want to put a string in program to a bucket use key like  "foo.txt"
I Read [PutObjectStreaming](https://docs.minio.io/docs/golang-client-api-reference#PutObjectStreaming) 
The code like 
`	file, err := os.Open("my-testfile")
	if err != nil {
	    fmt.Println(err)
	    return
	}
	defer file.Close()
	
	n, err := minioClient.PutObjectStreaming("mybucket", "myobject", file)
	if err != nil {
	    fmt.Println(err)
	    return
	}`
**Next** I write code to put a string to bucket:
`	
objectName := "aa.txt"
	var f *os.File
	defer f.Close()
	wt := bufio.NewWriter(f)
	n4, err3 := wt.WriteString("bufferedn，中华人民共和国")
	if err3 !=nil{
		fmt.Println(err3)
		return
	}
	fmt.Println("write %d 个btn", n4)
	wt.Flush()

	nx, err4 := minioClient.PutObjectStreaming("billschen", objectName, f)
	if err4 != nil {
		fmt.Println("PutObjectStreaming error:")
		fmt.Println(err4)
		return
	}else{
		fmt.Println(nx)
	}
`

**BUT**  ERROR HAPPEN on PutObjectStreaming function :**invalid argument**

**Comment by vadmeste** [comment]
@billschen, 

In the second code snippet, f is nil. That's why you have invalid argument error.

**Comment by billschen** [comment]
@vadmeste 👍 Could you tell me a way create one file from a string but not save to disk?
I use golang just a few days~

**Comment by vadmeste** [comment]
Why do you need to create a file without saving it ? You only need to pass io.Reader to PutObjectStream(), as the following example:

`minioClient.PutObjectStreaming("billschen", objectName, bytes.NewReader(|]byte("your string"))`

**Comment by billschen** [comment]
@vadmeste.
   I use minio in company LAN for file shared.
I tkink it is good idea that people can use minio like windowns file system.so, I provide funtions like:create folder,delete folder and list folder.
when people create.a folder,I just create a small file in bucket.and this small file don't show to the use.
so,when doing this function,I don't want to read filr from dish.

**Comment by vadmeste** [comment]
okay, so bytes.NewReader([]byte("string")] should work for you as I suggested above.

**Comment by billschen** [comment]
@vadmeste,Yes.Thank you!
meanwhile,I hope this project can privode like :
https://github.com/aliyun/aliyun-oss-go-sdk
