### ISSUE TITLE
Functional tests not passing when Minio server has a new default region

### ISSUE THREAD

**Issue by vadmeste** [minio/minio-go#791]
When I set Minio region to "us-west-2" in ~/.minio/config.json, functional tests won't pass anymore:

```
$ go run functional_tests.go
...
INFO[0015]                                               file=functional_tests.go function:=main.testGetObjectClosedTwice line#=665
FATA[0041] Error:Put http://localhost:9000/minio-go-testiuzn23cfq9jrzlcnz/1yzgz903xtgj9tceycazirws0cmlla: Connection closed by foreign host http://localhost:9000/minio-go-testiuzn23cfq9jrzlcnz/1yzgz903xtgj9tceycazirws0cmlla. Retry again.minio-go-testiuzn23cfq9jrzlcnz1yzgz903xtgj9tceycazirws0cmlla  file=functional_tests.go function:=main.testGetObjectClosedTwice line#=705
exit status 1
```

**Comment by poornas** [comment]
testGetObjectClosedTwice() test creates a bucket on us-east-1 and does  a PutObject request - server rejects the request because of signature mismatch (server uses u-west-2). Perhaps we should make SERVER_REGION an optional environment variable for Mint so that it isn't hard coded for functional tests.

**Comment by vadmeste** [comment]
@poornas, the test `testPutObjectWithMetadata` is successful though server region is us-west-2, I don't see why `testGetObjectClosedTwice` would fail. I think there is a bug somewhere.

**Comment by poornas** [comment]
The cause is Unexpected EOF when the http request is executed, seems to be related to limitReader implementation(PR #780).  Not identified a fix yet.

**Comment by vadmeste** [comment]
```
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"math/rand"
	"time"

	minio "github.com/minio/minio-go"
)

func main() {
	// Seed random based on current time.
	rand.Seed(time.Now().Unix())

	// Instantiate new minio client object.
	c, err := minio.New("localhost:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatal("Error:", err)
	}

	bucketName := fmt.Sprintf("minio-go-test.%d", rand.Int())
	err = c.MakeBucket(bucketName, "us-east-1")
	if err != nil {
		log.Fatal("Error:", err, bucketName)
	}

	bufSize := rand.Intn(1<<20) + 32*1024
	var reader = ioutil.NopCloser(bytes.NewReader(bytes.Repeat([]byte("a"), bufSize)))
	defer reader.Close()

	// Save the data
	objectName := fmt.Sprintf("obj.%d", rand.Int())
	_, err = c.PutObject(bucketName, objectName, reader, "binary/octet-stream")
	if err != nil {
		log.Fatal("Error:", err, bucketName, objectName)
	}
}
```

This is the code that reproduces the issue, the reason is that a wrong region is specified when creating the bucket. MakeBucket() can manage when the user passes an empty or wrong region but it looks it doesn't update internally the correct region, I guess after calling bucket location API. That's why PUT fails.

**Comment by harshavardhana** [comment]
Is this still a problem @poornas @vadmeste ?

**Comment by kannappanr** [comment]
With the given sample code, I am unable to reproduce the issue with the latest version of minio-go connecting to my local Minio server (Version: 2017-09-01T19:22:40Z) with the region attribute in config.json file set to "us-west-2".

**Comment by vadmeste** [comment]
yeah @kannappanr , sorry.. That example only shows an error log in Minio output which is a normal thing since the passed region is wrong. The following code reproduces the issue seen in minio-go function tests:

```
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"math/rand"
	"os"
	"time"

	minio "github.com/minio/minio-go"
)

type sizedReader struct {
	io.Reader
	size int
}

func (l *sizedReader) Size() int {
	return l.size
}

func (l *sizedReader) Close() error {
	return nil
}

type randomReader struct{ seed []byte }

func (r *randomReader) Read(b []byte) (int, error) {
	return copy(b, bytes.Repeat(r.seed, len(b))), nil
}

// read data from file if it exists or optionally create a buffer of particular size
func getDataReader(filePath string, size int) io.ReadCloser {
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		return &sizedReader{
			Reader: io.LimitReader(&randomReader{seed: []byte("a")}, int64(size)),
			size:   size,
		}
	}
	reader, _ := os.Open(filePath)
	return reader
}

func main() {
	// initialize logging params
	startTime := time.Now()
	function := "GetObject(bucketName, objectName)"
	args := map[string]interface{}{
		"bucketName": "",
		"objectName": "",
	}

	// Seed random based on current time.
	rand.Seed(time.Now().Unix())

	// Instantiate new minio client object.
	c, err := minio.New("localhost:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatalln(function, args, startTime, "", "Minio client object creation failed", err)
	}

	// Enable tracing, write to stderr.
	// c.TraceOn(os.Stderr)

	// Set user agent.
	c.SetAppInfo("Minio-go-FunctionalTest", "0.1.0")

	// Generate a new random bucket name.
	bucketName := fmt.Sprintf("minio-go-test.%d", rand.Int())
	args["bucketName"] = bucketName

	// Make a new bucket.
	err = c.MakeBucket(bucketName, "us-east-1")
	if err != nil {
		log.Fatalln(function, args, startTime, "", "MakeBucket failed", err)
	}

	// Generate 33K of data.
	bufSize := 33 * 1024
	thirtyThreeKiB := bufSize

	var reader = getDataReader("datafile-33-kB", thirtyThreeKiB)
	defer reader.Close()

	// Save the data
	objectName := fmt.Sprintf("obj.%d", rand.Int())
	args["objectName"] = objectName

	_, err = c.PutObject(bucketName, objectName, reader, "binary/octet-stream")
	if err != nil {
		log.Fatalln(function, args, startTime, "", "PutObject failed", err)
	}
}
```

`datafile-33-kB` should not exist in file system to reproduce the issue.

I am currently investigating the exact origin of the problem.

**Comment by kannappanr** [comment]
The fix for this issue is to not set the BucketLocationCache in MakeBucket method in the file api-put-bucket.go . 

`
func (c Client) MakeBucket(bucketName string, location string) (err error) {
	defer func() {
		// Save the location into cache on a successful makeBucket response.
		if err == nil {
			c.bucketLocCache.Set(bucketName, location)
		}
	}()
`
This will require the PutObject to request the Bucket Location from the server and then calculate the signature.

**Comment by vadmeste** [comment]
@kannappanr, thanks for bringing up this. 

Actually it seems there is more than one bug here,

The first one which is catching my attention is that we are retrying requests even when the user passes a io.Reader. We can't seek to the beginning of data before we retry the request. That's why we have that weird error "Connection closed by foreign host" in minio-go.

The second one, is that PutObject() is still signing requests with us-east-1 region (I added some log to detect that), so the correct region must be updated in MakeBucket()

**Comment by vadmeste** [comment]
@harshavardhana, it looks like Minio server doesn't refuse a make bucket request with wrong region, minio-go doesn't even know if it sent a correct or wrong region in contrast to other API calls.

In that case, I think @kannappanr suggestion makes sense now, we shouldn't cache bucket location after a make bucket call. It doesn't seem there is another solution. Besides, it seems to me an acceptable solution since MakeBucket() is not kind of functions that will be heavily called.

**Comment by harshavardhana** [comment]
@vadmeste that was done on purpose . We used to refuse but did that for requirements of gateway. Also region is sort of meaningless we also support region as empty as well. So any region based tests are not valid with Minio.

**Comment by harshavardhana** [comment]
Make bucket can cache but only on success..

**Comment by vadmeste** [comment]
> Make bucket can cache but only on success..

I am not sure I understood this, Make bucket already makes only one successful request to create a bucket even if the passed region is wrong. How caching only on success will resolve the problem ?

**Comment by deekoder** [comment]
This is the related PR https://github.com/minio/minio/pull/4969

**Comment by harshavardhana** [comment]
This is fixed in Minio server @vadmeste , feel free to close it if it fixes the minio-go problem.

**Comment by vadmeste** [comment]
Fixed by https://github.com/minio/minio/pull/4969
