### ISSUE TITLE
how can i generate it about resource share link?

### ISSUE THREAD

**Issue by sunvim** [minio/minio-go#792]
as above the title, minio-go api can't find api, thabks

**Comment by sunvim** [comment]
PresignedGetObject(bucketName, objectName string, expiry time.Duration, reqParams url.Values) (*url.URL, error)

**Comment by irwaank** [comment]
Hi @sunvim 

How do I make the **PresignedGetObject()** not directly download the object, but only rendered it in browser ?
I am uploaded a picture

Thank You
