### ISSUE TITLE
put object to ceph got stuck forever.

### ISSUE THREAD

**Issue by philoles** [minio/minio-go#793]
I used https://hub.docker.com/r/ceph/demo/ to setup a ceph s3 api. Everything works fine with s3cmd.
When I use minio-go, create bucket, get object works.  but put object (FPutObject) got stuck forever. No error shows and never end

**Comment by philoles** [comment]
Also when I use https://github.com/aws/aws-sdk-go to put object to ceph. It works too.

**Comment by harshavardhana** [comment]
minio-go uses streaming signature v4 but default these seems to be a bug on ceph.  As a workaround use minio.NewV2 for now.

**Comment by harshavardhana** [comment]
> minio-go uses streaming signature v4 but default these seems to be a bug on ceph. As a workaround use minio.NewV2 for now

Closing this as ceph bug.
