### ISSUE TITLE
I can't use direct url although  I have use SetBucketPolicy to BucketPolicyReadWrite

### ISSUE THREAD

**Issue by billschen** [minio/minio-go#796]
@vadmeste 
I want to use direct url like 
`<img src="http://192.168.1.40:9000/minio/billschen/imgs/foo.png" alt="bar" />`
I create a bucket in "http://192.168.1.40:9000/minio" and use golang code [SetBucketPolicy](https://docs.minio.io/docs/golang-client-api-reference#SetBucketPolicy) ：
`
err := minioClient.SetBucketPolicy(bucketName,  "", policy.BucketPolicyReadWrite)
`
But I can't use direct url also

**Comment by harshavardhana** [comment]
"/minio" not bucket it is just used in the browser for routing - your original URL is `http://192.168.1.40:9000/billschen/imgs/foo.png` not `http://192.168.1.40:9000/minio/billschen/imgs/foo.png`

**Comment by billschen** [comment]
@harshavardhana 👍  okay! I just make a mistake. 
thank you for your help!
