### ISSUE TITLE
minio.Client.WGet? (Get + io.Writer Feature Request)

### ISSUE THREAD

**Issue by jimrobinson** [minio/minio-go#800]
Have you considered adding a Get function in minio-go that can accept an io.Writer implementation?  That would offer some more flexibility to clients using the API.

As a specific example, I'm looking at implementing an io.Reader / io.Seeker / io.Writer implementation backed by an os.File to allow for streaming very large objects back to the user more quickly.

As the API currently stands it appears that I'll have to use concurrent byte Range requests via the minio-go api to feed my io.Reader / io.Seeker / io.Writer.  So I have a path forward, but a minio.Client.WGet(..., io.Writer) method would have solved the problem in a very straight-forward fashion.

**Comment by harshavardhana** [comment]
Current GetObject implementation is more idiomatic in nature similar to os.Open() and the returned object has all the methods satisfying io.Reader, io.ReaderAt, io.Seeker and io.Closer implementations.

You can implement your own version using lower level core API GetObject to implement such a functionality.

**Comment by jimrobinson** [comment]
Ah, I hadn't realized that under the hood of FGetObject you were just calling getObject and passing that off to io.CopyN.
