### ISSUE TITLE
RemoveObjects works only for files but not for directories

### ISSUE THREAD

**Issue by blacklp** [minio/minio-go#803]
I am trying to use the minio client's RemoveObjects function like this:

```
filesToDelete := make(chan string)

go func() {
	filesToDelete <- prefix
	close(filesToDelete)
}()
errorCh := minioClient.RemoveObjects("my_bucket", filesToDelete)
```

When prefix is an existing file in the remote filesystem, e.g. my_file.txt, the file is correctly removed.

However, when prefix is a directory containing some subdirectories and files, e.g. my_directory, nothing is removed from the remote filesystem.

As the function's signature is
``RemoveObjects(bucketName string, objectsCh chan string) errorCh chan minio.RemoveObjectError`` and the description for the ``objectsCh`` parameter is ``Prefix of objects to be removed``,  I would expect it to correctly match and remove directories, since they are actually prefixes.

Could you please confirm that this function is currently working as expected?

Thanks in advance!

Lucía

**Comment by vadmeste** [comment]
> Could you please confirm that this function is currently working as expected?

RemoveObjects() can only remove objects but nothing else. To remove `my_directory` and all objects inside, you need to call ListObjects() with recursive flag enabled and then pass found objects to RemoveObjects()

**Comment by blacklp** [comment]
Ok, good to know. Thanks a lot for the explanation!
