### ISSUE TITLE
ListObjectsV2 returns partial results

### ISSUE THREAD

**Issue by blacklp** [minio/minio-go#804]
I am using the ListObjectsV2 function to get a list of all the files inside a certain directory:

```
endpoint := "my.endpoint.com"
accessKey := "my-access-key"
secretKey := "my-secret-key"
minioClient, err := minio.New(endpoint, accessKey, secretKey, true)
doneCh := make(chan struct{})
defer close(doneCh)

prefix := "directory"
// prefix := "root_file.txt"
objectsCh := minioClient.ListObjectsV2("my_bucket", prefix, true, doneCh)
filesToDelete := make(chan string)

go func() {
	count := 0
	for objectCh := range objectsCh {
		filesToDelete <- objectCh.Key
		count++
	}
	fmt.Println("count: ", count)
}()

errorCh := minioClient.RemoveObjects("my_bucket", filesToDelete)

for e := range errorCh {
	fmt.Println(e.Err)
}
```

With the following file structure:
```
/directory/subdirectory/subfile.txt
/directory/file.txt
root_file.txt
```

When I indicate ``prefix=directory`` I get different results every time I run it. Sometimes I get ``/directory/file.txt``. Some other times I get both ``/directory/subdirectory/subfile.txt`` and ``/directory/file.txt``

When I indicate ``prefix=root_file.txt``, sometimes the root_file.txt is returned as a result and some other times no file is returned.

Could you please indicate whether there is any issue in ListObjectsV2? I saw a similar behavior when using the ListObjects function?

Thanks in advance!
Lucía

**Comment by vadmeste** [comment]
@blacklp, can you paste your (minimal) code here ? I guess you missed something to do in your code

**Comment by blacklp** [comment]
@vadmeste I have just updated the description. Could you please confirm that it is Ok now?

**Comment by vadmeste** [comment]
@blacklp, you don't have to use the goroutine, using the goroutine is causing the problem for you, just disable it.

**Comment by blacklp** [comment]
Well, now I see that the code is still incomplete. I am using the goroutine to fill another channel, i.e. the delete channel that gets the data from the result of the list call. In such case I need to use a goroutine, right? I will update the description with the full code.

**Comment by blacklp** [comment]
I have just updated.

**Comment by vadmeste** [comment]
> I have just updated.

Can you paste a more complete code? with at least main() in it ? that will help us clarify what is the bug in your code.

**Comment by blacklp** [comment]
@vadmeste Thanks for your reply. That would be a bit hard for me since what I am developing is a Cloud Foundry plugin, so there is no main().

**Comment by blacklp** [comment]
I have just updated the code to include the RemoveObjects part.

**Comment by blacklp** [comment]
I already fixed the issue by using a temporary array to keep the results returned by the ListObjectsV2 call and then filling the channel needed for RemoveObjects by iterating over the array.

**Comment by vadmeste** [comment]
@blacklp, this short code works fine for me:

```
package main

import (
	"fmt"
	"log"

	minio "github.com/minio/minio-go"
)

func main() {
	endpoint := "localhost:9000"
	accessKey := "minio"
	secretKey := "minio123"
	minioClient, err := minio.New(endpoint, accessKey, secretKey, false)
	if err != nil {
		log.Fatal(err)
	}
	doneCh := make(chan struct{})
	defer close(doneCh)

	prefix := "directory"
	// prefix := "root_file.txt"
	objectsCh := minioClient.ListObjectsV2("mybucket", prefix, true, doneCh)
	filesToDelete := make(chan string)

	go func() {
		count := 0
		for objectCh := range objectsCh {
			filesToDelete <- objectCh.Key
			count++
		}
		fmt.Println("count: ", count)
		close(filesToDelete)
	}()

	errorCh := minioClient.RemoveObjects("mybucket", filesToDelete)

	for e := range errorCh {
		fmt.Println(e.Err)
	}
}
```

The only difference between this code and yours is the `close(filesToDelete)` code which is needed to finish the removal.

**Comment by blacklp** [comment]
I am also using ``close(filesToDelete)``. I forgot to paste it. That wasn't the issue. I fixed in the way described in my previous comment. Thanks!
