### ISSUE TITLE
Minio Go API PutObject() reads the entire object into memory

### ISSUE THREAD

**Issue by justinclift** [minio/minio-go#805]
Tracking down a problem with our server running out memory when uploading new example data sets last night (1GB+ each).

After converting much of our initial naive code :wink: to now use fixed sized buffers and/or streaming, the remaining problem seems to be in Minio Go API code.  Specifically, at least this line (called by PutObject) appears to read the entire object into memory before attempting the transfer:

https://github.com/minio/minio-go/blob/e7255dff98bae181f1710a21702fcf15aab24e95/api.go#L568

While not a problem with small objects, it's fairly catastrophic (!) with larger ones.

Any workarounds until this is fixed?

**Comment by justinclift** [comment]
Ahhh, `PutObjectStreaming()` seems to do the job. :smile:

**Comment by vadmeste** [comment]
Hey @justinclift,


> minio-go/api.go
> Line 568 in e7255df
>  errBodyBytes, err := ioutil.ReadAll(res.Body)

If the code reached the line above, it means there is an error happened and we expect a short xml error body returned from the server. There is some work done to address this issue, are you using the last master version ?

**Comment by justinclift** [comment]
Nah, not using the latest master... I should probably update eh?

Either way the PutObjectStreaming() is working, which is likely good enough for now. :smile:

**Comment by vadmeste** [comment]
Since minio-go 3.0.0, PutObject() uses AWS Streaming Signature V4 by default. @justinclift, what version are you using ?

**Comment by justinclift** [comment]
Hmmm, git log on the minio-go source dir shows it's HEAD as `f2362d9e7d8daf89594ee0a079be2424eaf360be`.  So, looks to be ~ v2.1.0.

I'll update it now and see if that helps too. :smile:

**Comment by justinclift** [comment]
Yep, that seems good too.  Updated to commit `e7255dff98bae181f1710a21702fcf15aab24e95` (~3.1.0) and our previous `PutObject()` code now seems to work without excessive memory.

I'll try some of our multi-GB data sets just to make sure, but yep, I think this is taken care of now.

Thanks @vadmeste. :smile:
