### ISSUE TITLE
Is PutObjectStreaming() listed in the wrong spot?

### ISSUE THREAD

**Issue by justinclift** [minio/minio-go#806]
Looking at the hmm... "Table of Contents" thing here:

&nbsp; &nbsp; https://docs.minio.io/docs/golang-client-api-reference

`PutObjectStreaming()` is listed underneath the "Encrypted Object operations" column.

Is that correct?  Kind of thinking it should it be listed under "Object operations" instead, but not sure.

**Comment by vadmeste** [comment]
@justinclift, you are right, this needs to be fixed, thanks for reporting it.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by deekoder** [comment]
Thanks @justinclift
