### ISSUE TITLE
API cleanup and new APIs to be added 

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-go#819]
- Bring back PutEncryptedObject(bucket, object, data, size, encryptedMaterials)
- Implement FGetEncryptedObject(), FPutEncryptedObject() as well
- GetEncryptedObject() takes (bucket, object, encryptedMaterials)
- GetObject() takes (bucket, object, options) - options here is GetObjectOptions struct

```
type GetObjectOptions struct {
       Conditions RequestHeaders
       Encrypt     encrypt.Materials
}
```

- pkg/encrypt needs to now provide two concrete types ServerMaterials, ClientMaterials.  Default ClientMaterials is set to AES-CBC encryption, explicitly if set will use DARE encryption.

**Comment by harshavardhana** [comment]
// cc @aead @poornas please update if i have missed some things. Thanks

**Comment by poornas** [comment]
There was additional implementation details on passing PutObjectOptions as struct instead of a pointer to struct as well as removing EncryptionMaterials from the PutObjectOptions struct.

**Comment by poornas** [comment]
PutEncryptedObject signature needs to be 
```PutEncryptedObject(bucket, object, data, size, encryptedMaterials,opts)``` so that reader and metadata can be passed in. Or we could leave it as it was before the refactor to take in metadata and reader as additional args.

**Comment by harshavardhana** [comment]
We don't need opts variant for PutEncryptedObject current API can remain the same serving the purpose.
