### ISSUE TITLE
copy object or folder with js client api

### ISSUE THREAD

**Issue by faizalpribadi** [minio/minio-go#820]
There's weird for me, i'm trying to copy folder with js client doesn't working , but with `mc` tool, can do it with `mc  cp --recursive folder host/bucket/inside`, im looking reference in the docs (https://docs.minio.io/docs/javascript-client-api-reference), what i'm missed here ? can anyone help ? thanks

**Comment by harshavardhana** [comment]
CopyObject is only meant for an source object to destination object @faizalpribadi which employs server side copy. CopyObject is an implementation of following AWS S3 API http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html

`mc` is a tool and implements a richer composed functionality by using multitudes of APIs one of it is CopyObject(). 

`minio-go` implements the REST API instead for talking to an S3 compatible server and some composable functionality but `mc cp` has nothing to do with CopyObject in minio-go.

**Comment by deekoder** [comment]
@faizalpribadi  can we close this. I believe PutObject is something that will be useful for your needs.

**Comment by faizalpribadi** [comment]
Sureee :)
