### ISSUE TITLE
Support Client and Server side encryption

### ISSUE THREAD

**Issue by aead** [minio/minio-go#823]
Currently minio-go supports only client-side encryption (and only a "insecure" AWS compatible version). The client and server-side encryption should be unified. Further the minio-go API should be provided functions like GetEncryptedObject and PutEncryptedObject (and the file-based equivalents).

**Comment by aead** [comment]
#830 is marked as high priority but recent changes of SSE-C require some conceptual changes to the PR @harshavardhana proposed to split PR to get the 4.0.0 release out.
I agree that we may can define the API in advance (to avoid breaking changes) and later add additional implementations. (Of course we would not release just the API but maybe defer different implementations (AES-CBC vs. DARE))

One important API change I would like to see in the 4.0 release is:
`GetEncryptedObject(bucket, object, password string) (Object, error)` (also for PUTs)
This would make encryption **much** easier for users - they even don't need to import the `pkg/encrypt` package anymore.
Further `Get/PutObjectOptions` need two different fields (one for SSE and one for CSE) because clients can use SSE and CSE at the same time.
There is bunch of other stuff to do - so is 4.0 release that important to break issue/PR into parts @deekoder ?

**Comment by harshavardhana** [comment]
> There is bunch of other stuff to do - so is 4.0 release that important to break issue/PR into parts @deekoder ?

4.0 release here is blocking mint release @aead  - that is one of the reasons why i asked you to split PRs.

**Comment by aead** [comment]
I see - Okay I try to get this PR (re-viewable / ready-to-merge) this week. Will split it into API and functionality...

**Comment by harshavardhana** [comment]
We are going to make 4.0.0 anyways, we can make 5.0.0 if we break the API.

**Comment by aead** [comment]
Close - See #883
