### ISSUE TITLE
Content-Md5 header should not be set when the md5 digest is empty

### ISSUE THREAD

**Issue by kannappanr** [minio/minio-go#831]
Currently the check for md5 digest checks only whether it is nil. It should also check if it is empty, then it should skip.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-go/commit/414c6b6a2e97428776cd831d9745589ebcf873e5

**Comment by kannappanr** [comment]
This is a duplicate of of #828 . So closing it.
