### ISSUE TITLE
find method remove objects the start with save prfix

### ISSUE THREAD

**Issue by billschen** [minio/minio-go#854]
I know the api have [RemoveObject](https://docs.minio.io/docs/golang-client-api-reference#RemoveObject) method and  [RemoveObjects](https://docs.minio.io/docs/golang-client-api-reference#RemoveObjects) method。Now I want to Remove Objects the have the save prefix.Like
objects 
a/c/hello.txt
a/c/world.pdf
I find one method Like  **RemoveObjects(bucketName string, bucketName preifx) (errorCh <-chan RemoveObjectError)**

**Comment by harshavardhana** [comment]
Here is an example that you need to use 

```go
        objectsCh := make(chan string)

        // Send object names that are needed to be removed to objectsCh
        go func() {
                defer close(objectsCh)
                for obj := range minioClient.ListObjects(bucket, prefix, nil)  {
                        objectsCh <- obj.Key
                }
        }()

        // Call RemoveObjects API
        errorCh := s3Client.RemoveObjects("my-bucketname", objectsCh)

        // Print errors received from RemoveObjects API
        for e := range errorCh {
                log.Fatalln("Failed to remove " + e.ObjectName + ", error: " + e.Err.Error())
        }

        log.Println("Success")
```

**Comment by billschen** [comment]
@harshavardhana :+1: than you.
