### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by jawnsy** [minio/minio-go#858]
Hi there,

Thanks for your hard work producing this great library! I noticed that it's been about a month since the last release, and several interesting changes have landed in `master` in that time: [https://github.com/minio/minio-go/compare/3.0.3...master](https://github.com/minio/minio-go/compare/3.0.3...master), particularly several new APIs.

Please consider releasing a new version soon. I noticed this because the vendor dependency manager I'm using (`dep`) seems to pull the latest release rather than master.

Cheers,

Jonathan

**Comment by harshavardhana** [comment]
We will be making a release soon.

**Comment by ebozduman** [comment]
This is not an issue @jawnsy .
Please use slack for questions and recommendations.
