### ISSUE TITLE
Re-implement pkg/policy package

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-go#863]
pkg/policy is complex with much expanded scope in its current implementation, which is not needed for AWS S3 APIs requirement. Simplify the package for future maintenance and stability.

**Comment by deekoder** [comment]
moving it to future milestone.

**Comment by deekoder** [comment]
Will close it now as wont fix. We will revisit this when we have more bandwidth to take it on.

**Comment by deekoder** [comment]
We have not had the cycles to fix this issue. Will close it and reopen it when we are able to. This is also a great item for community contribution, if anyone wants to take it up.
