### ISSUE TITLE
Uploading files does not preserve timestamps

### ISSUE THREAD

**Issue by deepakprabhakara** [minio/minio-go#864]
Using FPutObject doesn't seem to preserve modified timestamps on the files. Is there an option to enable this?

**Comment by harshavardhana** [comment]
There is no way preserve this from our end. You need to save original mtime as part of UserMetadata . It requires special interpretation from your application so it is upto you.

**Comment by deepakprabhakara** [comment]
Aah yes, thanks @harshavardhana . I'll checkout the possible headers from my end.

**Comment by deepakprabhakara** [comment]
Though it looks like there is some amazon specific prefixing going on with user metadata. It should be enough to pass Last-Modified header from my side but it seems like minio is no doing it?

**Comment by harshavardhana** [comment]
No there is no way to directly set Last-Modified. Only way is using x-amz-meta style.

**Comment by deepakprabhakara** [comment]
Aah, makes sense. Thanks again. Sorry for the noise. :-)
