### ISSUE TITLE
Support SSE-C GET, PUT and HEAD

### ISSUE THREAD

**Issue by aead** [minio/minio-go#882]
This is a proposal for adding SSE-C support. 

## Proposal
In general there are two different ways to use encryption:
 - SSE-C through `Get/Put/Stat EncryptedObject`
 - SSE-C, CSE, and KMS through `Get/Put/Stat Options` (will be addressed in a separate issue / PR)

Why use SSE-C for `Get/Put/Stat EncryptedObject`:
 - SSE-C works for all S3 compatible object storage solutions (Minio, AWS, ....)
 - SSE-C works across all S3 compatible object storage solutions (Minio, AWS, ....)
 - SSE-C does not require encryption library support for the client-sdk

### API
This proposal defines the following API:
 - `GetEncryptedObject(bucket, object, password string) (io.ReadCloser, error)`
 - `FGetEncryptedObject(bucket, object, filePath, password string) error`
 - `PutEncryptedObject(bucket, object string, reader io.Reader, size int64, password string) (int64, error)`
 - `FPutEncryptedObject(bucket, object, filePath, password string) (int64, error)`
 - `StatEncryptedObject(bucket, object, password string) (ObjectInfo, error)`
 - `ComposeObject(dst DestinationInfo, src ...SourceInfo) error`

The general idea is that the `password` and the `bucket + object` is used to derive an encryption key:
`key = scrypt.Key(password, bucket + object, 32768, 8, 1, 32) // scrypt 2017 params`
The `key` is unique per object identifier (`bucket + object`). It's the responsibility of the server to ensure that the encryption key is unique (minio server does that - see DARE integration). Even if one `key` is compromised the `password` is not compromised (as long as scrypt is secure) - this may happen e.g. during TLS MitM.

Additionally it's very convenient for clients to use (one) passwords instead of dealing with symmetric keys and  the security of algorithms.

**Comment by harshavardhana** [comment]
do we need this to be open @aead ?

**Comment by aead** [comment]
Not implemented at all - This was addressed by a PR I opened (https://github.com/minio/minio-go/pull/883) but I closed it since it also required CSE refactoring to avoid API versioning issues. I will address.

**Comment by harshavardhana** [comment]
> Not implemented at all - This was addressed by a PR I opened (#883) but I closed it since it also required CSE refactoring to avoid API versioning issues. I will address.

Oh yes i got confused with server issue, i see this is minio-go
