### ISSUE TITLE
Do you have the api for getting the quotas on users and on a bucket owned by users?

### ISSUE THREAD

**Issue by yingyan003** [minio/minio-go#889]
Our project need these APIs to meet demands,but I can't find them in your APIs，or maybe I don't
exactly know which one is。

**Comment by yingyan003** [comment]
I sincerely hope you provide this function

**Comment by harshavardhana** [comment]
> Our project need these APIs to meet demands,but I can't find them in your APIs，or maybe I don't
> exactly know which one is

AFAIK there are no such S3 APIs . This is an S3 API SDK so unless you can point us to an exact API for your needs there is nothing we can do here.

**Comment by yingyan003** [comment]
we mean to operate the radosgw of CEPH with S3 API compatible,but the api we want seems just provided by ceph itself,not nimio-go.Thanks.

**Comment by harshavardhana** [comment]
Can you point us to the API ?

**Comment by harshavardhana** [comment]
> we mean to operate the radosgw of CEPH with S3 API compatible,but the api we want seems just provided by ceph itself,not nimio-go.Thanks.

I don't see anything related to quotas API here http://docs.ceph.com/docs/master/radosgw/s3/

**Comment by yingyan003** [comment]
http://docs.ceph.com/docs/master/radosgw/adminops/?highlight=quota.
almost in the end of the page,just like "GET USER QUOTA" . But I Just realize that it seems not the part of S3 APIs compatible.
