### ISSUE TITLE
got "The authorization mechanism you have provided (AWS4-HMAC-SHA256) is not supported" when connecting to riak

### ISSUE THREAD

**Issue by IvanLuber** [minio/minio-go#891]
I currently have a code in ruby which successfully connected to a Riak CS host. using fog-aws [https://github.com/fog/fog-aws](url) with this configuration :
```
FOG_CREDENTIALS = {
  provider:               "AWS",
  aws_access_key_id:      ENV["RIAKCS_KEY"],
  aws_secret_access_key:  ENV["RIAKCS_SECRET"],
  aws_signature_version:  2,
  scheme:                 "http",
  connection_options: {
    proxy: ENV["RIAKCS_HOST"],
    instrumentor: ActiveSupport::Notifications
  }
}
Fog::Storage.new(FOG_CREDENTIALS)
```

I need to make a same client connection in golang , using minio-go (which is btw, have a great tutorial and code examples). 
So I made :
```
minioClient, err := minio.New(ENV["RIAKCS_HOST"], ENV["RIAKCS_KEY"], ENV["RIAKCS_SECRET"], false)
found, err := minioClient.BucketExists("uploads") // "uploads" is an existing bucket name in corresponding host

```

But I got error in the last line (as this issue's title). Is Riak CS really not supported ?
CMIIW, but I read in a reddit post that riak cs is signature version 2 and default of minio-go is version 4. Is there any way to change the default?

I'm quite new in using aws & riak cs, I hope you can answer and explain it to me,
Best Regards, Thanks in advance ~

*Im using the latest version of minio-go,
*fog-aws version (0.4.0)

**Comment by IvanLuber** [comment]
*Im using the latest version of minio-go,
*fog-aws version (0.4.0)

**Comment by harshavardhana** [comment]
You should use minio.NewV2() to use signature V2 . Signature v4 is default.

**Comment by IvanLuber** [comment]
omg it works. Thank you so much for the fast-response.
I didn't find that function on [https://docs.minio.io/docs/golang-client-api-reference](url) .
Sorry for my simple Questions.

Again , Thanks ! It's a great service

**Comment by harshavardhana** [comment]
Well it is in our interest to actively deprecate signature V2 usage so API.md only describes the safest and latest. For more detailed docs would be https//godoc.org/github.com/minio/minio-go
