### ISSUE TITLE
functional test: server side encrypted copy object fails on mint

### ISSUE THREAD

**Issue by poornas** [minio/minio-go#897]
testEncryptedCopyObjectWrapper not being run conditionally -- fails when run with ENABLE_HTTPS=0.

Running minio-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {},
  "duration": 2,
  "error": "Requests specifying Server Side Encryption with Customer provided keys must be made over a secure connection",
  "function": "testEncryptedCopyObjectWrapper(minioClient)",
  "message": "PutObjectWithSize failed",
  "name": "minio-go",
  "status": "fail"
}

**Comment by poornas** [comment]
it is possible my mint image is older - see that tls check is already present in the functional tests. removing mint image and rebuilding..

**Comment by harshavardhana** [comment]
> it is possible my mint image is older - see that tls check is already present in the functional tests. removing mint image and rebuilding..

This we already fixed in a previous run @poornas you might have to check again locally.

**Comment by poornas** [comment]
closing this - as issue was caused by docker pull not rebuilding layer and retaining older cached version.
