### ISSUE TITLE
Uploads never do checksums?

### ISSUE THREAD

**Issue by lauri-elevant** [minio/minio-go#914]
The signature of the `putObjectNoChecksum`  function is as follows:

```
// putObjectNoChecksum special function used Google Cloud Storage. This special function
// is used for Google Cloud Storage since Google's multipart API is not S3 compatible.
func (c Client) putObjectNoChecksum(ctx context.Context, bucketName, objectName string, reader io.Reader, size int64, opts PutObjectOptions) (n int64, err error) {
...
```

But apparently it is used in a lot of ways, in addition to handling the special case of Google Cloud Storage. For example:
https://github.com/minio/minio-go/blob/master/api-put-object.go#L155

This is confusing. Is it skipping the checksum intentionally?

**Comment by harshavardhana** [comment]
Yes it is skipping it intentionally for Google Cloud Storage @lauri-elevant

**Comment by lauri-elevant** [comment]
Thanks for looking into it! 

> Yes it is skipping it intentionally for Google Cloud Storage @lauri-elevant
This is clear. 

But if you go to line 155:
https://github.com/minio/minio-go/blob/master/api-put-object.go#L155

It is actually used also for the generic case as well. Does the library do streaming checksums at all, ever?

**Comment by harshavardhana** [comment]
> It is actually used also for the generic case as well. Does the library do streaming checksums at all, ever?

It is on purpose, it doesn't calculate md5 or sha256 it simply does streaming signature v4 - https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

**Comment by lauri-elevant** [comment]
Understood and this is certainly reassuring :) Thank you for the link and apologies for turning your tracker into a support board.

We have a lot of services to convert from Swift to S3 and this library seems to be **perfect** (compared to offical AMZ SDK) if we want to carry a bit less cruft and give ops guys free reign to run Minio / AMZ / Google / Ceph where appropriate.

Kudos!
