### ISSUE TITLE
Can't connect to digitalocean spaces using it's default example

### ISSUE THREAD

**Issue by johncming** [minio/minio-go#916]
https://developers.digitalocean.com/documentation/spaces/

**Comment by harshavardhana** [comment]
Is there any more information that you can provide to help us? Like a debug output or the error that occurred.

**Comment by harshavardhana** [comment]
Closing this issue with lack of information.

**Comment by johncming** [comment]
Run this code in the link: https://developers.digitalocean.com/documentation/spaces/

`package main

import (
    "fmt"
    "log"
    "os"

    "github.com/minio/minio-go"
)

func main() {
    accessKey := os.Getenv("SPACES_KEY")
    secKey := os.Getenv("SPACES_SECRET")
    endpoint := "nyc3.digitaloceanspaces.com"
    ssl := true

    // Initiate a client using DigitalOcean Spaces.
    client, err := minio.New(endpoint, accessKey, secKey, ssl)
    if err != nil {
        log.Fatal(err)
    }

    // List all Spaces.
    spaces, err := client.ListBuckets()
    if err != nil {
        log.Fatal(err)
    }
    for _, space := range spaces {
        fmt.Println(space.Name)
    }
}`

Its output is nothing.

**Comment by kannappanr** [comment]
@johncming I tested the above code with my keys and I do not see any issue. Maybe you do not have any buckets. Can you try the following code?

```
package main

import (
    "fmt"
    "log"

    "github.com/minio/minio-go"
)

func main() {
    accessKey := "Access_Key" // Replace it with your key
    secKey := "Secret_Key" // Replace it with you secret
    endpoint := "nyc3.digitaloceanspaces.com"
    ssl := true

    // Initiate a client using DigitalOcean Spaces.
    client, err := minio.New(endpoint, accessKey, secKey, ssl)
    if err != nil {
        log.Fatal(err)
    }

    // Create new bucket.
    err = client.MakeBucket("mytestbucket", "us-east-1")
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println("Successfully created mytestbucket.")

    // List all Spaces.
    spaces, err := client.ListBuckets()
    if err != nil {
        log.Fatal(err)
    }
    fmt.Print("Number of spaces is ")
    fmt.Println(len(spaces))
    for _, space := range spaces {
        fmt.Println(space.Name)
    }

    // Remove bucket.
    err = client.RemoveBucket("mytestbucket")
    if err != nil {
        fmt.Println(err)
        return
    }
}
```
Can you paste the output you see on your screen?

**Comment by johncming** [comment]
It worked!
Thank you!

**Comment by kannappanr** [comment]
Great! Will close the issue. Please feel free to open an issue if you have any further questions.
