### ISSUE TITLE
support region detection for GET

### ISSUE THREAD

**Issue by bodepd** [minio/minio-go#923]
as a part of the GET command, a call to HEAD fails if region is not passed when the region is not us-east-1.

This is because the call to c.getBucketLocation(metadata.bucketName) does not seem to be returning the correct bucket name (in my case it was us-west-2, but this call returned us-east-1)

this results in a 400 from the HEAD call used to get the checksum.

**Comment by harshavardhana** [comment]
In a case where you have GetBucketLocation API disabled in your IAM policy you simply use NewWithRegion to pass your required region @bodepd

**Comment by bodepd** [comment]
@harshavardhana I can try setting that policy in AWS and see if New works without setting regions. Thanks!

**Comment by harshavardhana** [comment]
> @harshavardhana I can try setting that policy in AWS and see if New works without setting regions. Thanks! I figured out the workaround, but I was working on a downstream project and this issue caused me quite a bit of confusion ( I had to dig around in the minio code to figure it out) I want to make sure that I make the appropriate changes downstream to make sure no one needs to figure this out again :)

Unfortunately we cannot correctly throw an valid error here @bodepd since we don't know what APIs you might have disabled, when GetBucketLocation is disabled we simply employ best possible by choosing default region and then failing.

**Comment by bodepd** [comment]
This behavior worked for PUT, but not GET. IE: a call to `minioClient.FPutObject` without any region being provided makes two PUT calls to S3. One with the wrong default region and one with the correct region.

**Comment by harshavardhana** [comment]
> This behavior worked for PUT, but not GET. IE: a call to minioClient.FPutObject without any region being provided makes two PUT calls to S3. One with the wrong default region and one with the correct region. Which results in the call ultimately succeeding.

It works because inconsistently S3 returns `x-amz-bucket-region` HTTP header which we use to successfully retry the request.

**Comment by bodepd** [comment]
@harshavardhana haha. you really know how the code internals work :)

**Comment by kannappanr** [comment]
Marking the issue as answered. Please feel free to open a new issue if you have any more questions.
