### ISSUE TITLE
Client wasting connections

### ISSUE THREAD

**Issue by folbricht** [minio/minio-go#924]
Under load, the client is currently wasting TCP connection and not properly re-using them. This can very quickly lead to exhaustion and errors like:
```
Put http://127.0.0.1:9000/store/e29c518982e2bbf93efc7743e7ef3abff8f403cf811cdbc9e27b7701a42d92a5: dial tcp 127.0.0.1:9000: connect: can't assign requested address
```

Reproduce with this code, while watching the number of connections on the system.
```golang
	minioClient, err := minio.New(endpoint, accessKeyID, secretAccessKey, useSSL)
	if err != nil {
		log.Fatalln(err)
	}

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			for i := 0; i < 10000; i++ {
				minioClient.BucketExists(bucketName)
			}
			wg.Done()
		}()
	}
	wg.Wait()
```

The issue appears to be in this line https://github.com/minio/minio-go/blob/368f6da0bdf6d5bb6fbcbf6afdb626e711bab6df/transport.go#L37 
It actually needs to read:
```golang
MaxIdleConnsPerHost:   100,
```
If that is not set, it defaults to http.DefaultMaxIdleConnsPerHost (2) and connections are wasted.

**Comment by harshavardhana** [comment]
You can set your own custom transport using SetCustomTransport().

Also can you elaborate a bit more about the issue ?

**Comment by folbricht** [comment]
`MaxIdleConns` limits the total number of connections kept in the pool for re-use. In addition, `MaxIdleConnsPerHost` limits the number for a single host. Since a minio client usually (always?) connects to the same host, setting `MaxIdleConns=100` won't really have much of an impact since the idle connection pool is limited to 2 anyway.

Now, with the pool set to a limit of 2, and when using the client heavily from 2+ goroutines, the http.Transport will open a connection, use it, then try to return it to the idle-pool which often fails since there's a limit of 2. So it's going to close the connection and new ones will be opened on demand again, many of which get closed soon after being used. Since those connections/sockets don't disappear from the OS immediately, they add up quite quickly until limits are reached.

If you run the code above against a local instance of the minio server, then at the same time watch the output of `netstat -anl|grep 9000|wc -l` or similar to see the old connections piling up, then getting reaped a few seconds later.

**Comment by harshavardhana** [comment]
Looks like Go http is behaving as expected will need to add an additional `MaxIdleConnsPerHost: 100`.
