### ISSUE TITLE
Error:  "undefined: NewAsymmetricKey" while trying to use Asymmetric encryption

### ISSUE THREAD

**Issue by wilyarti** [minio/minio-go#931]
When I try to use your example for Asymmetric Encryption I get "undefined: NewAsymmetricKey"

I am at a loss to why this error occurs. The NewSymmetricKey func works fine.

Here is example code:
https://github.com/wilyarti/hashtree/blob/master/test.go

**Comment by wilyarti** [comment]
aSymmetricKey,err  := encrypt.NewAsymmetricKey(privateKey, publicKey) works thanks.

I will update your examples when I get the time. Thank you.

**Comment by nitisht** [comment]
Great, thank you @wilyarti

**Comment by vadmeste** [comment]
Let's reopen this so we don't forget about this issue.
