### ISSUE TITLE
Issues with high memory consuption when running concurrent go routines and minio s3Client.PutEncryptedObject

### ISSUE THREAD

**Issue by wilyarti** [minio/minio-go#945]
I have a program that runs (5) concurrent go routines that implement the s3Client.PutEncryptedObject function.

I have over 2000 files to upload and have noticed a large memory consumption of around 2GB for the length of the programs life.

I have analyzed the program while running using pprof and the output is in this folder: https://github.com/wilyarti/hashtree/tree/master/debug

The problem seems to be: github.com/minio/minio-go.Client.putObjectMultipartStreamNoLength consuming over 1200MB of RAM.

There are obviously inefficiencies elsewhere in my program but this part is consuming %96 of the ram.

The other interesting detail is high cpu usage:
 0 0% 96.41% 4.16s 87.95% github.com/minio/minio-go.Client.putObjectMultipartStreamNoLength

Please refer to https://github.com/wilyarti/hashtree/blob/master/debug/analysis.txt for CPU usage.

Please let me know if I can provide more details.

**Comment by harshavardhana** [comment]
Do not use the encrypted APIs just yet they are being revamped. Memory usage is expected because we have to upload in parts when we don't know the size and we have to buffer up the memory of 64MiB for each Put()

We are revamping the API such that only SSE-C is supported.

**Comment by wilyarti** [comment]
Ok. I will have implement client side encryption myself. Server side encryption doesn't suit my purpose.

**Comment by harshavardhana** [comment]
You can simply use sio.Reader implementation  https://godoc.org/github.com/minio/sio#EncryptReader

**Comment by harshavardhana** [comment]
@wilyarti here is an example of how you can achieve this... 

```go
package main

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"os"

	"github.com/minio/minio-go"
	"github.com/minio/sio"
	"golang.org/x/crypto/hkdf"
)

const (
	// SSE dare package block size.
	sseDAREPackageBlockSize = 64 * 1024 // 64KiB bytes

	// SSE dare package meta padding bytes.
	sseDAREPackageMetaSize = 32 // 32 bytes
)

// EncryptedSize returns the size of the object after encryption.
// An encrypted object is always larger than a plain object
// except for zero size objects.
func getEncryptedSize(size int64) int64 {
	ssize := (size / sseDAREPackageBlockSize) * (sseDAREPackageBlockSize + sseDAREPackageMetaSize)
	if mod := size % (sseDAREPackageBlockSize); mod > 0 {
		ssize += mod + sseDAREPackageMetaSize
	}
	return ssize
}

func main() {
	// Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY, my-testfile, my-bucketname and
	// my-objectname are dummy values, please replace them with original values.

	// Requests are always secure (HTTPS) by default. Set secure=false to enable insecure (HTTP) access.
	// This boolean value is the last argument for New().

	// New returns an Amazon S3 compatible client object. API compatibility (v2 or v4) is automatically
	// determined based on the Endpoint value.
	s3Client, err := minio.New("localhost:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatalln(err)
	}

	// the master key used to derive encryption keys
	// this key must be kept secret
	masterkey, err := hex.DecodeString("000102030405060708090A0B0C0D0E0FF0E0D0C0B0A090807060504030201000") // use your own key here
	if err != nil {
		fmt.Printf("Cannot decode hex key: %v", err) // add error handling
		return
	}

	// generate a random nonce to derive an encryption key from the master key
	// this nonce must be saved to be able to decrypt the data again - it is not
	// required to be kept secret
	var nonce [32]byte
	if _, err = io.ReadFull(rand.Reader, nonce[:]); err != nil {
		fmt.Printf("Failed to read random data: %v", err) // add error handling
		return
	}

	// derive an encryption key from the master key and the nonce
	var key [32]byte
	kdf := hkdf.New(sha256.New, masterkey, nonce[:], nil)
	if _, err = io.ReadFull(kdf, key[:]); err != nil {
		fmt.Printf("Failed to derive encryption key: %v", err) // add error handling
		return
	}

	object, err := os.Open("/etc/issue")
	if err != nil {
		log.Fatalln(err)
	}
	defer object.Close()
	objectStat, err := object.Stat()
	if err != nil {
		log.Fatalln(err)
	}

	encrypted, err := sio.EncryptReader(object, sio.Config{Key: key[:]})
	if err != nil {
		log.Fatalln(err)
	}

	n, err := s3Client.PutObject("testbucket", "my-objectname", encrypted, getEncryptedSize(objectStat.Size()), minio.PutObjectOptions{
		ContentType: "application/octet-stream",
	})
	if err != nil {
		log.Fatalln(err)
	}
	log.Println("Uploaded", "my-objectname", " of size: ", n, "Successfully.")
}
```

**Comment by aead** [comment]
@wilyarti I can only recommend to use the shown solution instead of AWS S3 client-side-encryption. 
The AWS client side encryption has a flawed design and it is non-trivial to use it correctly. Even if you would use it correctly it will cause very high memory consumption.

**Comment by wilyarti** [comment]
Thank you harshavardhana for going out of your way to help. I implemented you example code in 30 mins and the performance is dramatically improved. The error rate has also reduced.

Thanks again.
