### ISSUE TITLE
Publicly Put Object

### ISSUE THREAD

**Issue by harkce** [minio/minio-go#946]
In [s3cmd](http://s3tools.org/usage), we can use `-P` options when we put and object, it store objects with ACL allowing read for anyone. Can we do that in minio? Because I want to retrieve an object URL without expire time. I currently use `PresignedGetObject` but the URL is not permanent.

**Comment by harshavardhana** [comment]
You should set bucket policies instead. minio-go doesn't support ACLs.

**Comment by kannappanr** [comment]
@harkce Closing the issue, as we do not support ACLs. Please feel free to open new issue if you have further questions.
