### ISSUE TITLE
[Question] Set a ReadOnly policy to a bucket ?

### ISSUE THREAD

**Issue by JulienTant** [minio/minio-go#976]
Hello,

I'm discovering the minio sdk and have a probably simple question have policies. I was looking for 'How am i suppose to create a bucket and set a policy to make it "readonly" for anonymous access'. Creating a bucket was as easy, but it looks like creating a policy is cleary not. I was expecting an api like `client.SetBucketPolicy("myBucket", policy.ReadOnlyPolicy)`, but i feel like I must craft some JSON ? Am I missing something obvious ?

Thanks a lot for your help!

**Comment by harshavardhana** [comment]
> I'm discovering the minio sdk and have a probably simple question have policies. I was looking for 'How am i suppose to create a bucket and set a policy to make it "readonly" for anonymous access'. Creating a bucket was as easy, but it looks like creating a policy is cleary not. I was expecting an api like client.SetBucketPolicy("myBucket", policy.ReadOnlyPolicy), but i feel like I must craft some JSON ? Am I missing something obvious ?

@JulienTant you need to look at examples here  https://docs.minio.io/docs/golang-client-api-reference#SetBucketPolicy  .  To construct a policy you should use https://awspolicygen.s3.amazonaws.com/policygen.html

**Comment by JulienTant** [comment]
Hi,

Thank you for your response. I ended out using mc to create a download policy, then coding a small utility to download the policy, and then reused it in my codebase ^^

**Comment by lukepighetti** [comment]
I'm going to make this a feature request. If we can do `mc policy download http://minio:9000/images` it would be nice to also do `s.Client.SetBucketPolicy("images", "download")`

**Comment by harshavardhana** [comment]
Please open the issue in mc @lukepighetti

**Comment by lukepighetti** [comment]
This is a `mini-go` issue, the inability to easily set a bucket policy with the shorthand keywords like `download`

**Comment by harshavardhana** [comment]
We used to have that, but it is intentional the way it is right now. Because we cannot satisfy all policy requirements and variations - so we will not be implementing it @lukepighetti

**Comment by lukepighetti** [comment]
The fragmentation between `mc` and `minio-go` feels incomplete. Do you plan to remove canned style from `mc`?

**Comment by harshavardhana** [comment]
mc is a higher level tool, it does both custom policy and canned - minio-go is library they are not meant to replace each other

**Comment by lukepighetti** [comment]
I understand and respect your position but I do think this would add significant ease of use to `minio-go` users. Thank you for your consideration.

**Comment by harshavardhana** [comment]
> I understand and respect your position but I do think this would add non-trivial ease of use/developer experience to `minio-go` users. Thank you for your consideration.

Yes, we had that in mind but there were many who wanted a more elaborate input. That is when it was found that taking a JSON input would satisfy everyone.   We can additionally add SetCannedBucketPolicy() like APIs, feel free to open a new github issue we will take a look.
