### ISSUE TITLE
StatObject does not timeout

### ISSUE THREAD

**Issue by alvaroaleman** [minio/minio-go#979]
Hello there,

We are using the  minio-go client in the Thanos project to implement S3 support. While using that functionality, I ran in the issue of having a faulty S3 endpoint (radosgw) which accepts connections but never returns anything. This resulted in `Client.StatObject` to block forever.

A renderd pprof of that situation is here: https://github.com/improbable-eng/thanos/files/1970073/profile001.pdf

The issue in thanos is this one: https://github.com/improbable-eng/thanos/issues/315

If there is anything more I can do, just ping me.

**Comment by harshavardhana** [comment]
You should enable a custom transport which times out properly. Go default HTTP client doesn't timeout properly.

https://github.com/minio/minio-go/blob/master/docs/API.md#SetCustomTransport

**Comment by alvaroaleman** [comment]
Thanks for the hint, so using a custom transport with `ResponseHeaderTimeout` set will fix the issue for us.

Wouldn't it make sense to also set `ResponseHeaderTimeout` in the `defaultMinioTransport`?

**Comment by harshavardhana** [comment]
The problem is we cannot really choose correctly what is the right number for these values. We simply use the http.DefaultTransport by Go, any other customizations are done by consumers of this library. Unfortunately ResponseTimeout is not set by Go stdlib.

**Comment by alvaroaleman** [comment]
Ah okay, thanks for your help!

**Comment by Bplotka** [comment]
@harshavardhana: Follow up question: Is there any reason why for `StatObject` there is no `StatObjectWithContext`? As a result, we could adjust timeouts per different types of request not widely for whole client. Why some operations have `...WithContext` method some not?
