### ISSUE TITLE
release tag format, compatibility with the Go versioning proposal

### ISSUE THREAD

**Issue by fd0** [minio/minio-go#985]
Hey,

when testing if restic compiles with `vgo`, the prototype implementation for adding [versioning to the Go toolchain](https://github.com/golang/go/issues/24301), I noticed that some time ago you switched from release tags in the form `v1.2.3` (as required by `vgo`) to `1.2.3`, so the `v` prefix was dropped.

This leads to `vgo` selecting the `v1.0.0` release tag, which is ancient:
```
vgo: import "github.com/restic/restic/cmd/restic" ->
        import "github.com/restic/restic/internal/backend/location" ->
        import "github.com/restic/restic/internal/backend/s3" ->
        import "github.com/minio/minio-go/pkg/credentials" [/home/fd0/gopath/src/v/github.com/minio/minio-go@v1.0.0/pkg/credentials]: open /home/fd0/gopath/src/v/github.com/minio/minio-go@v1.0.0/pkg/credentials: no such file or directory
```

Would you mind adding a second tag `v6.0.1` which points to the same commit the tag `6.0.1` does, and tagging future releases with the `v` prefix? That'd be awesome :)

Thanks!

**Comment by harshavardhana** [comment]
We can definitely do that, let me see if we can edit older tags and avoid using `v` since we have automated most of our releases this is currently harder to do.

**Comment by fd0** [comment]
As far as I can see it's not necessary to change older tags, adding the ones with the `v` prefix and leaving the old ones as they are should be sufficient.

I'm not sure what you mean with "avoiding using `v`": It'd be great if new releases *have* the `v` prefix :)

**Comment by mastertinner** [comment]
New releases should absolutely have the `v` prefix. That's required by `vgo` and recommended by GitHub.

**Comment by fd0** [comment]
As far as I understood the implementation and the proposal, version tags are required to start with `v` (e.g. `v1.2.3`). I don't know why this was chosen, maybe it was even arbitrarily, but that's the way it is. :)
