### ISSUE TITLE
Expose IAM Provider to use in Chain

### ISSUE THREAD

**Issue by rackonnoiter** [minio/minio-go#987]
The current IAM implementation in `iam_aws.go` only exposes a `*Credentials` type which does not satisfy the `Provider` interface needed to use it in a `Chain`, and its `provider` field is unexported. The `IAM` struct would be ideal, however since the `endpoint` field is also unexported, it is unsettable outside of the `credential` package.

I think the ideal solution would be to create a `NewIAMProvider` function to create, initialize, and return an `IAM` struct.

https://github.com/minio/minio-go/blob/034ea465b079a920e0720e3e1e0cbf5ccfeb6373/pkg/credentials/iam_aws.go#L59-L70

**Comment by harshavardhana** [comment]
Isn't this possible @rackonnoiter 

```
   // Chains all credential types, in the following order:
        //      - Static credentials provided by user
        //      - AWS env vars (i.e. AWS_ACCESS_KEY_ID)
        //  - Minio env vars (i.e. MINIO_ACCESS_KEY)
        //  - AWS creds file (i.e. AWS_SHARED_CREDENTIALS_FILE or ~/.aws/credentials)
        //  - Minio creds file (i.e. MINIO_SHARED_CREDENTIALS_FILE or ~/.mc/config.json)
        //  - IAM profile based credentials. (performs an HTTP
        //    call to a pre-defined endpoint, only valid inside
        //    configured ec2 instances)
        creds := credentials.NewChainCredentials([]credentials.Provider{
                &credentials.Static{
                        Value: credentials.Value{
                                AccessKeyID:     cfg.KeyID,
                                SecretAccessKey: cfg.Secret,
                        },
                },
                &credentials.EnvAWS{},
                &credentials.EnvMinio{},
                &credentials.FileAWSCredentials{},
                &credentials.FileMinioClient{},
                &credentials.IAM{
                        Client: &http.Client{
                                Transport: http.DefaultTransport,
                        },
                },
        })
```

**Comment by rackonnoiter** [comment]
Ha! Yes, it is! I didn't follow the code long enough to see this:
https://github.com/minio/minio-go/blob/034ea465b079a920e0720e3e1e0cbf5ccfeb6373/pkg/credentials/iam_aws.go#L114-L116

If unable to set the endpoint, whenever `getCredentials` is called, `getIAMRoleURL` is called and will set the appropriate `endpoint`. Thank you for pointing that out. 👍
