### ISSUE TITLE
Large memory consumption when specifiying size of "-1" to .PutObject function

### ISSUE THREAD

**Issue by wilyarti** [minio/minio-go#989]
Hi,
I am getting high memory consumption when trying to upload a file stream. The file stream is of unknown size because it is a compressed data (LZ4).

Here is the line of code (https://github.com/wilyarti/hashtree/blob/master/uploadFiles/uploadFiles.go line 195):
>                size, err := s3Client.PutObject(bucket, hash, encrypted, -1, minio.PutObjectOptions{})

Here is the pprof output on the running process:
```
(pprof) top
Showing nodes accounting for 1.12GB, 99.59% of 1.13GB total
Dropped 56 nodes (cum <= 0.01GB)
      flat  flat%   sum%        cum   cum%
    1.12GB 99.59% 99.59%     1.13GB 99.68%  github.com/minio/minio-go.Client.putObjectMultipartStreamNoLength
         0     0% 99.59%     1.13GB 99.68%  github.com/minio/minio-go.Client.PutObject
         0     0% 99.59%     1.13GB 99.68%  github.com/minio/minio-go.Client.PutObjectWithContext
         0     0% 99.59%     1.13GB 99.68%  github.com/minio/minio-go.Client.putObjectCommon
         0     0% 99.59%     1.13GB 99.73%  hashtree/uploadFiles.UploadFile

```

I have created an issue on my repo here: https://github.com/wilyarti/hashtree/issues/1

Everything was working fine until I incorporated LZ4 compression and then had to specify a file length of -1 to indicate it is an unknown length file stream.

Cheers!

**Comment by wilyarti** [comment]
I was digging around in the source code. Here is where the memory is created:
```
(pprof) top
Showing nodes accounting for 1.12GB, 99.60% of 1.13GB total
Dropped 30 nodes (cum <= 0.01GB)
      flat  flat%   sum%        cum   cum%
    1.12GB 99.60% 99.60%     1.12GB 99.60%  github.com/minio/minio-go.Client.putObjectMultipartStreamNoLength
         0     0% 99.60%     1.12GB 99.60%  github.com/minio/minio-go.Client.PutObject
         0     0% 99.60%     1.12GB 99.60%  github.com/minio/minio-go.Client.PutObjectWithContext
         0     0% 99.60%     1.12GB 99.60%  github.com/minio/minio-go.Client.putObjectCommon
         0     0% 99.60%     1.13GB 99.65%  hashtree/uploadFiles.UploadFile
(pprof) list Multi
Total: 1.13GB
ROUTINE ======================== github.com/minio/minio-go.Client.putObjectMultipartStreamNoLength in /home/undef/go/src/github.com/minio/minio-go/api-put-object.go
    1.12GB     1.12GB (flat, cum) 99.60% of Total
         .          .    198:
         .          .    199:	// Initialize parts uploaded map.
         .          .    200:	partsInfo := make(map[int]ObjectPart)
         .          .    201:
         .          .    202:	// Create a buffer.
    1.12GB     1.12GB    203:	buf := make([]byte, partSize)
         .          .    204:	defer debug.FreeOSMemory()
         .          .    205:
         .          .    206:	for partNumber <= totalPartsCount {
         .          .    207:		length, rErr := io.ReadFull(reader, buf)
         .          .    208:		if rErr == io.EOF && partNumber > 1 {
(pprof) 

```

**Comment by wilyarti** [comment]
Changing github.com/minio/minio-go/constants.go line 35 to:
> const maxPartsCount = 80000

Reduces the part size to 134217728b (128MiB) which is larger than the 64MiB minimum chunk.

Would this be a reasonable compromise? Otherwise the buffer allocation is 600+ MiB (5TiB/maxPartsCount)....

This is a small change and fixes my use case. 2 go routines using 128MiB is acceptable.

**Comment by poornas** [comment]
@wilyarti, could you describe your setup and the RAM size available

**Comment by harshavardhana** [comment]
> const maxPartsCount = 80000

You cannot change this and will lead to bugs, AWS S3 maximum number of parts per object is 10,000. Higher memory usage is not a bug it is an intended behavior to support 5TiB objects within 10,000 parts. 

Your issue is not being able to set the right content size while uploading. Also when you don't know the size you should upload one file at a time. This would essentially only use 525MiB.  I see in your code there is parallelism which is not going to work in your scenario.  

If you change the number of parts or part size it would hinder the ability to handle larger file sizes. True streaming is not possible with AWS S3 protocol so there is no way out. 

If you want to keep parallelism simply stage the file locally and pass the *os.File to the PutObject(). This would help in the long run to keep the memory usage minimal and effectively use local disk space instead.

**Comment by wilyarti** [comment]
Thanks for the feedback. Unfortunately your suggestions do not suit my usage case.

I will make a fork of your project and pass a size estimation to the upload function (negative number).

I will use this to estimate a smaller part size but overestimate the total parts to ensure the function reaches EOF.

My app runs on mobile devices and most files are a few kB.
