### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by wilyarti** [minio/minio-go#992]
I tried to update to the latest minio version. I get the following error:
```
$ go get github.com/minio/minio-go
# github.com/minio/minio-go
../github.com/minio/minio-go/api-put-object.go:104:7: undefined: httpguts.ValidHeaderFieldName
../github.com/minio/minio-go/api-put-object.go:107:7: undefined: httpguts.ValidHeaderFieldValue

```
Thanks

**Comment by wilyarti** [comment]
I'm running Ubuntu:
```
$ uname -a
Linux undefined 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ go version
go version go1.10 linux/amd64


```

**Comment by wilyarti** [comment]
I reverted to aa6cfd6a4adf5ee81ba8ea5307fee8c696023d62 commit and this fixes this bug.

**Comment by harshavardhana** [comment]
> $ go get github.com/minio/minio-go

you should `go get -u github.com/minio/minio-go` to download the dependencies

**Comment by deekoder** [comment]
@wilyarti  let us know if go get -u fixes it. It seems to work ok for me.

**Comment by wilyarti** [comment]
Yes mate that works fine. Silly me.

Thank you.
